-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: 701811bcd7d759c952ec647ed89eccc40f9dbfd490583c3cd7c1ae2df8bda846
-- lane 'ih6' (import-hero/insert), 11 row(s) to create; run stamp 'insert-2026-10-07-002-001'.
-- Every row is created together with its journal rows, inside this transaction: a journal that
-- disagrees with the data cannot be committed, and a rolled-back statement leaves nothing behind.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_insert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    filename          TEXT NOT NULL,
    original_url      TEXT NOT NULL,
    commons_page_url  TEXT NOT NULL,
    title             TEXT NOT NULL,
    author            TEXT NOT NULL,
    author_url        TEXT NOT NULL,
    license           TEXT NOT NULL,
    license_url       TEXT NOT NULL,
    width             INTEGER NOT NULL,
    height            INTEGER NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT NOT NULL,
    change_key        TEXT NOT NULL,
    reason            TEXT NOT NULL,
    evidence          JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_insert (seq, site_id, filename, original_url, commons_page_url, title, author, author_url, license, license_url, width, height, file_size_bytes, demoted_id, old_thumbnail, new_thumbnail, change_key, reason, evidence) VALUES
    (1, '218340f9-7b59-4e98-a13a-31452278ae01'::uuid, 'Salle couverte de grandes dalles situées au Sud u monastère.webp', 'https://upload.wikimedia.org/wikipedia/commons/3/34/Salle_couverte_de_grandes_dalles_situ%C3%A9es_au_Sud_u_monast%C3%A8re.jpg', 'https://commons.wikimedia.org/wiki/File%3ASalle%20couverte%20de%20grandes%20dalles%20situ%C3%A9es%20au%20Sud%20u%20monast%C3%A8re.jpg', 'Salle couverte de grandes dalles situées au Sud u monastère', 'IssamBarhoumi', 'https://commons.wikimedia.org/wiki/User:IssamBarhoumi', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1064, 416414, NULL, NULL, '/data/images/wiki/218340f9/Salle couverte de grandes dalles situées au Sud u monastère.webp', 'import-hero/insert:218340f9-7b59-4e98-a13a-31452278ae01', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/3/34/Salle_couverte_de_grandes_dalles_situ%C3%A9es_au_Sud_u_monast%C3%A8re.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ASalle%20couverte%20de%20grandes%20dalles%20situ%C3%A9es%20au%20Sud%20u%20monast%C3%A8re.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/3/34/Salle_couverte_de_grandes_dalles_situ%C3%A9es_au_Sud_u_monast%C3%A8re.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 218340f9-7b59-4e98-a13a-31452278ae01"}]'::jsonb),
    (2, '218a4df9-1bc1-43ce-a054-1d964d7232a4'::uuid, 'Tarragal Cave.webp', 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Tarragal_Cave.jpg', 'https://commons.wikimedia.org/wiki/File%3ATarragal%20Cave.jpg', 'Tarragal Cave', '1geel0ng1', 'https://commons.wikimedia.org/wiki/User:1geel0ng1', 'CC BY 4.0', 'https://creativecommons.org/licenses/by/4.0', 1600, 2133, 672934, NULL, NULL, '/data/images/wiki/218a4df9/Tarragal Cave.webp', 'import-hero/insert:218a4df9-1bc1-43ce-a054-1d964d7232a4', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Tarragal_Cave.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ATarragal%20Cave.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/b/b6/Tarragal_Cave.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 218a4df9-1bc1-43ce-a054-1d964d7232a4"}]'::jsonb),
    (3, '22bc5858-875a-4603-b94a-866aaf0a14e1'::uuid, 'Stratonicea toilets in 2015 4212.webp', 'https://upload.wikimedia.org/wikipedia/commons/8/82/Stratonicea_toilets_in_2015_4212.jpg', 'https://commons.wikimedia.org/wiki/File%3AStratonicea%20toilets%20in%202015%204212.jpg', 'Stratonicea toilets in 2015 4212', 'Dosseman', 'https://commons.wikimedia.org/wiki/User:Dosseman', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1065, 436268, NULL, NULL, '/data/images/wiki/22bc5858/Stratonicea toilets in 2015 4212.webp', 'import-hero/insert:22bc5858-875a-4603-b94a-866aaf0a14e1', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/8/82/Stratonicea_toilets_in_2015_4212.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AStratonicea%20toilets%20in%202015%204212.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/8/82/Stratonicea_toilets_in_2015_4212.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 22bc5858-875a-4603-b94a-866aaf0a14e1"}]'::jsonb),
    (4, '22dba69d-525f-4b01-9fb7-a8db7036bb0e'::uuid, 'Village hall, Hadzhidimitrovo, Veliko Tarnovo Province.webp', 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Village_hall%2C_Hadzhidimitrovo%2C_Veliko_Tarnovo_Province.jpg', 'https://commons.wikimedia.org/wiki/File%3AVillage%20hall%2C%20Hadzhidimitrovo%2C%20Veliko%20Tarnovo%20Province.jpg', 'Village hall, Hadzhidimitrovo, Veliko Tarnovo Province', 'Powerfox', 'https://commons.wikimedia.org/w/index.php?title=User:Powerfox&amp;action=edit&amp;redlink=1', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1200, 250620, NULL, NULL, '/data/images/wiki/22dba69d/Village hall, Hadzhidimitrovo, Veliko Tarnovo Province.webp', 'import-hero/insert:22dba69d-525f-4b01-9fb7-a8db7036bb0e', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Village_hall%2C_Hadzhidimitrovo%2C_Veliko_Tarnovo_Province.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AVillage%20hall%2C%20Hadzhidimitrovo%2C%20Veliko%20Tarnovo%20Province.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/e/e9/Village_hall%2C_Hadzhidimitrovo%2C_Veliko_Tarnovo_Province.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 22dba69d-525f-4b01-9fb7-a8db7036bb0e"}]'::jsonb),
    (5, '23098ff4-34c5-4071-8298-97e16d7bae84'::uuid, 'Quriwayrachina.webp', 'https://upload.wikimedia.org/wikipedia/commons/a/af/Quriwayrachina.jpg', 'https://commons.wikimedia.org/wiki/File%3AQuriwayrachina.jpg', 'Quriwayrachina', 'Phil Whitehouse', 'https://www.flickr.com/people/19451080@N00', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', 1600, 1200, 517382, NULL, NULL, '/data/images/wiki/23098ff4/Quriwayrachina.webp', 'import-hero/insert:23098ff4-34c5-4071-8298-97e16d7bae84', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/a/af/Quriwayrachina.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AQuriwayrachina.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/a/af/Quriwayrachina.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 23098ff4-34c5-4071-8298-97e16d7bae84"}]'::jsonb),
    (6, '248be59c-06f7-453b-9062-9e254c9da942'::uuid, 'St Remy Glanum vue10.webp', 'https://upload.wikimedia.org/wikipedia/commons/f/fc/St_Remy_Glanum_vue10.jpg', 'https://commons.wikimedia.org/wiki/File%3ASt%20Remy%20Glanum%20vue10.jpg', 'St Remy Glanum vue10', 'Jacques Le Letty', 'https://commons.wikimedia.org/wiki/User:Vitr%C3%A92.0', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1200, 700764, NULL, NULL, '/data/images/wiki/248be59c/St Remy Glanum vue10.webp', 'import-hero/insert:248be59c-06f7-453b-9062-9e254c9da942', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/f/fc/St_Remy_Glanum_vue10.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ASt%20Remy%20Glanum%20vue10.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/f/fc/St_Remy_Glanum_vue10.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 248be59c-06f7-453b-9062-9e254c9da942"}]'::jsonb),
    (7, '24de1fb5-935c-4fc0-89d0-00539a0ce610'::uuid, 'Chile-03199 - Special Rock (49072671368).webp', 'https://upload.wikimedia.org/wikipedia/commons/7/74/Chile-03199_-_Special_Rock_%2849072671368%29.jpg', 'https://commons.wikimedia.org/wiki/File%3AChile-03199%20-%20Special%20Rock%20%2849072671368%29.jpg', 'Chile-03199 - Special Rock (49072671368)', 'Dennis G. Jarvis', 'https://www.wikidata.org/wiki/Q122977591', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0', 1600, 1067, 862712, NULL, NULL, '/data/images/wiki/24de1fb5/Chile-03199 - Special Rock (49072671368).webp', 'import-hero/insert:24de1fb5-935c-4fc0-89d0-00539a0ce610', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/7/74/Chile-03199_-_Special_Rock_%2849072671368%29.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AChile-03199%20-%20Special%20Rock%20%2849072671368%29.jpg"}, {"quote": "2 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/7/74/Chile-03199_-_Special_Rock_%2849072671368%29.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 24de1fb5-935c-4fc0-89d0-00539a0ce610"}]'::jsonb),
    (8, '25910998-3672-4869-84cd-d737e7b8b611'::uuid, 'Easter Island, Ahu Nau Nau (6691343477).webp', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Easter_Island%2C_Ahu_Nau_Nau_%286691343477%29.jpg', 'https://commons.wikimedia.org/wiki/File%3AEaster%20Island%2C%20Ahu%20Nau%20Nau%20%286691343477%29.jpg', 'Easter Island, Ahu Nau Nau (6691343477)', 'Arian Zwegers', 'https://www.flickr.com/people/67769030@N07', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', 1600, 1067, 281796, NULL, NULL, '/data/images/wiki/25910998/Easter Island, Ahu Nau Nau (6691343477).webp', 'import-hero/insert:25910998-3672-4869-84cd-d737e7b8b611', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Easter_Island%2C_Ahu_Nau_Nau_%286691343477%29.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AEaster%20Island%2C%20Ahu%20Nau%20Nau%20%286691343477%29.jpg"}, {"quote": "1 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/f/f8/Easter_Island%2C_Ahu_Nau_Nau_%286691343477%29.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 25910998-3672-4869-84cd-d737e7b8b611"}]'::jsonb),
    (9, '28163f7d-d85a-4fa6-ba08-c33cd62b1da8'::uuid, 'Patallacta from Inca Trail.webp', 'https://upload.wikimedia.org/wikipedia/commons/6/63/Patallacta_from_Inca_Trail.jpg', 'https://commons.wikimedia.org/wiki/File%3APatallacta%20from%20Inca%20Trail.jpg', 'Patallacta from Inca Trail', 'Daretruth', 'https://commons.wikimedia.org/w/index.php?title=User:Daretruth&amp;action=edit&amp;redlink=1', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1067, 508976, NULL, NULL, '/data/images/wiki/28163f7d/Patallacta from Inca Trail.webp', 'import-hero/insert:28163f7d-d85a-4fa6-ba08-c33cd62b1da8', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/6/63/Patallacta_from_Inca_Trail.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3APatallacta%20from%20Inca%20Trail.jpg"}, {"quote": "2 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/6/63/Patallacta_from_Inca_Trail.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 28163f7d-d85a-4fa6-ba08-c33cd62b1da8"}]'::jsonb),
    (10, '29651376-c3fa-484e-b3bd-a6a64e97d0c6'::uuid, 'Gavurkale2.webp', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Gavurkale2.jpg', 'https://commons.wikimedia.org/wiki/File%3AGavurkale2.jpg', 'Gavurkale2', 'Klaus-Peter Simon', 'https://commons.wikimedia.org/wiki/User:Kpisimon', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', 1600, 1067, 394152, NULL, NULL, '/data/images/wiki/29651376/Gavurkale2.webp', 'import-hero/insert:29651376-c3fa-484e-b3bd-a6a64e97d0c6', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/2/24/Gavurkale2.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AGavurkale2.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/2/24/Gavurkale2.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 29651376-c3fa-484e-b3bd-a6a64e97d0c6"}]'::jsonb),
    (11, '2a453751-5937-45b7-ac50-a5e5bab66680'::uuid, 'The Knave - geograph.org.uk - 7016403.webp', 'https://upload.wikimedia.org/wikipedia/commons/7/79/The_Knave_-_geograph.org.uk_-_7016403.jpg', 'https://commons.wikimedia.org/wiki/File%3AThe%20Knave%20-%20geograph.org.uk%20-%207016403.jpg', 'The Knave - geograph.org.uk - 7016403', 'Eirian Evans', 'https://www.geograph.org.uk/profile/4582', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0', 1600, 1200, 551430, NULL, NULL, '/data/images/wiki/2a453751/The Knave - geograph.org.uk - 7016403.webp', 'import-hero/insert:2a453751-5937-45b7-ac50-a5e5bab66680', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/7/79/The_Knave_-_geograph.org.uk_-_7016403.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AThe%20Knave%20-%20geograph.org.uk%20-%207016403.jpg"}, {"quote": "1 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/7/79/The_Knave_-_geograph.org.uk_-_7016403.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 2a453751-5937-45b7-ac50-a5e5bab66680"}]'::jsonb);

DO $$
DECLARE
    bad  integer;
    r    RECORD;
    new_id integer;
    cols TEXT;
BEGIN
    -- guard 1: every planned site is a curated site (the message names the source in words, so
    -- the log of a refused wave says what was expected)
    SELECT count(*) INTO bad FROM (SELECT DISTINCT site_id FROM _ih_insert) p
      LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % planned site(s) are not ancient_nerds sites',
            'insert-2026-10-07-002-001', bad;
    END IF;

    FOR r IN SELECT * FROM _ih_insert ORDER BY seq LOOP
        -- guard 2: no row of this site holds the file yet. The unique constraint on
        -- (site_id, original_url) is a second line of defence behind this one.
        IF EXISTS (SELECT 1 FROM wiki_images w
                    WHERE w.site_id = r.site_id AND w.original_url = r.original_url) THEN
            RAISE EXCEPTION '%: site % already holds this file', r.change_key, r.site_id;
        END IF;

        -- guard 3: the file reaches the hero floor
        IF r.width < 1600 OR r.height < 900 THEN
            RAISE EXCEPTION '%: the file is %x%, under the %x% this lane serves', r.change_key,
                r.width, r.height, 1600, 900;
        END IF;

        -- guard 4: the row that holds the flag is still the one the plan demotes
        IF r.demoted_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM wiki_images w
             WHERE w.id = r.demoted_id AND w.site_id = r.site_id AND w.is_hero) THEN
            RAISE EXCEPTION '%: the row that held the flag for site % moved since the read',
                r.change_key, r.site_id;
        END IF;

        -- guard 5: the thumbnail still holds the value the read found
        IF (SELECT u.thumbnail_url FROM unified_sites u WHERE u.id = r.site_id)
           IS DISTINCT FROM r.old_thumbnail THEN
            RAISE EXCEPTION '%: the thumbnail of site % moved since the read', r.change_key, r.site_id;
        END IF;

        -- the row that gives up the flag, and the row that takes it
        IF r.demoted_id IS NOT NULL THEN
            UPDATE wiki_images SET is_hero = false
             WHERE id = r.demoted_id AND is_hero AND site_id = r.site_id;
        END IF;

        -- the three columns the file does not carry: the next free number of this site (derived,
        -- never invented), the owner's picture rather than a measured lead image of the article,
        -- and the source 49,683 of the 49,691 curated rows carry
        INSERT INTO wiki_images
            (site_id, filename, original_url, commons_page_url, title, author, author_url, license, license_url, width, height, file_size_bytes, is_lead, sort_order, source_type, is_hero, is_excluded)
        SELECT r.site_id, r.filename, r.original_url, r.commons_page_url, r.title, r.author, r.author_url, r.license, r.license_url, r.width, r.height, r.file_size_bytes, false,
               (SELECT COALESCE(MAX(w2.sort_order), -1) + 1 FROM wiki_images w2
                 WHERE w2.site_id = r.site_id),
               'wikimedia', true, false
        RETURNING id INTO new_id;

        IF r.new_thumbnail IS DISTINCT FROM r.old_thumbnail THEN
            UPDATE unified_sites SET thumbnail_url = r.new_thumbnail WHERE id = r.site_id;
        END IF;

        -- the journal, in this transaction: one row per column this statement wrote,
        -- read back from the row it created, so the journal records what the database holds
        INSERT INTO remediation_change_log
            (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value, change_key,
             confidence, evidence, site_id_ref)
        SELECT 'insert-2026-10-07-002-001', 'import-hero/insert/owner-2026-10-05', 'wiki_images', t.col, new_id::text, NULL, t.val,
               r.change_key || ':' || t.col, 'authoritative', r.evidence, r.site_id
          FROM wiki_images w
          CROSS JOIN LATERAL (VALUES
              ('filename', w.filename::text),
              ('original_url', w.original_url::text),
              ('commons_page_url', w.commons_page_url::text),
              ('title', w.title::text),
              ('author', w.author::text),
              ('author_url', w.author_url::text),
              ('license', w.license::text),
              ('license_url', w.license_url::text),
              ('width', w.width::text),
              ('height', w.height::text),
              ('file_size_bytes', w.file_size_bytes::text),
              ('is_lead', w.is_lead::text),
              ('sort_order', w.sort_order::text),
              ('source_type', w.source_type::text)
          ) AS t(col, val)
         WHERE w.id = new_id;

        IF r.demoted_id IS NOT NULL THEN
            INSERT INTO remediation_change_log
                (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value,
                 change_key, confidence, evidence, site_id_ref)
            VALUES ('insert-2026-10-07-002-001', 'import-hero/insert/owner-2026-10-05', 'wiki_images', 'is_hero',
                    r.demoted_id::text, 'true', 'false', r.change_key || ':demote',
                    'authoritative', r.evidence, r.site_id);
        END IF;

        IF r.new_thumbnail IS DISTINCT FROM r.old_thumbnail THEN
            INSERT INTO remediation_change_log
                (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value,
                 change_key, confidence, evidence, site_id_ref)
            VALUES ('insert-2026-10-07-002-001', 'import-hero/insert/owner-2026-10-05', 'unified_sites', 'thumbnail_url',
                    r.site_id::text, r.old_thumbnail, r.new_thumbnail,
                    r.change_key || ':thumbnail', 'authoritative', r.evidence, r.site_id);
        END IF;
    END LOOP;

    -- invariant 1: every planned row stands, with the planned values, the flag and the three
    -- columns the statement derived for it. The temp table is aliased `p`, never `r`: the loop
    -- variable of this block is `r`, and Postgres refuses a reference that could mean either
    -- (measured 2026-10-06, in the rehearsal of chunk-001).
    SELECT count(*) INTO bad FROM _ih_insert p
      LEFT JOIN wiki_images w ON w.site_id = p.site_id AND w.original_url = p.original_url
     WHERE w.id IS NULL OR w.is_hero IS NOT TRUE OR w.is_excluded IS NOT FALSE
        OR w.width IS DISTINCT FROM p.width OR w.height IS DISTINCT FROM p.height
        OR w.file_size_bytes IS DISTINCT FROM p.file_size_bytes
        OR w.filename IS DISTINCT FROM p.filename OR w.original_url IS DISTINCT FROM p.original_url
        OR w.is_lead IS NOT FALSE OR w.source_type IS DISTINCT FROM 'wikimedia'
        OR w.sort_order <> (SELECT COALESCE(MAX(w3.sort_order), 0) FROM wiki_images w3
                             WHERE w3.site_id = p.site_id);
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % inserted row(s) do not stand as planned', 'insert-2026-10-07-002-001', bad;
    END IF;

    -- invariant 2: at most one live hero per touched site (T09's invariant)
    SELECT count(*) INTO bad FROM (
        SELECT w.site_id FROM wiki_images w
          JOIN _ih_insert p ON p.site_id = w.site_id
         WHERE w.is_hero AND w.is_excluded IS NOT TRUE
         GROUP BY w.site_id HAVING count(*) > 1) d;
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % touched site(s) hold more than one live hero row',
            'insert-2026-10-07-002-001', bad;
    END IF;

    -- invariant 3: the journal carries every write, and nothing else
    SELECT count(*) INTO bad FROM _ih_insert p
      LEFT JOIN (SELECT site_id_ref, count(*) AS n FROM remediation_change_log
                  WHERE run_stamp = 'insert-2026-10-07-002-001' GROUP BY site_id_ref) l
        ON l.site_id_ref = p.site_id
     WHERE COALESCE(l.n, 0) <> 14
        + CASE WHEN p.demoted_id IS NOT NULL THEN 1 ELSE 0 END
        + CASE WHEN p.new_thumbnail IS DISTINCT FROM p.old_thumbnail THEN 1 ELSE 0 END;
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % site(s) do not have exactly their planned journal rows',
            'insert-2026-10-07-002-001', bad;
    END IF;
END $$;

-- the same two read-back lines the shared writer ends with, so `--rehearse` recognises the run
SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-002-001';
SELECT 'planned rows', count(*)::text FROM _ih_insert;
COMMIT;
