-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: 45b538c2bef5196ffee0feca66cbc8180d58737228d893b405427bdd0861ed3e
-- The reversal of lane 'ih6': the rows this wave created go back out, the flag returns to
-- the row that held it, and the thumbnail returns to the value the read found.
-- The row is named by the triple this lane wrote - (site_id, original_url, file_size_bytes) - so
-- the statement cannot delete a row somebody else created.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_uninsert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    original_url      TEXT NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT,
    change_key        TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_uninsert VALUES
    (1, '0b7f8fc6-0c2b-40c1-bfa2-f493afe1698a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Chinchero_%284463387386%29.jpg', 287710, NULL, NULL, '/data/images/wiki/0b7f8fc6/Chinchero (4463387386).webp', 'import-hero/insert:0b7f8fc6-0c2b-40c1-bfa2-f493afe1698a'),
    (2, '0e627b04-0c07-4967-9b94-0967a2eca175'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/08/%CE%9B%CE%AC%CE%BA%CE%BA%CE%BF%CF%82_%CE%A3%CE%B5%CF%81%CF%81%CF%8E%CE%BD_6.jpg', 691980, NULL, NULL, '/data/images/wiki/0e627b04/Λάκκος Σερρών 6.webp', 'import-hero/insert:0e627b04-0c07-4967-9b94-0967a2eca175'),
    (3, '11aae1cf-691a-45a5-a873-e4ac938587b2'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/d7/%C3%96k%C3%BCzl%C3%BCT%C3%BCr2Sturz.jpg', 536240, NULL, NULL, '/data/images/wiki/11aae1cf/ÖküzlüTür2Sturz.webp', 'import-hero/insert:11aae1cf-691a-45a5-a873-e4ac938587b2'),
    (4, '12e0a51b-54c4-4d30-abcb-7ef995ccd49f'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Sistema_de_recirculaci%C3%B3n_de_aire_en_las_qolqas_de_Wayna_Tawqaray.jpg', 442008, NULL, NULL, '/data/images/wiki/12e0a51b/Sistema de recirculación de aire en las qolqas de Wayna Tawqaray.webp', 'import-hero/insert:12e0a51b-54c4-4d30-abcb-7ef995ccd49f'),
    (5, '138007c5-f824-446e-84ad-cf44e7cfde76'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Nashtifan_Windmills.jpg', 356306, NULL, NULL, '/data/images/wiki/138007c5/Nashtifan Windmills.webp', 'import-hero/insert:138007c5-f824-446e-84ad-cf44e7cfde76'),
    (6, '14aacb74-9cd3-4766-b74b-4911d804c415'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/15/Welsh_Road_lock_and_cottage_-_geograph.org.uk_-_7279320.jpg', 448292, NULL, NULL, '/data/images/wiki/14aacb74/Welsh Road lock and cottage - geograph.org.uk - 7279320.webp', 'import-hero/insert:14aacb74-9cd3-4766-b74b-4911d804c415'),
    (7, '15c7e942-5ff2-4ceb-ae6e-e78cdfbb8b99'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Korykos_Zisterne01.jpg', 422768, NULL, NULL, '/data/images/wiki/15c7e942/Korykos Zisterne01.webp', 'import-hero/insert:15c7e942-5ff2-4ceb-ae6e-e78cdfbb8b99'),
    (8, '1cef558f-8c07-494e-b32a-6bb5690934a7'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Swarn_Bhandar_Caves.jpg', 550914, NULL, NULL, '/data/images/wiki/1cef558f/Swarn Bhandar Caves.webp', 'import-hero/insert:1cef558f-8c07-494e-b32a-6bb5690934a7'),
    (9, '1cf08f5b-a8a8-4e06-a586-17ae6d0cf153'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/69/Central_area_of_Pumamarca.jpg', 600630, NULL, NULL, '/data/images/wiki/1cf08f5b/Central area of Pumamarca.webp', 'import-hero/insert:1cf08f5b-a8a8-4e06-a586-17ae6d0cf153'),
    (10, '1dfccf93-13b6-46cf-a719-8cfd1683e097'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Sagalassos_Antonine_Fountain_in_2012_2684.jpg', 437914, NULL, NULL, '/data/images/wiki/1dfccf93/Sagalassos Antonine Fountain in 2012 2684.webp', 'import-hero/insert:1dfccf93-13b6-46cf-a719-8cfd1683e097');

DO $$
DECLARE
    bad integer;
BEGIN
    -- every named row is still the one this wave created
    SELECT count(*) INTO bad FROM _ih_uninsert r
      LEFT JOIN wiki_images w
        ON w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes
     WHERE w.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'rollback %: % row(s) this wave created are not there to undo',
            'insert-2026-10-07-001-001', bad;
    END IF;

    DELETE FROM wiki_images w USING _ih_uninsert r
     WHERE w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes;

    UPDATE wiki_images w SET is_hero = true
      FROM _ih_uninsert r
     WHERE r.demoted_id IS NOT NULL AND w.id = r.demoted_id AND w.is_hero IS NOT TRUE;

    UPDATE unified_sites u SET thumbnail_url = r.old_thumbnail
      FROM _ih_uninsert r
     WHERE u.id = r.site_id AND r.new_thumbnail IS DISTINCT FROM r.old_thumbnail
       AND u.thumbnail_url IS DISTINCT FROM r.old_thumbnail;

    -- the journal goes with the write it describes
    DELETE FROM remediation_change_log l USING _ih_uninsert r
     WHERE l.run_stamp = 'insert-2026-10-07-001-001' AND l.change_key LIKE r.change_key || '%';
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-001-001';
SELECT 'rows this chunk created',
       count(*)::text
  FROM wiki_images w
  JOIN _ih_uninsert r ON w.site_id = r.site_id AND w.original_url = r.original_url
                    AND w.file_size_bytes = r.file_size_bytes;
COMMIT;
