-- Generated by scripts/remediation/bcases/coord_plan.py - do not edit by hand.
-- plan sha256 2cce0e2281744de5e09fd1851b3f352724bb2b9488044d26f02d4cb5c5586e71
-- the coordinate reversal of 4 curated site(s): 12 journalled changes (geom, lat, lon each); run stamp '2026-09-23_owner-case-coordinates-wave2-rollback'.
-- Every change goes through apply_remediation_change(): conditional on the old value, one
-- row by unified_sites.id, re-read, journalled in the same statement.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _coord_plan (
    site_id     UUID NOT NULL,
    column_name TEXT NOT NULL,
    old_value   TEXT NOT NULL,
    new_value   TEXT NOT NULL,
    change_key  TEXT NOT NULL,
    evidence    JSONB NOT NULL,
    PRIMARY KEY (site_id, column_name)
) ON COMMIT DROP;

INSERT INTO _coord_plan (site_id, column_name, old_value, new_value, change_key, evidence) VALUES
    ('294968f3-036b-44ff-b704-91593648927d'::uuid, 'geom', 'SRID=4326;POINT(24.3286228 37.6808994)', '0101000020E61000005F9BB52190563840641A667579D24240', 'coordinates:5046016004c2807b32cb0aeec73af513f0b6d4092e5fbe8e329a48edd96d958a-rollback', '[{"quote": "P625 = 37.680899, 24.328623 (precision 2.77777777778e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1739125"}, {"quote": "Latitude: 37.681700 Longitude: 24.328600", "source": "witness:web:topostext.org", "url": "https://topostext.org/place/377243XKef"}, {"quote": "wikidata and web:topostext.org agree within 89 m (independent), the stored point is 4.15 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('294968f3-036b-44ff-b704-91593648927d'::uuid, 'lat', '37.6808994', '37.64433162198546', 'coordinates:4d69f088577562c7dd64ce84cda3be10ebc920ca376e7b240529322cb3871550-rollback', '[{"quote": "P625 = 37.680899, 24.328623 (precision 2.77777777778e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1739125"}, {"quote": "Latitude: 37.681700 Longitude: 24.328600", "source": "witness:web:topostext.org", "url": "https://topostext.org/place/377243XKef"}, {"quote": "wikidata and web:topostext.org agree within 89 m (independent), the stored point is 4.15 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('294968f3-036b-44ff-b704-91593648927d'::uuid, 'lon', '24.3286228', '24.338136774861933', 'coordinates:8f53cfc497e9034849ea75f04485a3bc40faa9669f63911d05bb7c63a700374b-rollback', '[{"quote": "P625 = 37.680899, 24.328623 (precision 2.77777777778e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1739125"}, {"quote": "Latitude: 37.681700 Longitude: 24.328600", "source": "witness:web:topostext.org", "url": "https://topostext.org/place/377243XKef"}, {"quote": "wikidata and web:topostext.org agree within 89 m (independent), the stored point is 4.15 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('b8ddb28d-b0b8-4d6e-bdec-c5346a0de1a1'::uuid, 'geom', 'SRID=4326;POINT(72.3934053 34.2454644)', '0101000020E6100000CDB4FD1BDC1D5240BADDA54CF30E4140', 'coordinates:829c97af118c609bfc3d73017e01492a2ebe264d91db2c3c76b5148d98ee4333-rollback', '[{"quote": "P625 = 34.245464, 72.393405 (precision 1e-07)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q88078046"}, {"quote": "Latitude: 34.241666667 Longitude: 72.402333333", "source": "witness:web:doam.gov.pk", "url": "https://doam.gov.pk/public/sites/2330"}, {"quote": "wikidata and web:doam.gov.pk agree within 923 m (independent), the stored point is 15.81 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('b8ddb28d-b0b8-4d6e-bdec-c5346a0de1a1'::uuid, 'lat', '34.2454644', '34.11679990862781', 'coordinates:994395630606637a097761603e1a65d697b46aa5b8976b1160ca5ca4652c7106-rollback', '[{"quote": "P625 = 34.245464, 72.393405 (precision 1e-07)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q88078046"}, {"quote": "Latitude: 34.241666667 Longitude: 72.402333333", "source": "witness:web:doam.gov.pk", "url": "https://doam.gov.pk/public/sites/2330"}, {"quote": "wikidata and web:doam.gov.pk agree within 923 m (independent), the stored point is 15.81 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('b8ddb28d-b0b8-4d6e-bdec-c5346a0de1a1'::uuid, 'lon', '72.3934053', '72.466559407959', 'coordinates:aa74099743cc1f4409e4d614fde77d169fd5580f4c0b2545d2f266d816069399-rollback', '[{"quote": "P625 = 34.245464, 72.393405 (precision 1e-07)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q88078046"}, {"quote": "Latitude: 34.241666667 Longitude: 72.402333333", "source": "witness:web:doam.gov.pk", "url": "https://doam.gov.pk/public/sites/2330"}, {"quote": "wikidata and web:doam.gov.pk agree within 923 m (independent), the stored point is 15.81 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('cbc93ea2-6ae5-4be6-a320-254960a60ab7'::uuid, 'geom', 'SRID=4326;POINT(18.12269444 59.13194444)', '0101000020E61000001D1A89A52522324034A7753758954D40', 'coordinates:6dba2b712c1a6e58421e43099ed736f5c32e67a7076a698abc94c6dd8fd0e44f-rollback', '[{"quote": "P625 = 59.131944, 18.122694 (precision 2.777777777778e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q10540828"}, {"quote": "59°7′53.7″N 18°7′29.0″E", "source": "witness:web:guidebook-sweden.com", "url": "https://www.guidebook-sweden.com/en/guidebook/destination/jordbro-gravfaelt-grave-field-jordbro"}, {"quote": "wikidata and web:guidebook-sweden.com agree within 122 m (independent), the stored point is 3.92 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('cbc93ea2-6ae5-4be6-a320-254960a60ab7'::uuid, 'lat', '59.13194444', '59.16675465817244', 'coordinates:556feecc24026fb2264835298a0080b39b1244f7e7811d9b5e8afc1b3d1ed52b-rollback', '[{"quote": "P625 = 59.131944, 18.122694 (precision 2.777777777778e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q10540828"}, {"quote": "59°7′53.7″N 18°7′29.0″E", "source": "witness:web:guidebook-sweden.com", "url": "https://www.guidebook-sweden.com/en/guidebook/destination/jordbro-gravfaelt-grave-field-jordbro"}, {"quote": "wikidata and web:guidebook-sweden.com agree within 122 m (independent), the stored point is 3.92 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('cbc93ea2-6ae5-4be6-a320-254960a60ab7'::uuid, 'lon', '18.12269444', '18.13338694188325', 'coordinates:7cf8ea193b97d5506425a9e58670971ae2cb7a9f8c9917e5e56298602fdf0e8c-rollback', '[{"quote": "P625 = 59.131944, 18.122694 (precision 2.777777777778e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q10540828"}, {"quote": "59°7′53.7″N 18°7′29.0″E", "source": "witness:web:guidebook-sweden.com", "url": "https://www.guidebook-sweden.com/en/guidebook/destination/jordbro-gravfaelt-grave-field-jordbro"}, {"quote": "wikidata and web:guidebook-sweden.com agree within 122 m (independent), the stored point is 3.92 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('d3d33b4f-7d75-4ce6-962d-386834c72cab'::uuid, 'geom', 'SRID=4326;POINT(13.6091 54.5021)', '0101000020E610000068543F30123E2B40F04177B896414B40', 'coordinates:7735260077fc3fcf0bcd7c758b2c080acd29929ebac05fddbda74008207e193a-rollback', '[{"quote": "P625 = 54.502100, 13.609100 (precision 0.0001)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q575698"}, {"quote": "54.5020817, 13.6069502", "source": "witness:web:paganplaces.com", "url": "https://paganplaces.com/places/great-dolmen-of-dwasieden/"}, {"quote": "wikidata and web:paganplaces.com agree within 139 m (independent), the stored point is 1.39 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('d3d33b4f-7d75-4ce6-962d-386834c72cab'::uuid, 'lat', '54.5021', '54.51241212676166', 'coordinates:787c70f136929e2d76e903cb0eff094946bf59f66e3fcfed894a7e77ac7873be-rollback', '[{"quote": "P625 = 54.502100, 13.609100 (precision 0.0001)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q575698"}, {"quote": "54.5020817, 13.6069502", "source": "witness:web:paganplaces.com", "url": "https://paganplaces.com/places/great-dolmen-of-dwasieden/"}, {"quote": "wikidata and web:paganplaces.com agree within 139 m (independent), the stored point is 1.39 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('d3d33b4f-7d75-4ce6-962d-386834c72cab'::uuid, 'lon', '13.6091', '13.621232516985586', 'coordinates:bdb3be5508dd043dd19c8815fd0a2ce7fc1b2c8e4b43619b5394b7f6581ed539-rollback', '[{"quote": "P625 = 54.502100, 13.609100 (precision 0.0001)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q575698"}, {"quote": "54.5020817, 13.6069502", "source": "witness:web:paganplaces.com", "url": "https://paganplaces.com/places/great-dolmen-of-dwasieden/"}, {"quote": "wikidata and web:paganplaces.com agree within 139 m (independent), the stored point is 1.39 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb);

DO $$
DECLARE
    bad      INTEGER;
    moved    INTEGER := 0;
    expected INTEGER := 12;
    r        RECORD;
BEGIN
    -- guard 1: every site is a curated site that still exists
    SELECT count(*) INTO bad FROM _coord_plan p LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) are not curated sites', bad;
    END IF;
    -- guard 2: every site moves as a whole - geom, lat and lon, nothing else
    SELECT count(*) INTO bad FROM (
        SELECT site_id FROM _coord_plan GROUP BY site_id
        HAVING array_agg(column_name ORDER BY column_name) <> ARRAY['geom', 'lat', 'lon']
    ) x;
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % site(s) do not move geom, lat and lon together', bad;
    END IF;
    -- guard 3: every row still holds the planned old value, compared in the column's type
    SELECT count(*) INTO bad FROM _coord_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE (p.column_name = 'lat' AND u.lat IS DISTINCT FROM p.old_value::double precision)
        OR (p.column_name = 'lon' AND u.lon IS DISTINCT FROM p.old_value::double precision)
        OR (p.column_name = 'geom' AND u.geom IS DISTINCT FROM p.old_value::geometry);
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) no longer hold the planned old value', bad;
    END IF;
    -- guard 4: the planned geom is the planned point
    SELECT count(*) INTO bad FROM _coord_plan g
      JOIN _coord_plan a ON a.site_id = g.site_id AND a.column_name = 'lat'
      JOIN _coord_plan o ON o.site_id = g.site_id AND o.column_name = 'lon'
     WHERE g.column_name = 'geom' AND g.new_value::geometry IS DISTINCT FROM
           ST_SetSRID(ST_MakePoint(o.new_value::double precision,
                                   a.new_value::double precision), 4326);
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % planned geom value(s) are not the planned point', bad;
    END IF;
    -- the writes: apply_remediation_change raises unless exactly one row matched
    FOR r IN SELECT * FROM _coord_plan ORDER BY site_id, column_name LOOP
        moved := moved + apply_remediation_change(
            'unified_sites', r.column_name, 'id', r.site_id::text,
            r.old_value, r.new_value,
            'B1B2/coordinates', '2026-09-23_owner-case-coordinates-wave2-rollback', r.change_key, 'two_source', r.evidence, r.site_id);
    END LOOP;
    IF moved <> expected THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) changed, % planned', moved, expected;
    END IF;
    -- invariant 1: every site holds the new point, and a geom that is that point
    SELECT count(*) INTO bad FROM _coord_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE (p.column_name = 'lat' AND u.lat IS DISTINCT FROM p.new_value::double precision)
        OR (p.column_name = 'lon' AND u.lon IS DISTINCT FROM p.new_value::double precision)
        OR (p.column_name = 'geom' AND u.geom IS DISTINCT FROM
            ST_SetSRID(ST_MakePoint(u.lon, u.lat), 4326));
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) do not hold the new point', bad;
    END IF;
    -- invariant 2: the journal and the plan agree in both directions
    SELECT count(*) INTO bad FROM _coord_plan p LEFT JOIN remediation_change_log l
        ON l.run_stamp = '2026-09-23_owner-case-coordinates-wave2-rollback' AND l.change_key = p.change_key
       AND l.table_name = 'unified_sites' AND l.column_name = p.column_name
       AND l.row_pk = p.site_id::text
       AND l.old_value = p.old_value AND l.new_value = p.new_value
     WHERE l.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) have no matching journal row', bad;
    END IF;
    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = '2026-09-23_owner-case-coordinates-wave2-rollback'
       AND NOT EXISTS (SELECT 1 FROM _coord_plan p WHERE p.change_key = l.change_key);
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: this stamp journalled % row(s) outside the plan', bad;
    END IF;
    RAISE NOTICE 'owner-case coordinates: % row(s) changed and journalled', moved;
END $$;

COMMIT;

SELECT 'journal rows for this stamp' AS metric, count(*)::text AS value
  FROM remediation_change_log WHERE run_stamp = '2026-09-23_owner-case-coordinates-wave2-rollback';
