-- Generated by scripts/remediation/gallery_audit/chunk_writer.py - do not edit by hand.
-- plan sha256 e38b3fd9a2f9119a1e78c53bd78805949a53eccbea1dd0a0a4a237ac01fdc97a
-- The reversal of lane 'import-hero', chunk 004: 73 row(s) over 10 site(s);
-- scope source_id = 'ancient_nerds'; run stamp 'import-hero-2026-10-06-005-004-rollback'; journal test id 'import-hero/owner-2026-10-05'.
-- Every row goes through apply_remediation_change() (migrations 0017/0018/0022): the conditional
-- UPDATE and its journal row are one statement. This file holds no DELETE and no UPDATE.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _img_plan (
    seq         INTEGER PRIMARY KEY,
    table_name  TEXT NOT NULL,
    column_name TEXT NOT NULL,
    row_key     TEXT NOT NULL,
    site_id     UUID NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    evidence    JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _img_plan (seq, table_name, column_name, row_key, site_id, old_value, new_value, change_key, reason, evidence) VALUES
    (1, 'unified_sites', 'thumbnail_url', 'fa579d23-36bc-469f-9351-2be5f11e180f', 'fa579d23-36bc-469f-9351-2be5f11e180f'::uuid, '/data/images/wiki/fa579d23/Mankiala Stupa.webp', '/data/images/wiki/fa579d23/hero.webp', 'import-hero-rollback:unified_sites.thumbnail_url:fa579d23-36bc-469f-9351-2be5f11e180f', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on fa579d23-36bc-469f-9351-2be5f11e180f returned to ''/data/images/wiki/fa579d23/Mankiala Stupa.webp'' -> ''/data/images/wiki/fa579d23/hero.webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:fa579d23-36bc-469f-9351-2be5f11e180f: ''/data/images/wiki/fa579d23/hero.webp'' -> ''/data/images/wiki/fa579d23/Mankiala Stupa.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (2, 'wiki_images', 'file_size_bytes', '106694', 'fa579d23-36bc-469f-9351-2be5f11e180f'::uuid, '244236', '114582', 'import-hero-rollback:wiki_images.file_size_bytes:106694', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 106694 returned to ''244236'' -> ''114582''', '[{"quote": "import-hero:wiki_images.file_size_bytes:106694: ''114582'' -> ''244236''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (3, 'wiki_images', 'filename', '106694', 'fa579d23-36bc-469f-9351-2be5f11e180f'::uuid, 'Mankiala Stupa.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:106694', 'rollback of import-hero chunk 004: wiki_images.filename on 106694 returned to ''Mankiala Stupa.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:106694: ''hero.webp'' -> ''Mankiala Stupa.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (4, 'wiki_images', 'height', '106694', 'fa579d23-36bc-469f-9351-2be5f11e180f'::uuid, '1200', '600', 'import-hero-rollback:wiki_images.height:106694', 'rollback of import-hero chunk 004: wiki_images.height on 106694 returned to ''1200'' -> ''600''', '[{"quote": "import-hero:wiki_images.height:106694: ''600'' -> ''1200''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (5, 'wiki_images', 'title', '106694', 'fa579d23-36bc-469f-9351-2be5f11e180f'::uuid, 'Mankiala Stupa', 'Mankiala', 'import-hero-rollback:wiki_images.title:106694', 'rollback of import-hero chunk 004: wiki_images.title on 106694 returned to ''Mankiala Stupa'' -> ''Mankiala''', '[{"quote": "import-hero:wiki_images.title:106694: ''Mankiala'' -> ''Mankiala Stupa''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (6, 'wiki_images', 'width', '106694', 'fa579d23-36bc-469f-9351-2be5f11e180f'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:106694', 'rollback of import-hero chunk 004: wiki_images.width on 106694 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:106694: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (7, 'unified_sites', 'thumbnail_url', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943'::uuid, '/data/images/wiki/fabd8d1b/Vila Romana de Frielas1.webp', '/data/images/wiki/fabd8d1b/Villa Romana de Frielas - Portugal (8097572268).webp', 'import-hero-rollback:unified_sites.thumbnail_url:fabd8d1b-1a9c-4266-8ff6-d764c6229943', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on fabd8d1b-1a9c-4266-8ff6-d764c6229943 returned to ''/data/images/wiki/fabd8d1b/Vila Romana de Frielas1.webp'' -> ''/data/images/wiki/fabd8d1b/Villa Romana de Frielas - Portugal (8097572268).webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:fabd8d1b-1a9c-4266-8ff6-d764c6229943: ''/data/images/wiki/fabd8d1b/Villa Romana de Frielas - Portugal (8097572268).webp'' -> ''/data/images/wiki/fabd8d1b/Vila Romana de Frielas1.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (8, 'wiki_images', 'file_size_bytes', '106718', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943'::uuid, '404104', '134276', 'import-hero-rollback:wiki_images.file_size_bytes:106718', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 106718 returned to ''404104'' -> ''134276''', '[{"quote": "import-hero:wiki_images.file_size_bytes:106718: ''134276'' -> ''404104''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (9, 'wiki_images', 'filename', '106718', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943'::uuid, 'Vila Romana de Frielas1.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:106718', 'rollback of import-hero chunk 004: wiki_images.filename on 106718 returned to ''Vila Romana de Frielas1.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:106718: ''hero.webp'' -> ''Vila Romana de Frielas1.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (10, 'wiki_images', 'height', '106718', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943'::uuid, '941', '470', 'import-hero-rollback:wiki_images.height:106718', 'rollback of import-hero chunk 004: wiki_images.height on 106718 returned to ''941'' -> ''470''', '[{"quote": "import-hero:wiki_images.height:106718: ''470'' -> ''941''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (11, 'wiki_images', 'is_hero', '106717', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943'::uuid, 'false', 'true', 'import-hero-rollback:wiki_images.is_hero:106717', 'rollback of import-hero chunk 004: wiki_images.is_hero on 106717 returned to ''false'' -> ''true''', '[{"quote": "import-hero:wiki_images.is_hero:106717: ''true'' -> ''false''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (12, 'wiki_images', 'is_hero', '106718', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943'::uuid, 'true', 'false', 'import-hero-rollback:wiki_images.is_hero:106718', 'rollback of import-hero chunk 004: wiki_images.is_hero on 106718 returned to ''true'' -> ''false''', '[{"quote": "import-hero:wiki_images.is_hero:106718: ''false'' -> ''true''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (13, 'wiki_images', 'title', '106718', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943'::uuid, 'Vila Romana de Frielas1', 'Roman Villa of Frielas', 'import-hero-rollback:wiki_images.title:106718', 'rollback of import-hero chunk 004: wiki_images.title on 106718 returned to ''Vila Romana de Frielas1'' -> ''Roman Villa of Frielas''', '[{"quote": "import-hero:wiki_images.title:106718: ''Roman Villa of Frielas'' -> ''Vila Romana de Frielas1''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (14, 'wiki_images', 'width', '106718', 'fabd8d1b-1a9c-4266-8ff6-d764c6229943'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:106718', 'rollback of import-hero chunk 004: wiki_images.width on 106718 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:106718: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (15, 'unified_sites', 'thumbnail_url', 'facb2c7f-777a-4eb0-8036-731853847f07', 'facb2c7f-777a-4eb0-8036-731853847f07'::uuid, '/data/images/wiki/facb2c7f/Lavaderovirgen0001.webp', '/data/images/wiki/facb2c7f/hero.webp', 'import-hero-rollback:unified_sites.thumbnail_url:facb2c7f-777a-4eb0-8036-731853847f07', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on facb2c7f-777a-4eb0-8036-731853847f07 returned to ''/data/images/wiki/facb2c7f/Lavaderovirgen0001.webp'' -> ''/data/images/wiki/facb2c7f/hero.webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:facb2c7f-777a-4eb0-8036-731853847f07: ''/data/images/wiki/facb2c7f/hero.webp'' -> ''/data/images/wiki/facb2c7f/Lavaderovirgen0001.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (16, 'wiki_images', 'file_size_bytes', '106720', 'facb2c7f-777a-4eb0-8036-731853847f07'::uuid, '516006', '176844', 'import-hero-rollback:wiki_images.file_size_bytes:106720', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 106720 returned to ''516006'' -> ''176844''', '[{"quote": "import-hero:wiki_images.file_size_bytes:106720: ''176844'' -> ''516006''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (17, 'wiki_images', 'filename', '106720', 'facb2c7f-777a-4eb0-8036-731853847f07'::uuid, 'Lavaderovirgen0001.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:106720', 'rollback of import-hero chunk 004: wiki_images.filename on 106720 returned to ''Lavaderovirgen0001.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:106720: ''hero.webp'' -> ''Lavaderovirgen0001.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (18, 'wiki_images', 'height', '106720', 'facb2c7f-777a-4eb0-8036-731853847f07'::uuid, '1200', '600', 'import-hero-rollback:wiki_images.height:106720', 'rollback of import-hero chunk 004: wiki_images.height on 106720 returned to ''1200'' -> ''600''', '[{"quote": "import-hero:wiki_images.height:106720: ''600'' -> ''1200''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (19, 'wiki_images', 'title', '106720', 'facb2c7f-777a-4eb0-8036-731853847f07'::uuid, 'Lavaderovirgen0001', 'Kunturmarka, Ayacucho', 'import-hero-rollback:wiki_images.title:106720', 'rollback of import-hero chunk 004: wiki_images.title on 106720 returned to ''Lavaderovirgen0001'' -> ''Kunturmarka, Ayacucho''', '[{"quote": "import-hero:wiki_images.title:106720: ''Kunturmarka, Ayacucho'' -> ''Lavaderovirgen0001''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (20, 'wiki_images', 'width', '106720', 'facb2c7f-777a-4eb0-8036-731853847f07'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:106720', 'rollback of import-hero chunk 004: wiki_images.width on 106720 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:106720: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (21, 'unified_sites', 'thumbnail_url', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f'::uuid, '/data/images/wiki/fc215bfb/Standing Stones of Stenness 062015.webp', '/data/images/wiki/fc215bfb/Francis_Sylvester_Walker_etching,_Stones_of_Stennis.webp', 'import-hero-rollback:unified_sites.thumbnail_url:fc215bfb-e68e-4aa0-844a-c15d8047f62f', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on fc215bfb-e68e-4aa0-844a-c15d8047f62f returned to ''/data/images/wiki/fc215bfb/Standing Stones of Stenness 062015.webp'' -> ''/data/images/wiki/fc215bfb/Francis_Sylvester_Walker_etching,_Stones_of_Stennis.webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:fc215bfb-e68e-4aa0-844a-c15d8047f62f: ''/data/images/wiki/fc215bfb/Francis_Sylvester_Walker_etching,_Stones_of_Stennis.webp'' -> ''/data/images/wiki/fc215bfb/Standing Stones of Stenness 062015.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (22, 'wiki_images', 'file_size_bytes', '106893', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f'::uuid, '185788', '41898', 'import-hero-rollback:wiki_images.file_size_bytes:106893', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 106893 returned to ''185788'' -> ''41898''', '[{"quote": "import-hero:wiki_images.file_size_bytes:106893: ''41898'' -> ''185788''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (23, 'wiki_images', 'filename', '106893', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f'::uuid, 'Standing Stones of Stenness 062015.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:106893', 'rollback of import-hero chunk 004: wiki_images.filename on 106893 returned to ''Standing Stones of Stenness 062015.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:106893: ''hero.webp'' -> ''Standing Stones of Stenness 062015.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (24, 'wiki_images', 'height', '106893', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f'::uuid, '935', '468', 'import-hero-rollback:wiki_images.height:106893', 'rollback of import-hero chunk 004: wiki_images.height on 106893 returned to ''935'' -> ''468''', '[{"quote": "import-hero:wiki_images.height:106893: ''468'' -> ''935''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (25, 'wiki_images', 'is_hero', '106888', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f'::uuid, 'false', 'true', 'import-hero-rollback:wiki_images.is_hero:106888', 'rollback of import-hero chunk 004: wiki_images.is_hero on 106888 returned to ''false'' -> ''true''', '[{"quote": "import-hero:wiki_images.is_hero:106888: ''true'' -> ''false''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (26, 'wiki_images', 'is_hero', '106893', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f'::uuid, 'true', 'false', 'import-hero-rollback:wiki_images.is_hero:106893', 'rollback of import-hero chunk 004: wiki_images.is_hero on 106893 returned to ''true'' -> ''false''', '[{"quote": "import-hero:wiki_images.is_hero:106893: ''false'' -> ''true''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (27, 'wiki_images', 'title', '106893', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f'::uuid, 'Standing Stones of Stenness 062015', 'Stones of Stenness', 'import-hero-rollback:wiki_images.title:106893', 'rollback of import-hero chunk 004: wiki_images.title on 106893 returned to ''Standing Stones of Stenness 062015'' -> ''Stones of Stenness''', '[{"quote": "import-hero:wiki_images.title:106893: ''Stones of Stenness'' -> ''Standing Stones of Stenness 062015''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (28, 'wiki_images', 'width', '106893', 'fc215bfb-e68e-4aa0-844a-c15d8047f62f'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:106893', 'rollback of import-hero chunk 004: wiki_images.width on 106893 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:106893: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (29, 'unified_sites', 'thumbnail_url', 'fd79f148-d931-42c7-8883-41732a93d209', 'fd79f148-d931-42c7-8883-41732a93d209'::uuid, '/data/images/wiki/fd79f148/Marayniyoq0002.webp', '/data/images/wiki/fd79f148/Marayniyoq0001.webp', 'import-hero-rollback:unified_sites.thumbnail_url:fd79f148-d931-42c7-8883-41732a93d209', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on fd79f148-d931-42c7-8883-41732a93d209 returned to ''/data/images/wiki/fd79f148/Marayniyoq0002.webp'' -> ''/data/images/wiki/fd79f148/Marayniyoq0001.webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:fd79f148-d931-42c7-8883-41732a93d209: ''/data/images/wiki/fd79f148/Marayniyoq0001.webp'' -> ''/data/images/wiki/fd79f148/Marayniyoq0002.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (30, 'wiki_images', 'file_size_bytes', '107241', 'fd79f148-d931-42c7-8883-41732a93d209'::uuid, '594118', '175466', 'import-hero-rollback:wiki_images.file_size_bytes:107241', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 107241 returned to ''594118'' -> ''175466''', '[{"quote": "import-hero:wiki_images.file_size_bytes:107241: ''175466'' -> ''594118''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (31, 'wiki_images', 'filename', '107241', 'fd79f148-d931-42c7-8883-41732a93d209'::uuid, 'Marayniyoq0002.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:107241', 'rollback of import-hero chunk 004: wiki_images.filename on 107241 returned to ''Marayniyoq0002.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:107241: ''hero.webp'' -> ''Marayniyoq0002.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (32, 'wiki_images', 'height', '107241', 'fd79f148-d931-42c7-8883-41732a93d209'::uuid, '1200', '600', 'import-hero-rollback:wiki_images.height:107241', 'rollback of import-hero chunk 004: wiki_images.height on 107241 returned to ''1200'' -> ''600''', '[{"quote": "import-hero:wiki_images.height:107241: ''600'' -> ''1200''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (33, 'wiki_images', 'is_hero', '107239', 'fd79f148-d931-42c7-8883-41732a93d209'::uuid, 'false', 'true', 'import-hero-rollback:wiki_images.is_hero:107239', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107239 returned to ''false'' -> ''true''', '[{"quote": "import-hero:wiki_images.is_hero:107239: ''true'' -> ''false''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (34, 'wiki_images', 'is_hero', '107241', 'fd79f148-d931-42c7-8883-41732a93d209'::uuid, 'true', 'false', 'import-hero-rollback:wiki_images.is_hero:107241', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107241 returned to ''true'' -> ''false''', '[{"quote": "import-hero:wiki_images.is_hero:107241: ''false'' -> ''true''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (35, 'wiki_images', 'title', '107241', 'fd79f148-d931-42c7-8883-41732a93d209'::uuid, 'Marayniyoq0002', 'Marayniyoq', 'import-hero-rollback:wiki_images.title:107241', 'rollback of import-hero chunk 004: wiki_images.title on 107241 returned to ''Marayniyoq0002'' -> ''Marayniyoq''', '[{"quote": "import-hero:wiki_images.title:107241: ''Marayniyoq'' -> ''Marayniyoq0002''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (36, 'wiki_images', 'width', '107241', 'fd79f148-d931-42c7-8883-41732a93d209'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:107241', 'rollback of import-hero chunk 004: wiki_images.width on 107241 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:107241: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (37, 'unified_sites', 'thumbnail_url', 'fe268a4c-2d51-42f9-a00e-addd8fe217da', 'fe268a4c-2d51-42f9-a00e-addd8fe217da'::uuid, '/data/images/wiki/fe268a4c/The Longstone, Mottistone, IW, UK.webp', '/data/images/wiki/fe268a4c/The longstone, Mottistone, Isle of Wight, England (2).webp', 'import-hero-rollback:unified_sites.thumbnail_url:fe268a4c-2d51-42f9-a00e-addd8fe217da', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on fe268a4c-2d51-42f9-a00e-addd8fe217da returned to ''/data/images/wiki/fe268a4c/The Longstone, Mottistone, IW, UK.webp'' -> ''/data/images/wiki/fe268a4c/The longstone, Mottistone, Isle of Wight, England (2).webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:fe268a4c-2d51-42f9-a00e-addd8fe217da: ''/data/images/wiki/fe268a4c/The longstone, Mottistone, Isle of Wight, England (2).webp'' -> ''/data/images/wiki/fe268a4c/The Longstone, Mottistone, IW, UK.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (38, 'wiki_images', 'file_size_bytes', '107355', 'fe268a4c-2d51-42f9-a00e-addd8fe217da'::uuid, '476884', '227328', 'import-hero-rollback:wiki_images.file_size_bytes:107355', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 107355 returned to ''476884'' -> ''227328''', '[{"quote": "import-hero:wiki_images.file_size_bytes:107355: ''227328'' -> ''476884''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (39, 'wiki_images', 'filename', '107355', 'fe268a4c-2d51-42f9-a00e-addd8fe217da'::uuid, 'The Longstone, Mottistone, IW, UK.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:107355', 'rollback of import-hero chunk 004: wiki_images.filename on 107355 returned to ''The Longstone, Mottistone, IW, UK.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:107355: ''hero.webp'' -> ''The Longstone, Mottistone, IW, UK.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (40, 'wiki_images', 'height', '107355', 'fe268a4c-2d51-42f9-a00e-addd8fe217da'::uuid, '2133', '1067', 'import-hero-rollback:wiki_images.height:107355', 'rollback of import-hero chunk 004: wiki_images.height on 107355 returned to ''2133'' -> ''1067''', '[{"quote": "import-hero:wiki_images.height:107355: ''1067'' -> ''2133''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (41, 'wiki_images', 'is_hero', '107353', 'fe268a4c-2d51-42f9-a00e-addd8fe217da'::uuid, 'false', 'true', 'import-hero-rollback:wiki_images.is_hero:107353', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107353 returned to ''false'' -> ''true''', '[{"quote": "import-hero:wiki_images.is_hero:107353: ''true'' -> ''false''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (42, 'wiki_images', 'is_hero', '107355', 'fe268a4c-2d51-42f9-a00e-addd8fe217da'::uuid, 'true', 'false', 'import-hero-rollback:wiki_images.is_hero:107355', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107355 returned to ''true'' -> ''false''', '[{"quote": "import-hero:wiki_images.is_hero:107355: ''false'' -> ''true''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (43, 'wiki_images', 'title', '107355', 'fe268a4c-2d51-42f9-a00e-addd8fe217da'::uuid, 'The Longstone, Mottistone, IW, UK', 'The Longstone, Mottistone', 'import-hero-rollback:wiki_images.title:107355', 'rollback of import-hero chunk 004: wiki_images.title on 107355 returned to ''The Longstone, Mottistone, IW, UK'' -> ''The Longstone, Mottistone''', '[{"quote": "import-hero:wiki_images.title:107355: ''The Longstone, Mottistone'' -> ''The Longstone, Mottistone, IW, UK''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (44, 'wiki_images', 'width', '107355', 'fe268a4c-2d51-42f9-a00e-addd8fe217da'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:107355', 'rollback of import-hero chunk 004: wiki_images.width on 107355 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:107355: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (45, 'unified_sites', 'thumbnail_url', 'fe663edf-4b9e-480b-a976-c8ecf135249d', 'fe663edf-4b9e-480b-a976-c8ecf135249d'::uuid, '/data/images/wiki/fe663edf/8th century Durga temple exterior view, Aihole Hindu temples and monuments 3.webp', '/data/images/wiki/fe663edf/Huchimalligudi_Aihole_Karnataka.webp', 'import-hero-rollback:unified_sites.thumbnail_url:fe663edf-4b9e-480b-a976-c8ecf135249d', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on fe663edf-4b9e-480b-a976-c8ecf135249d returned to ''/data/images/wiki/fe663edf/8th century Durga temple exterior view, Aihole Hindu temples and monuments 3.webp'' -> ''/data/images/wiki/fe663edf/Huchimalligudi_Aihole_Karnataka.webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:fe663edf-4b9e-480b-a976-c8ecf135249d: ''/data/images/wiki/fe663edf/Huchimalligudi_Aihole_Karnataka.webp'' -> ''/data/images/wiki/fe663edf/8th century Durga temple exterior view, Aihole Hindu temples and monuments 3.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (46, 'wiki_images', 'file_size_bytes', '107404', 'fe663edf-4b9e-480b-a976-c8ecf135249d'::uuid, '255786', '75202', 'import-hero-rollback:wiki_images.file_size_bytes:107404', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 107404 returned to ''255786'' -> ''75202''', '[{"quote": "import-hero:wiki_images.file_size_bytes:107404: ''75202'' -> ''255786''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (47, 'wiki_images', 'filename', '107404', 'fe663edf-4b9e-480b-a976-c8ecf135249d'::uuid, '8th century Durga temple exterior view, Aihole Hindu temples and monuments 3.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:107404', 'rollback of import-hero chunk 004: wiki_images.filename on 107404 returned to ''8th century Durga temple exterior view, Aihole Hindu temples and monuments 3.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:107404: ''hero.webp'' -> ''8th century Durga temple exterior view, Aihole Hindu temples and monuments 3.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (48, 'wiki_images', 'height', '107404', 'fe663edf-4b9e-480b-a976-c8ecf135249d'::uuid, '1015', '507', 'import-hero-rollback:wiki_images.height:107404', 'rollback of import-hero chunk 004: wiki_images.height on 107404 returned to ''1015'' -> ''507''', '[{"quote": "import-hero:wiki_images.height:107404: ''507'' -> ''1015''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (49, 'wiki_images', 'is_hero', '107398', 'fe663edf-4b9e-480b-a976-c8ecf135249d'::uuid, 'false', 'true', 'import-hero-rollback:wiki_images.is_hero:107398', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107398 returned to ''false'' -> ''true''', '[{"quote": "import-hero:wiki_images.is_hero:107398: ''true'' -> ''false''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (50, 'wiki_images', 'is_hero', '107404', 'fe663edf-4b9e-480b-a976-c8ecf135249d'::uuid, 'true', 'false', 'import-hero-rollback:wiki_images.is_hero:107404', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107404 returned to ''true'' -> ''false''', '[{"quote": "import-hero:wiki_images.is_hero:107404: ''false'' -> ''true''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (51, 'wiki_images', 'title', '107404', 'fe663edf-4b9e-480b-a976-c8ecf135249d'::uuid, '8th century Durga temple exterior view, Aihole Hindu temples and monuments 3', 'Aihole', 'import-hero-rollback:wiki_images.title:107404', 'rollback of import-hero chunk 004: wiki_images.title on 107404 returned to ''8th century Durga temple exterior view, Aihole Hindu temples and monuments 3'' -> ''Aihole''', '[{"quote": "import-hero:wiki_images.title:107404: ''Aihole'' -> ''8th century Durga temple exterior view, Aihole Hindu temples and monuments 3''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (52, 'wiki_images', 'width', '107404', 'fe663edf-4b9e-480b-a976-c8ecf135249d'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:107404', 'rollback of import-hero chunk 004: wiki_images.width on 107404 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:107404: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (53, 'unified_sites', 'thumbnail_url', 'fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8', 'fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8'::uuid, '/data/images/wiki/fe7d7ee7/Calcaria.webp', NULL, 'import-hero-rollback:unified_sites.thumbnail_url:fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8 returned to ''/data/images/wiki/fe7d7ee7/Calcaria.webp'' -> None', '[{"quote": "import-hero:unified_sites.thumbnail_url:fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8: None -> ''/data/images/wiki/fe7d7ee7/Calcaria.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (54, 'wiki_images', 'file_size_bytes', '107436', 'fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8'::uuid, '216254', '100960', 'import-hero-rollback:wiki_images.file_size_bytes:107436', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 107436 returned to ''216254'' -> ''100960''', '[{"quote": "import-hero:wiki_images.file_size_bytes:107436: ''100960'' -> ''216254''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (55, 'wiki_images', 'filename', '107436', 'fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8'::uuid, 'Calcaria.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:107436', 'rollback of import-hero chunk 004: wiki_images.filename on 107436 returned to ''Calcaria.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:107436: ''hero.webp'' -> ''Calcaria.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (56, 'wiki_images', 'height', '107436', 'fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8'::uuid, '1200', '600', 'import-hero-rollback:wiki_images.height:107436', 'rollback of import-hero chunk 004: wiki_images.height on 107436 returned to ''1200'' -> ''600''', '[{"quote": "import-hero:wiki_images.height:107436: ''600'' -> ''1200''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (57, 'wiki_images', 'is_excluded', '107436', 'fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8'::uuid, 'false', 'true', 'import-hero-rollback:wiki_images.is_excluded:107436', 'rollback of import-hero chunk 004: wiki_images.is_excluded on 107436 returned to ''false'' -> ''true''', '[{"quote": "import-hero:wiki_images.is_excluded:107436: ''true'' -> ''false''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (58, 'wiki_images', 'is_hero', '107436', 'fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8'::uuid, 'true', 'false', 'import-hero-rollback:wiki_images.is_hero:107436', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107436 returned to ''true'' -> ''false''', '[{"quote": "import-hero:wiki_images.is_hero:107436: ''false'' -> ''true''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (59, 'wiki_images', 'width', '107436', 'fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:107436', 'rollback of import-hero chunk 004: wiki_images.width on 107436 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:107436: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (60, 'unified_sites', 'thumbnail_url', 'ff4dc88e-bebe-4b88-90d3-6697bffc9107', 'ff4dc88e-bebe-4b88-90d3-6697bffc9107'::uuid, '/data/images/wiki/ff4dc88e/Huamanmarka Archaeological site.webp', '/data/images/wiki/ff4dc88e/hero.webp', 'import-hero-rollback:unified_sites.thumbnail_url:ff4dc88e-bebe-4b88-90d3-6697bffc9107', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on ff4dc88e-bebe-4b88-90d3-6697bffc9107 returned to ''/data/images/wiki/ff4dc88e/Huamanmarka Archaeological site.webp'' -> ''/data/images/wiki/ff4dc88e/hero.webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:ff4dc88e-bebe-4b88-90d3-6697bffc9107: ''/data/images/wiki/ff4dc88e/hero.webp'' -> ''/data/images/wiki/ff4dc88e/Huamanmarka Archaeological site.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (61, 'wiki_images', 'file_size_bytes', '107632', 'ff4dc88e-bebe-4b88-90d3-6697bffc9107'::uuid, '535080', '143138', 'import-hero-rollback:wiki_images.file_size_bytes:107632', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 107632 returned to ''535080'' -> ''143138''', '[{"quote": "import-hero:wiki_images.file_size_bytes:107632: ''143138'' -> ''535080''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (62, 'wiki_images', 'filename', '107632', 'ff4dc88e-bebe-4b88-90d3-6697bffc9107'::uuid, 'Huamanmarka Archaeological site.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:107632', 'rollback of import-hero chunk 004: wiki_images.filename on 107632 returned to ''Huamanmarka Archaeological site.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:107632: ''hero.webp'' -> ''Huamanmarka Archaeological site.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (63, 'wiki_images', 'height', '107632', 'ff4dc88e-bebe-4b88-90d3-6697bffc9107'::uuid, '1200', '600', 'import-hero-rollback:wiki_images.height:107632', 'rollback of import-hero chunk 004: wiki_images.height on 107632 returned to ''1200'' -> ''600''', '[{"quote": "import-hero:wiki_images.height:107632: ''600'' -> ''1200''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (64, 'wiki_images', 'title', '107632', 'ff4dc88e-bebe-4b88-90d3-6697bffc9107'::uuid, 'Huamanmarka Archaeological site', 'Huamanmarca, La Convención', 'import-hero-rollback:wiki_images.title:107632', 'rollback of import-hero chunk 004: wiki_images.title on 107632 returned to ''Huamanmarka Archaeological site'' -> ''Huamanmarca, La Convención''', '[{"quote": "import-hero:wiki_images.title:107632: ''Huamanmarca, La Convención'' -> ''Huamanmarka Archaeological site''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (65, 'wiki_images', 'width', '107632', 'ff4dc88e-bebe-4b88-90d3-6697bffc9107'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:107632', 'rollback of import-hero chunk 004: wiki_images.width on 107632 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:107632: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (66, 'unified_sites', 'thumbnail_url', 'ffd8b3fc-4127-4b2b-9df1-212aac377683', 'ffd8b3fc-4127-4b2b-9df1-212aac377683'::uuid, '/data/images/wiki/ffd8b3fc/The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020.webp', '/data/images/wiki/ffd8b3fc/Orchomenos_Boeotia_AncientGreekTheater_0004_NorthView.webp', 'import-hero-rollback:unified_sites.thumbnail_url:ffd8b3fc-4127-4b2b-9df1-212aac377683', 'rollback of import-hero chunk 004: unified_sites.thumbnail_url on ffd8b3fc-4127-4b2b-9df1-212aac377683 returned to ''/data/images/wiki/ffd8b3fc/The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020.webp'' -> ''/data/images/wiki/ffd8b3fc/Orchomenos_Boeotia_AncientGreekTheater_0004_NorthView.webp''', '[{"quote": "import-hero:unified_sites.thumbnail_url:ffd8b3fc-4127-4b2b-9df1-212aac377683: ''/data/images/wiki/ffd8b3fc/Orchomenos_Boeotia_AncientGreekTheater_0004_NorthView.webp'' -> ''/data/images/wiki/ffd8b3fc/The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (67, 'wiki_images', 'file_size_bytes', '107754', 'ffd8b3fc-4127-4b2b-9df1-212aac377683'::uuid, '466438', '118138', 'import-hero-rollback:wiki_images.file_size_bytes:107754', 'rollback of import-hero chunk 004: wiki_images.file_size_bytes on 107754 returned to ''466438'' -> ''118138''', '[{"quote": "import-hero:wiki_images.file_size_bytes:107754: ''118138'' -> ''466438''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (68, 'wiki_images', 'filename', '107754', 'ffd8b3fc-4127-4b2b-9df1-212aac377683'::uuid, 'The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020.webp', 'hero.webp', 'import-hero-rollback:wiki_images.filename:107754', 'rollback of import-hero chunk 004: wiki_images.filename on 107754 returned to ''The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020.webp'' -> ''hero.webp''', '[{"quote": "import-hero:wiki_images.filename:107754: ''hero.webp'' -> ''The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020.webp''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (69, 'wiki_images', 'height', '107754', 'ffd8b3fc-4127-4b2b-9df1-212aac377683'::uuid, '1067', '533', 'import-hero-rollback:wiki_images.height:107754', 'rollback of import-hero chunk 004: wiki_images.height on 107754 returned to ''1067'' -> ''533''', '[{"quote": "import-hero:wiki_images.height:107754: ''533'' -> ''1067''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (70, 'wiki_images', 'is_hero', '107751', 'ffd8b3fc-4127-4b2b-9df1-212aac377683'::uuid, 'false', 'true', 'import-hero-rollback:wiki_images.is_hero:107751', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107751 returned to ''false'' -> ''true''', '[{"quote": "import-hero:wiki_images.is_hero:107751: ''true'' -> ''false''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (71, 'wiki_images', 'is_hero', '107754', 'ffd8b3fc-4127-4b2b-9df1-212aac377683'::uuid, 'true', 'false', 'import-hero-rollback:wiki_images.is_hero:107754', 'rollback of import-hero chunk 004: wiki_images.is_hero on 107754 returned to ''true'' -> ''false''', '[{"quote": "import-hero:wiki_images.is_hero:107754: ''false'' -> ''true''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (72, 'wiki_images', 'title', '107754', 'ffd8b3fc-4127-4b2b-9df1-212aac377683'::uuid, 'The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020', 'Orchomenus, Boeotia', 'import-hero-rollback:wiki_images.title:107754', 'rollback of import-hero chunk 004: wiki_images.title on 107754 returned to ''The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020'' -> ''Orchomenus, Boeotia''', '[{"quote": "import-hero:wiki_images.title:107754: ''Orchomenus, Boeotia'' -> ''The derelict state of the tower on the top of the Acropolis of Orchomenus on September 30, 2020''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb),
    (73, 'wiki_images', 'width', '107754', 'ffd8b3fc-4127-4b2b-9df1-212aac377683'::uuid, '1600', '800', 'import-hero-rollback:wiki_images.width:107754', 'rollback of import-hero chunk 004: wiki_images.width on 107754 returned to ''1600'' -> ''800''', '[{"quote": "import-hero:wiki_images.width:107754: ''800'' -> ''1600''", "source": "remediation_change_log (the row this undoes)", "url": "remediation_change_log.run_stamp=import-hero-2026-10-06-005-004"}]'::jsonb);

CREATE TEMP TABLE _img_may_empty (site_id UUID PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _img_may_empty (site_id) VALUES ('fe7d7ee7-ca93-4cf5-93d8-0cc80564ccd8'::uuid);

CREATE TEMP TABLE _img_live_before ON COMMIT DROP AS
  SELECT DISTINCT w.site_id FROM wiki_images w
   WHERE w.site_id IN (SELECT site_id FROM _img_plan) AND w.is_excluded IS NOT TRUE;

DO $$
DECLARE
    bad      integer;
    moved    integer := 0;
    expected integer := 73;
    r        RECORD;
BEGIN
    -- guard 1: every planned site is a curated site (the source is a RAISE argument, never
    -- part of the quoted message)
    SELECT count(*) INTO bad FROM (SELECT DISTINCT site_id FROM _img_plan) p
      LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned site(s) are not % sites', bad, 'ancient_nerds';
    END IF;

    -- guard 2: every planned image row exists and lives on the site the plan names
    SELECT count(*) INTO bad FROM _img_plan p
      LEFT JOIN wiki_images w ON w.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND (w.id IS NULL OR w.site_id IS DISTINCT FROM p.site_id);
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned image row(s) do not live on the site the plan names', bad;
    END IF;

    -- guard 3: every planned row still holds the planned old value (NULL-safe)

    SELECT count(*) INTO bad FROM _img_plan p JOIN unified_sites t ON t.id = CASE WHEN p.table_name = 'unified_sites' THEN p.row_key::uuid END
     WHERE p.table_name = 'unified_sites' AND p.column_name = 'thumbnail_url'
       AND t.thumbnail_url::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned thumbnail_url row(s) no longer hold the planned old value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'file_size_bytes'
       AND t.file_size_bytes::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned file_size_bytes row(s) no longer hold the planned old value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'filename'
       AND t.filename::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned filename row(s) no longer hold the planned old value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'height'
       AND t.height::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned height row(s) no longer hold the planned old value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'is_excluded'
       AND t.is_excluded::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned is_excluded row(s) no longer hold the planned old value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'is_hero'
       AND t.is_hero::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned is_hero row(s) no longer hold the planned old value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'title'
       AND t.title::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned title row(s) no longer hold the planned old value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'width'
       AND t.width::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned width row(s) no longer hold the planned old value', bad;
    END IF;

    -- the only writer
    FOR r IN SELECT * FROM _img_plan ORDER BY seq LOOP
        moved := moved + apply_remediation_change(
            r.table_name, r.column_name, 'id', r.row_key, r.old_value, r.new_value,
            'import-hero/owner-2026-10-05', 'import-hero-2026-10-06-005-004-rollback', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;
    IF moved <> expected THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds its new value

    SELECT count(*) INTO bad FROM _img_plan p JOIN unified_sites t ON t.id = CASE WHEN p.table_name = 'unified_sites' THEN p.row_key::uuid END
     WHERE p.table_name = 'unified_sites' AND p.column_name = 'thumbnail_url'
       AND t.thumbnail_url::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned thumbnail_url row(s) do not hold the new value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'file_size_bytes'
       AND t.file_size_bytes::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned file_size_bytes row(s) do not hold the new value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'filename'
       AND t.filename::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned filename row(s) do not hold the new value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'height'
       AND t.height::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned height row(s) do not hold the new value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'is_excluded'
       AND t.is_excluded::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned is_excluded row(s) do not hold the new value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'is_hero'
       AND t.is_hero::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned is_hero row(s) do not hold the new value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'title'
       AND t.title::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned title row(s) do not hold the new value', bad;
    END IF;

    SELECT count(*) INTO bad FROM _img_plan p JOIN wiki_images t ON t.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND p.column_name = 'width'
       AND t.width::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned width row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: plan -> journal, row for row, with the planned values and keys
    SELECT count(*) INTO bad FROM _img_plan p
      LEFT JOIN remediation_change_log l
        ON l.run_stamp = 'import-hero-2026-10-06-005-004-rollback' AND l.table_name = p.table_name
       AND l.column_name = p.column_name AND l.row_pk = p.row_key
     WHERE l.id IS NULL OR l.old_value IS DISTINCT FROM p.old_value
        OR l.new_value IS DISTINCT FROM p.new_value OR l.change_key IS DISTINCT FROM p.change_key;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % planned row(s) disagree with the journal', bad;
    END IF;

    -- invariant 3: journal -> plan: this run stamp journalled the planned rows and nothing else
    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = 'import-hero-2026-10-06-005-004-rollback'
       AND NOT EXISTS (SELECT 1 FROM _img_plan p
                        WHERE p.table_name = l.table_name AND p.column_name = l.column_name
                          AND p.row_key = l.row_pk);
    IF bad > 0 OR (SELECT count(*) FROM remediation_change_log WHERE run_stamp = 'import-hero-2026-10-06-005-004-rollback') <> expected THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: the journal of this run stamp is not the plan (% unplanned row(s))', bad;
    END IF;

    -- invariant 4: at most one hero per touched site
    -- the invariant the repair must leave behind: at most one hero per touched site
    -- (DISTINCT: _img_plan holds several rows per site, and a plain join would count each
    --  hero row twice - the check would then fail on a correct repair)
    SELECT count(*) INTO bad FROM (
        SELECT s.site_id FROM (SELECT DISTINCT site_id FROM _img_plan) s
          JOIN wiki_images w ON w.site_id = s.site_id
         GROUP BY s.site_id HAVING count(*) FILTER (WHERE w.is_hero) > 1) x;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % touched site(s) end with more than one hero', bad;
    END IF;

    -- invariant 5: no hero on an excluded row of a touched site
    SELECT count(*) INTO bad FROM wiki_images w
     WHERE w.site_id IN (SELECT site_id FROM _img_plan) AND w.is_hero AND w.is_excluded IS TRUE;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % hero row(s) are excluded', bad;
    END IF;

    -- invariant 6: a touched site that had a live image still has one, unless the chunk names it
    SELECT count(*) INTO bad FROM _img_live_before b
     WHERE NOT EXISTS (SELECT 1 FROM wiki_images w
                        WHERE w.site_id = b.site_id AND w.is_excluded IS NOT TRUE)
       AND b.site_id NOT IN (SELECT site_id FROM _img_may_empty);
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % site(s) lost their last live image', bad;
    END IF;

    -- invariant 7: every image kind of a touched row is in migration 0019's vocabulary
    SELECT count(*) INTO bad FROM wiki_images w
     WHERE w.site_id IN (SELECT site_id FROM _img_plan)
       AND w.image_kind IS NOT NULL AND w.image_kind NOT IN ('artifact', 'map_or_document', 'other', 'painting_or_artwork', 'people', 'site_photo', 'unknown');
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-005 - the import image takes the hero flag rollback chunk 004: % image kind(s) outside the vocabulary', bad;
    END IF;
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'import-hero-2026-10-06-005-004-rollback';
SELECT 'planned rows', count(*)::text FROM _img_plan;
COMMIT;
