"""The paper workspace and the pulled dossier.

dossier.json.gz      the bundle `theo_dossier export` streamed (spec 2.8)
dossier_from.json    {"request_id": RUN} when the dossier is a fresh run's, for the rewrite of
                     this public paper (`paper pull ID --dossier-from RUN`, owner decisions 17
                     and 18); absent otherwise
brief.md             the writer brief (generated by `paper pull`)
texts/<sid>.txt      the archived source texts from the dossier, one file per source
draft.md             Claude's draft, citing with [S:<source_id>]
paper_meta.json      Claude's {title, card_description}
evidence.json        Claude's evidence entries (validated by evidence.py)
sources.json         [N] -> source id, written by `paper number`
paper.md             the numbered paper with images and References (derived, never edited)
claims_check/        the claim-check handoff (tasks, prompts, verdicts, accepted)
images/              opportunities.json (Claude), candidates/, the image-check handoff,
                     selected/ and selected.json
check_report.json    every gate, written by `paper check`
bundle.json          the publish bundle (`paper bundle` rewrites it at will)
published_bundle.json the bundle a successful apply sent (publish or republish): the published
                     baseline a text correction is compared with
publish_outcome.json what theo_publish answered (`published_slug`: the slug of a successful apply);
                     a publish after the founder route unpublished the paper keeps the earlier
                     record as publish_outcome.<its at, colons removed>.json
"""

from __future__ import annotations

import gzip
import json
import zlib
from dataclasses import dataclass
from functools import cached_property
from pathlib import Path
from typing import Any

from pipeline.lyra.theo_citations import CitedSource
from pipeline.studio import config
from pipeline.studio.errors import StudioError

# The ten keys every export carries (spec 2.8). Stream A's export adds an eleventh,
# `texts_mode` ("cited" | "all"); extra keys are tolerated, missing ones refused.
DOSSIER_KEYS = frozenset(
    {
        "version",
        "request",
        "manifest",
        "moderated",
        "synthesis",
        "debate",
        "angles",
        "sources",
        "texts",
        "images",
    }
)


@dataclass(frozen=True)
class PaperWorkspace:
    root: Path
    request_id: str

    @property
    def dossier_gz(self) -> Path:
        return self.root / "dossier.json.gz"

    @property
    def dossier_from(self) -> Path:
        return self.root / "dossier_from.json"

    @property
    def brief(self) -> Path:
        return self.root / "brief.md"

    @property
    def texts_dir(self) -> Path:
        return self.root / "texts"

    @property
    def draft(self) -> Path:
        return self.root / "draft.md"

    @property
    def meta(self) -> Path:
        return self.root / "paper_meta.json"

    @property
    def evidence(self) -> Path:
        return self.root / "evidence.json"

    @property
    def sources_json(self) -> Path:
        return self.root / "sources.json"

    @property
    def paper(self) -> Path:
        return self.root / "paper.md"

    @property
    def claims_dir(self) -> Path:
        return self.root / "claims_check"

    @property
    def images_dir(self) -> Path:
        return self.root / "images"

    @property
    def check_report(self) -> Path:
        return self.root / "check_report.json"

    @property
    def checks(self) -> Path:
        """One line per run of the gates: the paper's own iteration count.

        The count lives beside the report it describes rather than in the driver's
        state, so a state file that is lost, shared or written by a foreign id cannot
        reset a paper's history.
        """
        return self.root / "checks.jsonl"

    @property
    def bundle(self) -> Path:
        return self.root / "bundle.json"

    @property
    def published_bundle(self) -> Path:
        return self.root / "published_bundle.json"

    @property
    def publish_outcome(self) -> Path:
        return self.root / "publish_outcome.json"

    def text_path(self, source_id: str) -> Path:
        return self.texts_dir / f"{source_id}.txt"

    def require(self, path: Path, hint: str) -> Path:
        if not path.exists():
            raise StudioError(f"{path} does not exist: {hint}")
        return path


def workspace(request_id: str) -> PaperWorkspace:
    return PaperWorkspace(config.paper_dir(request_id), request_id)


@dataclass(frozen=True)
class Dossier:
    data: dict[str, Any]

    @property
    def request_id(self) -> str:
        return self.data["request"]["id"]

    @property
    def question(self) -> str:
        return self.data["request"]["question"]

    @cached_property
    def sources(self) -> dict[str, dict[str, Any]]:
        return {s["id"]: s for s in self.data["sources"]}

    @property
    def texts(self) -> dict[str, str]:
        return self.data["texts"]

    @cached_property
    def citable_ids(self) -> list[str]:
        """The sources the writer may cite, in first-seen order.

        Stream A's `cited_source_ids` (the moderated claims' sources plus every source of an
        angle finding that shares one with them) is exactly the set whose non-TDM texts
        `theo_dossier export --texts cited` ships; ids missing from the registry are left out.
        """
        from pipeline.lyra.dossier_manifest import cited_source_ids

        cited = cited_source_ids(self.data["moderated"], self.data["angles"])
        return [sid for sid in cited if sid in self.sources]

    def text_status(self, source_id: str) -> str:
        """full_text | abstract_only | tdm_reserved | missing.

        Stream A's one classifier (`training_corpus.classify_archive_row`) reads the archive
        row the export ships in `sources[].archive`, the same function A's manifest counts
        use; a full text or abstract whose body the export did not ship is `missing` here.
        """
        from pipeline.lyra.training_corpus import classify_archive_row

        source = self.sources.get(source_id)
        if source is None:
            raise StudioError(f"source {source_id} is not in the dossier")
        status = classify_archive_row(source["archive"])
        if status in ("full_text", "abstract_only") and source_id not in self.texts:
            return "missing"
        return status

    def cited_source(self, source_id: str) -> CitedSource:
        """The dossier source as the registry type format_references_list renders."""
        s = self.sources.get(source_id)
        if s is None:
            raise StudioError(f"source {source_id} is not in the dossier")
        title = " ".join(str(s.get("title") or "").split())
        if not title:
            raise StudioError(f"source {source_id} has no title: cite another source")
        archive = s.get("archive") or {}
        return CitedSource(
            id=source_id,
            url=s["url"],
            title=title,
            snippet="",
            date=str(s.get("date") or ""),
            domain=str(s.get("domain") or ""),
            reliability_tier=int(s.get("reliability_tier") or 0),
            access_timestamp=str(archive.get("fetched_at") or ""),
            doi=str(s.get("doi") or ""),
            authors=list(s.get("authors") or []),
            venue=str(s.get("venue") or ""),
            source_api=str(s.get("source_api") or ""),
            license=str(s.get("license") or ""),
        )


def parse_dossier(raw: bytes) -> Dossier:
    """Decompress and check the exported bundle; refuse anything that is not version 1."""
    try:
        data = json.loads(gzip.decompress(raw).decode("utf-8"))
    # OSError: no gzip header or a bad CRC; EOFError: a truncated stream (an interrupted
    # ssh pipe); zlib.error: damaged deflate data; ValueError: not UTF-8 or not JSON.
    except (OSError, EOFError, zlib.error, ValueError) as exc:
        raise StudioError(f"the dossier export is not gzip'd JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise StudioError("the dossier export is not a JSON object")
    missing = sorted(DOSSIER_KEYS - data.keys())
    if missing:
        raise StudioError(f"the dossier export lacks {missing}")
    if data["version"] != 1:
        raise StudioError(f"dossier version {data['version']!r}; this studio reads version 1")
    return Dossier(data)


def dossier_request_id(ws: PaperWorkspace) -> str:
    """The request whose dossier this workspace holds: its own, or the fresh run it names.

    `paper pull TARGET --dossier-from RUN` rewrites the public paper TARGET from a fresh Theo
    run RUN on its question (owner decisions 17 and 18): the workspace, every image web path
    and every publish call stay TARGET's, the dossier is RUN's, and dossier_from.json names RUN.
    """
    if not ws.dossier_from.exists():
        return ws.request_id
    record = read_json(ws.dossier_from, "")
    if not isinstance(record, dict) or set(record) != {"request_id"}:
        raise StudioError('dossier_from.json must be exactly {"request_id": "<fresh run id>"}')
    return config.check_request_id(record["request_id"])


def load_dossier(ws: PaperWorkspace) -> Dossier:
    ws.require(ws.dossier_gz, f"run `python -m pipeline.studio paper pull {ws.request_id}`")
    dossier = parse_dossier(ws.dossier_gz.read_bytes())
    expected = dossier_request_id(ws)
    if dossier.request_id != expected:
        raise StudioError(f"dossier.json.gz belongs to {dossier.request_id}, not {expected}")
    return dossier


def read_json(path: Path, hint: str) -> Any:
    if not path.exists():
        raise StudioError(f"{path} does not exist: {hint}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except UnicodeDecodeError as exc:
        raise StudioError(f"{path.name} is not UTF-8 JSON: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise StudioError(f"{path.name} is not valid JSON: {exc}") from exc


def read_meta(ws: PaperWorkspace) -> dict[str, str]:
    """Claude's paper_meta.json, exactly {title, card_description}, both strings.

    Every step that reads it (numbering, the claim check, the check, the bundle, a
    correction) reads it here, so a malformed file is one StudioError, never a KeyError."""
    meta = read_json(ws.meta, "write paper_meta.json {title, card_description} from brief.md")
    if (
        not isinstance(meta, dict)
        or set(meta) != {"title", "card_description"}
        or not all(isinstance(value, str) for value in meta.values())
    ):
        raise StudioError(
            'paper_meta.json must be exactly {"title": "...", "card_description": "..."}'
        )
    return meta


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")


def published_slug(outcome: Path) -> str | None:
    """The slug a successful `paper publish` recorded in publish_outcome.json, else None.

    Only an apply that exited 0 with `ok: true` published the paper. A dry run (`apply` null),
    a refused apply (exit 1 still names the would-be slug) and an error outcome
    (`{ok: false, error}`, exit 2-4) did not.
    """
    if not outcome.exists():
        return None
    record = read_json(outcome, "")
    applied = record["apply"]
    if record.get("apply_exit_code") == 0 and applied is not None and applied["ok"] is True:
        return applied["slug"]
    return None
