-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: 53b98684680f160c9f14aec9b5719e915a1d4d04dc23178e582b8db8b88427c2
-- The reversal of lane 'ih6': the rows this wave created go back out, the flag returns to
-- the row that held it, and the thumbnail returns to the value the read found.
-- The row is named by the triple this lane wrote - (site_id, original_url, file_size_bytes) - so
-- the statement cannot delete a row somebody else created.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_uninsert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    original_url      TEXT NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT,
    change_key        TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_uninsert VALUES
    (1, '9755c087-8b24-46e2-9785-b5ac6c91f3ea'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Moray_-_Qechuyoq.JPG', 846532, 86784, '/data/images/wiki/9755c087/Moray, 2023 (13).webp', '/data/images/wiki/9755c087/Moray - Qechuyoq.webp', 'import-hero/insert:9755c087-8b24-46e2-9785-b5ac6c91f3ea'),
    (2, '9a95f005-3bee-4270-a718-5aad8b971a5b'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/21/Erice_mura3.jpg', 580084, NULL, '/data/images/wiki/9a95f005/Erice_Sicily_Italy_25.webp', '/data/images/wiki/9a95f005/Erice mura3.webp', 'import-hero/insert:9a95f005-3bee-4270-a718-5aad8b971a5b'),
    (3, '9aab078b-ef81-43a1-8169-235e5b22dd34'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Longyou_Xiaonanhai_Shishi_2016.12.11_16-10-51.jpg', 343486, 87379, '/data/images/wiki/9aab078b/Longyou Xiaonanhai Shishi 2016.12.11 16-07-21.webp', '/data/images/wiki/9aab078b/Longyou Xiaonanhai Shishi 2016.12.11 16-10-51.webp', 'import-hero/insert:9aab078b-ef81-43a1-8169-235e5b22dd34'),
    (4, '9d6541e1-162d-475e-a01a-efa1da58c9ee'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/93/Al_Ula_old_town%2C_Saudi_Arabia_2011.jpg', 455182, 88028, '/data/images/wiki/9d6541e1/Al-Ula_Old_Town_2021.webp', '/data/images/wiki/9d6541e1/Al Ula old town, Saudi Arabia 2011.webp', 'import-hero/insert:9d6541e1-162d-475e-a01a-efa1da58c9ee'),
    (5, 'a808b0ee-786e-4677-92d6-1eb5a15e297a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Roman_villa_of_els_Munts_La_Tartana_image_50752513.jpg', 707936, 89845, '/data/images/wiki/a808b0ee/151 Vil·la romana dels Munts (Altafulla), les termes, vistes des de l''oest.webp', '/data/images/wiki/a808b0ee/Roman villa of els Munts La Tartana image 50752513.webp', 'import-hero/insert:a808b0ee-786e-4677-92d6-1eb5a15e297a'),
    (6, 'ab077874-2a7f-4add-adec-8cb42e9e9561'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/02/Madain_Saleh_%286811791359%29.jpg', 259204, 90366, '/data/images/wiki/ab077874/Qasr_al_Farid.webp', '/data/images/wiki/ab077874/Madain Saleh (6811791359).webp', 'import-hero/insert:ab077874-2a7f-4add-adec-8cb42e9e9561'),
    (7, 'ab6ffb1d-c6d2-4c14-96e8-7f76a2607d7d'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Amnissos_fresco._Iraklion%2C_Crete%2C_Archaeological_Museum.jpg', 695184, 90481, '/data/images/wiki/ab6ffb1d/Έπαυλη_των_Κρίνων_-_Αμνισός_3273.webp', '/data/images/wiki/ab6ffb1d/Amnissos fresco. Iraklion, Crete, Archaeological Museum.webp', 'import-hero/insert:ab6ffb1d-c6d2-4c14-96e8-7f76a2607d7d'),
    (8, 'ac46cdfd-877f-47d4-8403-90d21983364f'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/a/a7/The_Acropolis_of_Athens_viewed_from_the_Hill_of_the_Muses_%2814220794964%29.jpg', 404458, NULL, '/data/images/wiki/ac46cdfd/1029_Acropolis_of_Athens_in_Greece_at_night_Photo_by_Giles_Laurent.webp', '/data/images/wiki/ac46cdfd/The Acropolis of Athens viewed from the Hill of the Muses (14220794964).webp', 'import-hero/insert:ac46cdfd-877f-47d4-8403-90d21983364f'),
    (9, 'ad73de2d-5176-4436-a2fb-4b75c81fb234'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Grap%C4%8Deva_cave_20220727_03.jpg', 233516, NULL, NULL, '/data/images/wiki/ad73de2d/Grapčeva cave 20220727 03.webp', 'import-hero/insert:ad73de2d-5176-4436-a2fb-4b75c81fb234'),
    (10, 'b1e7b190-e66c-49da-8df8-2b1345fa68fd'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Slune%C4%8Dn%C3%AD_br%C3%A1na_-_Puerta_del_Sol%2C_Tiwanaku_-_panoramio_%281%29.jpg', 329392, 91902, '/data/images/wiki/b1e7b190/Tiwanaku_-_Puerta_de_la_Luna_-_panoramio.webp', '/data/images/wiki/b1e7b190/Sluneční brána - Puerta del Sol, Tiwanaku - panoramio (1).webp', 'import-hero/insert:b1e7b190-e66c-49da-8df8-2b1345fa68fd'),
    (11, 'b5e251e7-b1d1-46d4-8bba-b02956ff13c9'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/85/Cuevas_de_Nerja.JPG', 616224, 92705, '/data/images/wiki/b5e251e7/Cueva_de_Nerja_2020.webp', '/data/images/wiki/b5e251e7/Cuevas de Nerja.webp', 'import-hero/insert:b5e251e7-b1d1-46d4-8bba-b02956ff13c9'),
    (12, 'bcc97a7c-6bba-4f86-abe0-18d57356eaf2'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/7/77/St_Marys_Church%2C_Credenhill_%28geograph_2557447%29.jpg', 357902, NULL, NULL, '/data/images/wiki/bcc97a7c/St Marys Church, Credenhill (geograph 2557447).webp', 'import-hero/insert:bcc97a7c-6bba-4f86-abe0-18d57356eaf2'),
    (13, 'c070b6b0-3fd2-4d6c-acbe-105539188253'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/49/Eartham_Pit%2C_Boxgrove.JPG', 280010, 94693, '/data/images/wiki/c070b6b0/Boxgrove_handaxe.webp', '/data/images/wiki/c070b6b0/Eartham Pit, Boxgrove.webp', 'import-hero/insert:c070b6b0-3fd2-4d6c-acbe-105539188253'),
    (14, 'c15b3210-d987-4ced-9d94-1f3af0d41905'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/8a/ArcAR.jpg', 195156, 94835, '/data/images/wiki/c15b3210/20141109- DSC1706 (15877644631).webp', '/data/images/wiki/c15b3210/ArcAR.webp', 'import-hero/insert:c15b3210-d987-4ced-9d94-1f3af0d41905'),
    (15, 'c2e7a1e8-c56f-40e9-8516-79e0c6bdd747'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/8a/%CE%A0%CF%8D%CE%BB%CE%B7_%CE%91%CF%81%CF%87%CE%B1%CE%AF%CE%B1%CF%82_%CE%A1%CF%89%CE%BC%CE%B1%CF%8A%CE%BA%CE%AE%CF%82_%CE%91%CE%B3%CE%BF%CF%81%CE%AC%CF%82%2C_%CE%91%CE%B8%CE%AE%CE%BD%CE%B1_6186.jpg', 362412, 95266, '/data/images/wiki/c2e7a1e8/The_Gate_of_Athena_Archegetis_in_Athens_on_May_6,_2021.webp', '/data/images/wiki/c2e7a1e8/Πύλη Αρχαίας Ρωμαϊκής Αγοράς, Αθήνα 6186.webp', 'import-hero/insert:c2e7a1e8-c56f-40e9-8516-79e0c6bdd747'),
    (16, 'c8ec86a6-5e59-47c9-a1be-51db69a2f0d7'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Castlerigg_Stone_Circle.JPG', 663488, 96568, '/data/images/wiki/c8ec86a6/1011362 Castlerigg stone circle St. John''s Castlerigg and Wythburn 20240526 0001.webp', '/data/images/wiki/c8ec86a6/Castlerigg Stone Circle.webp', 'import-hero/insert:c8ec86a6-5e59-47c9-a1be-51db69a2f0d7'),
    (17, 'cb100b64-537e-4105-802b-acf4d530254e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Town_of_Ollantaytambo.jpg', 644954, NULL, '/data/images/wiki/cb100b64/- panoramio (274).webp', '/data/images/wiki/cb100b64/Town of Ollantaytambo.webp', 'import-hero/insert:cb100b64-537e-4105-802b-acf4d530254e'),
    (18, 'cc89fe8f-328b-470e-adcd-0d1244f28acf'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/20/Isabella_Plantation%2C_Richmond_Park%2C_London_-_April_2011.jpg', 1143142, 97561, '/data/images/wiki/cc89fe8f/Panorama_of_King_Henry''s_Mound.webp', '/data/images/wiki/cc89fe8f/Isabella Plantation, Richmond Park, London - April 2011.webp', 'import-hero/insert:cc89fe8f-328b-470e-adcd-0d1244f28acf'),
    (19, 'cecfe56c-84f1-4958-b40e-ebaf52ace4a9'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/20/Fossato_tra_torre_d%27italia_e_porta_san_giovanni%2C_bastione_con_stemma_pierre_d%27aubusson_00.jpg', 430774, 98040, '/data/images/wiki/cecfe56c/Fortifications_of_the_Medieval_City_of_Rhodes_Viewed_from_the_East.webp', '/data/images/wiki/cecfe56c/Fosato tra torre d''italia e porta san giovanni, bastione con stemma pierre d''aubusson 00.webp', 'import-hero/insert:cecfe56c-84f1-4958-b40e-ebaf52ace4a9'),
    (20, 'd0b9e72f-73a8-4671-a01f-5cafa6e53bf8'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/41/White_Temple_ziggurat_in_Uruk.jpg', 157132, 98518, '/data/images/wiki/d0b9e72f/معبد_كاريوس_...اوروك_...._مدينة_الوركاء_..._المثنى.webp', '/data/images/wiki/d0b9e72f/White Temple ziggurat in Uruk.webp', 'import-hero/insert:d0b9e72f-73a8-4671-a01f-5cafa6e53bf8'),
    (21, 'd953e9b3-de33-4c7d-9357-bbc5d94d2a16'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/d5/G%C3%B6bekli_Tepe%2C_Urfa.jpg', 565444, NULL, '/data/images/wiki/d953e9b3/Gobekli_Tepe,_enclosure_D_stela._Şanlıurfa_Museum.webp', '/data/images/wiki/d953e9b3/Göbekli Tepe, Urfa.webp', 'import-hero/insert:d953e9b3-de33-4c7d-9357-bbc5d94d2a16'),
    (22, 'da62b3af-331d-461c-a715-d64e35870466'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Neu-Kalabscha_Dedwen_05.JPG', 410762, NULL, NULL, '/data/images/wiki/da62b3af/Neu-Kalabscha Dedwen 05.webp', 'import-hero/insert:da62b3af-331d-461c-a715-d64e35870466'),
    (23, 'ddd6cdfa-6891-4f6f-932a-e276f2be47bd'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e3/%D0%90%D1%80%D1%85%D1%96%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BD%D0%BE-%D0%B0%D1%80%D1%85%D0%B5%D0%BE%D0%BB%D0%BE%D0%B3%D1%96%D1%87%D0%BD%D0%B8%D0%B9_%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81_%C2%AB%D0%A1%D1%82%D0%B0%D1%80%D0%BE%D0%B4%D0%B0%D0%B2%D0%BD%D1%94_%D0%BC%D1%96%D1%81%D1%82%D0%BE_%D0%9F%D0%B0%D0%BD%D1%82%D1%96%D0%BA%D0%B0%D0%BF%D0%B5%D0%B9%C2%BB.JPG', 497638, 100978, '/data/images/wiki/ddd6cdfa/2015. Пантикапей 002.webp', '/data/images/wiki/ddd6cdfa/Архітектурно-археологічний комплекс «Стародавнє місто Пантікапей».webp', 'import-hero/insert:ddd6cdfa-6891-4f6f-932a-e276f2be47bd'),
    (24, 'dde17f3b-8489-41f6-83e4-7cb23927e266'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/02/Positano_veduta_003.jpg', 500678, NULL, NULL, '/data/images/wiki/dde17f3b/Positano veduta 003.webp', 'import-hero/insert:dde17f3b-8489-41f6-83e4-7cb23927e266'),
    (25, 'de42523e-9322-4dba-9448-016174872c48'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/01/Teonate.JPG', 250692, 101054, '/data/images/wiki/de42523e/Cabeza_de_felino,_Teotihuacán,_México,_2013-10-13,_DD_03.webp', '/data/images/wiki/de42523e/Teonate.webp', 'import-hero/insert:de42523e-9322-4dba-9448-016174872c48'),
    (26, 'e06caf0a-2a7c-44d5-8cdb-5473d995f896'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Amaru_Markawasi_7.jpg', 852120, NULL, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Templo_Cusco_Luna_Sup.jpg/1280px-Templo_Cusco_Luna_Sup.jpg', '/data/images/wiki/e06caf0a/Amaru Markawasi 7.webp', 'import-hero/insert:e06caf0a-2a7c-44d5-8cdb-5473d995f896'),
    (27, 'e3a400b7-f8cd-4c4d-a2b0-b79ac18d2258'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/14/Acanceh1.jpg', 398126, 102250, '/data/images/wiki/e3a400b7/Acanceh pyramid, Yucatan, Mexico April 2021.webp', '/data/images/wiki/e3a400b7/Acanceh1.webp', 'import-hero/insert:e3a400b7-f8cd-4c4d-a2b0-b79ac18d2258'),
    (28, 'ef479a70-837a-468b-b107-86751269b431'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Akeman_Street.jpg', 386702, 104311, '/data/images/wiki/ef479a70/Akeman_Street.webp', '/data/images/wiki/ef479a70/Akeman Street.webp', 'import-hero/insert:ef479a70-837a-468b-b107-86751269b431'),
    (29, 'f3c2a268-f63e-41be-b587-1885a7e1cfae'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/de/Birka_Boot_2008.JPG', 736278, 105241, '/data/images/wiki/f3c2a268/Birka Vikingabegravningar.webp', '/data/images/wiki/f3c2a268/Birka Boot 2008.webp', 'import-hero/insert:f3c2a268-f63e-41be-b587-1885a7e1cfae'),
    (30, 'f7dd4933-c591-4d4a-b900-22edb8cb2276'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Senlis_%2860%29%2C_fa%C3%A7ade_nord-est_de_l%27ancien_%C3%A9v%C3%AAch%C3%A9_depuis_la_rue_aux_Flageards.jpg', 349000, 106171, '/data/images/wiki/f7dd4933/Portail_de_l''ancien_château_royal_depuis_l''impasse_Saint-Maurice.webp', '/data/images/wiki/f7dd4933/Senlis (60), façade nord-est de l''ancien évêché depuis la rue aux Flageards.webp', 'import-hero/insert:f7dd4933-c591-4d4a-b900-22edb8cb2276'),
    (31, 'fadd9ef3-4d6a-4a8b-8b2a-250388ee531d'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/33/BW_Heuneburg_01.jpg', 488564, 106754, '/data/images/wiki/fadd9ef3/Heuneburg_(Hundersingen)-6065.webp', '/data/images/wiki/fadd9ef3/BW Heuneburg 01.webp', 'import-hero/insert:fadd9ef3-4d6a-4a8b-8b2a-250388ee531d'),
    (32, 'fd7f614f-4547-4b2d-9534-a0b7f61d20eb'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Iximch%C3%A9_%285%29_%2838826491572%29.jpg', 379572, 107255, '/data/images/wiki/fd7f614f/Iximche_guatemala_2009.webp', '/data/images/wiki/fd7f614f/Iximché (5) (38826491572).webp', 'import-hero/insert:fd7f614f-4547-4b2d-9534-a0b7f61d20eb'),
    (33, 'fe252099-6b31-4704-bb59-2b03b02252f5'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Chesterfield_Montage.jpg', 387318, 107336, '/data/images/wiki/fe252099/Chesterfield_Parish_Church.webp', '/data/images/wiki/fe252099/Chesterfield Montage.webp', 'import-hero/insert:fe252099-6b31-4704-bb59-2b03b02252f5'),
    (34, 'fead42ae-fdd5-48d1-bcc9-567c1c7873b8'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Denbury_Hill_Fort_-_Earthworks_-_geograph.org.uk_-_2350383.jpg', 865734, 107486, '/data/images/wiki/fead42ae/East-Facing_View_of_Denbury_Down.webp', '/data/images/wiki/fead42ae/Denbury Hill Fort - Earthworks - geograph.org.uk - 2350383.webp', 'import-hero/insert:fead42ae-fdd5-48d1-bcc9-567c1c7873b8'),
    (35, 'ff1c4702-9115-43fc-b64f-15a9729bc6d9'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Kharkhorum_Museum_in_Kharkhorin%2C_Mongolia.jpg', 139260, 107575, '/data/images/wiki/ff1c4702/hero.webp', '/data/images/wiki/ff1c4702/Kharkhorum Museum in Kharkhorin, Mongolia.webp', 'import-hero/insert:ff1c4702-9115-43fc-b64f-15a9729bc6d9'),
    (36, 'ff3dcd2e-6e3b-405b-a532-09b7cf71dff0'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/44/Sarc%C3%B3fagos_de_Karaj%C3%ADa-1.jpg', 632674, 107613, '/data/images/wiki/ff3dcd2e/Karajía, 2023 (01).webp', '/data/images/wiki/ff3dcd2e/Sarcófagos de Karajía-1.webp', 'import-hero/insert:ff3dcd2e-6e3b-405b-a532-09b7cf71dff0'),
    (37, 'ff76a431-09d7-40b4-8dc5-b80211b2e246'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/26/%CE%A3%CE%B1%CE%B3%CF%81%CE%AC%CE%B4%CE%B1_%CE%A6%CE%B1%CE%BC%CE%AF%CE%BB%CE%B9%CE%B1_2941.jpg', 721520, 107698, '/data/images/wiki/ff76a431/Muralla_Raval.webp', '/data/images/wiki/ff76a431/Σαγράδα Φαμίλια 2941 (cropped).webp', 'import-hero/insert:ff76a431-09d7-40b4-8dc5-b80211b2e246');

DO $$
DECLARE
    bad integer;
BEGIN
    -- every named row is still the one this wave created
    SELECT count(*) INTO bad FROM _ih_uninsert r
      LEFT JOIN wiki_images w
        ON w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes
     WHERE w.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'rollback %: % row(s) this wave created are not there to undo',
            'import-hero-2026-10-06-006-002', bad;
    END IF;

    DELETE FROM wiki_images w USING _ih_uninsert r
     WHERE w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes;

    UPDATE wiki_images w SET is_hero = true
      FROM _ih_uninsert r
     WHERE r.demoted_id IS NOT NULL AND w.id = r.demoted_id AND w.is_hero IS NOT TRUE;

    UPDATE unified_sites u SET thumbnail_url = r.old_thumbnail
      FROM _ih_uninsert r
     WHERE u.id = r.site_id AND r.new_thumbnail IS DISTINCT FROM r.old_thumbnail
       AND u.thumbnail_url IS DISTINCT FROM r.old_thumbnail;

    -- the journal goes with the write it describes
    DELETE FROM remediation_change_log l USING _ih_uninsert r
     WHERE l.run_stamp = 'import-hero-2026-10-06-006-002' AND l.change_key LIKE r.change_key || '%';
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'import-hero-2026-10-06-006-002';
SELECT 'rows this chunk created',
       count(*)::text
  FROM wiki_images w
  JOIN _ih_uninsert r ON w.site_id = r.site_id AND w.original_url = r.original_url
                    AND w.file_size_bytes = r.file_size_bytes;
COMMIT;
