-- plan sha256 563313084e860b08f6edb22938f53bc623b694c8392b1e6ed547f5dc55b91c5a
-- Generated by scripts/remediation/mechanical/apply.py - do not edit by hand.
-- 4 row(s) over 2 site(s); scope source_id = 'ancient_nerds';
-- run stamp '2026-09-26_mechanical-name-l5-rollback'; journal test id 'B1/name-l5'.
-- Every UPDATE is conditioned on the old value the plan names; every change is journalled
-- in the same transaction, so the audit trail cannot disagree with the data.
\set ON_ERROR_STOP on
BEGIN;

-- The server bounds this transaction itself: a lock wait or a runaway statement raises
-- here, psql stops the script (exit 3) and nothing is kept. A client that gives up does
-- not stop the server - psql has the whole script on its stdin.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _name_l5_plan (
    site_id     UUID NOT NULL,
    column_name TEXT NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    evidence    JSONB NOT NULL,
    PRIMARY KEY (site_id, column_name)
) ON COMMIT DROP;

INSERT INTO _name_l5_plan (site_id, column_name, old_value, new_value, change_key, reason, evidence) VALUES
    ('1d7cca0c-fb61-4b09-8692-52781474ed3e'::uuid, 'name', 'Dhank Caves', 'Dhank Buddhist Archaeological Site', 'name-l5-rollback:1d7cca0c-fb61-4b09-8692-52781474ed3e:name', 'rollback of name-l5: name ''Dhank Buddhist Archaeological Site'' restored on Dhank Buddhist Archaeological Site', '[{"source": "https://en.wikipedia.org/wiki/Dhank_Caves", "url": "https://en.wikipedia.org/wiki/Dhank_Caves", "quote": "The Dhank Caves are located near Dhank village near Upleta, Rajkot district, Gujarat, India."}, {"source": "https://en.wikipedia.org/wiki/Dhank_Caves", "url": "https://en.wikipedia.org/wiki/Dhank_Caves", "quote": "The caves are influenced by Buddhist and Jain cultures."}]'::jsonb),
    ('1d7cca0c-fb61-4b09-8692-52781474ed3e'::uuid, 'name_normalized', 'dhank caves', 'dhank buddhist archaeological site', 'name-l5-rollback:1d7cca0c-fb61-4b09-8692-52781474ed3e:name_normalized', 'rollback of name-l5: name_normalized ''dhank buddhist archaeological site'' restored on Dhank Buddhist Archaeological Site', '[{"source": "https://en.wikipedia.org/wiki/Dhank_Caves", "url": "https://en.wikipedia.org/wiki/Dhank_Caves", "quote": "The Dhank Caves are located near Dhank village near Upleta, Rajkot district, Gujarat, India."}, {"source": "https://en.wikipedia.org/wiki/Dhank_Caves", "url": "https://en.wikipedia.org/wiki/Dhank_Caves", "quote": "The caves are influenced by Buddhist and Jain cultures."}]'::jsonb),
    ('3199f739-6eaf-4065-8a07-4e44ec4695f7'::uuid, 'name', 'Arch of Augustus', 'Augustòs Arch', 'name-l5-rollback:3199f739-6eaf-4065-8a07-4e44ec4695f7:name', 'rollback of name-l5: name ''Augustòs Arch'' restored on Augustòs Arch', '[{"source": "https://en.wikipedia.org/wiki/Arch_of_Augustus_(Susa)", "url": "https://en.wikipedia.org/wiki/Arch_of_Augustus_(Susa)", "quote": "The Arch of Augustus is an Ancient Roman arch constructed in the city of Susa"}, {"source": "https://www.wikidata.org/wiki/Special:EntityData/Q1892101.json", "url": "https://www.wikidata.org/wiki/Special:EntityData/Q1892101.json", "quote": "Arch of Augustus"}]'::jsonb),
    ('3199f739-6eaf-4065-8a07-4e44ec4695f7'::uuid, 'name_normalized', 'arch of augustus', 'augustos arch', 'name-l5-rollback:3199f739-6eaf-4065-8a07-4e44ec4695f7:name_normalized', 'rollback of name-l5: name_normalized ''augustos arch'' restored on Augustòs Arch', '[{"source": "https://en.wikipedia.org/wiki/Arch_of_Augustus_(Susa)", "url": "https://en.wikipedia.org/wiki/Arch_of_Augustus_(Susa)", "quote": "The Arch of Augustus is an Ancient Roman arch constructed in the city of Susa"}, {"source": "https://www.wikidata.org/wiki/Special:EntityData/Q1892101.json", "url": "https://www.wikidata.org/wiki/Special:EntityData/Q1892101.json", "quote": "Arch of Augustus"}]'::jsonb);

DO $$
DECLARE
    bad      INTEGER;
    moved    INTEGER := 0;
    expected INTEGER := 4;
    r        RECORD;
BEGIN
    -- expected is the plan's own row count, rendered here, and not a second count of the
    -- temp table the loop below iterates: counting the same table twice would make the
    -- comparison after the loop a tautology. The instance that makes a short loop
    -- unreachable is apply_remediation_change, which raises unless exactly one row
    -- matched; this guard is what reports a loop that changed fewer rows than the plan.

    -- scope guard 1: every planned row is a curated site that still exists
    SELECT count(*) INTO bad
      FROM _name_l5_plan p LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        -- the source name is a RAISE argument, never part of the quoted message: a name
        -- spliced into the message text only parses while the name happens to contain no
        -- quote, which is a property of today's value and not of this code. G0's guard is
        -- the shape this one copies.
        RAISE EXCEPTION 'L5 name repair: % planned row(s) are not % sites', bad, 'ancient_nerds';
    END IF;

    -- scope guard 2: the plan is a set of real changes, each one writable in its column
    -- (compared in the column's own type; CASE, because only CASE fixes the order in
    -- which the casts are evaluated)
    SELECT count(*) INTO bad FROM _name_l5_plan p
     WHERE p.new_value = '' OR CASE p.column_name
                WHEN 'name' THEN p.new_value::character varying IS NOT DISTINCT FROM p.old_value::character varying OR p.old_value IS NULL OR p.new_value IS NULL OR length(p.new_value) > 500
                WHEN 'name_normalized' THEN p.new_value::character varying IS NOT DISTINCT FROM p.old_value::character varying OR p.old_value IS NULL OR p.new_value IS NULL OR length(p.new_value) > 500
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'L5 name repair: % planned row(s) are not writable changes', bad;
    END IF;

    -- scope guard 3: every planned row still holds the old value the plan names
    SELECT count(*) INTO bad
      FROM _name_l5_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE CASE p.column_name
                WHEN 'name' THEN u.name IS DISTINCT FROM p.old_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS DISTINCT FROM p.old_value::character varying
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'L5 name repair: % planned row(s) no longer hold the planned old value', bad;
    END IF;

    -- the only writer: the conditional UPDATE and its journal row commit together, and
    -- the function raises unless exactly one row matched
    FOR r IN SELECT * FROM _name_l5_plan ORDER BY site_id, column_name LOOP
        moved := moved + apply_remediation_change(
            'unified_sites', r.column_name, 'id', r.site_id::text,
            r.old_value, r.new_value,
            'B1/name-l5', '2026-09-26_mechanical-name-l5-rollback', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;

    IF moved <> expected THEN
        RAISE EXCEPTION 'L5 name repair: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds the new value
    SELECT count(*) INTO bad
      FROM _name_l5_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE CASE p.column_name
                WHEN 'name' THEN u.name IS DISTINCT FROM p.new_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS DISTINCT FROM p.new_value::character varying
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'L5 name repair: % planned row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: the journal and the data agree, row for row, in both directions
    SELECT count(*) INTO bad
      FROM _name_l5_plan p LEFT JOIN remediation_change_log l
        ON l.row_pk = p.site_id::text AND l.table_name = 'unified_sites'
       AND l.column_name = p.column_name
       AND l.run_stamp = '2026-09-26_mechanical-name-l5-rollback'
     WHERE l.id IS NULL
        OR l.new_value IS DISTINCT FROM p.new_value
        OR l.old_value IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'L5 name repair: % planned row(s) have no matching journal row', bad;
    END IF;

    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = '2026-09-26_mechanical-name-l5-rollback'
       AND (l.table_name <> 'unified_sites' OR l.column_name NOT IN ('name', 'name_normalized'));
    IF bad > 0 THEN
        RAISE EXCEPTION 'L5 name repair: this run stamp journalled % row(s) outside unified_sites.(name, name_normalized)', bad;
    END IF;

    -- invariant 3, the lane's own: no planned site is one of the
    -- curated rows whose name_normalized is not the key of their name
    SELECT count(*) INTO bad FROM unified_sites
     WHERE id IN (SELECT site_id FROM _name_l5_plan)
       AND (name_normalized IS DISTINCT FROM left(lower(unaccent(name)), 500));
    IF bad > 0 THEN
        RAISE EXCEPTION 'L5 name repair: % planned site(s) break the lane invariant after the write', bad;
    END IF;

    RAISE NOTICE 'L5 name repair: % of % planned cell(s) changed and journalled over 2 curated site(s)',
        moved, expected;
END $$;

COMMIT;

-- Post-commit read: the numbers the report quotes, from the database, not from the plan.
SELECT 'journal rows for this run stamp' AS metric, count(*)::text AS value
  FROM remediation_change_log WHERE run_stamp = '2026-09-26_mechanical-name-l5-rollback'
UNION ALL
SELECT 'journal rows for this test id', count(*)::text
  FROM remediation_change_log WHERE test_id = 'B1/name-l5'
UNION ALL
SELECT 'planned rows now holding the new value', count(*)::text
  FROM remediation_change_log l
 WHERE l.run_stamp = '2026-09-26_mechanical-name-l5-rollback' AND l.table_name = 'unified_sites'
   AND l.column_name IN ('name', 'name_normalized')
   AND EXISTS (SELECT 1 FROM unified_sites u
                WHERE u.id::text = l.row_pk AND CASE l.column_name
                WHEN 'name' THEN u.name IS NOT DISTINCT FROM l.new_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS NOT DISTINCT FROM l.new_value::character varying
                ELSE false END)
UNION ALL
SELECT 'curated rows whose name_normalized is not the key of their name', count(*)::text
  FROM unified_sites
 WHERE source_id = 'ancient_nerds' AND name_normalized IS DISTINCT FROM left(lower(unaccent(name)), 500)
UNION ALL
SELECT 'curated sites', count(*)::text
  FROM unified_sites WHERE source_id = 'ancient_nerds';
