-- plan sha256 f3e883dcfc10168c83cf580a795b7c5acea73c9d026760ad765cb52dfe4d60ee
-- Generated by scripts/remediation/mechanical/apply.py - do not edit by hand.
-- 2 row(s) over 1 site(s); scope source_id = 'ancient_nerds';
-- run stamp '2026-09-29_mechanical-chiapa-hide-rollback'; journal test id 'Nr7/duplicate-hide'.
-- Every UPDATE is conditioned on the old value the plan names; every change is journalled
-- in the same transaction, so the audit trail cannot disagree with the data.
\set ON_ERROR_STOP on
BEGIN;

-- The server bounds this transaction itself: a lock wait or a runaway statement raises
-- here, psql stops the script (exit 3) and nothing is kept. A client that gives up does
-- not stop the server - psql has the whole script on its stdin.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _chiapa_hide_plan (
    site_id     UUID NOT NULL,
    column_name TEXT NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    premise     TEXT NOT NULL,
    evidence    JSONB NOT NULL,
    PRIMARY KEY (site_id, column_name)
) ON COMMIT DROP;

INSERT INTO _chiapa_hide_plan (site_id, column_name, old_value, new_value, change_key, reason, premise, evidence) VALUES
    ('24aa135d-4714-47f5-96c0-d58f0bc04b6f'::uuid, 'scope_reason', 'duplicate_of:ed186ea9-9ed1-415d-828b-97d9f21401d2', NULL, 'chiapa-hide-rollback:24aa135d-4714-47f5-96c0-d58f0bc04b6f:scope_reason', 'rollback of chiapa-hide: scope_reason None restored on Chiapa de Corzo', 'content links 0, images 0', '[{"source": "output/remediation/HUMAN_ONLY_DECISIONS_2026-09-26.md", "url": null, "quote": "Nr. 7: eine Stätte, Richtung wie empfohlen - Chiapa de Corzo ausblenden (duplicate_of:ed186ea9...) und die Zoque-Zeile in ''Chiapa de Corzo'' umbenennen"}, {"source": "production:unified_sites", "url": null, "quote": "''Chiapa de Corzo'' (24aa135d-4714-47f5-96c0-d58f0bc04b6f): 0 content link(s), 0 image(s), external ids none; ''Zoque Culture Archaeological Zone'' (ed186ea9-9ed1-415d-828b-97d9f21401d2): 3 content link(s), 20 image(s), external ids enwiki_title=Chiapa de Corzo (Mesoamerican site), wikidata_qid=Q4384315; 7.4 m apart (read 2026-09-29 15:49:43.193037+00)"}, {"source": "survivor rule", "url": "scripts/remediation/mechanical/scope.py:survivor_rank", "quote": "older row, then more content links, description citations, images: ''Zoque Culture Archaeological Zone'' (2026-03-04 21:07:57.660461, 3 links, 0 citations, 20 images) over ''Chiapa de Corzo'' (2026-03-04 21:07:57.660461, 0 links, 0 citations, 0 images)"}]'::jsonb),
    ('24aa135d-4714-47f5-96c0-d58f0bc04b6f'::uuid, 'scope_status', 'retired', NULL, 'chiapa-hide-rollback:24aa135d-4714-47f5-96c0-d58f0bc04b6f:scope_status', 'rollback of chiapa-hide: scope_status None restored on Chiapa de Corzo', 'content links 0, images 0', '[{"source": "output/remediation/HUMAN_ONLY_DECISIONS_2026-09-26.md", "url": null, "quote": "Nr. 7: eine Stätte, Richtung wie empfohlen - Chiapa de Corzo ausblenden (duplicate_of:ed186ea9...) und die Zoque-Zeile in ''Chiapa de Corzo'' umbenennen"}, {"source": "production:unified_sites", "url": null, "quote": "''Chiapa de Corzo'' (24aa135d-4714-47f5-96c0-d58f0bc04b6f): 0 content link(s), 0 image(s), external ids none; ''Zoque Culture Archaeological Zone'' (ed186ea9-9ed1-415d-828b-97d9f21401d2): 3 content link(s), 20 image(s), external ids enwiki_title=Chiapa de Corzo (Mesoamerican site), wikidata_qid=Q4384315; 7.4 m apart (read 2026-09-29 15:49:43.193037+00)"}, {"source": "survivor rule", "url": "scripts/remediation/mechanical/scope.py:survivor_rank", "quote": "older row, then more content links, description citations, images: ''Zoque Culture Archaeological Zone'' (2026-03-04 21:07:57.660461, 3 links, 0 citations, 20 images) over ''Chiapa de Corzo'' (2026-03-04 21:07:57.660461, 0 links, 0 citations, 0 images)"}]'::jsonb);

DO $$
DECLARE
    bad      INTEGER;
    moved    INTEGER := 0;
    expected INTEGER := 2;
    r        RECORD;
BEGIN
    -- expected is the plan's own row count, rendered here, and not a second count of the
    -- temp table the loop below iterates: counting the same table twice would make the
    -- comparison after the loop a tautology. The instance that makes a short loop
    -- unreachable is apply_remediation_change, which raises unless exactly one row
    -- matched; this guard is what reports a loop that changed fewer rows than the plan.

    -- scope guard 1: every planned row is a curated site that still exists
    SELECT count(*) INTO bad
      FROM _chiapa_hide_plan p LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        -- the source name is a RAISE argument, never part of the quoted message: a name
        -- spliced into the message text only parses while the name happens to contain no
        -- quote, which is a property of today's value and not of this code. G0's guard is
        -- the shape this one copies.
        RAISE EXCEPTION 'Nr 7 duplicate hide: % planned row(s) are not % sites', bad, 'ancient_nerds';
    END IF;

    -- scope guard 2: the plan is a set of real changes, each one writable in its column
    -- (compared in the column's own type; CASE, because only CASE fixes the order in
    -- which the casts are evaluated)
    SELECT count(*) INTO bad FROM _chiapa_hide_plan p
     WHERE p.new_value = '' OR CASE p.column_name
                WHEN 'scope_status' THEN p.new_value::text IS NOT DISTINCT FROM p.old_value::text OR p.old_value IS NULL
                WHEN 'scope_reason' THEN p.new_value::text IS NOT DISTINCT FROM p.old_value::text OR p.old_value IS NULL
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 duplicate hide: % planned row(s) are not writable changes', bad;
    END IF;

    -- scope guard 3: every planned row still holds the old value the plan names
    SELECT count(*) INTO bad
      FROM _chiapa_hide_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE CASE p.column_name
                WHEN 'scope_status' THEN u.scope_status IS DISTINCT FROM p.old_value::text
                WHEN 'scope_reason' THEN u.scope_reason IS DISTINCT FROM p.old_value::text
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 duplicate hide: % planned row(s) no longer hold the planned old value', bad;
    END IF;

    -- scope guard 4: every planned row undos a value this lane owns (old value)
    SELECT count(*) INTO bad FROM _chiapa_hide_plan p
     WHERE CASE p.column_name
                WHEN 'scope_status' THEN p.old_value NOT IN ('retired')
                ELSE false END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 duplicate hide: % planned row(s) undo a value this lane does not own', bad;
    END IF;

    -- scope guard 5: every planned row still holds the input its value was derived from
    SELECT count(*) INTO bad
      FROM (SELECT DISTINCT site_id, premise FROM _chiapa_hide_plan) p JOIN unified_sites u ON u.id = p.site_id
     WHERE ('content links ' || CAST((SELECT count(*) FROM site_content_links c WHERE c.site_id = u.id) AS text) || ', images ' || CAST((SELECT count(*) FROM wiki_images w WHERE w.site_id = u.id) AS text)) IS DISTINCT FROM p.premise;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 duplicate hide: % planned row(s) no longer hold the premise the plan derived its value from', bad;
    END IF;

    -- the only writer: the conditional UPDATE and its journal row commit together, and
    -- the function raises unless exactly one row matched
    FOR r IN SELECT * FROM _chiapa_hide_plan ORDER BY site_id, column_name LOOP
        moved := moved + apply_remediation_change(
            'unified_sites', r.column_name, 'id', r.site_id::text,
            r.old_value, r.new_value,
            'Nr7/duplicate-hide', '2026-09-29_mechanical-chiapa-hide-rollback', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;

    IF moved <> expected THEN
        RAISE EXCEPTION 'Nr 7 duplicate hide: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds the new value
    SELECT count(*) INTO bad
      FROM _chiapa_hide_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE CASE p.column_name
                WHEN 'scope_status' THEN u.scope_status IS DISTINCT FROM p.new_value::text
                WHEN 'scope_reason' THEN u.scope_reason IS DISTINCT FROM p.new_value::text
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 duplicate hide: % planned row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: the journal and the data agree, row for row, in both directions
    SELECT count(*) INTO bad
      FROM _chiapa_hide_plan p LEFT JOIN remediation_change_log l
        ON l.row_pk = p.site_id::text AND l.table_name = 'unified_sites'
       AND l.column_name = p.column_name
       AND l.run_stamp = '2026-09-29_mechanical-chiapa-hide-rollback'
     WHERE l.id IS NULL
        OR l.new_value IS DISTINCT FROM p.new_value
        OR l.old_value IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 duplicate hide: % planned row(s) have no matching journal row', bad;
    END IF;

    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = '2026-09-29_mechanical-chiapa-hide-rollback'
       AND (l.table_name <> 'unified_sites' OR l.column_name NOT IN ('scope_status', 'scope_reason'));
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 duplicate hide: this run stamp journalled % row(s) outside unified_sites.(scope_status, scope_reason)', bad;
    END IF;

    RAISE NOTICE 'Nr 7 duplicate hide: % of % planned cell(s) changed and journalled over 1 curated site(s)',
        moved, expected;
END $$;

ROLLBACK;
-- after ROLLBACK of the reversal: the reversal must leave nothing behind either
WITH planned(site_id, column_name, written) AS (VALUES ('24aa135d-4714-47f5-96c0-d58f0bc04b6f'::uuid, 'scope_status', 'retired'), ('24aa135d-4714-47f5-96c0-d58f0bc04b6f'::uuid, 'scope_reason', 'duplicate_of:ed186ea9-9ed1-415d-828b-97d9f21401d2'))
SELECT 'journal rows for the rollback stamp' AS metric, count(*)::text AS value
  FROM remediation_change_log WHERE run_stamp = '2026-09-29_mechanical-chiapa-hide-rollback'
UNION ALL
SELECT 'planned rows still holding the written value', count(*)::text
  FROM planned p JOIN unified_sites u ON u.id = p.site_id
 WHERE CASE p.column_name
                WHEN 'scope_status' THEN u.scope_status IS NOT DISTINCT FROM p.written::text
                WHEN 'scope_reason' THEN u.scope_reason IS NOT DISTINCT FROM p.written::text
                ELSE false END
UNION ALL
SELECT 'curated sites', count(*)::text
  FROM unified_sites WHERE source_id = 'ancient_nerds'
UNION ALL
SELECT 'temp table _chiapa_hide_plan left behind',
       (to_regclass('pg_temp._chiapa_hide_plan') IS NOT NULL)::int::text
