-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: cb1a359f2b80f62baf5404187988f8b7ce055df683c5be172ecfb6cec8a07324
-- The reversal of lane 'ih6': the rows this wave created go back out, the flag returns to
-- the row that held it, and the thumbnail returns to the value the read found.
-- The row is named by the triple this lane wrote - (site_id, original_url, file_size_bytes) - so
-- the statement cannot delete a row somebody else created.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_uninsert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    original_url      TEXT NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT,
    change_key        TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_uninsert VALUES
    (1, '11ac5108-ad13-4b42-babc-ed1e298bebe3'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/92/Templo_del_Sol_1.jpg', 121436, NULL, NULL, '/data/images/wiki/11ac5108/Templo del Sol 1.webp', 'import-hero/insert:11ac5108-ad13-4b42-babc-ed1e298bebe3'),
    (2, '336a2e13-3348-4c15-a0cb-b5523ac32913'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Margum_ausgrabung_2011_%281%29.JPG', 95068, NULL, NULL, '/data/images/wiki/336a2e13/Margum ausgrabung 2011 (1).webp', 'import-hero/insert:336a2e13-3348-4c15-a0cb-b5523ac32913'),
    (3, '3e0ef472-929c-4669-ad45-c7a19c78d25f'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Balo_Kale_Stupa_Swat_Valley_Pakistan.jpg', 103682, NULL, NULL, '/data/images/wiki/3e0ef472/Balo Kale Stupa Swat Valley Pakistan.webp', 'import-hero/insert:3e0ef472-929c-4669-ad45-c7a19c78d25f'),
    (4, '3e7d6ad9-37c8-4899-9956-99088ff63c78'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Visitors_car_park_at_Achadh_an_Marbh-Annaghmare_Court_Tomb_-_geograph.org.uk_-_4172658.jpg', 131936, NULL, NULL, '/data/images/wiki/3e7d6ad9/Visitors car park at Achadh an Marbh-Annaghmare Court Tomb - geograph.org.uk - 4172658.webp', 'import-hero/insert:3e7d6ad9-37c8-4899-9956-99088ff63c78'),
    (5, '43c12659-d785-44da-ab9b-e0e5fedee349'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Chullpas_de_Molloko_en_Puno%2C_Per%C3%BA.jpg', 318142, NULL, NULL, '/data/images/wiki/43c12659/Chullpas de Molloko en Puno, Perú.webp', 'import-hero/insert:43c12659-d785-44da-ab9b-e0e5fedee349'),
    (6, '44996991-ef99-4593-a645-74bf63d9056a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/09/Funziegirt%2C_south-west_of_Vord_Hill%2C_Fetlar_-_geograph.org.uk_-_4308134.jpg', 132080, NULL, NULL, '/data/images/wiki/44996991/Funziegirt, south-west of Vord Hill, Fetlar - geograph.org.uk - 4308134.webp', 'import-hero/insert:44996991-ef99-4593-a645-74bf63d9056a'),
    (7, '4c3d31bc-8f57-44e5-988b-4bb0e3d3d516'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/92/Earthworks_at_Kinver_Edge_Hillfort_-_geograph.org.uk_-_7359414.jpg', 281938, NULL, NULL, '/data/images/wiki/4c3d31bc/Earthworks at Kinver Edge Hillfort - geograph.org.uk - 7359414.webp', 'import-hero/insert:4c3d31bc-8f57-44e5-988b-4bb0e3d3d516'),
    (8, '50f3f5c5-fcc1-443e-b516-9aaf6ca13d0c'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/08/Dolmen_at_Ballyalton_-_geograph.org.uk_-_2527862.jpg', 224558, NULL, NULL, '/data/images/wiki/50f3f5c5/Dolmen at Ballyalton - geograph.org.uk - 2527862.webp', 'import-hero/insert:50f3f5c5-fcc1-443e-b516-9aaf6ca13d0c'),
    (9, '534c1035-fbfe-46fe-8127-a709d32dc1c7'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/7/7e/The_Leper_Stone%2C_Llanrhidian_-_geograph.org.uk_-_8394027.jpg', 456240, NULL, NULL, '/data/images/wiki/534c1035/The Leper Stone, Llanrhidian - geograph.org.uk - 8394027.webp', 'import-hero/insert:534c1035-fbfe-46fe-8127-a709d32dc1c7'),
    (10, '57f3306b-9927-46a4-84ef-9688bc9809f5'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/91/A_lidar_view_of_Bowes_Castle_within_the_ruins_of_the_Roman_fort_of_Lavatrae.jpg', 223528, NULL, NULL, '/data/images/wiki/57f3306b/A lidar view of Bowes Castle within the ruins of the Roman fort of Lavatrae.webp', 'import-hero/insert:57f3306b-9927-46a4-84ef-9688bc9809f5'),
    (11, '69b83929-86e2-4a3e-8e0d-2418db5192ed'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/08/View_to_Neu_K%C3%B6nigsaue_%28Aschersleben%29.jpg', 304348, NULL, NULL, '/data/images/wiki/69b83929/View to Neu Königsaue (Aschersleben).webp', 'import-hero/insert:69b83929-86e2-4a3e-8e0d-2418db5192ed'),
    (12, '72f50344-3b9f-4390-929c-78d72d7a6e01'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Cerrig_ar_rostir_ger_Banc_Du_-_Stones_on_moorland_near_Banc_Du_-_geograph.org.uk_-_7905287.jpg', 184458, NULL, NULL, '/data/images/wiki/72f50344/Cerrig ar rostir ger Banc Du - Stones on moorland near Banc Du - geograph.org.uk - 7905287.webp', 'import-hero/insert:72f50344-3b9f-4390-929c-78d72d7a6e01'),
    (13, '7adac3e8-3eef-4c99-a403-e0ef8f6be97e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/d3/NetherLargieMid1.jpg', 452686, NULL, NULL, '/data/images/wiki/7adac3e8/NetherLargieMid1.webp', 'import-hero/insert:7adac3e8-3eef-4c99-a403-e0ef8f6be97e'),
    (14, '8f5e0a0d-a4e5-4c7d-8c73-80695a6a5290'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e8/K%C4%B1zlar_kalesi_%282%29.jpg', 160448, NULL, NULL, '/data/images/wiki/8f5e0a0d/Kızlar kalesi (2).webp', 'import-hero/insert:8f5e0a0d-a4e5-4c7d-8c73-80695a6a5290'),
    (15, '9c35081a-a345-4545-962d-d3aeeb2f2b0c'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/46/Wiesmath_1_%28Gilching%29_3.jpg', 451984, NULL, NULL, '/data/images/wiki/9c35081a/Wiesmath 1 (Gilching) 3.webp', 'import-hero/insert:9c35081a-a345-4545-962d-d3aeeb2f2b0c'),
    (16, '9c3e1746-6da1-412c-aeb3-eb61cb3cafbb'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Qalagah_kils%C9%99sinin_xarabal%C4%B1qlar%C4%B1.jpg', 290952, NULL, NULL, '/data/images/wiki/9c3e1746/Qalagah kilsəsinin xarabalıqları.webp', 'import-hero/insert:9c3e1746-6da1-412c-aeb3-eb61cb3cafbb'),
    (17, '9ca828d9-f880-4675-b304-0718ddce9010'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Fethiye_Theater_01.JPG', 467922, NULL, NULL, '/data/images/wiki/9ca828d9/Fethiye Theater 01.webp', 'import-hero/insert:9ca828d9-f880-4675-b304-0718ddce9010'),
    (18, 'a6e95853-236b-4de9-b496-1491fd915423'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e3/%C3%9C%C3%A7a%C4%9F%C4%B1z_View_of_remains_of_Theimussa_0071_panorama.jpg', 113498, NULL, NULL, '/data/images/wiki/a6e95853/Üçağız View of remains of Theimussa 0071 panorama.webp', 'import-hero/insert:a6e95853-236b-4de9-b496-1491fd915423'),
    (19, 'aa75397c-7bdf-4b31-bbfc-1aa544fe91b5'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Archaeological_site_of_Philippi_BW_2017-10-05_13-40-03.jpg', 245764, NULL, NULL, '/data/images/wiki/aa75397c/Archaeological site of Philippi BW 2017-10-05 13-40-03.webp', 'import-hero/insert:aa75397c-7bdf-4b31-bbfc-1aa544fe91b5'),
    (20, 'b287e7d6-f61a-4397-b847-56ce0419dd0c'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/6b/The_Archaeological_Site_of_Uthina_01.jpg', 284674, NULL, NULL, '/data/images/wiki/b287e7d6/The Archaeological Site of Uthina 01.webp', 'import-hero/insert:b287e7d6-f61a-4397-b847-56ce0419dd0c'),
    (21, 'bc85d3d5-a47e-4c4d-be70-aaa1c18915d1'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/19/Crkvine_0593.jpg', 110142, NULL, NULL, '/data/images/wiki/bc85d3d5/Crkvine 0593.webp', 'import-hero/insert:bc85d3d5-a47e-4c4d-be70-aaa1c18915d1'),
    (22, 'c8e0a91d-298d-40f1-aef8-f8503e44b05a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Fen_Causeway_underpass%2C_Cambridge_-_geograph.org.uk_-_5275920.jpg', 149334, NULL, NULL, '/data/images/wiki/c8e0a91d/Fen Causeway underpass, Cambridge - geograph.org.uk - 5275920.webp', 'import-hero/insert:c8e0a91d-298d-40f1-aef8-f8503e44b05a'),
    (23, 'cce286a3-5ba9-4724-b465-6df5835eebc0'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/67/Inside_Ivington_Camp_-_geograph.org.uk_-_5573482.jpg', 148278, NULL, NULL, '/data/images/wiki/cce286a3/Inside Ivington Camp - geograph.org.uk - 5573482.webp', 'import-hero/insert:cce286a3-5ba9-4724-b465-6df5835eebc0'),
    (24, 'd3dde28f-ad70-41ce-b5b4-6bb943aebbee'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/d3/NetherLargieMid1.jpg', 452686, NULL, NULL, '/data/images/wiki/d3dde28f/NetherLargieMid1.webp', 'import-hero/insert:d3dde28f-ad70-41ce-b5b4-6bb943aebbee'),
    (25, 'd571a05b-ece2-4cee-b252-2590660bf26c'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/05/Panorama_of_Perge_theatre.jpg', 291632, NULL, NULL, '/data/images/wiki/d571a05b/Panorama of Perge theatre.webp', 'import-hero/insert:d571a05b-ece2-4cee-b252-2590660bf26c'),
    (26, 'da35c9fa-fd61-4188-96c6-342d9b0789e9'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/3a/El_fuerte_Paso_del_macho.jpg', 544988, NULL, NULL, '/data/images/wiki/da35c9fa/El fuerte Paso del macho.webp', 'import-hero/insert:da35c9fa-fd61-4188-96c6-342d9b0789e9'),
    (27, 'dc38ed07-f75e-4d92-b932-cd8275b35a09'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/08/The_Victoria_history_of_the_county_of_Devon%3B_%281906%29_%2820773958825%29.jpg', 142574, NULL, NULL, '/data/images/wiki/dc38ed07/The Victoria history of the county of Devon; (1906) (20773958825).webp', 'import-hero/insert:dc38ed07-f75e-4d92-b932-cd8275b35a09'),
    (28, 'f15d2047-cd5a-4524-b39a-06ab10d77f36'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/7/78/Seaton_Down_Hoard%2C_RAMM_-_geograph.org.uk_-_6006673.jpg', 345714, NULL, NULL, '/data/images/wiki/f15d2047/Seaton Down Hoard, RAMM - geograph.org.uk - 6006673.webp', 'import-hero/insert:f15d2047-cd5a-4524-b39a-06ab10d77f36'),
    (29, 'fe3f5d3d-79d9-4790-b4ca-6b80aec4f558'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Tambomachay%2C_Cuzco%2C_Per%C3%BA%2C_2011-11-17_%283%29.jpg', 527134, NULL, NULL, '/data/images/wiki/fe3f5d3d/Tambomachay, Cuzco, Perú, 2011-11-17 (3).webp', 'import-hero/insert:fe3f5d3d-79d9-4790-b4ca-6b80aec4f558'),
    (30, 'fee01523-1686-437c-97ef-9e3566fba1c3'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/91/Y_Foel_Chwern_-_geograph.org.uk_-_6494728.jpg', 266058, NULL, NULL, '/data/images/wiki/fee01523/Y Foel Chwern - geograph.org.uk - 6494728.webp', 'import-hero/insert:fee01523-1686-437c-97ef-9e3566fba1c3');

DO $$
DECLARE
    bad integer;
BEGIN
    -- every named row is still the one this wave created
    SELECT count(*) INTO bad FROM _ih_uninsert r
      LEFT JOIN wiki_images w
        ON w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes
     WHERE w.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'rollback %: % row(s) this wave created are not there to undo',
            'insert-2026-10-07-010-001', bad;
    END IF;

    DELETE FROM wiki_images w USING _ih_uninsert r
     WHERE w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes;

    UPDATE wiki_images w SET is_hero = true
      FROM _ih_uninsert r
     WHERE r.demoted_id IS NOT NULL AND w.id = r.demoted_id AND w.is_hero IS NOT TRUE;

    UPDATE unified_sites u SET thumbnail_url = r.old_thumbnail
      FROM _ih_uninsert r
     WHERE u.id = r.site_id AND r.new_thumbnail IS DISTINCT FROM r.old_thumbnail
       AND u.thumbnail_url IS DISTINCT FROM r.old_thumbnail;

    -- the journal goes with the write it describes
    DELETE FROM remediation_change_log l USING _ih_uninsert r
     WHERE l.run_stamp = 'insert-2026-10-07-010-001' AND l.change_key LIKE r.change_key || '%';
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-010-001';
SELECT 'rows this chunk created',
       count(*)::text
  FROM wiki_images w
  JOIN _ih_uninsert r ON w.site_id = r.site_id AND w.original_url = r.original_url
                    AND w.file_size_bytes = r.file_size_bytes;
COMMIT;
