/**
 * ArticlesPage - Weekly digest articles generated by Lyra.
 * Accessed via /articles.html (separate Vite entry point).
 *
 * Newspaper-style layout with hero + grid listing and full-page reader.
 * Hash-based routing: /articles.html#slug opens an article directly.
 * Share URLs use the canonical SEO path: /articles/{slug}
 */

import { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import ReactMarkdown, { type Components } from 'react-markdown'
import { config } from '../config'
import CitationPopover from '../components/news/CitationPopover'
import type { NewsItemData } from '../types/news'
import type { NewsCardProps } from '../components/news/NewsCard'
import '../components/news/news-cards.css'

interface Article {
  id: number
  title: string
  content: string
  summary: string | null
  week_start: string
  week_end: string
  published_at: string | null
}

function slugify(title: string): string {
  return title.toLowerCase().trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 120)
}

function formatDateRange(start: string, end: string): string {
  const s = new Date(start)
  const e = new Date(end)
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' }
  const yearOpts: Intl.DateTimeFormatOptions = { ...opts, year: 'numeric' }
  if (s.getFullYear() !== e.getFullYear()) {
    return `${s.toLocaleDateString('en-US', yearOpts)} – ${e.toLocaleDateString('en-US', yearOpts)}`
  }
  return `${s.toLocaleDateString('en-US', opts)} – ${e.toLocaleDateString('en-US', yearOpts)}`
}

/** Convert bare [1] references to clickable anchor links pointing to #sources. */
function enrichCitations(content: string): string {
  return content.replace(/(?<!\[)\[(\d+)\](?!\()/g, '[$1](#sources)')
}

function firstImageUrl(article: Article): string | null {
  const m = article.content.match(/!\[.*?\]\((\S+?)\)/)
  return m ? m[1] : null
}

function shareUrl(article: Article): string {
  return `https://ancientnerds.com/articles/${slugify(article.title)}`
}

/** Convert an API NewsItemData into NewsCardProps for CitationPopover. */
function itemToCardProps(item: NewsItemData): NewsCardProps {
  const screenshotUrl = item.screenshot_url
    ? `${config.api.baseUrl}${item.screenshot_url.replace('/api', '')}`
    : item.video.thumbnail_url
  const deepLink = item.youtube_deep_url || item.youtube_url || '#'
  return {
    headline: item.headline,
    postText: item.post_text,
    channelName: item.video.channel_name,
    publishedAt: item.video.published_at,
    significance: item.significance,
    newsCategory: item.news_category,
    speculativeTag: item.speculative_tag,
    screenshotUrl,
    deepLink,
    videoId: item.video.id,
    videoTitle: item.video.title,
    durationMinutes: item.video.duration_minutes,
    timestampSeconds: item.timestamp_seconds,
    siteName: item.site_name || item.site_name_extracted,
    siteNameExtracted: item.site_name_extracted,
    siteId: item.site_id,
    siteCountry: item.site_country,
    siteType: item.site_type,
    sitePeriodName: item.site_period_name,
    sitePeriodStart: item.site_period_start,
    facts: item.facts,
  }
}

function makeArticleComponents(
  citationItems: Map<number, NewsItemData>,
  onCitationEnter: (num: number, rect: DOMRect) => void,
  onCitationLeave: () => void,
): Components {
  return {
    img: ({ src, alt }) => (
      <figure className="article-figure">
        <img src={src} alt={alt || ''} loading="lazy" className="article-screenshot" />
        {alt && <figcaption className="article-figcaption">{alt}</figcaption>}
      </figure>
    ),
    a: ({ href, children }) => {
      if (href === '#sources') {
        const num = parseInt(String(children).replace(/[[\]]/g, ''), 10)
        const hasCard = citationItems.has(num)
        return (
          <a
            href={href}
            className={`article-citation-link${hasCard ? ' has-popover' : ''}`}
            onMouseEnter={hasCard ? (e) => onCitationEnter(num, e.currentTarget.getBoundingClientRect()) : undefined}
            onMouseLeave={hasCard ? onCitationLeave : undefined}
          >
            {children}
          </a>
        )
      }
      return <a href={href} target="_blank" rel="noopener noreferrer">{children}</a>
    },
    h3: ({ children }) => {
      const text = String(children)
      if (text === 'Sources') return <h3 id="sources">{children}</h3>
      return <h3>{children}</h3>
    },
  }
}

function ShareButton({ article }: { article: Article }) {
  const [copied, setCopied] = useState(false)

  const handleShare = async () => {
    const url = shareUrl(article)
    if (navigator.share) {
      try {
        await navigator.share({ title: article.title, url })
        return
      } catch { /* user cancelled or API unavailable */ }
    }
    await navigator.clipboard.writeText(url)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <button className="articles-share-btn" onClick={handleShare} title="Share article">
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 12v8a2 2 0 002 2h12a2 2 0 002-2v-8" />
        <polyline points="16 6 12 2 8 6" />
        <line x1="12" y1="2" x2="12" y2="15" />
      </svg>
      {copied ? 'Copied!' : 'Share'}
    </button>
  )
}

function CopyLinkButton({ article }: { article: Article }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(shareUrl(article))
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <button className="articles-share-btn" onClick={handleCopy} title="Copy link">
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71" />
        <path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71" />
      </svg>
      {copied ? 'Copied!' : 'Copy Link'}
    </button>
  )
}

export default function ArticlesPage() {
  const [articles, setArticles] = useState<Article[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [view, setView] = useState<'listing' | 'reading'>('listing')
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null)
  const [readProgress, setReadProgress] = useState(0)

  // Citation hover card state
  const [citationItems, setCitationItems] = useState<Map<number, NewsItemData>>(new Map())
  const [hoverCitation, setHoverCitation] = useState<{ num: number; rect: DOMRect } | null>(null)
  const hoverTimeout = useRef<ReturnType<typeof setTimeout> | null>(null)

  const cancelHoverClose = () => {
    if (hoverTimeout.current) {
      clearTimeout(hoverTimeout.current)
      hoverTimeout.current = null
    }
  }

  const scheduleHoverClose = () => {
    cancelHoverClose()
    hoverTimeout.current = setTimeout(() => setHoverCitation(null), 150)
  }

  const handleCitationEnter = (num: number, rect: DOMRect) => {
    cancelHoverClose()
    setHoverCitation({ num, rect })
  }

  // Resolve hash → article once articles are loaded
  const resolveHash = useCallback((articleList: Article[]) => {
    const hash = window.location.hash.slice(1)
    if (!hash) {
      setView('listing')
      setSelectedArticle(null)
      return
    }
    const match = articleList.find(a => slugify(a.title) === hash)
    if (match) {
      setSelectedArticle(match)
      setView('reading')
    } else {
      setView('listing')
      setSelectedArticle(null)
    }
  }, [])

  useEffect(() => {
    fetch(`${config.api.baseUrl}/news/articles?limit=50`)
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then((data: Article[]) => {
        setArticles(data)
        setLoading(false)
        resolveHash(data)
      })
      .catch(e => {
        setError(e instanceof Error ? e.message : 'Failed to load')
        setLoading(false)
      })
  }, [resolveHash])

  // Listen for hash changes (browser back/forward)
  useEffect(() => {
    const onHashChange = () => resolveHash(articles)
    window.addEventListener('hashchange', onHashChange)
    return () => window.removeEventListener('hashchange', onHashChange)
  }, [articles, resolveHash])

  const openArticle = (article: Article) => {
    window.location.hash = slugify(article.title)
  }

  const backToListing = () => {
    history.pushState(null, '', window.location.pathname + window.location.search)
    setView('listing')
    setSelectedArticle(null)
    window.scrollTo(0, 0)
  }

  // Fetch citation items when entering reading view
  useEffect(() => {
    if (view !== 'reading' || !selectedArticle) {
      setCitationItems(new Map())
      setHoverCitation(null)
      return
    }
    let cancelled = false
    fetch(`${config.api.baseUrl}/news/articles/${selectedArticle.id}/citations`)
      .then(r => r.ok ? r.json() : {})
      .then((data: Record<string, NewsItemData>) => {
        if (cancelled) return
        const map = new Map<number, NewsItemData>()
        for (const [key, item] of Object.entries(data)) {
          map.set(parseInt(key, 10), item)
        }
        setCitationItems(map)
      })
      .catch(() => { /* non-critical — popover just won't show */ })
    return () => { cancelled = true }
  }, [view, selectedArticle])

  // Scroll to top when entering reading view + track read progress
  useEffect(() => {
    if (view === 'reading') {
      window.scrollTo(0, 0)
      setReadProgress(0)
      const onScroll = () => {
        const scrollable = document.documentElement.scrollHeight - window.innerHeight
        setReadProgress(scrollable > 0 ? Math.min(100, (window.scrollY / scrollable) * 100) : 0)
      }
      window.addEventListener('scroll', onScroll, { passive: true })
      return () => window.removeEventListener('scroll', onScroll)
    }
    setReadProgress(0)
  }, [view])

  // Memoize ReactMarkdown components to avoid remounting on every render
  const mdComponents = useMemo(
    () => makeArticleComponents(citationItems, handleCitationEnter, scheduleHoverClose),
    [citationItems],
  )

  const hero = articles[0] ?? null
  const older = articles.slice(1)

  return (
    <div className="articles-page">
      <header className="articles-page-header">
        <a href="/globe.html" className="articles-page-brand">
          <img src="/an-logo.svg" alt="" className="articles-page-logo" />
          <span className="articles-page-brand-text">ANCIENT NERDS</span>
        </a>
        <div className="articles-page-divider" />
        {view === 'listing' ? (
          <span className="articles-page-title">Articles</span>
        ) : (
          <button className="articles-page-back-btn" onClick={backToListing}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="15 18 9 12 15 6" />
            </svg>
            All Articles
          </button>
        )}
      </header>

      {view === 'reading' && (
        <div className="articles-progress-track">
          <div className="articles-progress-bar" style={{ width: `${readProgress}%` }} />
        </div>
      )}

      <main className="articles-page-content">
        {loading && <div className="articles-page-loading">Loading articles...</div>}
        {error && (
          <div className="articles-page-error">
            {error}
            <button onClick={() => window.location.reload()}>Retry</button>
          </div>
        )}
        {!loading && !error && articles.length === 0 && (
          <div className="articles-page-empty">No articles yet. Check back soon.</div>
        )}

        {/* ── Listing view: hero + grid ── */}
        {view === 'listing' && !loading && !error && hero && (
          <>
            <section className="articles-hero" onClick={() => openArticle(hero)}>
              <h1 className="articles-hero-title">{hero.title}</h1>
              <span className="articles-hero-date">
                {formatDateRange(hero.week_start, hero.week_end)}
              </span>
              <div className="articles-hero-body">
                {hero.summary && (
                  <p className="articles-hero-summary">{hero.summary}</p>
                )}
                {firstImageUrl(hero) && (
                  <img
                    src={firstImageUrl(hero)!}
                    alt=""
                    className="articles-hero-img"
                    loading="lazy"
                  />
                )}
              </div>
              <div className="articles-hero-actions">
                <button className="articles-hero-cta" onClick={(e) => { e.stopPropagation(); openArticle(hero) }}>
                  Read Article
                </button>
                <div onClick={e => e.stopPropagation()}>
                  <ShareButton article={hero} />
                </div>
              </div>
            </section>

            {older.length > 0 && (
              <section className="articles-grid-section">
                <span className="articles-grid-label">PREVIOUS ARTICLES</span>
                <div className="articles-grid">
                  {older.map(article => (
                    <article
                      key={article.id}
                      className="articles-grid-card"
                      onClick={() => openArticle(article)}
                    >
                      {firstImageUrl(article) && (
                        <img
                          src={firstImageUrl(article)!}
                          alt=""
                          className="articles-grid-card-img"
                          loading="lazy"
                        />
                      )}
                      <h2 className="articles-grid-card-title">{article.title}</h2>
                      <span className="articles-grid-card-date">
                        {formatDateRange(article.week_start, article.week_end)}
                      </span>
                      {article.summary && (
                        <p className="articles-grid-card-summary">{article.summary}</p>
                      )}
                      <div className="articles-grid-card-footer" onClick={e => e.stopPropagation()}>
                        <ShareButton article={article} />
                      </div>
                    </article>
                  ))}
                </div>
              </section>
            )}
          </>
        )}

        {/* ── Reading view: full-page article ── */}
        {view === 'reading' && selectedArticle && (
          <article className="articles-reader">
            <h1 className="articles-reader-title">{selectedArticle.title}</h1>
            <div className="articles-reader-meta">
              <span className="articles-reader-date">
                {formatDateRange(selectedArticle.week_start, selectedArticle.week_end)}
              </span>
              <div className="articles-reader-meta-actions">
                <ShareButton article={selectedArticle} />
                <CopyLinkButton article={selectedArticle} />
              </div>
            </div>
            <div className="articles-reader-body">
              <ReactMarkdown components={mdComponents}>
                {enrichCitations(selectedArticle.content)}
              </ReactMarkdown>
            </div>
            <footer className="articles-reader-footer">
              <button className="articles-reader-back-link" onClick={backToListing}>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="15 18 9 12 15 6" />
                </svg>
                Back to all articles
              </button>
            </footer>
          </article>
        )}

        {/* Citation hover popover */}
        {hoverCitation && citationItems.has(hoverCitation.num) && (
          <CitationPopover
            cardProps={itemToCardProps(citationItems.get(hoverCitation.num)!)}
            anchorRect={hoverCitation.rect}
            onMouseEnter={cancelHoverClose}
            onMouseLeave={scheduleHoverClose}
          />
        )}
      </main>
    </div>
  )
}
