/**
 * ArticlesPage - Weekly digest articles generated by Lyra.
 * Accessed via /articles.html (separate Vite entry point).
 */

import { useState, useEffect } from 'react'
import { config } from '../config'

interface Article {
  id: number
  title: string
  content: string
  summary: string | null
  week_start: string
  week_end: string
  published_at: string | null
}

function formatDateRange(start: string, end: string): string {
  const s = new Date(start)
  const e = new Date(end)
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' }
  const yearOpts: Intl.DateTimeFormatOptions = { ...opts, year: 'numeric' }
  if (s.getFullYear() !== e.getFullYear()) {
    return `${s.toLocaleDateString('en-US', yearOpts)} – ${e.toLocaleDateString('en-US', yearOpts)}`
  }
  return `${s.toLocaleDateString('en-US', opts)} – ${e.toLocaleDateString('en-US', yearOpts)}`
}

export default function ArticlesPage() {
  const [articles, setArticles] = useState<Article[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [expandedId, setExpandedId] = useState<number | null>(null)

  useEffect(() => {
    fetch(`${config.api.baseUrl}/news/articles?limit=50`)
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then((data: Article[]) => {
        setArticles(data)
        setLoading(false)
      })
      .catch(e => {
        setError(e instanceof Error ? e.message : 'Failed to load')
        setLoading(false)
      })
  }, [])

  return (
    <div className="articles-page">
      <header className="articles-page-header">
        <a href="/" className="articles-page-brand">
          <img src="/an-logo.svg" alt="" className="articles-page-logo" />
          <span className="articles-page-brand-text">ANCIENT NERDS</span>
        </a>
        <div className="articles-page-divider" />
        <span className="articles-page-title">Articles</span>
      </header>

      <main className="articles-page-content">
        {loading && <div className="articles-page-loading">Loading articles...</div>}
        {error && (
          <div className="articles-page-error">
            {error}
            <button onClick={() => window.location.reload()}>Retry</button>
          </div>
        )}
        {!loading && !error && articles.length === 0 && (
          <div className="articles-page-empty">No articles yet. Check back soon.</div>
        )}

        <div className="articles-page-list">
          {articles.map(article => {
            const isExpanded = expandedId === article.id
            return (
              <article
                key={article.id}
                className={`articles-page-card${isExpanded ? ' expanded' : ''}`}
                onClick={() => setExpandedId(isExpanded ? null : article.id)}
              >
                <div className="articles-page-card-header">
                  <h2 className="articles-page-card-title">{article.title}</h2>
                  <span className="articles-page-card-date">
                    {formatDateRange(article.week_start, article.week_end)}
                  </span>
                </div>

                {!isExpanded && article.summary && (
                  <p className="articles-page-card-summary">{article.summary}</p>
                )}

                {isExpanded && (
                  <div className="articles-page-card-content">
                    {article.content.split('\n').map((paragraph, i) =>
                      paragraph.trim() ? <p key={i}>{paragraph}</p> : null
                    )}
                  </div>
                )}

                <div className="articles-page-card-expand">
                  {isExpanded ? 'Click to collapse' : 'Click to read'}
                </div>
              </article>
            )
          })}
        </div>
      </main>
    </div>
  )
}
