-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: 31ad0e2e180df6aeb63366ffac162ada5e9691a48d1b2dce726c5fb425034827
-- The reversal of lane 'ih6': the rows this wave created go back out, the flag returns to
-- the row that held it, and the thumbnail returns to the value the read found.
-- The row is named by the triple this lane wrote - (site_id, original_url, file_size_bytes) - so
-- the statement cannot delete a row somebody else created.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_uninsert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    original_url      TEXT NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT,
    change_key        TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_uninsert VALUES
    (1, 'c250e4dc-81e8-4b7b-8da5-3947e346e2ef'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Schinderhannesh%C3%B6hle_Teufelsrutsch_Wendelsheim_2026.jpg', 445686, NULL, NULL, '/data/images/wiki/c250e4dc/Schinderhanneshöhle Teufelsrutsch Wendelsheim 2026.webp', 'import-hero/insert:c250e4dc-81e8-4b7b-8da5-3947e346e2ef'),
    (2, 'c5d05e95-f6a3-454f-85ba-6ebb4736b7bb'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/64/Arco_di_augusto_di_sera.jpg', 477088, NULL, NULL, '/data/images/wiki/c5d05e95/Arco di augusto di sera.webp', 'import-hero/insert:c5d05e95-f6a3-454f-85ba-6ebb4736b7bb'),
    (3, 'c8370b05-1d32-491a-a735-344f6534b4d8'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Ashley_Court_-_geograph.org.uk_-_6545415.jpg', 288928, NULL, NULL, '/data/images/wiki/c8370b05/Ashley Court - geograph.org.uk - 6545415.webp', 'import-hero/insert:c8370b05-1d32-491a-a735-344f6534b4d8'),
    (4, 'ca329810-35cd-431c-9313-0b53a706b325'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Zona_Arqueol%C3%B3gica_Lagartero%2C_La_Trinitaria%2C_Chiapas.jpg', 355740, NULL, NULL, '/data/images/wiki/ca329810/Zona Arqueológica Lagartero, La Trinitaria, Chiapas.webp', 'import-hero/insert:ca329810-35cd-431c-9313-0b53a706b325'),
    (5, 'ca33a292-b102-4efe-b644-48959d8ff741'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Templo_de_Nefertari%2C_Abu_Simbel%2C_Egipto%2C_2022-04-02%2C_DD_128-130_HDR.jpg', 472250, NULL, NULL, '/data/images/wiki/ca33a292/Templo de Nefertari, Abu Simbel, Egipto, 2022-04-02, DD 128-130 HDR.webp', 'import-hero/insert:ca33a292-b102-4efe-b644-48959d8ff741'),
    (6, 'cbfd3d2a-70f5-41f4-a3db-298b56040fea'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Befundskizze_Kastell_Ebchester.png', 123990, NULL, NULL, '/data/images/wiki/cbfd3d2a/Befundskizze Kastell Ebchester.webp', 'import-hero/insert:cbfd3d2a-70f5-41f4-a3db-298b56040fea'),
    (7, 'cc3e0e34-8532-41dd-9988-6c20e37be8e6'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Rocha_da_Mina_%2812%29.jpg', 580768, NULL, NULL, '/data/images/wiki/cc3e0e34/Rocha da Mina (12).webp', 'import-hero/insert:cc3e0e34-8532-41dd-9988-6c20e37be8e6'),
    (8, 'cfdbdb6f-7420-49f2-9f19-8922851ddc24'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Kinichn%C3%A1%2C_Acr%C3%B3polis.JPG', 553860, NULL, NULL, '/data/images/wiki/cfdbdb6f/Kinichná, Acrópolis.webp', 'import-hero/insert:cfdbdb6f-7420-49f2-9f19-8922851ddc24'),
    (9, 'd1720193-07a3-495c-ba7e-823426aa4f17'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/30/Quiahuiztlan%2C_tombs_%2820693486681%29.jpg', 478162, NULL, NULL, '/data/images/wiki/d1720193/Quiahuiztlan, tombs (20693486681).webp', 'import-hero/insert:d1720193-07a3-495c-ba7e-823426aa4f17'),
    (10, 'd2295d88-dbe5-4755-8905-ee782722af30'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/80/The_rock_tombs_of_ancient_Myra%2C_carved_into_the_cliffs_of_Demre%2C_Turkey.jpg', 618030, NULL, NULL, '/data/images/wiki/d2295d88/The rock tombs of ancient Myra, carved into the cliffs of Demre, Turkey.webp', 'import-hero/insert:d2295d88-dbe5-4755-8905-ee782722af30'),
    (11, 'd3789a45-3747-4bae-8b9e-88f359f5561d'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Odry_z_drona.jpg', 874538, NULL, NULL, '/data/images/wiki/d3789a45/Odry z drona.webp', 'import-hero/insert:d3789a45-3747-4bae-8b9e-88f359f5561d'),
    (12, 'd5fc9a81-4a7a-427d-8f28-244eff8582ac'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/33/Ancient_theater%2C_Limenas%2C_Thassos._1983._%2840502068574%29.jpg', 656290, NULL, NULL, '/data/images/wiki/d5fc9a81/Ancient theater, Limenas, Thassos. 1983. (40502068574).webp', 'import-hero/insert:d5fc9a81-4a7a-427d-8f28-244eff8582ac'),
    (13, 'd7f5b63f-d9a6-41a4-b491-7ba11aa9cc96'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Area_archeologica_di_Pranu_Muttedu_2025_009.jpg', 736152, NULL, NULL, '/data/images/wiki/d7f5b63f/Area archeologica di Pranu Muttedu 2025 009.webp', 'import-hero/insert:d7f5b63f-d9a6-41a4-b491-7ba11aa9cc96'),
    (14, 'd9023096-4bef-47a7-bcb4-2e3f4cf0ba36'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/19/Villa_Romana_da_Quinta_da_Bolacha_006.jpeg', 824100, NULL, NULL, '/data/images/wiki/d9023096/Villa Romana da Quinta da Bolacha 006.webp', 'import-hero/insert:d9023096-4bef-47a7-bcb4-2e3f4cf0ba36'),
    (15, 'd9bf804c-0891-424e-a272-cb3681d3497a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/23/Mural_cabeza_clava.jpg', 64096, NULL, NULL, '/data/images/wiki/d9bf804c/Mural cabeza clava.webp', 'import-hero/insert:d9bf804c-0891-424e-a272-cb3681d3497a'),
    (16, 'e046b573-d1cc-454c-94f9-01f5fd51e233'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/5/59/Ancaster_station_-_geograph.org.uk_-_5498281.jpg', 393014, NULL, NULL, '/data/images/wiki/e046b573/Ancaster station - geograph.org.uk - 5498281.webp', 'import-hero/insert:e046b573-d1cc-454c-94f9-01f5fd51e233'),
    (17, 'e1976732-579b-4f25-be81-626008526093'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Athena_Tap%C4%B1na%C4%9F%C4%B1_%28Priene%29_06.jpg', 712618, NULL, NULL, '/data/images/wiki/e1976732/Athena Tapınağı (Priene) 06.webp', 'import-hero/insert:e1976732-579b-4f25-be81-626008526093'),
    (18, 'e2032339-c139-444d-9347-5d30ecd0b048'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Viran_Kap%C4%B1.jpg', 388316, NULL, NULL, '/data/images/wiki/e2032339/Viran Kapı.webp', 'import-hero/insert:e2032339-c139-444d-9347-5d30ecd0b048'),
    (19, 'e258fc5f-e771-442a-9c65-3839a084199a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Pasl1i.jpg', 429290, NULL, NULL, '/data/images/wiki/e258fc5f/Pasl1i.webp', 'import-hero/insert:e258fc5f-e771-442a-9c65-3839a084199a'),
    (20, 'e473f682-8b9c-4d5c-b2cc-0ca24fcc06bc'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Burledge_Hill_fort_-_geograph.org.uk_-_4856777.jpg', 614528, NULL, NULL, '/data/images/wiki/e473f682/Burledge Hill fort - geograph.org.uk - 4856777.webp', 'import-hero/insert:e473f682-8b9c-4d5c-b2cc-0ca24fcc06bc'),
    (21, 'e5051a8b-714a-4878-869d-6190e20380cd'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Grim%27s_Ditch%2C_Middlesex_-_geograph-2387972.jpg', 684590, NULL, NULL, '/data/images/wiki/e5051a8b/Grim''s Ditch, Middlesex - geograph-2387972.webp', 'import-hero/insert:e5051a8b-714a-4878-869d-6190e20380cd'),
    (22, 'e5e74a71-b666-42a3-917b-cec6e80c81ca'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Ancient_Greece_Marble_Cylindrical_altar_of_the_Twelve_Gods%2C_found_near_the_Agora%2C_350-340_BC.jpg', 99828, NULL, NULL, '/data/images/wiki/e5e74a71/Ancient Greece Marble Cylindrical altar of the Twelve Gods, found near the Agora, 350-340 BC.webp', 'import-hero/insert:e5e74a71-b666-42a3-917b-cec6e80c81ca'),
    (23, 'e8235f8c-e30c-4c97-8297-639b2681d46b'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/f1/%C3%85sli-Vasshalsen_9066.jpg', 1219504, NULL, NULL, '/data/images/wiki/e8235f8c/Åsli-Vasshalsen 9066.webp', 'import-hero/insert:e8235f8c-e30c-4c97-8297-639b2681d46b'),
    (24, 'e8879fb9-adb0-48f3-8672-51923c57047d'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/5/59/Blaundos_Antik_Kenti_-_U%C5%9Fak.jpg', 233524, NULL, NULL, '/data/images/wiki/e8879fb9/Blaundos Antik Kenti - Uşak.webp', 'import-hero/insert:e8879fb9-adb0-48f3-8672-51923c57047d'),
    (25, 'e89f8ecd-2c72-4d59-8618-315d5b0e2361'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/de/Olmedo_-_Monte_Baranta_%2805%29.JPG', 455786, NULL, NULL, '/data/images/wiki/e89f8ecd/Olmedo - Monte Baranta (05).webp', 'import-hero/insert:e89f8ecd-2c72-4d59-8618-315d5b0e2361');

DO $$
DECLARE
    bad integer;
BEGIN
    -- every named row is still the one this wave created
    SELECT count(*) INTO bad FROM _ih_uninsert r
      LEFT JOIN wiki_images w
        ON w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes
     WHERE w.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'rollback %: % row(s) this wave created are not there to undo',
            'insert-2026-10-07-007-001', bad;
    END IF;

    DELETE FROM wiki_images w USING _ih_uninsert r
     WHERE w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes;

    UPDATE wiki_images w SET is_hero = true
      FROM _ih_uninsert r
     WHERE r.demoted_id IS NOT NULL AND w.id = r.demoted_id AND w.is_hero IS NOT TRUE;

    UPDATE unified_sites u SET thumbnail_url = r.old_thumbnail
      FROM _ih_uninsert r
     WHERE u.id = r.site_id AND r.new_thumbnail IS DISTINCT FROM r.old_thumbnail
       AND u.thumbnail_url IS DISTINCT FROM r.old_thumbnail;

    -- the journal goes with the write it describes
    DELETE FROM remediation_change_log l USING _ih_uninsert r
     WHERE l.run_stamp = 'insert-2026-10-07-007-001' AND l.change_key LIKE r.change_key || '%';
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-007-001';
SELECT 'rows this chunk created',
       count(*)::text
  FROM wiki_images w
  JOIN _ih_uninsert r ON w.site_id = r.site_id AND w.original_url = r.original_url
                    AND w.file_size_bytes = r.file_size_bytes;
COMMIT;
