-- Generated by scripts/remediation/bcases/coord_plan.py - do not edit by hand.
-- plan sha256 4cf9b517288bc99d5a835feff0f6e8d4fa1fa6b4a7aabfa0736091945060405c
-- the coordinate move of 9 curated site(s): 27 journalled changes (geom, lat, lon each); run stamp '2026-09-23_owner-case-coordinates'.
-- Every change goes through apply_remediation_change(): conditional on the old value, one
-- row by unified_sites.id, re-read, journalled in the same statement.
\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _coord_plan (
    site_id     UUID NOT NULL,
    column_name TEXT NOT NULL,
    old_value   TEXT NOT NULL,
    new_value   TEXT NOT NULL,
    change_key  TEXT NOT NULL,
    evidence    JSONB NOT NULL,
    PRIMARY KEY (site_id, column_name)
) ON COMMIT DROP;

INSERT INTO _coord_plan (site_id, column_name, old_value, new_value, change_key, evidence) VALUES
    ('27330a46-8900-4b3b-9094-1910364284bf'::uuid, 'geom', '0101000020E61000009DD4887AF1145D402F42B67EBFF04340', 'SRID=4326;POINT(115.768498 40.462413)', 'coordinates:a7b78900ce302b3f9ab0eb9c2497c5bfe04567f147b2b7c84e90adfc9c6c5968', '[{"quote": "P625 = 40.462413, 115.768498 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q10913277"}, {"quote": "enwiki ''Guyaju Caves'' coordinates = 40.46555556, 115.76888889 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Guyaju_Caves"}, {"quote": "wikidata and enwiki agree within 351 m (independent), the stored point is 80.22 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('27330a46-8900-4b3b-9094-1910364284bf'::uuid, 'lat', '39.8808439626631', '40.462413', 'coordinates:cd31a984ac6fb124a09a561e46bffd08781dad00dd04dfa387312376045e0977', '[{"quote": "P625 = 40.462413, 115.768498 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q10913277"}, {"quote": "enwiki ''Guyaju Caves'' coordinates = 40.46555556, 115.76888889 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Guyaju_Caves"}, {"quote": "wikidata and enwiki agree within 351 m (independent), the stored point is 80.22 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('27330a46-8900-4b3b-9094-1910364284bf'::uuid, 'lon', '116.32723868715625', '115.768498', 'coordinates:10f7ea484137bdcd9df2a462a3ebd196027df885b0652ccf7342ae8d3e256fdd', '[{"quote": "P625 = 40.462413, 115.768498 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q10913277"}, {"quote": "enwiki ''Guyaju Caves'' coordinates = 40.46555556, 115.76888889 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Guyaju_Caves"}, {"quote": "wikidata and enwiki agree within 351 m (independent), the stored point is 80.22 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('7d1856ba-e68a-4b0a-b3d9-1da34299a6d0'::uuid, 'geom', '0101000020E6100000E9E4F577242B51C0DB7C00B5FAF02EC0', 'SRID=4326;POINT(-68.67305556 -15.49472222)', 'coordinates:7842a086f6ec4a1f9f20869203a1053619a82ca2991959e90e63758c24cbf14f', '[{"quote": "P625 = -15.494722, -68.673056 (precision 0.00027777777777778)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1674009"}, {"quote": "enwiki ''Iskanwaya'' coordinates = -15.486558, -68.674285 (given to 6 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Iskanwaya"}, {"quote": "wikidata and enwiki agree within 917 m (independent), the stored point is 2.68 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('7d1856ba-e68a-4b0a-b3d9-1da34299a6d0'::uuid, 'lat', '-15.470662742909942', '-15.49472222', 'coordinates:60d95efc12c4bc04c7786cb315c6ead846c7f8d4dc1f8dd3bd6c3ff248df69b7', '[{"quote": "P625 = -15.494722, -68.673056 (precision 0.00027777777777778)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1674009"}, {"quote": "enwiki ''Iskanwaya'' coordinates = -15.486558, -68.674285 (given to 6 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Iskanwaya"}, {"quote": "wikidata and enwiki agree within 917 m (independent), the stored point is 2.68 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('7d1856ba-e68a-4b0a-b3d9-1da34299a6d0'::uuid, 'lon', '-68.67410086644271', '-68.67305556', 'coordinates:b0c03e5d988d806d3d8b0e4ca173a755724bdeaf788fba203f2b1e39206ba86c', '[{"quote": "P625 = -15.494722, -68.673056 (precision 0.00027777777777778)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1674009"}, {"quote": "enwiki ''Iskanwaya'' coordinates = -15.486558, -68.674285 (given to 6 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Iskanwaya"}, {"quote": "wikidata and enwiki agree within 917 m (independent), the stored point is 2.68 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('84894867-d7b1-49b7-a1e7-398e73a725f2'::uuid, 'geom', '0101000020E6100000D5B1987EEE7B4540D7E5F8B7B4764240', 'SRID=4326;POINT(42.940816 36.838181)', 'coordinates:242bf3df6be1192832272334dbc09bf41156d82d2ed53f6cb234a52bf05d1c37', '[{"quote": "P625 = 36.838181, 42.940816 (precision 1e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q106371911"}, {"quote": "enwiki ''Halamata Cave'' coordinates = 36.8404006, 42.9450336 (given to 7 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Halamata_Cave"}, {"quote": "wikidata and enwiki agree within 449 m (independent), the stored point is 10.21 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('84894867-d7b1-49b7-a1e7-398e73a725f2'::uuid, 'lat', '36.92739009526456', '36.838181', 'coordinates:14ede450add285e1eb9501e86ce44a1e2927ae78f4901b3b8f5c8cfac4e1da62', '[{"quote": "P625 = 36.838181, 42.940816 (precision 1e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q106371911"}, {"quote": "enwiki ''Halamata Cave'' coordinates = 36.8404006, 42.9450336 (given to 7 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Halamata_Cave"}, {"quote": "wikidata and enwiki agree within 449 m (independent), the stored point is 10.21 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('84894867-d7b1-49b7-a1e7-398e73a725f2'::uuid, 'lon', '42.968215775068224', '42.940816', 'coordinates:6090caa5f2d265811f0b899a082fe619406f9440ebf1dc1e0870d989cd358479', '[{"quote": "P625 = 36.838181, 42.940816 (precision 1e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q106371911"}, {"quote": "enwiki ''Halamata Cave'' coordinates = 36.8404006, 42.9450336 (given to 7 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Halamata_Cave"}, {"quote": "wikidata and enwiki agree within 449 m (independent), the stored point is 10.21 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('b8abad34-a66f-4e08-85e9-9b069301128b'::uuid, 'geom', '0101000020E6100000E1647508C135404059DACCA628454840', 'SRID=4326;POINT(32.37936 48.72456)', 'coordinates:90dd0f90d6360f55ad226eb7c769e7e716b44603920dab1d8cebc8c150da4e54', '[{"quote": "P625 = 48.724560, 32.379360 (precision 1e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q12122408"}, {"quote": "enwiki ''Melgunov Kurgan'' coordinates = 48.72469444, 32.38055556 (given to 8 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Melgunov_Kurgan"}, {"quote": "wikidata and enwiki agree within 89 m (independent), the stored point is 20.70 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('b8abad34-a66f-4e08-85e9-9b069301128b'::uuid, 'lat', '48.54030308725914', '48.72456', 'coordinates:35ebb164fcc2aa4d1cc397bc7c3bf66d8b8939c707c64e7fe7dee6a5317ca81f', '[{"quote": "P625 = 48.724560, 32.379360 (precision 1e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q12122408"}, {"quote": "enwiki ''Melgunov Kurgan'' coordinates = 48.72469444, 32.38055556 (given to 8 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Melgunov_Kurgan"}, {"quote": "wikidata and enwiki agree within 89 m (independent), the stored point is 20.70 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('b8abad34-a66f-4e08-85e9-9b069301128b'::uuid, 'lon', '32.41995340091831', '32.37936', 'coordinates:bc5d6f6e9fe0ae81343721d938c144d1d497116556a6343f181f42519af238fa', '[{"quote": "P625 = 48.724560, 32.379360 (precision 1e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q12122408"}, {"quote": "enwiki ''Melgunov Kurgan'' coordinates = 48.72469444, 32.38055556 (given to 8 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Melgunov_Kurgan"}, {"quote": "wikidata and enwiki agree within 89 m (independent), the stored point is 20.70 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('bc28c81f-db22-46a5-bc4e-18cb8c2ecbec'::uuid, 'geom', '0101000020E6100000EB918BEDC29558C04ADADDC6433E3340', 'SRID=4326;POINT(-89.81055555555555 18.105)', 'coordinates:7fcdc4a522ca56151f53ff1bb491dff56d3db75982818194536e7d4f3dd471d7', '[{"quote": "P625 = 18.105000, -89.810556 (precision 0.0002777777777777778)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q272771"}, {"quote": "enwiki ''Calakmul'' coordinates = 18.10539167, -89.81082778 (given to 8 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Calakmul"}, {"quote": "wikidata and enwiki agree within 52 m (independent), the stored point is 907.27 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('bc28c81f-db22-46a5-bc4e-18cb8c2ecbec'::uuid, 'lat', '19.243221692240958', '18.105', 'coordinates:e0b7d6032150565be4920f849565c32273258b027636c4049c9f394b746e625e', '[{"quote": "P625 = 18.105000, -89.810556 (precision 0.0002777777777777778)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q272771"}, {"quote": "enwiki ''Calakmul'' coordinates = 18.10539167, -89.81082778 (given to 8 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Calakmul"}, {"quote": "wikidata and enwiki agree within 52 m (independent), the stored point is 907.27 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('bc28c81f-db22-46a5-bc4e-18cb8c2ecbec'::uuid, 'lon', '-98.34002245550043', '-89.81055555555555', 'coordinates:a0a2cc3a2945263db4c91e7b2127552b3a7f612292e69c85d7dcdf017e452b3c', '[{"quote": "P625 = 18.105000, -89.810556 (precision 0.0002777777777777778)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q272771"}, {"quote": "enwiki ''Calakmul'' coordinates = 18.10539167, -89.81082778 (given to 8 decimals)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Calakmul"}, {"quote": "wikidata and enwiki agree within 52 m (independent), the stored point is 907.27 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('c365e1f8-e4bb-43f0-9c46-58497b709fae'::uuid, 'geom', '0101000020E6100000448303705C1E3D40D8B3F81AFCF44240', 'SRID=4326;POINT(29.1223 37.9236)', 'coordinates:1ecd6e2c3ed8f98cda981e8fb211fab48e70a0dab4a4be9d06adc10b5d1938bc', '[{"quote": "P625 = 37.923600, 29.122300 (precision 0.0001)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q105893254"}, {"quote": "enwiki ''Pamukkale'' coordinates = 37.92388889, 29.12333333 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Pamukkale"}, {"quote": "wikidata and enwiki agree within 96 m (independent), the stored point is 1.12 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('c365e1f8-e4bb-43f0-9c46-58497b709fae'::uuid, 'lat', '37.91394364494016', '37.9236', 'coordinates:d2d520cff2b62a97c18782786390f9753126a6971fb108ab00a1db5813d92b76', '[{"quote": "P625 = 37.923600, 29.122300 (precision 0.0001)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q105893254"}, {"quote": "enwiki ''Pamukkale'' coordinates = 37.92388889, 29.12333333 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Pamukkale"}, {"quote": "wikidata and enwiki agree within 96 m (independent), the stored point is 1.12 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('c365e1f8-e4bb-43f0-9c46-58497b709fae'::uuid, 'lon', '29.118597985131842', '29.1223', 'coordinates:70a8f47354f6f1b3d04863593cb87eb6d4e2a96882141ad6a580f59edbf7828a', '[{"quote": "P625 = 37.923600, 29.122300 (precision 0.0001)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q105893254"}, {"quote": "enwiki ''Pamukkale'' coordinates = 37.92388889, 29.12333333 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Pamukkale"}, {"quote": "wikidata and enwiki agree within 96 m (independent), the stored point is 1.12 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('c81634b0-969c-484b-aa1f-5b5926e05fd3'::uuid, 'geom', '0101000020E61000000D0526DD39151BC051A7FC1E1A3C4540', 'SRID=4326;POINT(-6.759002 42.458699)', 'coordinates:ac2344e977fd271b793022f23284ab26b4a8d4bc8da7fd2fe93e9c66c3fa2997', '[{"quote": "P625 = 42.458699, -6.759002 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q696803"}, {"quote": "enwiki ''Las Médulas'' coordinates = 42.45888889, -6.76 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Las_Médulas"}, {"quote": "wikidata and enwiki agree within 85 m (independent), the stored point is 1.54 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('c81634b0-969c-484b-aa1f-5b5926e05fd3'::uuid, 'lat', '42.46954715096093', '42.458699', 'coordinates:41311e32f61c46ffa72e112077f22a5499c46c3cf342f513f8dfae3f3a132043', '[{"quote": "P625 = 42.458699, -6.759002 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q696803"}, {"quote": "enwiki ''Las Médulas'' coordinates = 42.45888889, -6.76 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Las_Médulas"}, {"quote": "wikidata and enwiki agree within 85 m (independent), the stored point is 1.54 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('c81634b0-969c-484b-aa1f-5b5926e05fd3'::uuid, 'lon', '-6.770728545613804', '-6.759002', 'coordinates:1d5a7f27fb7ab714ff8a6f13060139fc9e0986d82c9affba907ca987da69e41c', '[{"quote": "P625 = 42.458699, -6.759002 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q696803"}, {"quote": "enwiki ''Las Médulas'' coordinates = 42.45888889, -6.76 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Las_Médulas"}, {"quote": "wikidata and enwiki agree within 85 m (independent), the stored point is 1.54 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('d6d44645-a99b-4826-85b3-eb0123faadd2'::uuid, 'geom', '0101000020E6100000AE2B548AA6534340E9CBF5B2A2F94240', 'SRID=4326;POINT(36.60455 45.349449)', 'coordinates:4515ca9325339c04b861af52143f3a6f7b23699aff4bc55bffffbdd496e7d09d', '[{"quote": "P625 = 45.349449, 36.604550 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q772781"}, {"quote": "enwiki ''Yeni-Kale'' coordinates = 45.34916667, 36.60472222 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Yeni-Kale"}, {"quote": "wikidata and enwiki agree within 34 m (independent), the stored point is 840.10 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('d6d44645-a99b-4826-85b3-eb0123faadd2'::uuid, 'lat', '37.950277681367716', '45.349449', 'coordinates:b8cc64dd51ea09ea839cd222b4d7f93ef300ea8ff615886e28829b4433ab1741', '[{"quote": "P625 = 45.349449, 36.604550 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q772781"}, {"quote": "enwiki ''Yeni-Kale'' coordinates = 45.34916667, 36.60472222 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Yeni-Kale"}, {"quote": "wikidata and enwiki agree within 34 m (independent), the stored point is 840.10 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('d6d44645-a99b-4826-85b3-eb0123faadd2'::uuid, 'lon', '38.65351990804571', '36.60455', 'coordinates:7b66ad034f7832b94a67c6dc7219a838be770082008c6d5936545c0fea8220e3', '[{"quote": "P625 = 45.349449, 36.604550 (precision 1e-06)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q772781"}, {"quote": "enwiki ''Yeni-Kale'' coordinates = 45.34916667, 36.60472222 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Yeni-Kale"}, {"quote": "wikidata and enwiki agree within 34 m (independent), the stored point is 840.10 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('f947a367-a17a-4cb3-9d43-93965c88d3bf'::uuid, 'geom', '0101000020E6100000A34672537F0F58C0D464B5AE80433340', 'SRID=4326;POINT(-96.4041111111111 19.44708333333333)', 'coordinates:7cfc88ab48f011a8fddd5a29d637a6397456d1ba41b3d2ce2e3cbfd290a7c969', '[{"quote": "P625 = 19.447083, -96.404111 (precision 2.777777777777778e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1053364"}, {"quote": "enwiki ''Cempoala'' coordinates = 19.445, -96.40888889 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Cempoala"}, {"quote": "wikidata and enwiki agree within 552 m (independent), the stored point is 26.54 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('f947a367-a17a-4cb3-9d43-93965c88d3bf'::uuid, 'lat', '19.26368228844224', '19.44708333333333', 'coordinates:45d9570c08056d441f9160db83bbffd45650fbb9a466019ff04cb9f51d4e7138', '[{"quote": "P625 = 19.447083, -96.404111 (precision 2.777777777777778e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1053364"}, {"quote": "enwiki ''Cempoala'' coordinates = 19.445, -96.40888889 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Cempoala"}, {"quote": "wikidata and enwiki agree within 552 m (independent), the stored point is 26.54 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb),
    ('f947a367-a17a-4cb3-9d43-93965c88d3bf'::uuid, 'lon', '-96.24214636001356', '-96.4041111111111', 'coordinates:9c932efa7d9c67e4e8a1d3738d262a84a5a08f323a1bfafe35dbe023fe5d003b', '[{"quote": "P625 = 19.447083, -96.404111 (precision 2.777777777777778e-05)", "source": "witness:wikidata", "url": "https://www.wikidata.org/wiki/Q1053364"}, {"quote": "enwiki ''Cempoala'' coordinates = 19.445, -96.40888889 (given to whole arcseconds)", "source": "witness:enwiki", "url": "https://en.wikipedia.org/wiki/Cempoala"}, {"quote": "wikidata and enwiki agree within 552 m (independent), the stored point is 26.54 km away; tolerance 1000.0 m; rule two-independent-witnesses", "source": "owner-case classifier", "url": null}]'::jsonb);

DO $$
DECLARE
    bad      INTEGER;
    moved    INTEGER := 0;
    expected INTEGER := 27;
    r        RECORD;
BEGIN
    -- guard 1: every site is a curated site that still exists
    SELECT count(*) INTO bad FROM _coord_plan p LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) are not curated sites', bad;
    END IF;
    -- guard 2: every site moves as a whole - geom, lat and lon, nothing else
    SELECT count(*) INTO bad FROM (
        SELECT site_id FROM _coord_plan GROUP BY site_id
        HAVING array_agg(column_name ORDER BY column_name) <> ARRAY['geom', 'lat', 'lon']
    ) x;
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % site(s) do not move geom, lat and lon together', bad;
    END IF;
    -- guard 3: every row still holds the planned old value, compared in the column's type
    SELECT count(*) INTO bad FROM _coord_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE (p.column_name = 'lat' AND u.lat IS DISTINCT FROM p.old_value::double precision)
        OR (p.column_name = 'lon' AND u.lon IS DISTINCT FROM p.old_value::double precision)
        OR (p.column_name = 'geom' AND u.geom IS DISTINCT FROM p.old_value::geometry);
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) no longer hold the planned old value', bad;
    END IF;
    -- guard 4: the planned geom is the planned point
    SELECT count(*) INTO bad FROM _coord_plan g
      JOIN _coord_plan a ON a.site_id = g.site_id AND a.column_name = 'lat'
      JOIN _coord_plan o ON o.site_id = g.site_id AND o.column_name = 'lon'
     WHERE g.column_name = 'geom' AND g.new_value::geometry IS DISTINCT FROM
           ST_SetSRID(ST_MakePoint(o.new_value::double precision,
                                   a.new_value::double precision), 4326);
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % planned geom value(s) are not the planned point', bad;
    END IF;
    -- the writes: apply_remediation_change raises unless exactly one row matched
    FOR r IN SELECT * FROM _coord_plan ORDER BY site_id, column_name LOOP
        moved := moved + apply_remediation_change(
            'unified_sites', r.column_name, 'id', r.site_id::text,
            r.old_value, r.new_value,
            'B1B2/coordinates', '2026-09-23_owner-case-coordinates', r.change_key, 'two_source', r.evidence, r.site_id);
    END LOOP;
    IF moved <> expected THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) changed, % planned', moved, expected;
    END IF;
    -- invariant 1: every site holds the new point, and a geom that is that point
    SELECT count(*) INTO bad FROM _coord_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE (p.column_name = 'lat' AND u.lat IS DISTINCT FROM p.new_value::double precision)
        OR (p.column_name = 'lon' AND u.lon IS DISTINCT FROM p.new_value::double precision)
        OR (p.column_name = 'geom' AND u.geom IS DISTINCT FROM
            ST_SetSRID(ST_MakePoint(u.lon, u.lat), 4326));
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) do not hold the new point', bad;
    END IF;
    -- invariant 2: the journal and the plan agree in both directions
    SELECT count(*) INTO bad FROM _coord_plan p LEFT JOIN remediation_change_log l
        ON l.run_stamp = '2026-09-23_owner-case-coordinates' AND l.change_key = p.change_key
       AND l.table_name = 'unified_sites' AND l.column_name = p.column_name
       AND l.row_pk = p.site_id::text
       AND l.old_value = p.old_value AND l.new_value = p.new_value
     WHERE l.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: % row(s) have no matching journal row', bad;
    END IF;
    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = '2026-09-23_owner-case-coordinates'
       AND NOT EXISTS (SELECT 1 FROM _coord_plan p WHERE p.change_key = l.change_key);
    IF bad > 0 THEN
        RAISE EXCEPTION 'owner-case coordinates: this stamp journalled % row(s) outside the plan', bad;
    END IF;
    RAISE NOTICE 'owner-case coordinates: % row(s) changed and journalled', moved;
END $$;

COMMIT;

SELECT 'journal rows for this stamp' AS metric, count(*)::text AS value
  FROM remediation_change_log WHERE run_stamp = '2026-09-23_owner-case-coordinates';
