-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: c37f8fe122ce2e1c740cf2dc83789ab2e3958dd5c42a3a6145f49a419af59e34
-- lane 'ih6' (import-hero/insert), 5 row(s) to create; run stamp 'insert-2026-10-07-003-001'.
-- Every row is created together with its journal rows, inside this transaction: a journal that
-- disagrees with the data cannot be committed, and a rolled-back statement leaves nothing behind.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_insert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    filename          TEXT NOT NULL,
    original_url      TEXT NOT NULL,
    commons_page_url  TEXT NOT NULL,
    title             TEXT NOT NULL,
    author            TEXT NOT NULL,
    author_url        TEXT NOT NULL,
    license           TEXT NOT NULL,
    license_url       TEXT NOT NULL,
    width             INTEGER NOT NULL,
    height            INTEGER NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT NOT NULL,
    change_key        TEXT NOT NULL,
    reason            TEXT NOT NULL,
    evidence          JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_insert (seq, site_id, filename, original_url, commons_page_url, title, author, author_url, license, license_url, width, height, file_size_bytes, demoted_id, old_thumbnail, new_thumbnail, change_key, reason, evidence) VALUES
    (1, '3315cd99-84ed-4e95-b743-fe75fb4c7654'::uuid, 'Torre de Almofala (8).webp', 'https://upload.wikimedia.org/wikipedia/commons/7/73/Torre_de_Almofala_%288%29.jpg', 'https://commons.wikimedia.org/wiki/File%3ATorre%20de%20Almofala%20%288%29.jpg', 'Torre de Almofala (8)', 'Hugo Ferreira', 'https://commons.wikimedia.org/w/index.php?title=User:HugoNissa&amp;action=edit&amp;redlink=1', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1200, 414978, NULL, NULL, '/data/images/wiki/3315cd99/Torre de Almofala (8).webp', 'import-hero/insert:3315cd99-84ed-4e95-b743-fe75fb4c7654', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/7/73/Torre_de_Almofala_%288%29.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ATorre%20de%20Almofala%20%288%29.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/7/73/Torre_de_Almofala_%288%29.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 3315cd99-84ed-4e95-b743-fe75fb4c7654"}]'::jsonb),
    (2, '34fd3d60-f6b8-4ea4-8d6d-36ec82d70a5f'::uuid, 'Sanctuary of Aphrodite, Palaepaphos.webp', 'https://upload.wikimedia.org/wikipedia/commons/7/76/Sanctuary_of_Aphrodite%2C_Palaepaphos.jpg', 'https://commons.wikimedia.org/wiki/File%3ASanctuary%20of%20Aphrodite%2C%20Palaepaphos.jpg', 'Sanctuary of Aphrodite, Palaepaphos', 'Rjdeadly', 'https://commons.wikimedia.org/w/index.php?title=User:Rjdeadly&amp;action=edit&amp;redlink=1', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1119, 88462, NULL, NULL, '/data/images/wiki/34fd3d60/Sanctuary of Aphrodite, Palaepaphos.webp', 'import-hero/insert:34fd3d60-f6b8-4ea4-8d6d-36ec82d70a5f', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/7/76/Sanctuary_of_Aphrodite%2C_Palaepaphos.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ASanctuary%20of%20Aphrodite%2C%20Palaepaphos.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/7/76/Sanctuary_of_Aphrodite%2C_Palaepaphos.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 34fd3d60-f6b8-4ea4-8d6d-36ec82d70a5f"}]'::jsonb),
    (3, '351a3b2e-3492-4b92-adf0-700269fb06c7'::uuid, 'Torralba d''en Salort (29836859620).webp', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Torralba_d%27en_Salort_%2829836859620%29.jpg', 'https://commons.wikimedia.org/wiki/File%3ATorralba%20d%27en%20Salort%20%2829836859620%29.jpg', 'Torralba d''en Salort (29836859620)', 'Ben Salter from Wales', 'https://www.flickr.com/people/45767493@N00', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', 1600, 902, 180816, NULL, NULL, '/data/images/wiki/351a3b2e/Torralba d''en Salort (29836859620).webp', 'import-hero/insert:351a3b2e-3492-4b92-adf0-700269fb06c7', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Torralba_d%27en_Salort_%2829836859620%29.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ATorralba%20d%27en%20Salort%20%2829836859620%29.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/f/f2/Torralba_d%27en_Salort_%2829836859620%29.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 351a3b2e-3492-4b92-adf0-700269fb06c7"}]'::jsonb),
    (4, '37c35150-d91b-44bb-a039-48783357de8e'::uuid, 'World War I memorial on Kosmaj 2.webp', 'https://upload.wikimedia.org/wikipedia/commons/2/26/World_War_I_memorial_on_Kosmaj_2.jpg', 'https://commons.wikimedia.org/wiki/File%3AWorld%20War%20I%20memorial%20on%20Kosmaj%202.jpg', 'World War I memorial on Kosmaj 2', 'Vacant0', 'https://commons.wikimedia.org/wiki/User:Vacant0', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1200, 669412, NULL, NULL, '/data/images/wiki/37c35150/World War I memorial on Kosmaj 2.webp', 'import-hero/insert:37c35150-d91b-44bb-a039-48783357de8e', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/2/26/World_War_I_memorial_on_Kosmaj_2.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AWorld%20War%20I%20memorial%20on%20Kosmaj%202.jpg"}, {"quote": "20 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/2/26/World_War_I_memorial_on_Kosmaj_2.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 37c35150-d91b-44bb-a039-48783357de8e"}]'::jsonb),
    (5, '38a93ff8-af94-41d3-bc8a-7a60e529440a'::uuid, 'Camlet Way in Hadley Wood.webp', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Camlet_Way_in_Hadley_Wood.JPG', 'https://commons.wikimedia.org/wiki/File%3ACamlet%20Way%20in%20Hadley%20Wood.JPG', 'Camlet Way in Hadley Wood', 'Philafrenzy', 'https://commons.wikimedia.org/wiki/User:Philafrenzy', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1200, 610242, NULL, NULL, '/data/images/wiki/38a93ff8/Camlet Way in Hadley Wood.webp', 'import-hero/insert:38a93ff8-af94-41d3-bc8a-7a60e529440a', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Camlet_Way_in_Hadley_Wood.JPG", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ACamlet%20Way%20in%20Hadley%20Wood.JPG"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/e/e6/Camlet_Way_in_Hadley_Wood.JPG", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 38a93ff8-af94-41d3-bc8a-7a60e529440a"}]'::jsonb);

DO $$
DECLARE
    bad  integer;
    r    RECORD;
    new_id integer;
    cols TEXT;
BEGIN
    -- guard 1: every planned site is a curated site (the message names the source in words, so
    -- the log of a refused wave says what was expected)
    SELECT count(*) INTO bad FROM (SELECT DISTINCT site_id FROM _ih_insert) p
      LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % planned site(s) are not ancient_nerds sites',
            'insert-2026-10-07-003-001', bad;
    END IF;

    FOR r IN SELECT * FROM _ih_insert ORDER BY seq LOOP
        -- guard 2: no row of this site holds the file yet. The unique constraint on
        -- (site_id, original_url) is a second line of defence behind this one.
        IF EXISTS (SELECT 1 FROM wiki_images w
                    WHERE w.site_id = r.site_id AND w.original_url = r.original_url) THEN
            RAISE EXCEPTION '%: site % already holds this file', r.change_key, r.site_id;
        END IF;

        -- guard 3: the file reaches the hero floor
        IF r.width < 1600 OR r.height < 900 THEN
            RAISE EXCEPTION '%: the file is %x%, under the %x% this lane serves', r.change_key,
                r.width, r.height, 1600, 900;
        END IF;

        -- guard 4: the row that holds the flag is still the one the plan demotes
        IF r.demoted_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM wiki_images w
             WHERE w.id = r.demoted_id AND w.site_id = r.site_id AND w.is_hero) THEN
            RAISE EXCEPTION '%: the row that held the flag for site % moved since the read',
                r.change_key, r.site_id;
        END IF;

        -- guard 5: the thumbnail still holds the value the read found
        IF (SELECT u.thumbnail_url FROM unified_sites u WHERE u.id = r.site_id)
           IS DISTINCT FROM r.old_thumbnail THEN
            RAISE EXCEPTION '%: the thumbnail of site % moved since the read', r.change_key, r.site_id;
        END IF;

        -- the row that gives up the flag, and the row that takes it
        IF r.demoted_id IS NOT NULL THEN
            UPDATE wiki_images SET is_hero = false
             WHERE id = r.demoted_id AND is_hero AND site_id = r.site_id;
        END IF;

        -- the three columns the file does not carry: the next free number of this site (derived,
        -- never invented), the owner's picture rather than a measured lead image of the article,
        -- and the source 49,683 of the 49,691 curated rows carry
        INSERT INTO wiki_images
            (site_id, filename, original_url, commons_page_url, title, author, author_url, license, license_url, width, height, file_size_bytes, is_lead, sort_order, source_type, is_hero, is_excluded)
        SELECT r.site_id, r.filename, r.original_url, r.commons_page_url, r.title, r.author, r.author_url, r.license, r.license_url, r.width, r.height, r.file_size_bytes, false,
               (SELECT COALESCE(MAX(w2.sort_order), -1) + 1 FROM wiki_images w2
                 WHERE w2.site_id = r.site_id),
               'wikimedia', true, false
        RETURNING id INTO new_id;

        IF r.new_thumbnail IS DISTINCT FROM r.old_thumbnail THEN
            UPDATE unified_sites SET thumbnail_url = r.new_thumbnail WHERE id = r.site_id;
        END IF;

        -- the journal, in this transaction: one row per column this statement wrote,
        -- read back from the row it created, so the journal records what the database holds
        INSERT INTO remediation_change_log
            (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value, change_key,
             confidence, evidence, site_id_ref)
        SELECT 'insert-2026-10-07-003-001', 'import-hero/insert/owner-2026-10-05', 'wiki_images', t.col, new_id::text, NULL, t.val,
               r.change_key || ':' || t.col, 'authoritative', r.evidence, r.site_id
          FROM wiki_images w
          CROSS JOIN LATERAL (VALUES
              ('filename', w.filename::text),
              ('original_url', w.original_url::text),
              ('commons_page_url', w.commons_page_url::text),
              ('title', w.title::text),
              ('author', w.author::text),
              ('author_url', w.author_url::text),
              ('license', w.license::text),
              ('license_url', w.license_url::text),
              ('width', w.width::text),
              ('height', w.height::text),
              ('file_size_bytes', w.file_size_bytes::text),
              ('is_lead', w.is_lead::text),
              ('sort_order', w.sort_order::text),
              ('source_type', w.source_type::text)
          ) AS t(col, val)
         WHERE w.id = new_id;

        IF r.demoted_id IS NOT NULL THEN
            INSERT INTO remediation_change_log
                (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value,
                 change_key, confidence, evidence, site_id_ref)
            VALUES ('insert-2026-10-07-003-001', 'import-hero/insert/owner-2026-10-05', 'wiki_images', 'is_hero',
                    r.demoted_id::text, 'true', 'false', r.change_key || ':demote',
                    'authoritative', r.evidence, r.site_id);
        END IF;

        IF r.new_thumbnail IS DISTINCT FROM r.old_thumbnail THEN
            INSERT INTO remediation_change_log
                (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value,
                 change_key, confidence, evidence, site_id_ref)
            VALUES ('insert-2026-10-07-003-001', 'import-hero/insert/owner-2026-10-05', 'unified_sites', 'thumbnail_url',
                    r.site_id::text, r.old_thumbnail, r.new_thumbnail,
                    r.change_key || ':thumbnail', 'authoritative', r.evidence, r.site_id);
        END IF;
    END LOOP;

    -- invariant 1: every planned row stands, with the planned values, the flag and the three
    -- columns the statement derived for it. The temp table is aliased `p`, never `r`: the loop
    -- variable of this block is `r`, and Postgres refuses a reference that could mean either
    -- (measured 2026-10-06, in the rehearsal of chunk-001).
    SELECT count(*) INTO bad FROM _ih_insert p
      LEFT JOIN wiki_images w ON w.site_id = p.site_id AND w.original_url = p.original_url
     WHERE w.id IS NULL OR w.is_hero IS NOT TRUE OR w.is_excluded IS NOT FALSE
        OR w.width IS DISTINCT FROM p.width OR w.height IS DISTINCT FROM p.height
        OR w.file_size_bytes IS DISTINCT FROM p.file_size_bytes
        OR w.filename IS DISTINCT FROM p.filename OR w.original_url IS DISTINCT FROM p.original_url
        OR w.is_lead IS NOT FALSE OR w.source_type IS DISTINCT FROM 'wikimedia'
        OR w.sort_order <> (SELECT COALESCE(MAX(w3.sort_order), 0) FROM wiki_images w3
                             WHERE w3.site_id = p.site_id);
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % inserted row(s) do not stand as planned', 'insert-2026-10-07-003-001', bad;
    END IF;

    -- invariant 2: at most one live hero per touched site (T09's invariant)
    SELECT count(*) INTO bad FROM (
        SELECT w.site_id FROM wiki_images w
          JOIN _ih_insert p ON p.site_id = w.site_id
         WHERE w.is_hero AND w.is_excluded IS NOT TRUE
         GROUP BY w.site_id HAVING count(*) > 1) d;
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % touched site(s) hold more than one live hero row',
            'insert-2026-10-07-003-001', bad;
    END IF;

    -- invariant 3: the journal carries every write, and nothing else
    SELECT count(*) INTO bad FROM _ih_insert p
      LEFT JOIN (SELECT site_id_ref, count(*) AS n FROM remediation_change_log
                  WHERE run_stamp = 'insert-2026-10-07-003-001' GROUP BY site_id_ref) l
        ON l.site_id_ref = p.site_id
     WHERE COALESCE(l.n, 0) <> 14
        + CASE WHEN p.demoted_id IS NOT NULL THEN 1 ELSE 0 END
        + CASE WHEN p.new_thumbnail IS DISTINCT FROM p.old_thumbnail THEN 1 ELSE 0 END;
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % site(s) do not have exactly their planned journal rows',
            'insert-2026-10-07-003-001', bad;
    END IF;
END $$;

-- the same two read-back lines the shared writer ends with, so `--rehearse` recognises the run
SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-003-001';
SELECT 'planned rows', count(*)::text FROM _ih_insert;
COMMIT;
