-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: c37f8fe122ce2e1c740cf2dc83789ab2e3958dd5c42a3a6145f49a419af59e34
-- The reversal of lane 'ih6': the rows this wave created go back out, the flag returns to
-- the row that held it, and the thumbnail returns to the value the read found.
-- The row is named by the triple this lane wrote - (site_id, original_url, file_size_bytes) - so
-- the statement cannot delete a row somebody else created.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_uninsert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    original_url      TEXT NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT,
    change_key        TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_uninsert VALUES
    (1, '3315cd99-84ed-4e95-b743-fe75fb4c7654'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/7/73/Torre_de_Almofala_%288%29.jpg', 414978, NULL, NULL, '/data/images/wiki/3315cd99/Torre de Almofala (8).webp', 'import-hero/insert:3315cd99-84ed-4e95-b743-fe75fb4c7654'),
    (2, '34fd3d60-f6b8-4ea4-8d6d-36ec82d70a5f'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/7/76/Sanctuary_of_Aphrodite%2C_Palaepaphos.jpg', 88462, NULL, NULL, '/data/images/wiki/34fd3d60/Sanctuary of Aphrodite, Palaepaphos.webp', 'import-hero/insert:34fd3d60-f6b8-4ea4-8d6d-36ec82d70a5f'),
    (3, '351a3b2e-3492-4b92-adf0-700269fb06c7'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Torralba_d%27en_Salort_%2829836859620%29.jpg', 180816, NULL, NULL, '/data/images/wiki/351a3b2e/Torralba d''en Salort (29836859620).webp', 'import-hero/insert:351a3b2e-3492-4b92-adf0-700269fb06c7'),
    (4, '37c35150-d91b-44bb-a039-48783357de8e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/26/World_War_I_memorial_on_Kosmaj_2.jpg', 669412, NULL, NULL, '/data/images/wiki/37c35150/World War I memorial on Kosmaj 2.webp', 'import-hero/insert:37c35150-d91b-44bb-a039-48783357de8e'),
    (5, '38a93ff8-af94-41d3-bc8a-7a60e529440a'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Camlet_Way_in_Hadley_Wood.JPG', 610242, NULL, NULL, '/data/images/wiki/38a93ff8/Camlet Way in Hadley Wood.webp', 'import-hero/insert:38a93ff8-af94-41d3-bc8a-7a60e529440a');

DO $$
DECLARE
    bad integer;
BEGIN
    -- every named row is still the one this wave created
    SELECT count(*) INTO bad FROM _ih_uninsert r
      LEFT JOIN wiki_images w
        ON w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes
     WHERE w.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'rollback %: % row(s) this wave created are not there to undo',
            'insert-2026-10-07-003-001', bad;
    END IF;

    DELETE FROM wiki_images w USING _ih_uninsert r
     WHERE w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes;

    UPDATE wiki_images w SET is_hero = true
      FROM _ih_uninsert r
     WHERE r.demoted_id IS NOT NULL AND w.id = r.demoted_id AND w.is_hero IS NOT TRUE;

    UPDATE unified_sites u SET thumbnail_url = r.old_thumbnail
      FROM _ih_uninsert r
     WHERE u.id = r.site_id AND r.new_thumbnail IS DISTINCT FROM r.old_thumbnail
       AND u.thumbnail_url IS DISTINCT FROM r.old_thumbnail;

    -- the journal goes with the write it describes
    DELETE FROM remediation_change_log l USING _ih_uninsert r
     WHERE l.run_stamp = 'insert-2026-10-07-003-001' AND l.change_key LIKE r.change_key || '%';
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-003-001';
SELECT 'rows this chunk created',
       count(*)::text
  FROM wiki_images w
  JOIN _ih_uninsert r ON w.site_id = r.site_id AND w.original_url = r.original_url
                    AND w.file_size_bytes = r.file_size_bytes;
COMMIT;
