"""Undo a named list of journal rows - the journal-reversal lanes.

## What it does

Every production write of the remediation left a `remediation_change_log` row with the value it
replaced. Reversing one is a write of its own: the new value is the row's `old_value`, conditioned
on the live value still being the row's `new_value` (guard 3), and the transaction refuses unless
every planned cell is the exact inverse of the *last* journal row of its cell (guard 6). The
reversal gets its own run stamp, test id and change keys, so the phase-3 acceptance
(`output/remediation/tools/verify_writes.py --allow-stamp <stamp>`) reads the reversed rows as
superseded, never as deviations.

Each list is explicit and reviewed: `lane.REVERSAL_LISTS` in code (`journal-reversal-1`: 3 rows,
`journal-reversal-2`: 53, `journal-reversal-3`: the Opus re-verification's reverts and their period
labels, generated by `reversal_opus.py`), and per row the reason and the evidence in the lane
directory's `REASONS.json`. Both must name the same rows.

## How a row is decided (`classify_reversal`, first failure refuses)

1. the journal row exists and is the `unified_sites` cell `REASONS.json` names; 2. the column is
   one the lane owns; 3. the site is curated; 4. the cell's journal is continuous and ends at the
   live value (`plan.journal_break`); 5. the named row is the cell's last link; 6. the value it
   replaced is not NULL and reads in the column's type; 7. every quote of its evidence is where it
   says: the live description, the page `--collect` fetched (English Wikipedia, Wikidata), the
   gold-standard record - which must also judge the restored value CORRECT -, the evidence the
   undone journal row itself carries (`journal`), the re-review row that decided to reverse
   exactly this write (`rereview:<change_key>`, `REREVIEW_1_FINAL.jsonl` in the lane directory),
   or the Opus re-verification's decision to revert exactly this write (`opus:<change_key>`,
   `output/remediation/opus_audit/DECISIONS.jsonl`): the quote must be one its deciding verdicts
   carry - the counted verdicts that are not keep, in the verdict files the decision names -, each
   found by the audit's own machine quote check.

## The period label (`keep_the_period_label`, over the whole list)

`period_name` is the bucket of `period_start` (`categorize_period`; the period-name lane of
2026-09-22 re-derived it wherever the two disagreed). A reversal must not undo that: a
`period_name` row is restored only to the bucket of the `period_start` the list leaves the site
with, and a `period_start` row that would move the site out of its label's bucket is refused
unless the list also restores the label - so a refused start takes its label with it.

`--collect` fetches the pages the quotes name (read-only, the project USER_AGENT) into
`export/pages.json`; `--write` reads production (read-only) and writes `PLAN.jsonl`, `PLAN.md`,
`SKIPPED.jsonl`, `ROLLBACK.sql`. `apply.py --lane <lane>` renders and runs it.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, replace
from pathlib import Path
from types import MappingProxyType
from typing import Any

_HERE = Path(__file__).resolve()
REPO = _HERE.parents[3]
for _root in (str(REPO), str(REPO / "scripts" / "remediation")):
    if _root not in sys.path:
        sys.path.insert(0, _root)

from mechanical.apply import lane_dir, typed_value  # noqa: E402
from mechanical.lane import LANES, REVERSAL_LISTS, Lane, sql_literal  # noqa: E402
from mechanical.plan import (  # noqa: E402
    CURATED_SOURCE,
    WIKIDATA_API,
    JournalLink,
    Plan,
    PlanError,
    Verdict,
    _now,
    get_json,
    journal_break,
    psql_json_reader,
    sql_ids,
    write_plan_jsonl,
    write_rollback_sql,
    write_skipped_jsonl,
)
from pipeline.utils.text import categorize_period  # noqa: E402

log = logging.getLogger("mechanical.reversal")

GOLD = REPO / "output" / "remediation" / "gold_standard" / "sites.json"
ENWIKI_API = "https://en.wikipedia.org/w/api.php"
#: The re-review's decisions as it delivered them, copied into the lane directory that quotes them.
REREVIEW_FILE = "REREVIEW_1_FINAL.jsonl"
REREVIEW_KIND = "rereview"
#: The Opus re-verification (`scripts/remediation/opus_audit/`): its decisions, and the verdict
#: files a decision's `basis[].from` names ("<file> <section>"), read where the audit keeps them.
OPUS_AUDIT = REPO / "output" / "remediation" / "opus_audit"
OPUS_DECISIONS = "DECISIONS.jsonl"
OPUS_URL = "output/remediation/opus_audit/DECISIONS.jsonl"
OPUS_KIND = "opus"
OPUS_VERDICT_FILE = re.compile(r"VERDICTS_(RAW|ROUND[1-9][0-9]*)\.json")
#: The audit's words for a verdict that upholds the write and for a quote its check found
#: (`opus_audit.decide.KEEP`, `opus_audit.quotes.FOUND`).
OPUS_KEEP, OPUS_FOUND = "keep", "found"
#: The two columns whose agreement a reversal must not break, read for every site of a list.
PERIOD_START, PERIOD_NAME = "period_start", "period_name"


# ------------------------------------------------------------------------------ the reasons
@dataclass(frozen=True)
class Quote:
    source: str
    text: str


@dataclass(frozen=True)
class Reason:
    journal_id: int
    site_id: str
    name: str
    column: str
    reason: str
    quotes: tuple[Quote, ...]
    residual: str


def load_reasons(path: Path, lane: Lane, expected: Sequence[int]) -> list[Reason]:
    """`REASONS.json`, refused unless it lists exactly the lane's journal rows, each once."""
    if not path.exists():
        raise PlanError(f"{path} is missing - the reviewed reasons are part of the plan")
    raw = json.loads(path.read_text(encoding="utf-8"))
    reasons = [
        Reason(
            journal_id=int(entry["journal_id"]),
            site_id=str(entry["site_id"]),
            name=str(entry["name"]),
            column=str(entry["column"]),
            reason=str(entry["reason"]),
            quotes=tuple(Quote(str(q["source"]), str(q["text"])) for q in entry["quotes"]),
            residual=str(entry.get("residual") or ""),
        )
        for entry in raw["reversals"]
    ]
    ids = [r.journal_id for r in reasons]
    if sorted(ids) != sorted(expected) or len(set(ids)) != len(ids):
        raise PlanError(
            f"{path.name} lists journal rows {sorted(ids)}, the {lane.name} lane reverses "
            f"{sorted(expected)} - the reviewed list and the code must agree"
        )
    for r in reasons:
        # A quote without text is `in` every source, so it would pass every evidence check.
        if not r.reason or not r.quotes or any(not q.text.strip() for q in r.quotes):
            raise PlanError(f"journal row {r.journal_id}: a reversal needs a reason and evidence")
    return reasons


def load_rereview(path: Path) -> dict[str, Mapping[str, Any]]:
    """The re-review's rows by `change_key` - the decision and the WHY a `rereview:` quote cites."""
    if not path.exists():
        raise PlanError(f"{path} is missing - the re-review a quote cites is part of the plan")
    rows: dict[str, Mapping[str, Any]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        row = json.loads(line)
        if row["change_key"] in rows:
            raise PlanError(f"{path.name} decides {row['change_key']} twice")
        rows[str(row["change_key"])] = row
    return rows


def cites_the_rereview(reasons: Sequence[Reason]) -> bool:
    return any(q.source.partition(":")[0] == REREVIEW_KIND for r in reasons for q in r.quotes)


@dataclass(frozen=True)
class OpusDecision:
    """One row the Opus re-verification decided, as an `opus:` quote reads it: the write it judged,
    its decision, whether that decision goes to the reversal (a revert that is not superseded), and
    the quotes of its deciding verdicts - the counted ones that are not keep - that the audit's
    machine quote check found."""

    change_key: str
    site_id: str
    column: str
    old_value: str
    written_value: str
    decision: str
    reversal: bool
    quotes: tuple[str, ...]


#: No Opus decision read: a list that quotes none (`cites_the_opus_audit`).
NO_OPUS: Mapping[str, OpusDecision] = MappingProxyType({})


def _opus_verdict(audit: Path, files: dict[str, Any], origin: str, key: str) -> Mapping[str, Any]:
    """The verdict a decision's `basis[].from` names ("<file> <section>"), from the audit's files."""
    name, _, section = origin.rpartition(" ")
    if not OPUS_VERDICT_FILE.fullmatch(name):
        raise PlanError(f"{origin!r} is not a verdict file of the Opus re-verification")
    if name not in files:
        files[name] = json.loads((audit / name).read_text(encoding="utf-8"))
    verdict = files[name].get(section, {}).get(key)
    if verdict is None:
        raise PlanError(f"{origin} holds no verdict for {key}")
    return verdict


def load_opus(audit: Path) -> dict[str, OpusDecision]:
    """The Opus re-verification's decisions by `change_key` (`DECISIONS.jsonl`), each with the
    quotes of its deciding verdicts, read from the verdict files it names. Refused where a decision
    and its verdict files disagree: a verdict name, or a quote check that is not the verdict's."""
    path = audit / OPUS_DECISIONS
    if not path.exists():
        raise PlanError(
            f"{path} is missing - the Opus re-verification a quote cites is part of the plan"
        )
    files: dict[str, Any] = {}
    out: dict[str, OpusDecision] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        decided = json.loads(line)
        key = str(decided["change_key"])
        if key in out:
            raise PlanError(f"{path.name} decides {key} twice")
        quotes: list[str] = []
        for basis in decided["basis"]:
            if basis["verdict"] == OPUS_KEEP or not basis["counted"]:
                continue
            verdict = _opus_verdict(audit, files, basis["from"], key)
            if verdict["verdict"] != basis["verdict"]:
                raise PlanError(
                    f"{path.name} reads {basis['verdict']!r} for {key}, "
                    f"{basis['from']} holds {verdict['verdict']!r}"
                )
            checked = decided["quote_check"][basis["pass"]]["quotes"]
            if [c["source"] for c in checked] != [q["source"] for q in verdict["quotes"]]:
                raise PlanError(
                    f"the quote check of {basis['from']} for {key} is not that verdict's"
                )
            quotes += [
                q["quote"]
                for q, c in zip(verdict["quotes"], checked, strict=True)
                if c["outcome"] == OPUS_FOUND
            ]
        out[key] = OpusDecision(
            change_key=key,
            site_id=str(decided["site_id"]),
            column=str(decided["column"]),
            old_value=str(decided["old_value"]),
            written_value=str(decided["written_value"]),
            decision=str(decided["decision"]),
            reversal=bool(decided["reversal"]),
            quotes=tuple(quotes),
        )
    return out


def cites_the_opus_audit(reasons: Sequence[Reason]) -> bool:
    return any(q.source.partition(":")[0] == OPUS_KIND for r in reasons for q in r.quotes)


# ------------------------------------------------------------------------------- the state
@dataclass(frozen=True)
class Cell:
    """One reversal's live state: the journal row, the site, the cell's chain and its value."""

    entry: Mapping[str, Any] | None
    site: Mapping[str, Any] | None
    chain: tuple[JournalLink, ...]
    live: str | None


def site_columns(lane: Lane) -> tuple[str, ...]:
    """The columns read for every site of a list: the lane's own, and the period pair."""
    return (*lane.columns, *(c for c in (PERIOD_START, PERIOD_NAME) if c not in lane.columns))


def load_state(
    reader: Callable[[str], list[dict[str, Any]]], reasons: Sequence[Reason], lane: Lane
) -> dict[int, Cell]:
    """The journal rows, their sites and every journal row of each cell - read-only.

    The live values are read as text (`::text`), the form the journal records them in.
    """
    ids = ", ".join(str(int(r.journal_id)) for r in reasons)
    entries = {
        int(e["id"]): e
        for e in reader(
            "SELECT id, row_pk, table_name, column_name, old_value, new_value, run_stamp, "
            "coalesce(test_id, '') AS test_id, change_key, evidence FROM remediation_change_log "
            f"WHERE id IN ({ids})"
        )
    }
    values = ", ".join(f"{column}::text AS {column}" for column in site_columns(lane))
    sites = {
        str(s["id"]): s
        for s in reader(
            # `id IN ('...')`: the literals take the key's type and the primary key is used;
            # `id::text IN` would scan all 1.76M rows (the 0022 lesson)
            f"SELECT id::text AS id, name, source_id, description, {values} FROM unified_sites "
            f"WHERE id IN ({sql_ids(r.site_id for r in reasons)})"
        )
    }
    chains: dict[tuple[str, str], list[JournalLink]] = {}
    columns = ", ".join(sql_literal(c) for c in sorted({r.column for r in reasons}))
    for row in reader(
        "SELECT id, row_pk, column_name, run_stamp, coalesce(test_id, '') AS test_id, old_value, "
        "new_value FROM remediation_change_log WHERE table_name = 'unified_sites' "
        f"AND column_name IN ({columns}) AND row_pk IN ({sql_ids(r.site_id for r in reasons)}) "
        "ORDER BY id"
    ):
        chains.setdefault((str(row["row_pk"]), str(row["column_name"])), []).append(
            JournalLink(
                int(row["id"]),
                str(row["run_stamp"]),
                str(row["test_id"]),
                row["old_value"],
                row["new_value"],
            )
        )
    out: dict[int, Cell] = {}
    for r in reasons:
        site = sites.get(r.site_id)
        out[r.journal_id] = Cell(
            entry=entries.get(r.journal_id),
            site=site,
            chain=tuple(chains.get((r.site_id, r.column), ())),
            live=None if site is None else site.get(r.column),
        )
    return out


# ------------------------------------------------------------------------------ the pages
def collect_pages(reasons: Sequence[Reason], path: Path) -> int:
    """Fetch every page a quote names (English Wikipedia extract, Wikidata item), as fetched."""
    pages: dict[str, str] = {}
    for reason in reasons:
        for quote in reason.quotes:
            kind, _, ref = quote.source.partition(":")
            if kind == "enwiki" and quote.source not in pages:
                data = get_json(
                    ENWIKI_API,
                    {
                        "action": "query",
                        "prop": "extracts",
                        "titles": ref,
                        "explaintext": "1",
                        "redirects": "1",
                        "format": "json",
                    },
                )
                (page,) = data["query"]["pages"].values()
                if "missing" in page:
                    raise PlanError(f"en.wikipedia has no page {ref!r}")
                pages[quote.source] = str(page["extract"])
            elif kind == "wikidata" and quote.source not in pages:
                data = get_json(
                    WIKIDATA_API,
                    {
                        "action": "wbgetentities",
                        "ids": ref,
                        "props": "labels|descriptions|claims",
                        "languages": "en",
                        "format": "json",
                    },
                )
                pages[quote.source] = json.dumps(data["entities"][ref], ensure_ascii=False)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"fetched_at": _now(), "pages": pages}, ensure_ascii=False, indent=1),
        encoding="utf-8",
        newline="\n",
    )
    return len(pages)


def load_gold(path: Path = GOLD) -> dict[str, Mapping[str, Any]]:
    """The gold-standard records by site id (`output/remediation/gold_standard/sites.json`)."""
    raw = json.loads(path.read_text(encoding="utf-8"))
    return {str(r["site_id"]): r for r in raw["records"]}


def _rereview_text(
    ref: str, reason: Reason, entry: Mapping[str, Any], rereview: Mapping[str, Mapping[str, Any]]
) -> tuple[str | None, str]:
    """`(problem, text)`: the re-review row `ref` must have decided to reverse exactly this write."""
    row = rereview.get(ref)
    if row is None:
        return f"{REREVIEW_KIND}:{ref} is not a row of the re-review", ""
    if row["decision"] != "reverse":
        return f"the re-review decided {row['decision']!r} for {ref}, not 'reverse'", ""
    written = (entry["change_key"], reason.site_id, reason.column)
    written += (entry["old_value"], entry["new_value"])
    decided = (row["change_key"], row["site_id"], row["column"], row["old_value"], row["new_value"])
    if decided != written:
        return (
            f"the re-review row {ref} decided {decided[2:]!r} of {decided[1]}, journal row "
            f"{reason.journal_id} wrote {written[2:]!r} of {written[1]}",
            "",
        )
    return None, f"{row['why']}\n{row['new_reason']}"


def _opus_text(
    ref: str, reason: Reason, entry: Mapping[str, Any], opus: Mapping[str, OpusDecision]
) -> tuple[str | None, str]:
    """`(problem, text)`: the Opus re-verification must have decided to revert exactly this write,
    and not as a superseded row; the text is its deciding verdicts' found quotes, one per line."""
    judged = opus.get(ref)
    if judged is None:
        return f"{OPUS_KIND}:{ref} is not a row of the Opus re-verification", ""
    if not judged.reversal:
        return (
            f"the Opus re-verification decided {judged.decision!r} for {ref}, not a reversal "
            "(a revert that is not superseded)",
            "",
        )
    wrote = (entry["change_key"], reason.site_id, reason.column)
    wrote += (entry["old_value"], entry["new_value"])
    audited = (judged.change_key, judged.site_id, judged.column)
    audited += (judged.old_value, judged.written_value)
    if audited != wrote:
        return (
            f"the Opus re-verification judged {audited[2:]!r} of {audited[1]}, journal row "
            f"{reason.journal_id} wrote {wrote[2:]!r} of {wrote[1]}",
            "",
        )
    return None, "\n".join(judged.quotes)


def quote_problem(
    quote: Quote,
    reason: Reason,
    cell: Cell,
    pages: Mapping[str, str],
    gold: Mapping[str, Mapping[str, Any]],
    rereview: Mapping[str, Mapping[str, Any]],
    opus: Mapping[str, OpusDecision] = NO_OPUS,
) -> str | None:
    """Why a quote is not where it says it is - or None when it is. `cell.entry` is the journal
    row the reversal undoes (`classify_reversal` refuses a missing one first)."""
    kind, _, ref = quote.source.partition(":")
    entry = cell.entry or {}
    if kind == "description":
        text = str((cell.site or {}).get("description") or "")
    elif kind in ("enwiki", "wikidata"):
        if quote.source not in pages:
            return f"{quote.source} was not collected - run --collect"
        text = pages[quote.source]
    elif kind == "gold_standard":
        record = gold.get(ref)
        if record is None or ref != reason.site_id:
            return f"the gold standard has no record {ref} for this site"
        verdicts = {v["field"]: v for v in record["verdicts"]}
        verdict = verdicts.get(reason.column)
        if verdict is None or verdict["verdict"] != "CORRECT":
            return f"the gold standard does not judge {reason.column} CORRECT"
        restored = entry.get("old_value")
        if str(record["db_fields"].get(reason.column)) != str(restored):
            return (
                f"the gold standard judged {record['db_fields'].get(reason.column)!r}, the "
                f"reversal restores {restored!r}"
            )
        text = str(verdict["note"])
    elif kind == "journal" and not ref:
        if entry.get("evidence") is None:
            return f"journal row {reason.journal_id} carries no evidence"
        text = "\n".join(str(e.get("quote", "")) for e in entry["evidence"])
    elif kind == REREVIEW_KIND:
        problem, text = _rereview_text(ref, reason, entry, rereview)
        if problem is not None:
            return problem
    elif kind == OPUS_KIND:
        unjudged, text = _opus_text(ref, reason, entry, opus)
        if unjudged is not None:
            return unjudged
    else:
        return f"{quote.source!r} is not a source this lane can check"
    if quote.text not in text:
        return f"{quote.text!r} is not in {quote.source}"
    return None


# ------------------------------------------------------------------------------ the decision
def classify_reversal(
    reason: Reason,
    cell: Cell,
    *,
    lane: Lane,
    pages: Mapping[str, str],
    gold: Mapping[str, Mapping[str, Any]],
    rereview: Mapping[str, Mapping[str, Any]],
    opus: Mapping[str, OpusDecision] = NO_OPUS,
) -> Verdict:
    """Decide one reversal. Every check is named, and the first failure is the reason."""
    entry, site = cell.entry, cell.site

    def verdict(ok: bool, why: str, note: str, evidence: Sequence[dict[str, Any]] = ()) -> Verdict:
        return Verdict(
            site_id=reason.site_id,
            site_name=reason.name if site is None else str(site["name"]),
            ok=ok,
            old_value=cell.live,
            new_value=None if entry is None else entry["old_value"],
            rule="journal-reversal",
            reason=why,
            note=note,
            phase3=entry is not None and str(entry["run_stamp"]).startswith("phase3:"),
            finding_test_id=f"journal:{reason.journal_id}",
            evidence=tuple(evidence),
            column=reason.column,
            journal_id=reason.journal_id if ok else None,
        )

    if entry is None:
        return verdict(False, "journal-row-missing", f"no journal row {reason.journal_id}")
    if (
        entry["table_name"] != "unified_sites"
        or entry["column_name"] != reason.column
        or entry["row_pk"] != reason.site_id
    ):
        return verdict(
            False,
            "journal-row-is-another-cell",
            f"journal row {reason.journal_id} is {entry['table_name']}.{entry['column_name']} of "
            f"{entry['row_pk']}, the reason names unified_sites.{reason.column} of {reason.site_id}",
        )
    if reason.column not in lane.columns:
        return verdict(
            False, "column-not-owned", f"the {lane.name} lane does not write {reason.column}"
        )
    if site is None or site["source_id"] != CURATED_SOURCE:
        return verdict(False, "row-not-in-curated-source", "not a curated site")
    broken = journal_break(cell.chain, cell.live)
    if broken is not None:
        return verdict(False, *broken)
    if not cell.chain or cell.chain[-1].id != reason.journal_id:
        later = cell.chain[-1].id if cell.chain else None
        return verdict(
            False,
            "not-the-last-write",
            f"journal row {later} wrote the cell after {reason.journal_id}; reverse that one first",
        )
    restored = entry["old_value"]
    if restored is None:
        return verdict(
            False, "restores-null", "the row replaced a NULL; this lane never clears a column"
        )
    try:
        typed_value(lane.cell(reason.column), str(restored))
    except PlanError as exc:
        return verdict(False, "restored-value-unreadable", str(exc))
    for quote in reason.quotes:
        problem = quote_problem(quote, reason, cell, pages, gold, rereview, opus)
        if problem is not None:
            return verdict(False, "evidence-not-found", problem)
    evidence: list[dict[str, Any]] = [
        {
            "source": f"remediation_change_log:{entry['id']}",
            "url": "remediation_change_log",
            "quote": f"{entry['run_stamp']} ({entry['test_id']}): {reason.column} "
            f"{entry['old_value']!r} -> {entry['new_value']!r} - the write this row undoes",
        },
        *({"source": q.source, "url": _url(q.source), "quote": q.text} for q in reason.quotes),
    ]
    if reason.column == PERIOD_START:
        before, after = categorize_period(int(restored)), categorize_period(int(str(cell.live)))
        evidence.append(
            {
                "source": "pipeline/utils/text.py:categorize_period",
                "url": "pipeline/utils/text.py",
                "quote": f"categorize_period({restored}) = {before!r}, "
                f"categorize_period({cell.live}) = {after!r}"
                + (" - the same bucket" if before == after else " - another bucket"),
            }
        )
    if reason.residual:
        evidence.append({"source": "residual", "url": "REASONS.json", "quote": reason.residual})
    return verdict(True, "", reason.reason, evidence)


def _url(source: str) -> str:
    kind, _, ref = source.partition(":")
    if kind == "enwiki":
        return "https://en.wikipedia.org/wiki/" + ref.replace(" ", "_")
    if kind == "wikidata":
        return f"https://www.wikidata.org/wiki/{ref}"
    if kind == "gold_standard":
        return "output/remediation/gold_standard/sites.json"
    if kind == "journal":
        return "remediation_change_log.evidence"
    if kind == REREVIEW_KIND:
        return REREVIEW_FILE
    if kind == OPUS_KIND:
        return OPUS_URL
    return "unified_sites.description"


def _bucket(start: str | None) -> str | None:
    return None if start is None else categorize_period(int(str(start)))


def _refused(v: Verdict, why: str, note: str) -> Verdict:
    return replace(v, ok=False, reason=why, note=note, evidence=(), journal_id=None)


def keep_the_period_label(
    verdicts: Sequence[Verdict], sites: Mapping[str, Mapping[str, Any]]
) -> list[Verdict]:
    """The list's decisions, with `period_name` kept the bucket of `period_start` (module doc).

    First every planned label must be the bucket of the start the site is left with: the planned
    start, or the live one when no start is planned (or it was refused). Then every planned start
    must leave a label that is its bucket - the planned label that survived the first step, or the
    live one - unless the live label is already not the live start's bucket today (the list does
    not break a pair that is broken already). So a refused start refuses a label that is only the
    bucket of that start, and a refused label refuses a start whose bucket the live label is not; a
    start or a label alone is planned only where the pair stays consistent.
    """
    out = list(verdicts)
    starts = {v.site_id: v for v in out if v.ok and v.column == PERIOD_START}
    for i, v in enumerate(out):
        if not (v.ok and v.column == PERIOD_NAME):
            continue
        start = (
            starts[v.site_id].new_value if v.site_id in starts else sites[v.site_id][PERIOD_START]
        )
        bucket = _bucket(start)
        if v.new_value != bucket:
            out[i] = _refused(
                v,
                "period-name-not-the-bucket",
                f"restores {v.new_value!r}, but the site is left with period_start {start} "
                f"({bucket!r})",
            )
            continue
        out[i] = replace(
            v,
            evidence=(
                *v.evidence,
                {
                    "source": "pipeline/utils/text.py:categorize_period",
                    "url": "pipeline/utils/text.py",
                    "quote": f"categorize_period({start}) = {bucket!r} - the period_start the "
                    "site is left with",
                },
            ),
        )
    names = {v.site_id: v for v in out if v.ok and v.column == PERIOD_NAME}
    for i, v in enumerate(out):
        if not (v.ok and v.column == PERIOD_START):
            continue
        site = sites[v.site_id]
        if _bucket(site[PERIOD_START]) != site[PERIOD_NAME]:
            # the label is not the live start's bucket today: this list does not break the pair
            continue
        label = names[v.site_id].new_value if v.site_id in names else site[PERIOD_NAME]
        if _bucket(v.new_value) != label:
            out[i] = _refused(
                v,
                "period-name-left-behind",
                f"period_start {v.new_value} is in {_bucket(v.new_value)!r}, and the list leaves "
                f"the label {label!r}",
            )
    return out


def build_reversal_plan(
    reasons: Sequence[Reason],
    state: Mapping[int, Cell],
    *,
    lane: Lane,
    pages: Mapping[str, str],
    gold: Mapping[str, Mapping[str, Any]],
    rereview: Mapping[str, Mapping[str, Any]],
    built_at: str,
    opus: Mapping[str, OpusDecision] = NO_OPUS,
) -> Plan:
    """A pure function of its inputs: no database, no network, no clock of its own."""
    verdicts = [
        classify_reversal(
            r,
            state[r.journal_id],
            lane=lane,
            pages=pages,
            gold=gold,
            rereview=rereview,
            opus=opus,
        )
        for r in sorted(reasons, key=lambda r: r.journal_id)
    ]
    sites = {str(c.site["id"]): c.site for c in state.values() if c.site is not None}
    verdicts = keep_the_period_label(verdicts, sites)
    changes = tuple(v for v in verdicts if v.ok)
    skipped = tuple(v for v in verdicts if not v.ok)
    return Plan(
        changes=changes,
        skipped=skipped,
        built_at=built_at,
        counters={"reversals": len(verdicts), "changes": len(changes), "skipped": len(skipped)},
        lane=lane,
    )


def write_plan_md(plan: Plan, reasons: Sequence[Reason], path: Path) -> None:
    by_id = {r.journal_id: r for r in reasons}
    add = (lines := []).append
    add(f"# Journal reversal - plan ({plan.lane.name})")
    add("")
    add(
        f"Built {plan.built_at} by `scripts/remediation/mechanical/reversal.py`. Lane "
        f"`{plan.lane.name}`: run stamp `{plan.lane.run_stamp}`, journal test id "
        f"`{plan.lane.test_id}`, change keys `{plan.lane.key_prefix}:<site_id>:<column>`."
    )
    add("")
    add(
        f"**{len(plan.changes)} cell(s) will be written, {len(plan.skipped)} refused.** Each restores "
        "the value a journal row replaced, conditioned on the live value being the value that row "
        "wrote, and on that row being the last write of its cell (guard 6)."
    )
    add("")
    for change in plan.changes:
        reason = by_id[int(str(change.journal_id))]
        add(f"## {change.site_name} - `{change.column}` {change.old_value} -> {change.new_value}")
        add("")
        add(f"Site `{change.site_id}`, journal row {change.journal_id}.")
        add("")
        add(f"**Reason.** {reason.reason}.")
        add("")
        for e in change.evidence:
            add(f"* {e['source']}: {e['quote']}")
        add("")
    for s in plan.skipped:
        add(f"* REFUSED {s.site_name} ({s.finding_test_id}): `{s.reason}` - {s.note}")
    add("")
    add("## After the apply")
    add("")
    add(
        "The phase-3 acceptance reads these cells as superseded once it is told the stamp: "
        f"`verify_writes.py --allow-stamp {plan.lane.run_stamp}`, with the stamps of the lanes "
        "applied before it. Re-plan the scope lane and the card_stats recompute afterwards: the "
        "scope premise and the cards derive from these columns."
    )
    add("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


# ------------------------------------------------------------------------------------- CLI
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Plan a journal reversal (mechanical lane)")
    ap.add_argument("--lane", required=True, choices=sorted(REVERSAL_LISTS))
    ap.add_argument("--out", type=Path, help="the lane's directory unless given")
    ap.add_argument("--collect", action="store_true", help="fetch the pages the quotes name")
    ap.add_argument("--write", action="store_true", help="read production (read-only) and plan")
    args = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    if not (args.collect or args.write):
        ap.print_help()
        return 0
    lane = LANES[args.lane]
    out = lane_dir(lane) if args.out is None else args.out
    try:
        reasons = load_reasons(out / "REASONS.json", lane, REVERSAL_LISTS[lane.name])
        pages_path = out / "export" / "pages.json"
        if args.collect:
            log.info("%d page(s) collected", collect_pages(reasons, pages_path))
        if args.write:
            if not pages_path.exists():
                raise PlanError(f"{pages_path} is missing - run --collect")
            pages = json.loads(pages_path.read_text(encoding="utf-8"))["pages"]
            rereview = load_rereview(out / REREVIEW_FILE) if cites_the_rereview(reasons) else {}
            opus = load_opus(OPUS_AUDIT) if cites_the_opus_audit(reasons) else NO_OPUS
            plan = build_reversal_plan(
                reasons,
                load_state(psql_json_reader(), reasons, lane),
                lane=lane,
                pages=pages,
                gold=load_gold(),
                rereview=rereview,
                built_at=_now(),
                opus=opus,
            )
            write_plan_jsonl(plan, out / "PLAN.jsonl")
            write_skipped_jsonl(plan, out / "SKIPPED.jsonl")
            write_plan_md(plan, reasons, out / "PLAN.md")
            write_rollback_sql(plan, out / "ROLLBACK.sql", plan_path=out / "PLAN.jsonl")
            print(json.dumps(dict(plan.counters), indent=1, sort_keys=True))
    except PlanError as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
