-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: e6115c3cc0805a292072d20cd2c9ae67c2269eb6cc76fb15879724d6159624ce
-- lane 'ih6' (import-hero/insert), 10 row(s) to create; run stamp 'insert-2026-10-07-008-001'.
-- Every row is created together with its journal rows, inside this transaction: a journal that
-- disagrees with the data cannot be committed, and a rolled-back statement leaves nothing behind.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_insert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    filename          TEXT NOT NULL,
    original_url      TEXT NOT NULL,
    commons_page_url  TEXT NOT NULL,
    title             TEXT NOT NULL,
    author            TEXT NOT NULL,
    author_url        TEXT NOT NULL,
    license           TEXT NOT NULL,
    license_url       TEXT NOT NULL,
    width             INTEGER NOT NULL,
    height            INTEGER NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT NOT NULL,
    change_key        TEXT NOT NULL,
    reason            TEXT NOT NULL,
    evidence          JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_insert (seq, site_id, filename, original_url, commons_page_url, title, author, author_url, license, license_url, width, height, file_size_bytes, demoted_id, old_thumbnail, new_thumbnail, change_key, reason, evidence) VALUES
    (1, 'e9217b6f-c6c8-4798-a514-1e2751cf936b'::uuid, 'Northeast Facing View along the Long Burgh Long Barrow.webp', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Northeast_Facing_View_along_the_Long_Burgh_Long_Barrow.jpg', 'https://commons.wikimedia.org/wiki/File%3ANortheast%20Facing%20View%20along%20the%20Long%20Burgh%20Long%20Barrow.jpg', 'Northeast Facing View along the Long Burgh Long Barrow', 'Ethan Doyle White', 'https://commons.wikimedia.org/wiki/User:Ethan_Doyle_White', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1067, 500302, NULL, NULL, '/data/images/wiki/e9217b6f/Northeast Facing View along the Long Burgh Long Barrow.webp', 'import-hero/insert:e9217b6f-c6c8-4798-a514-1e2751cf936b', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Northeast_Facing_View_along_the_Long_Burgh_Long_Barrow.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ANortheast%20Facing%20View%20along%20the%20Long%20Burgh%20Long%20Barrow.jpg"}, {"quote": "1 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/a/a2/Northeast_Facing_View_along_the_Long_Burgh_Long_Barrow.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = e9217b6f-c6c8-4798-a514-1e2751cf936b"}]'::jsonb),
    (2, 'ec429566-4a7e-430c-a1a3-da90dc9f695f'::uuid, 'Arvalem Caves Goa.webp', 'https://upload.wikimedia.org/wikipedia/commons/2/25/Arvalem_Caves_Goa.jpg', 'https://commons.wikimedia.org/wiki/File%3AArvalem%20Caves%20Goa.jpg', 'Arvalem Caves Goa', 'Kavya Rastogi', 'https://commons.wikimedia.org/w/index.php?title=User:Rastogikavya&amp;action=edit&amp;redlink=1', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 961, 503056, NULL, NULL, '/data/images/wiki/ec429566/Arvalem Caves Goa.webp', 'import-hero/insert:ec429566-4a7e-430c-a1a3-da90dc9f695f', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/2/25/Arvalem_Caves_Goa.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AArvalem%20Caves%20Goa.jpg"}, {"quote": "1 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/2/25/Arvalem_Caves_Goa.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = ec429566-4a7e-430c-a1a3-da90dc9f695f"}]'::jsonb),
    (3, 'ec47336a-5eeb-4b59-b60c-9ef6d1901934'::uuid, 'Farley Green - geograph.org.uk - 6123743.webp', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Farley_Green_-_geograph.org.uk_-_6123743.jpg', 'https://commons.wikimedia.org/wiki/File%3AFarley%20Green%20-%20geograph.org.uk%20-%206123743.jpg', 'Farley Green - geograph.org.uk - 6123743', 'Michael Garlick', 'https://www.geograph.org.uk/profile/118660', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0', 1600, 1067, 317876, NULL, NULL, '/data/images/wiki/ec47336a/Farley Green - geograph.org.uk - 6123743.webp', 'import-hero/insert:ec47336a-5eeb-4b59-b60c-9ef6d1901934', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Farley_Green_-_geograph.org.uk_-_6123743.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AFarley%20Green%20-%20geograph.org.uk%20-%206123743.jpg"}, {"quote": "2 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/d/d3/Farley_Green_-_geograph.org.uk_-_6123743.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = ec47336a-5eeb-4b59-b60c-9ef6d1901934"}]'::jsonb),
    (4, 'ef4a8fe6-c961-4521-9242-9d3ac1168846'::uuid, 'Ruines de maisons de Makthar.webp', 'https://upload.wikimedia.org/wikipedia/commons/8/88/Ruines_de_maisons_de_Makthar.jpg', 'https://commons.wikimedia.org/wiki/File%3ARuines%20de%20maisons%20de%20Makthar.jpg', 'Ruines de maisons de Makthar', 'Noomen9', 'https://commons.wikimedia.org/wiki/User:Noomen9', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1062, 295830, NULL, NULL, '/data/images/wiki/ef4a8fe6/Ruines de maisons de Makthar.webp', 'import-hero/insert:ef4a8fe6-c961-4521-9242-9d3ac1168846', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/8/88/Ruines_de_maisons_de_Makthar.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ARuines%20de%20maisons%20de%20Makthar.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/8/88/Ruines_de_maisons_de_Makthar.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = ef4a8fe6-c961-4521-9242-9d3ac1168846"}]'::jsonb),
    (5, 'f0bcab22-b5ea-43e1-ace1-c9adc5d6e0db'::uuid, 'Milas Baltalı Kapı 038.webp', 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Milas_Baltal%C4%B1_Kap%C4%B1_038.jpg', 'https://commons.wikimedia.org/wiki/File%3AMilas%20Baltal%C4%B1%20Kap%C4%B1%20038.jpg', 'Milas Baltalı Kapı 038', 'Dosseman', 'https://commons.wikimedia.org/wiki/User:Dosseman', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1027, 480858, NULL, NULL, '/data/images/wiki/f0bcab22/Milas Baltalı Kapı 038.webp', 'import-hero/insert:f0bcab22-b5ea-43e1-ace1-c9adc5d6e0db', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/c/cd/Milas_Baltal%C4%B1_Kap%C4%B1_038.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AMilas%20Baltal%C4%B1%20Kap%C4%B1%20038.jpg"}, {"quote": "17 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/c/cd/Milas_Baltal%C4%B1_Kap%C4%B1_038.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = f0bcab22-b5ea-43e1-ace1-c9adc5d6e0db"}]'::jsonb),
    (6, 'f95bef03-ef56-40c2-9ee8-bb27572c9277'::uuid, 'Starčevo-Grad, Glačane sekire, kamen, Starčevačka kultura, neolit 02.webp', 'https://upload.wikimedia.org/wikipedia/commons/d/de/Star%C4%8Devo-Grad%2C_Gla%C4%8Dane_sekire%2C_kamen%2C_Star%C4%8Deva%C4%8Dka_kultura%2C_neolit_02.jpg', 'https://commons.wikimedia.org/wiki/File%3AStar%C4%8Devo-Grad%2C%20Gla%C4%8Dane%20sekire%2C%20kamen%2C%20Star%C4%8Deva%C4%8Dka%20kultura%2C%20neolit%2002.jpg', 'Starčevo-Grad, Glačane sekire, kamen, Starčevačka kultura, neolit 02', 'Nikolina Šepić', 'https://commons.wikimedia.org/wiki/User:Nikolina_%C5%A0epi%C4%87', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1067, 72850, NULL, NULL, '/data/images/wiki/f95bef03/Starčevo-Grad, Glačane sekire, kamen, Starčevačka kultura, neolit 02.webp', 'import-hero/insert:f95bef03-ef56-40c2-9ee8-bb27572c9277', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/d/de/Star%C4%8Devo-Grad%2C_Gla%C4%8Dane_sekire%2C_kamen%2C_Star%C4%8Deva%C4%8Dka_kultura%2C_neolit_02.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AStar%C4%8Devo-Grad%2C%20Gla%C4%8Dane%20sekire%2C%20kamen%2C%20Star%C4%8Deva%C4%8Dka%20kultura%2C%20neolit%2002.jpg"}, {"quote": "20 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/d/de/Star%C4%8Devo-Grad%2C_Gla%C4%8Dane_sekire%2C_kamen%2C_Star%C4%8Deva%C4%8Dka_kultura%2C_neolit_02.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = f95bef03-ef56-40c2-9ee8-bb27572c9277"}]'::jsonb),
    (7, 'fcf4c04e-fd5a-43b3-881b-47802ea4f924'::uuid, 'Ihuatzio1.webp', 'https://upload.wikimedia.org/wikipedia/commons/1/14/Ihuatzio1.jpg', 'https://commons.wikimedia.org/wiki/File%3AIhuatzio1.jpg', 'Ihuatzio1', 'HJPD', 'https://commons.wikimedia.org/wiki/User:HJPD', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', 1600, 1054, 292254, NULL, NULL, '/data/images/wiki/fcf4c04e/Ihuatzio1.webp', 'import-hero/insert:fcf4c04e-fd5a-43b3-881b-47802ea4f924', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/1/14/Ihuatzio1.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3AIhuatzio1.jpg"}, {"quote": "20 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/1/14/Ihuatzio1.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = fcf4c04e-fd5a-43b3-881b-47802ea4f924"}]'::jsonb),
    (8, 'fe3d5d3e-fef4-4ae8-bda9-bc41909c732e'::uuid, 'Taranto - Tempio di Poseidone - 2023-09-29 19-50-15 001.webp', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Taranto_-_Tempio_di_Poseidone_-_2023-09-29_19-50-15_001.jpg', 'https://commons.wikimedia.org/wiki/File%3ATaranto%20-%20Tempio%20di%20Poseidone%20-%202023-09-29%2019-50-15%20001.jpg', 'Taranto - Tempio di Poseidone - 2023-09-29 19-50-15 001', 'Riccardo Minetola', 'https://commons.wikimedia.org/w/index.php?title=User:Riccardo_Minetola&amp;action=edit&amp;redlink=1', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1067, 394786, NULL, NULL, '/data/images/wiki/fe3d5d3e/Taranto - Tempio di Poseidone - 2023-09-29 19-50-15 001.webp', 'import-hero/insert:fe3d5d3e-fef4-4ae8-bda9-bc41909c732e', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Taranto_-_Tempio_di_Poseidone_-_2023-09-29_19-50-15_001.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ATaranto%20-%20Tempio%20di%20Poseidone%20-%202023-09-29%2019-50-15%20001.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/2/2a/Taranto_-_Tempio_di_Poseidone_-_2023-09-29_19-50-15_001.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = fe3d5d3e-fef4-4ae8-bda9-bc41909c732e"}]'::jsonb),
    (9, 'ff136c0c-2d3a-4621-b27b-294758b9cc4d'::uuid, 'Treasure of Cyrene 1.webp', 'https://upload.wikimedia.org/wikipedia/commons/2/20/Treasure_of_Cyrene_1.jpg', 'https://commons.wikimedia.org/wiki/File%3ATreasure%20of%20Cyrene%201.jpg', 'Treasure of Cyrene 1', 'Davide Mauro', 'https://commons.wikimedia.org/wiki/User:Codas', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1200, 1002952, NULL, NULL, '/data/images/wiki/ff136c0c/Treasure of Cyrene 1.webp', 'import-hero/insert:ff136c0c-2d3a-4621-b27b-294758b9cc4d', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/2/20/Treasure_of_Cyrene_1.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ATreasure%20of%20Cyrene%201.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/2/20/Treasure_of_Cyrene_1.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = ff136c0c-2d3a-4621-b27b-294758b9cc4d"}]'::jsonb),
    (10, 'ff53d37c-ab2b-4874-8ed8-a3336ccd12fc'::uuid, 'Tholos tomb of Maleme 09.webp', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Tholos_tomb_of_Maleme_09.jpg', 'https://commons.wikimedia.org/wiki/File%3ATholos%20tomb%20of%20Maleme%2009.jpg', 'Tholos tomb of Maleme 09', 'Tomisti', 'https://commons.wikimedia.org/wiki/User:Tomisti', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 1600, 1200, 740602, NULL, NULL, '/data/images/wiki/ff53d37c/Tholos tomb of Maleme 09.webp', 'import-hero/insert:ff53d37c-ab2b-4874-8ed8-a3336ccd12fc', 'a model looked at every Commons candidate of this site and judged this file ''depicts'' - a picture of the site itself - while the site showed nothing at all: no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Tholos_tomb_of_Maleme_09.jpg", "source": "the candidate search''s confirmed verdict (candidate_search/VERDICTS.jsonl)", "url": "https://commons.wikimedia.org/wiki/File%3ATholos%20tomb%20of%20Maleme%2009.jpg"}, {"quote": "20 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/2/2c/Tholos_tomb_of_Maleme_09.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = ff53d37c-ab2b-4874-8ed8-a3336ccd12fc"}]'::jsonb);

DO $$
DECLARE
    bad  integer;
    r    RECORD;
    new_id integer;
    cols TEXT;
BEGIN
    -- guard 1: every planned site is a curated site (the message names the source in words, so
    -- the log of a refused wave says what was expected)
    SELECT count(*) INTO bad FROM (SELECT DISTINCT site_id FROM _ih_insert) p
      LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % planned site(s) are not ancient_nerds sites',
            'insert-2026-10-07-008-001', bad;
    END IF;

    FOR r IN SELECT * FROM _ih_insert ORDER BY seq LOOP
        -- guard 2: no row of this site holds the file yet. The unique constraint on
        -- (site_id, original_url) is a second line of defence behind this one.
        IF EXISTS (SELECT 1 FROM wiki_images w
                    WHERE w.site_id = r.site_id AND w.original_url = r.original_url) THEN
            RAISE EXCEPTION '%: site % already holds this file', r.change_key, r.site_id;
        END IF;

        -- guard 3: the file reaches the hero floor
        IF r.width < 1600 OR r.height < 900 THEN
            RAISE EXCEPTION '%: the file is %x%, under the %x% this lane serves', r.change_key,
                r.width, r.height, 1600, 900;
        END IF;

        -- guard 4: the row that holds the flag is still the one the plan demotes
        IF r.demoted_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM wiki_images w
             WHERE w.id = r.demoted_id AND w.site_id = r.site_id AND w.is_hero) THEN
            RAISE EXCEPTION '%: the row that held the flag for site % moved since the read',
                r.change_key, r.site_id;
        END IF;

        -- guard 5: the thumbnail still holds the value the read found
        IF (SELECT u.thumbnail_url FROM unified_sites u WHERE u.id = r.site_id)
           IS DISTINCT FROM r.old_thumbnail THEN
            RAISE EXCEPTION '%: the thumbnail of site % moved since the read', r.change_key, r.site_id;
        END IF;

        -- the row that gives up the flag, and the row that takes it
        IF r.demoted_id IS NOT NULL THEN
            UPDATE wiki_images SET is_hero = false
             WHERE id = r.demoted_id AND is_hero AND site_id = r.site_id;
        END IF;

        -- the three columns the file does not carry: the next free number of this site (derived,
        -- never invented), the owner's picture rather than a measured lead image of the article,
        -- and the source 49,683 of the 49,691 curated rows carry
        INSERT INTO wiki_images
            (site_id, filename, original_url, commons_page_url, title, author, author_url, license, license_url, width, height, file_size_bytes, is_lead, sort_order, source_type, is_hero, is_excluded)
        SELECT r.site_id, r.filename, r.original_url, r.commons_page_url, r.title, r.author, r.author_url, r.license, r.license_url, r.width, r.height, r.file_size_bytes, false,
               (SELECT COALESCE(MAX(w2.sort_order), -1) + 1 FROM wiki_images w2
                 WHERE w2.site_id = r.site_id),
               'wikimedia', true, false
        RETURNING id INTO new_id;

        IF r.new_thumbnail IS DISTINCT FROM r.old_thumbnail THEN
            UPDATE unified_sites SET thumbnail_url = r.new_thumbnail WHERE id = r.site_id;
        END IF;

        -- the journal, in this transaction: one row per column this statement wrote,
        -- read back from the row it created, so the journal records what the database holds
        INSERT INTO remediation_change_log
            (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value, change_key,
             confidence, evidence, site_id_ref)
        SELECT 'insert-2026-10-07-008-001', 'import-hero/insert/owner-2026-10-05', 'wiki_images', t.col, new_id::text, NULL, t.val,
               r.change_key || ':' || t.col, 'authoritative', r.evidence, r.site_id
          FROM wiki_images w
          CROSS JOIN LATERAL (VALUES
              ('filename', w.filename::text),
              ('original_url', w.original_url::text),
              ('commons_page_url', w.commons_page_url::text),
              ('title', w.title::text),
              ('author', w.author::text),
              ('author_url', w.author_url::text),
              ('license', w.license::text),
              ('license_url', w.license_url::text),
              ('width', w.width::text),
              ('height', w.height::text),
              ('file_size_bytes', w.file_size_bytes::text),
              ('is_lead', w.is_lead::text),
              ('sort_order', w.sort_order::text),
              ('source_type', w.source_type::text)
          ) AS t(col, val)
         WHERE w.id = new_id;

        IF r.demoted_id IS NOT NULL THEN
            INSERT INTO remediation_change_log
                (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value,
                 change_key, confidence, evidence, site_id_ref)
            VALUES ('insert-2026-10-07-008-001', 'import-hero/insert/owner-2026-10-05', 'wiki_images', 'is_hero',
                    r.demoted_id::text, 'true', 'false', r.change_key || ':demote',
                    'authoritative', r.evidence, r.site_id);
        END IF;

        IF r.new_thumbnail IS DISTINCT FROM r.old_thumbnail THEN
            INSERT INTO remediation_change_log
                (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value,
                 change_key, confidence, evidence, site_id_ref)
            VALUES ('insert-2026-10-07-008-001', 'import-hero/insert/owner-2026-10-05', 'unified_sites', 'thumbnail_url',
                    r.site_id::text, r.old_thumbnail, r.new_thumbnail,
                    r.change_key || ':thumbnail', 'authoritative', r.evidence, r.site_id);
        END IF;
    END LOOP;

    -- invariant 1: every planned row stands, with the planned values, the flag and the three
    -- columns the statement derived for it. The temp table is aliased `p`, never `r`: the loop
    -- variable of this block is `r`, and Postgres refuses a reference that could mean either
    -- (measured 2026-10-06, in the rehearsal of chunk-001).
    SELECT count(*) INTO bad FROM _ih_insert p
      LEFT JOIN wiki_images w ON w.site_id = p.site_id AND w.original_url = p.original_url
     WHERE w.id IS NULL OR w.is_hero IS NOT TRUE OR w.is_excluded IS NOT FALSE
        OR w.width IS DISTINCT FROM p.width OR w.height IS DISTINCT FROM p.height
        OR w.file_size_bytes IS DISTINCT FROM p.file_size_bytes
        OR w.filename IS DISTINCT FROM p.filename OR w.original_url IS DISTINCT FROM p.original_url
        OR w.is_lead IS NOT FALSE OR w.source_type IS DISTINCT FROM 'wikimedia'
        OR w.sort_order <> (SELECT COALESCE(MAX(w3.sort_order), 0) FROM wiki_images w3
                             WHERE w3.site_id = p.site_id);
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % inserted row(s) do not stand as planned', 'insert-2026-10-07-008-001', bad;
    END IF;

    -- invariant 2: at most one live hero per touched site (T09's invariant)
    SELECT count(*) INTO bad FROM (
        SELECT w.site_id FROM wiki_images w
          JOIN _ih_insert p ON p.site_id = w.site_id
         WHERE w.is_hero AND w.is_excluded IS NOT TRUE
         GROUP BY w.site_id HAVING count(*) > 1) d;
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % touched site(s) hold more than one live hero row',
            'insert-2026-10-07-008-001', bad;
    END IF;

    -- invariant 3: the journal carries every write, and nothing else
    SELECT count(*) INTO bad FROM _ih_insert p
      LEFT JOIN (SELECT site_id_ref, count(*) AS n FROM remediation_change_log
                  WHERE run_stamp = 'insert-2026-10-07-008-001' GROUP BY site_id_ref) l
        ON l.site_id_ref = p.site_id
     WHERE COALESCE(l.n, 0) <> 14
        + CASE WHEN p.demoted_id IS NOT NULL THEN 1 ELSE 0 END
        + CASE WHEN p.new_thumbnail IS DISTINCT FROM p.old_thumbnail THEN 1 ELSE 0 END;
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % site(s) do not have exactly their planned journal rows',
            'insert-2026-10-07-008-001', bad;
    END IF;
END $$;

-- the same two read-back lines the shared writer ends with, so `--rehearse` recognises the run
SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-008-001';
SELECT 'planned rows', count(*)::text FROM _ih_insert;
COMMIT;
