"""Mutation sweep for the duplicate merge and the parent lanes: every guard must be able to fail.

The machinery is `mechanical/mutation_sweep.py`'s (a case counts as FIRED only when its needle occurs
exactly once, the mutant compiles, the named test passed on the unmutated file and is reported
FAILED against the mutant - anything else fails the sweep). The cases are this package's: one per guard
of the row lane (`mechanical/rowlane.py`), the lane family in `mechanical/lane.py` (the move, retire and
parent lanes), the planners (`dup_merge.py`, `parent.py`), the two question stages (`dup_judge.py`,
`parent_judge.py`, `label_rounds.py`) and the calibration sets (`pair_calibration.py`), each naming the one test
that must notice.

A guard that is an `if` is found by its line: `at()` reads the file, takes the `nth` line equal to
`line` and extends it by the lines that follow until the needle occurs exactly once, so a repeated
`if row is None:` is told apart by what comes after it. The mutant is that `if` with its condition
replaced by `False` (`mutation_sweep.falsify`). Anything that is not an `if` is a `swap()` with its
exact text.

Run it from a parent process on a clean committed tree, never from inside a subagent lane (a lane
killed between applying a mutation and restoring it leaves the mutant behind):

    ./.venv/Scripts/python.exe scripts/remediation/identity/mutation_sweep_merge.py            # all
    ./.venv/Scripts/python.exe scripts/remediation/identity/mutation_sweep_merge.py rowlane     # by label

`git status` must be clean afterwards: the sweep restores every file and checks its sha256.
"""

from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve()
for _root in (str(_HERE.parents[3]), str(_HERE.parents[1])):
    if _root not in sys.path:
        sys.path.insert(0, _root)

from mechanical.mutation_sweep import REPO, Case, falsify, main  # noqa: E402

REMEDIATION = REPO / "scripts/remediation"
MECH = REMEDIATION / "mechanical"
IDENT = REMEDIATION / "identity"
LANE = MECH / "lane.py"
APPLY = MECH / "apply.py"
PLAN = MECH / "plan.py"
ROWLANE = MECH / "rowlane.py"
DUP_MERGE = MECH / "dup_merge.py"
PARENT = MECH / "parent.py"
DUP_JUDGE = IDENT / "dup_judge.py"
PARENT_JUDGE = IDENT / "parent_judge.py"
ROUNDS = IDENT / "label_rounds.py"
WIKI = IDENT / "wiki.py"
CALIBRATION = IDENT / "pair_calibration.py"
MCODE = REMEDIATION / "mcode_driver.py"

T_ROW = "tests/remediation/test_mechanical_rowlane.py"
T_DM = "tests/remediation/test_mechanical_dup_merge.py"
T_PAR = "tests/remediation/test_mechanical_parent.py"
T_CELLS = "tests/remediation/test_mechanical_cells.py"
T_DJ = "tests/remediation/test_identity_dup_judge.py"
T_PJ = "tests/remediation/test_identity_parent_judge.py"
T_RW = "tests/remediation/test_identity_rounds_wiki.py"
T_CAL = "tests/remediation/test_identity_calibration.py"


def _falsified(needle: str) -> str:
    """`falsify` for an `if`, and the same for an `elif` (the condition becomes `False`)."""
    first, sep, rest = needle.partition("\n")
    if first.strip().startswith("elif ") and first.strip().endswith(":"):
        indent = first[: len(first) - len(first.lstrip(" "))]
        return f"{indent}elif False:{sep}{rest}"
    return falsify(needle)


def at(label: str, path: Path, line: str, test: str, testfile: str, nth: int = 0) -> Case:
    """The `if` (or `elif`) guard on the `nth` line equal to `line`, with its condition made `False`."""
    text = path.read_text(encoding="utf-8")
    lines = text.split("\n")
    found = [i for i, candidate in enumerate(lines) if candidate == line]
    if len(found) <= nth:
        raise ValueError(f"{label}: {path.name} has {len(found)} line(s) {line!r}, not {nth + 1}")
    start = found[nth]
    for width in range(1, 12):
        needle = "\n".join(lines[start : start + width])
        if text.count(needle) == 1:
            return Case(label, path, needle, _falsified(needle), test, testfile)
    raise ValueError(f"{label}: no unique needle starting at line {start + 1} of {path.name}")


def swap(label: str, path: Path, old: str, new: str, test: str, testfile: str) -> Case:
    return Case(label, path, old, new, test, testfile)


CASES: list[Case] = [
    # ------------------------------------------------------------------- lane.py: the shape
    swap(
        "lane: a cell lane refuses a row-keyed target",
        LANE,
        "    if lane.target.row_keyed or lane.row_invariants:",
        "    if lane.row_invariants:",
        "test_a_row_keyed_target_is_a_row_lane_s_and_no_cell_lane_s",
        T_CELLS,
    ),
    swap(
        "lane: a cell lane refuses row invariants",
        LANE,
        "    if lane.target.row_keyed or lane.row_invariants:",
        "    if lane.target.row_keyed:",
        "test_row_invariants_belong_to_a_row_lane",
        T_ROW,
    ),
    at(
        "lane: a row lane names its cells in row_cells",
        LANE,
        "    if lane.column or lane.max_chars or lane.allowed_new_values or lane.cells:",
        "test_a_row_lane_that_breaks_its_shape_is_refused",
        T_ROW,
    ),
    at(
        "lane: a row lane has no site invariants",
        LANE,
        "    if lane.site_invariants or lane.write_invariant is not None or lane.reverses_journal:",
        "test_a_row_lane_that_breaks_its_shape_is_refused",
        T_ROW,
    ),
    at(
        "lane: a row lane reads unified_sites",
        LANE,
        "    if lane.target is not UNIFIED_SITES:",
        "test_a_row_lane_that_breaks_its_shape_is_refused",
        T_ROW,
    ),
    at(
        "lane: a row lane refuses a cell twice",
        LANE,
        "    if len({*names}) < len(names):",
        "test_a_row_lane_that_breaks_its_shape_is_refused",
        T_ROW,
    ),
    at(
        "lane: a row lane refuses a probe twice",
        LANE,
        "    if len({*probes}) < len(probes):",
        "test_a_row_lane_that_breaks_its_shape_is_refused",
        T_ROW,
    ),
    at(
        "lane: a row cell names a row-keyed table",
        LANE,
        "        if self.table not in ROW_TARGETS:",
        "test_a_row_cell_names_a_row_keyed_table",
        T_ROW,
    ),
    at(
        "lane: a row invariant is spliced safely (message)",
        LANE,
        "        if _SAYS.match(self.says) is None:",
        "test_a_row_invariant_is_spliced_safely",
        T_ROW,
    ),
    at(
        "lane: a row invariant reads the plan and not the block",
        LANE,
        '        if "{plan}" not in self.bad_sql or "$$" in self.bad_sql:',
        "test_a_row_invariant_is_spliced_safely",
        T_ROW,
    ),
    at(
        "lane: a row invariant names its probe",
        LANE,
        "        if not _KEY_PREFIX.match(self.probe):",
        "test_a_row_invariant_is_spliced_safely",
        T_ROW,
    ),
    swap(
        "lane: the row read-back replaces the site-keyed metrics",
        LANE,
        "    whose = row_whose if lane.row_cells else site_whose",
        "    whose = site_whose",
        "test_the_move_read_back_counts_what_must_not_change",
        T_ROW,
    ),
    swap(
        "lane: a row lane's outside check names table and column",
        LANE,
        "        return f\"({prefix}table_name || '.' || {prefix}column_name NOT IN ({listed}))\"",
        '        return f"({prefix}column_name NOT IN ({listed}))"',
        "test_where_a_row_lane_writes_is_every_qualified_column",
        T_ROW,
    ),
    # ----------------------------------------------------------- lane.py: the family
    at(
        "lane: a pair is two lower-case uuids",
        LANE,
        "        if not _UUID.match(self.loser) or not _UUID.match(self.survivor):",
        "test_a_pair_is_two_lower_case_uuids_that_differ",
        T_DM,
    ),
    at(
        "lane: a site is not its own survivor",
        LANE,
        "        if self.loser == self.survivor:",
        "test_a_pair_is_two_lower_case_uuids_that_differ",
        T_DM,
    ),
    at(
        "lane: a limit only widens",
        LANE,
        "        if self.metres_limit < DUP_RETIRE_METRES:",
        "test_a_limit_only_widens",
        T_DM,
    ),
    at(
        "lane: a wave label is a date",
        LANE,
        '    if re.match(rf"^{_WAVE}\\Z", wave) is None:',
        "test_the_labels_are_the_date_then_letters",
        T_DM,
    ),
    at(
        "lane: a wave holds a pair",
        LANE,
        "    if not pairs:",
        "test_a_wave_of_pairs_is_a_set_of_losers_without_a_chain",
        T_DM,
    ),
    at(
        "lane: a loser appears once",
        LANE,
        "    if len(set(losers)) != len(losers):",
        "test_a_wave_of_pairs_is_a_set_of_losers_without_a_chain",
        T_DM,
    ),
    at(
        "lane: a survivor is no other pair's loser",
        LANE,
        "    if chained:",
        "test_a_wave_of_pairs_is_a_set_of_losers_without_a_chain",
        T_DM,
    ),
    swap(
        "dup_merge: the limit's evidence is in the plan",
        DUP_MERGE,
        "            for q in (*pair.quotes, *pair.limit_evidence)",
        "            for q in pair.quotes",
        "test_a_pair_beyond_two_kilometres_journals_the_evidence_of_its_limit",
        T_DM,
    ),
    swap(
        "dup_merge: the decision's limit evidence reaches the pair",
        DUP_MERGE,
        '                    limit_evidence=tuple(m["limit_evidence"]),',
        "                    limit_evidence=(),",
        "test_the_override_s_evidence_reaches_the_pair",
        T_DM,
    ),
    swap(
        "dup_merge: the pairs file keeps the limit's evidence",
        DUP_MERGE,
        '            "limit_evidence": [dict(q) for q in self.limit_evidence],',
        '            "limit_evidence": [],',
        "test_a_wave_file_is_written_once_and_read_back",
        T_DM,
    ),
    at(
        "lane: the pairs file exists",
        LANE,
        "    if not path.exists():",
        "test_a_missing_file_is_named",
        T_DM,
        nth=0,
    ),
    at(
        "lane: the pairs file is the wave's",
        LANE,
        '    if data.get("wave") != wave:',
        "test_a_file_of_another_wave_is_refused",
        T_DM,
    ),
    at(
        "lane: a pair's own limit",
        LANE,
        "    if limits:",
        "test_a_pair_with_its_own_limit_changes_only_the_retire_survivor_check",
        T_DM,
    ),
    swap(
        "lane: the limit is read per loser",
        LANE,
        '            + f" ELSE {metres} END"',
        '            + f" ELSE 0 END"',
        "test_the_per_loser_limit_is_read_in_sql",
        T_DM,
    ),
    swap(
        "lane: the not-curated parent probe names a row that exists",
        LANE,
        '                "8db5555a-a9a3-417b-944c-6ec0c04de0db",  # GeoNames Chiapa de Corzo\n',
        '                "00000000-0000-0000-0000-000000000000",  # GeoNames Chiapa de Corzo\n',
        "test_the_other_probes_name_a_row_of_their_kind",
        T_PAR,
    ),
    swap(
        "lane: the retire lane checks the decided survivor",
        LANE,
        "            decided_survivor_invariant(pairs),\n",
        "",
        "test_the_retire_lane_ends_with_it_and_probes_it_with_a_neighbour",
        T_DM,
    ),
    swap(
        "lane: the decided survivor is the loser's own",
        LANE,
        '        predicate=f"u.scope_reason IS DISTINCT FROM {sql_literal(DUPLICATE_PREFIX)} || {survivor_of}",',
        '        predicate="u.scope_reason IS NULL",',
        "test_the_decided_survivor_breaks_nothing_and_another_curated_site_does",
        T_DM,
    ),
    swap(
        "lane: a neighbour is no survivor",
        LANE,
        "        f\"AND {not_retired('s')} AND CAST(s.id AS text) <> {sql_literal(survivor)} \"",
        "        f\"AND {not_retired('s')} \"",
        "test_the_neighbour_is_the_nearest_curated_shown_site_that_is_not_planned",
        T_DM,
    ),
    swap(
        "lane: a neighbour is no planned site",
        LANE,
        "        f\"AND CAST(s.id AS text) NOT IN ({others}) AND {sphere_metres('s', 'u')} <= {metres} \"",
        "        f\"AND {sphere_metres('s', 'u')} <= {metres} \"",
        "test_the_neighbour_is_the_nearest_curated_shown_site_that_is_not_planned",
        T_DM,
    ),
    swap(
        "lane: a neighbour is near",
        LANE,
        "        f\"AND CAST(s.id AS text) NOT IN ({others}) AND {sphere_metres('s', 'u')} <= {metres} \"",
        '        f"AND CAST(s.id AS text) NOT IN ({others}) "',
        "test_the_neighbour_is_the_nearest_curated_shown_site_that_is_not_planned",
        T_DM,
    ),
    swap(
        "lane: a placeholder probe is one placeholder",
        LANE,
        "            self.probe_values == (PROBE_SELF,) or PROBE_NEIGHBOUR in self.probe_values[0]",
        "            self.probe_values == (PROBE_SELF,) or True",
        "test_a_single_probe_value_that_is_no_placeholder_is_refused",
        T_DM,
    ),
    swap(
        "lane: a missing pairs file is a KeyError",
        LANE,
        '        raise KeyError(f"{name}: {exc}") from exc',
        "        raise",
        "test_the_lanes_resolve_from_a_wave_s_pairs_file",
        T_DM,
    ),
    # ------------------------------------------------- lane.py: the move's invariants in SQL
    swap(
        "move: a destination must be curated",
        LANE,
        "\"FROM {plan} q WHERE q.column_name = 'site_id' AND NOT EXISTS (SELECT 1 FROM \"",
        "\"FROM {plan} q WHERE q.column_name = 'site_id' AND EXISTS (SELECT 1 FROM \"",
        "test_a_destination_that_is_no_curated_site_is_counted",
        T_ROW,
    ),
    swap(
        "move: a destination must not be retired",
        LANE,
        "\"FROM {plan} q WHERE q.column_name = 'site_id' AND EXISTS (SELECT 1 FROM \"",
        "\"FROM {plan} q WHERE q.column_name = 'site_id' AND NOT EXISTS (SELECT 1 FROM \"",
        "test_a_destination_that_is_retired_is_counted",
        T_ROW,
    ),
    swap(
        "move: the survivor is the named one",
        LANE,
        "f\"WHERE q.column_name = 'site_id' AND (q.new_value IS DISTINCT FROM {survivor_q} \"",
        "f\"WHERE q.column_name = 'site_id' AND (q.new_value IS NOT DISTINCT FROM {survivor_q} \"",
        "test_a_destination_other_than_the_named_survivor_is_counted",
        T_ROW,
    ),
    swap(
        "move: the survivor is within the pair's limit",
        LANE,
        "f\"{sphere_metres('s', 'l')} > {limit_q}))\"",
        "f\"{sphere_metres('s', 'l')} < {limit_q}))\"",
        "test_the_default_limit_is_two_thousand_metres",
        T_ROW,
    ),
    swap(
        "move: a hero count above one",
        LANE,
        '"w.is_hero IS TRUE AND w.is_excluded IS NOT TRUE) > 1"',
        '"w.is_hero IS TRUE AND w.is_excluded IS NOT TRUE) > 2"',
        "test_two_live_heroes_on_a_touched_site_are_counted_and_an_excluded_one_is_not",
        T_ROW,
    ),
    swap(
        "move: an excluded hero is no hero",
        LANE,
        '"w.is_hero IS TRUE AND w.is_excluded IS NOT TRUE) > 1"',
        '"w.is_hero IS TRUE) > 1"',
        "test_two_live_heroes_on_a_touched_site_are_counted_and_an_excluded_one_is_not",
        T_ROW,
    ),
    swap(
        "move: the loser is a touched site",
        LANE,
        '"FROM (SELECT CAST(q.site_id AS text) AS sid FROM {plan} q UNION SELECT "',
        '"FROM (SELECT q.new_value AS sid FROM {plan} q UNION SELECT "',
        "test_the_loser_is_a_touched_site_too",
        T_ROW,
    ),
    swap(
        "move: the loser's name is the survivor's",
        LANE,
        '"JOIN unified_sites l ON CAST(l.id AS text) = t.sid WHERE NOT EXISTS (SELECT 1 "',
        '"JOIN unified_sites l ON CAST(l.id AS text) = t.sid WHERE EXISTS (SELECT 1 "',
        "test_a_loser_whose_name_is_not_a_name_of_its_survivor_is_counted",
        T_ROW,
    ),
    swap(
        "move: the alias is compared by the name key",
        LANE,
        "f\"AND n.name_normalized = {site_key_sql('l.name')})\"",
        'f"AND n.name_normalized = lower(l.name))"',
        "test_the_alias_is_compared_by_the_loser_s_name_key",
        T_ROW,
    ),
    swap(
        "move: the premise leaves the counts out",
        LANE,
        "        \"' | survivor ' || coalesce((SELECT \"",
        "        \"' | stranger ' || coalesce((SELECT \"",
        "test_the_move_premise_is_the_name_the_ids_and_the_survivor_s_name_and_ids",
        T_DM,
    ),
    swap(
        "move: the premise names the loser's scope (SQL)",
        LANE,
        "        \"coalesce(u.scope_status, 'NULL') || ' | ' || coalesce(u.scope_reason, 'NULL') || \"",
        "        \"'' || \"",
        "test_the_move_premise_names_the_loser_s_scope_so_the_move_cannot_be_undone_while_it_is_retired",
        T_DM,
    ),
    swap(
        "move: the premise names the loser's scope (Python)",
        DUP_MERGE,
        "        f\"{loser['name']} | {_ids(read, loser['id'])} | {status} | {reason} | \"",
        "        f\"{loser['name']} | {_ids(read, loser['id'])} | \"",
        "test_the_move_premise_names_the_loser_s_scope_so_the_move_cannot_be_undone_while_it_is_retired",
        T_DM,
    ),
    swap(
        "retire: the survivor's live images are in the premise",
        LANE,
        '"w WHERE w.site_id = s.id AND w.is_excluded IS NOT TRUE) AS text) "',
        '"w WHERE w.site_id = s.id AND w.is_excluded = 0) AS text) "',
        "test_an_excluded_image_of_the_survivor_is_not_live",
        T_DM,
    ),
    # ------------------------------------------------ lane.py: the parent's invariants in SQL
    swap(
        "parent: the parent is a curated site",
        LANE,
        'predicate=f"NOT EXISTS (SELECT 1 FROM unified_sites s WHERE {_PARENT})",',
        'predicate=f"EXISTS (SELECT 1 FROM unified_sites s WHERE {_PARENT})",',
        "test_a_parent_that_is_no_curated_site_is_counted",
        T_PAR,
    ),
    swap(
        "parent: the parent is shown",
        LANE,
        "f\"EXISTS (SELECT 1 FROM unified_sites s WHERE {_PARENT} AND {is_retired('s')})\"",
        "f\"EXISTS (SELECT 1 FROM unified_sites s WHERE {_PARENT} AND {not_retired('s')})\"",
        "test_a_retired_parent_is_counted_and_a_pending_one_is_not",
        T_PAR,
    ),
    swap(
        "parent: the country is the child's",
        LANE,
        "AND (s.country IS DISTINCT FROM u.country OR {sphere_metres('s', 'u')} > {metres}))",
        "AND (s.country IS NOT DISTINCT FROM u.country OR {sphere_metres('s', 'u')} > {metres}))",
        "test_another_country_is_counted_even_next_door",
        T_PAR,
    ),
    swap(
        "parent: at most 5 km",
        LANE,
        "OR {sphere_metres('s', 'u')} > {metres}))",
        "OR {sphere_metres('s', 'u')} < {metres}))",
        "test_5000_metres_is_the_limit",
        T_PAR,
    ),
    swap(
        "parent: a parent has no parent",
        LANE,
        '"s.id = u.parent_site_id AND s.parent_site_id IS NOT NULL) OR EXISTS (SELECT 1 "',
        '"s.id = u.parent_site_id AND s.parent_site_id IS NULL) OR EXISTS (SELECT 1 "',
        "test_a_parent_with_a_parent_is_counted",
        T_PAR,
    ),
    swap(
        "parent: a child has no children",
        LANE,
        '"FROM unified_sites c WHERE c.parent_site_id = u.id)"',
        '"FROM unified_sites c WHERE c.parent_site_id = c.id)"',
        "test_a_child_that_is_a_parent_is_counted",
        T_PAR,
    ),
    # ------------------------------------------------------------------ apply.py: the dispatch
    at(
        "apply: a row lane validates in rowlane",
        APPLY,
        "    if lane.row_cells:",
        "test_each_refusal",
        T_ROW,
        nth=0,
    ),
    at(
        "apply: a row lane renders in rowlane",
        APPLY,
        "    if lane.row_cells:",
        "test_one_transaction_with_its_guards_in_order",
        T_ROW,
        nth=1,
    ),
    at(
        "apply: a row lane's post-commit reads",
        APPLY,
        "    if lane.row_cells:",
        "test_the_post_commit_reads_hold_the_row_lane_s_journal_identity",
        T_ROW,
        nth=2,
    ),
    at(
        "apply: a row lane's read-back is asserted per cell",
        APPLY,
        "    if lane.row_cells:",
        "test_the_assert_reads_the_journal_and_the_cells_row_for_row",
        T_ROW,
        nth=3,
    ),
    at(
        "apply: a row lane's rollback rehearsal",
        APPLY,
        "    if lane.row_cells:",
        "test_the_rollback_rehearsal_asks_for_the_written_values",
        T_ROW,
        nth=4,
    ),
    at(
        "apply: a row lane's interests",
        APPLY,
        "    if lane.row_cells:",
        "test_the_interests_list_what_the_plan_touches",
        T_ROW,
        nth=5,
    ),
    at(
        "apply: a row lane's probes",
        APPLY,
        "    if lane.row_cells:",
        "test_every_guard_and_every_invariant_has_its_probe",
        T_ROW,
        nth=6,
    ),
    at(
        "apply: a row lane's unprobed invariants",
        APPLY,
        "    if lane.row_cells:",
        "test_a_plan_without_the_cells_a_probe_needs_names_the_invariants_it_cannot_probe",
        T_ROW,
        nth=7,
    ),
    at(
        "apply: a row lane's foreign row",
        APPLY,
        "    if lane.row_cells:",
        "test_every_probe_is_proven_when_its_own_guard_refuses_it",
        T_ROW,
        nth=8,
    ),
    at(
        "apply: the identity lanes' read-back",
        APPLY,
        "    if IDENTITY_LANE.match(lane.name):",
        "test_the_move_read_back_counts_what_must_not_change",
        T_ROW,
    ),
    at(
        "apply: the site's own id probes the depth",
        APPLY,
        "        if value == PROBE_SELF:",
        "test_the_site_s_own_id_probes_the_depth_check",
        T_PAR,
    ),
    at(
        "apply: a neighbour placeholder is replaced",
        APPLY,
        "        elif PROBE_NEIGHBOUR in value:",
        "test_probing_reads_the_neighbour_of_the_first_loser_and_a_lonely_one_fails",
        T_DM,
    ),
    at(
        "apply: a lane without a neighbour probe reads nothing",
        APPLY,
        "    if not wanting:",
        "test_probing_reads_the_neighbour_of_the_first_loser_and_a_lonely_one_fails",
        T_DM,
    ),
    at(
        "apply: a plan without the probed cell reads nothing",
        APPLY,
        "    if cell is None:",
        "test_probing_reads_the_neighbour_of_the_first_loser_and_a_lonely_one_fails",
        T_DM,
    ),
    at(
        "apply: a lonely loser cannot be probed",
        APPLY,
        "    if not rows:",
        "test_probing_reads_the_neighbour_of_the_first_loser_and_a_lonely_one_fails",
        T_DM,
    ),
    at(
        "apply: a uuid is how the database prints it",
        APPLY,
        '    if cell.sql_type == "uuid":',
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "apply: a uuid is lower case",
        APPLY,
        "        if not UUID_RE.match(text):",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "apply: a boolean is true or false",
        APPLY,
        '        if text not in ("true", "false"):',
        "test_each_refusal",
        T_ROW,
    ),
    swap(
        "apply: a missing pairs file is named by the CLI",
        APPLY,
        '            + (f": {exc.args[0]}" if exc.args and exc.args[0] != name else "")',
        '            + ""',
        "test_the_apply_cli_names_the_missing_file",
        T_DM,
    ),
    # --------------------------------------------------------------------- plan.py: the dispatch
    at(
        "plan: a row lane's plan record",
        PLAN,
        "    if lane.row_cells:",
        "test_the_line_names_the_row_the_cell_and_the_lane",
        T_ROW,
        nth=0,
    ),
    at(
        "plan: a row lane's reversal",
        PLAN,
        "    if lane.row_cells:",
        "test_the_reversal_of_a_valid_plan_is_valid",
        T_ROW,
        nth=1,
    ),
    # ----------------------------------------------------------------------- rowlane.py
    at(
        "rowlane: its tables share a key column",
        ROWLANE,
        "    if len(keys) != 1:",
        "test_tables_with_two_keys_are_refused",
        T_ROW,
    ),
    at(
        "rowlane: an empty plan is not validated",
        ROWLANE,
        "    if not records:",
        "test_each_refusal",
        T_ROW,
        nth=0,
    ),
    at(
        "rowlane: the curated source only (validation)",
        ROWLANE,
        "    if source != CURATED_SOURCE:",
        "test_another_source_is_refused",
        T_ROW,
    ),
    at(
        "rowlane: a site is a uuid",
        ROWLANE,
        "        if not UUID_RE.match(r.site_id):",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "rowlane: a record names its table row and column",
        ROWLANE,
        "        if r.table is None or r.row_id is None or r.column is None:",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "rowlane: a row id is a serial",
        ROWLANE,
        "        if not ROW_ID_RE.match(r.row_id):",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "rowlane: a cell appears once",
        ROWLANE,
        "        if key in seen:",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "rowlane: a site has one premise",
        ROWLANE,
        "        if premises.setdefault(r.site_id, r.premise) != r.premise:",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "rowlane: no journal id",
        ROWLANE,
        "        if r.journal_id is not None:",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "rowlane: a premise lane needs a premise",
        ROWLANE,
        "        if lane.premise_sql is not None and r.premise is None:",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "rowlane: a premise nobody checks is refused",
        ROWLANE,
        "        if lane.premise_sql is None and r.premise is not None:",
        "test_a_premise_nobody_checks_is_refused",
        T_ROW,
    ),
    at(
        "rowlane: a write is auditable",
        ROWLANE,
        "        if not r.reason or not r.evidence:",
        "test_each_refusal",
        T_ROW,
    ),
    at(
        "rowlane: an empty plan is not rendered",
        ROWLANE,
        "    if not records:",
        "test_an_empty_plan_is_not_rendered",
        T_ROW,
        nth=1,
    ),
    at(
        "rowlane: probes may skip the plan-side mirror",
        ROWLANE,
        "    if validate:",
        "test_probes_may_render_what_the_plan_side_mirror_refuses",
        T_ROW,
    ),
    at(
        "rowlane: the premise column and guard",
        ROWLANE,
        "    if premise:",
        "test_guard_5_conditions_the_write_on_the_premise_once_per_site",
        T_ROW,
        nth=1,
    ),
    at(
        "rowlane: guard 4 owns the alias and the demotion",
        ROWLANE,
        "    if owned_cells:",
        "test_guard_4_owns_the_alias_and_the_demotion_and_nothing_else",
        T_ROW,
    ),
    swap(
        "rowlane: the row invariants run on the write only",
        ROWLANE,
        "    for invariant in () if rollback else lane.row_invariants:",
        "    for invariant in lane.row_invariants:",
        "test_the_row_invariants_run_on_the_write_only",
        T_ROW,
    ),
    at(
        "rowlane: the do block stays closed",
        ROWLANE,
        '    if "$$" in block:',
        "test_a_value_that_would_end_the_do_block_is_refused",
        T_ROW,
    ),
    swap(
        "rowlane: the journal records the site the cell concerns",
        ROWLANE,
        '    add("        OR l.site_id_ref IS DISTINCT FROM p.site_id;")',
        '    add("        OR false;")',
        "test_the_journal_check_reads_the_site_the_cell_concerns",
        T_ROW,
    ),
    at(
        "rowlane: an empty plan has no read-back",
        ROWLANE,
        "    if not records:",
        "test_an_empty_plan_has_no_read_back",
        T_ROW,
        nth=2,
    ),
    at(
        "rowlane: the read-back agrees with the plan",
        ROWLANE,
        "        if got.get(name) != want:",
        "test_a_read_back_that_disagrees_with_the_plan_raises",
        T_ROW,
    ),
    at(
        "rowlane: a boolean is flipped",
        ROWLANE,
        '    if sql_type == "boolean":',
        "test_a_boolean_is_flipped_and_any_other_cell_gets_its_never_stored_value",
        T_ROW,
    ),
    at(
        "rowlane: a redirect needs a move",
        ROWLANE,
        "    if not movable:",
        "test_a_plan_without_the_cells_a_probe_needs_names_the_invariants_it_cannot_probe",
        T_ROW,
    ),
    swap(
        "rowlane: a redirect skips the site that is the destination",
        ROWLANE,
        "        if all(destination not in (records[i].old_value, records[i].new_value) for i in moves[site])",
        "        if all(True for i in moves[site])",
        "test_a_destination_probe_skips_the_site_that_is_itself_the_destination",
        T_ROW,
    ),
    at(
        "rowlane: the only cell is never dropped",
        ROWLANE,
        "    if index is None or len(records) == 1:",
        "test_a_single_cell_plan_cannot_drop_its_only_cell",
        T_ROW,
    ),
    at(
        "rowlane: an alias probe needs a name row",
        ROWLANE,
        "    if site is None:",
        "test_a_plan_without_the_cells_a_probe_needs_names_the_invariants_it_cannot_probe",
        T_ROW,
    ),
    at(
        "rowlane: a width probe",
        ROWLANE,
        "    if wide is not None:",
        "test_every_guard_and_every_invariant_has_its_probe",
        T_ROW,
    ),
    at(
        "rowlane: an ownership probe",
        ROWLANE,
        "    if owned is not None:",
        "test_every_guard_and_every_invariant_has_its_probe",
        T_ROW,
    ),
    at(
        "rowlane: a premise probe",
        ROWLANE,
        "    if lane.premise_sql is not None:",
        "test_every_guard_and_every_invariant_has_its_probe",
        T_ROW,
        nth=0,
    ),
    at(
        "rowlane: a plan record needs a premise on a premise lane",
        ROWLANE,
        "    if lane.premise_sql is not None:",
        "test_a_change_without_its_premise_is_refused",
        T_ROW,
        nth=1,
    ),
    at(
        "rowlane: an invariant that cannot be probed is left out",
        ROWLANE,
        "        if mutated is not None:",
        "test_a_plan_without_the_cells_a_probe_needs_names_the_invariants_it_cannot_probe",
        T_ROW,
    ),
    at(
        "rowlane: a foreign row exists",
        ROWLANE,
        "    if not rows:",
        "test_no_foreign_row_is_a_refusal",
        T_ROW,
    ),
    at(
        "rowlane: a plan change names its row",
        ROWLANE,
        "    if change.table is None or change.row_id is None or change.column is None:",
        "test_a_change_without_its_row_is_refused",
        T_ROW,
    ),
    at(
        "rowlane: a plan change has a row id",
        ROWLANE,
        "    if not ROW_ID_RE.match(change.row_id):",
        "test_a_change_with_a_row_id_that_is_no_serial_is_refused",
        T_ROW,
    ),
    at(
        "rowlane: a plan change has its premise",
        ROWLANE,
        "        if change.premise is None:",
        "test_a_change_without_its_premise_is_refused",
        T_ROW,
    ),
    # -------------------------------------------------------------------------- dup_merge.py
    at(
        "dup_merge: a chain ends at its last survivor",
        DUP_MERGE,
        "                if final not in target_of:",
        "test_a_decided_merge_is_a_pair_with_its_names_and_limit",
        T_DM,
    ),
    swap(
        "dup_merge: a circle of merges is refused",
        DUP_MERGE,
        """                raise P.PlanError(f"{m['site_id']}: the decisions merge it in a circle")""",
        "                pass",
        "test_two_decisions_that_merge_into_each_other_are_refused",
        T_DM,
    ),
    at(
        "dup_merge: waves under one date",
        DUP_MERGE,
        "    if count > len(letters) + 1:",
        "test_the_labels_are_the_date_then_letters",
        T_DM,
    ),
    at(
        "dup_merge: a survivor fits a wave",
        DUP_MERGE,
        "        if len(ids) > max_sites:",
        "test_a_wave_holds_whole_survivors_and_at_most_the_sites",
        T_DM,
    ),
    at(
        "dup_merge: a wave is cut at the site limit",
        DUP_MERGE,
        "        if current and len(sites | ids) > max_sites:",
        "test_a_wave_holds_whole_survivors_and_at_most_the_sites",
        T_DM,
    ),
    at(
        "dup_merge: a wave file is written once",
        DUP_MERGE,
        "    if path.exists():",
        "test_a_wave_file_is_written_once_and_read_back",
        T_DM,
    ),
    at(
        "dup_merge: a lane that wrote is never planned again",
        DUP_MERGE,
        "    if written:",
        "test_a_lane_that_has_written_is_never_planned_again",
        T_DM,
    ),
    at(
        "dup_merge: the loser and the survivor exist",
        DUP_MERGE,
        "        if row is None:",
        "test_each_check_holds_a_pair_back_on_its_own",
        T_DM,
        nth=0,
    ),
    at(
        "dup_merge: both are curated",
        DUP_MERGE,
        '        if row["source_id"] != P.CURATED_SOURCE:',
        "test_each_check_holds_a_pair_back_on_its_own",
        T_DM,
    ),
    at(
        "dup_merge: both are named as decided",
        DUP_MERGE,
        '        if row["name"] != wanted:',
        "test_each_check_holds_a_pair_back_on_its_own",
        T_DM,
    ),
    at(
        "dup_merge: the survivor shows",
        DUP_MERGE,
        '    if survivor["scope_status"] == RETIRED:',
        "test_each_check_holds_a_pair_back_on_its_own",
        T_DM,
    ),
    at(
        "dup_merge: a retired loser was retired for the survivor",
        DUP_MERGE,
        '        if loser["scope_reason"] != f"{DUPLICATE_PREFIX}{pair.survivor}":',
        "test_each_check_holds_a_pair_back_on_its_own",
        T_DM,
    ),
    at(
        "dup_merge: the decision's retired flag is true",
        DUP_MERGE,
        "    elif pair.already_retired:",
        "test_a_loser_the_decision_calls_retired_but_which_is_shown_is_held",
        T_DM,
    ),
    at(
        "dup_merge: nothing is retired onto the loser",
        DUP_MERGE,
        "    if onto:",
        "test_each_check_holds_a_pair_back_on_its_own",
        T_DM,
    ),
    at(
        "dup_merge: the pair has a distance",
        DUP_MERGE,
        "    if metres is None:",
        "test_each_check_holds_a_pair_back_on_its_own",
        T_DM,
    ),
    at(
        "dup_merge: the pair is within its limit",
        DUP_MERGE,
        "    if metres > pair.metres_limit:",
        "test_each_check_holds_a_pair_back_on_its_own",
        T_DM,
    ),
    swap(
        "dup_merge: a second loser meets the first one's images",
        DUP_MERGE,
        '    s_urls = {i["original_url"] for i in read.images.get(survivor, ())} | taken.urls\n',
        '    s_urls = {i["original_url"] for i in read.images.get(survivor, ())}\n',
        "test_a_url_both_losers_hold_moves_once",
        T_DM,
    ),
    swap(
        "dup_merge: a second loser meets the first one's hero",
        DUP_MERGE,
        "    s_has_hero = taken.hero or any(\n",
        "    s_has_hero = any(\n",
        "test_the_first_hero_stays_and_the_second_is_demoted",
        T_DM,
    ),
    swap(
        "dup_merge: a second loser meets the first one's links",
        DUP_MERGE,
        "    s_keys |= taken.links\n",
        "    s_keys |= set()\n",
        "test_a_content_link_both_hold_moves_once",
        T_DM,
    ),
    swap(
        "dup_merge: a second loser meets the first one's name",
        DUP_MERGE,
        "    moves_name = key not in taken.names and not any(\n",
        "    moves_name = not any(\n",
        "test_a_name_key_both_hold_moves_once",
        T_DM,
    ),
    swap(
        "dup_merge: a planned pair takes its images",
        DUP_MERGE,
        '    taken.urls |= {i["original_url"] for i in moved}\n',
        "    taken.urls |= set()\n",
        "test_a_url_both_losers_hold_moves_once",
        T_DM,
    ),
    swap(
        "dup_merge: a planned pair takes its links",
        DUP_MERGE,
        "    taken.links |= moved_links\n",
        "    taken.links |= set()\n",
        "test_a_content_link_both_hold_moves_once",
        T_DM,
    ),
    swap(
        "dup_merge: a planned pair takes the survivor's hero",
        DUP_MERGE,
        "    taken.hero = taken.hero or kept_hero\n",
        "    taken.hero = taken.hero\n",
        "test_the_first_hero_stays_and_the_second_is_demoted",
        T_DM,
    ),
    swap(
        "dup_merge: a planned pair takes its name",
        DUP_MERGE,
        "        taken.names.add(key)\n",
        "        taken.names.add('')\n",
        "test_a_name_key_both_hold_moves_once",
        T_DM,
    ),
    at(
        "dup_merge: a collision stays",
        DUP_MERGE,
        '        if image["original_url"] in s_urls:',
        "test_the_loser_s_rows_move_and_a_collision_stays",
        T_DM,
    ),
    at(
        "dup_merge: a second hero is demoted",
        DUP_MERGE,
        "        if s_has_hero or index > 0:",
        "test_a_moved_hero_is_demoted_when_the_survivor_has_a_live_hero",
        T_DM,
    ),
    swap(
        "dup_merge: the first moved hero stays when the survivor has none",
        DUP_MERGE,
        "        if s_has_hero or index > 0:",
        "        if s_has_hero or index >= 0:",
        "test_a_moved_hero_stays_when_the_survivor_has_none",
        T_DM,
    ),
    swap(
        "dup_merge: a survivor hero that is excluded does not count",
        DUP_MERGE,
        '        i["is_hero"] is True and live(i) for i in read.images.get(survivor, ())\n',
        '        i["is_hero"] is True for i in read.images.get(survivor, ())\n',
        "test_a_survivor_hero_that_is_excluded_does_not_count",
        T_DM,
    ),
    at(
        "dup_merge: a link collision stays",
        DUP_MERGE,
        '        if (link["content_source"], link["content_id"]) in s_keys:',
        "test_the_loser_s_rows_move_and_a_collision_stays",
        T_DM,
    ),
    swap(
        "dup_merge: a name the survivor holds needs no cell",
        DUP_MERGE,
        "    if moves_name:\n        row = next(",
        "    if True:\n        row = next(",
        "test_a_name_the_survivor_holds_already_needs_no_cell",
        T_DM,
    ),
    at(
        "dup_merge: no name row holds the pair",
        DUP_MERGE,
        "        if row is None:",
        "test_no_name_row_to_carry_the_alias_holds_the_pair",
        T_DM,
        nth=1,
    ),
    swap(
        "dup_merge: an alias already is one",
        DUP_MERGE,
        '        if row["name_type"] != ALIAS:',
        "        if True:",
        "test_a_name_row_that_is_an_alias_already_only_changes_site",
        T_DM,
    ),
    at(
        "dup_merge: the premise is the rows'",
        DUP_MERGE,
        '            if loser["move_premise"] != expected:',
        "test_a_premise_the_rows_do_not_give_holds_the_pair",
        T_DM,
    ),
    at(
        "dup_merge: a pair with nothing to move is listed",
        DUP_MERGE,
        "        if not cells:",
        "test_a_pair_with_nothing_to_move_is_listed_for_its_retirement",
        T_DM,
    ),
    at(
        "dup_merge: a move plan has cells",
        DUP_MERGE,
        "    if not changes:",
        "test_a_wave_with_nothing_to_move_is_refused",
        T_DM,
        nth=0,
    ),
    at(
        "dup_merge: an already retired loser is not retired again",
        DUP_MERGE,
        "        if pair.already_retired:",
        "test_an_already_retired_loser_is_not_planned",
        T_DM,
    ),
    at(
        "dup_merge: the loser has no scope decision",
        DUP_MERGE,
        '            if loser["scope_status"] is not None or loser["scope_reason"] is not None:',
        "test_each_incomplete_state_holds_the_loser",
        T_DM,
    ),
    at(
        "dup_merge: the scope journal ends at the live value",
        DUP_MERGE,
        "                if broken is not None:",
        "test_a_journal_that_does_not_end_at_the_live_value_holds_the_loser",
        T_DM,
    ),
    at(
        "dup_merge: the retire premise is the rows'",
        DUP_MERGE,
        '            if loser["retire_premise"] != expected:',
        "test_the_premise_must_be_the_one_the_rows_give",
        T_DM,
    ),
    at(
        "dup_merge: a retire plan has cells",
        DUP_MERGE,
        "    if not changes:",
        "test_an_already_retired_loser_is_not_planned",
        T_DM,
        nth=1,
    ),
    at(
        "dup_merge: the images moved first",
        DUP_MERGE,
        "    if left:",
        "test_a_loser_whose_move_is_not_done_is_held",
        T_DM,
    ),
    at(
        "dup_merge: the links moved first",
        DUP_MERGE,
        "    if left_links:",
        "test_each_incomplete_state_holds_the_loser",
        T_DM,
    ),
    swap(
        "dup_merge: the name moved first",
        DUP_MERGE,
        '    if not any(\n        n["name_normalized"] == loser["name_key"] for n in read.names.get(pair.survivor, ())\n    ):',
        "    if False:",
        "test_each_incomplete_state_holds_the_loser",
        T_DM,
    ),
    swap(
        "dup_merge: a shown image needs a survivor that shows one",
        DUP_MERGE,
        "    if any(live(i) for i in read.images.get(pair.loser, ())) and not any(\n        live(i) for i in read.images.get(pair.survivor, ())\n    ):",
        "    if False:",
        "test_each_incomplete_state_holds_the_loser",
        T_DM,
    ),
    at(
        "dup_merge: the held pairs are written",
        DUP_MERGE,
        "    if held:",
        "test_the_held_pairs_are_written_beside_the_plan",
        T_DM,
    ),
    at(
        "dup_merge: a decided merge exists",
        DUP_MERGE,
        "    if not pairs:",
        "test_the_waves_command_writes_one_file_per_wave_and_refuses_none",
        T_DM,
    ),
    at(
        "dup_merge: a dry plan reads nothing",
        DUP_MERGE,
        "    if not args.write:",
        "test_a_plan_command_without_write_only_says_what_it_would_do",
        T_DM,
    ),
    # ----------------------------------------------------------------------------- parent.py
    at(
        "parent: a family fits a wave",
        PARENT,
        "        if len(family) > max_children:",
        "test_the_children_of_one_parent_stay_in_one_wave",
        T_PAR,
    ),
    at(
        "parent: a wave is cut at the child limit",
        PARENT,
        "        if current and len(current) + len(family) > max_children:",
        "test_the_children_of_one_parent_stay_in_one_wave",
        T_PAR,
    ),
    at(
        "parent: waves under one date",
        PARENT,
        "    if count > len(letters) + 1:",
        "test_the_labels_are_the_date_then_letters",
        T_PAR,
    ),
    at(
        "parent: a wave file is written once",
        PARENT,
        "    if path.exists():",
        "test_the_wave_file_is_written_once_and_read_back",
        T_PAR,
    ),
    at(
        "parent: the wave file exists",
        PARENT,
        "    if not path.exists():",
        "test_a_file_of_another_wave_or_none_is_refused",
        T_PAR,
        nth=0,
    ),
    at(
        "parent: the wave file is the wave's",
        PARENT,
        '    if data.get("wave") != wave:',
        "test_a_file_of_another_wave_or_none_is_refused",
        T_PAR,
    ),
    at(
        "parent: both rows exist",
        PARENT,
        "        if row is None:",
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: both rows are curated",
        PARENT,
        '        if row["source_id"] != P.CURATED_SOURCE:',
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: both are named as decided",
        PARENT,
        '        if row["name"] != wanted:',
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: both show",
        PARENT,
        '        if row["scope_status"] == RETIRED:',
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: a site is not its own parent",
        PARENT,
        "    if c.child == c.parent:",
        "test_a_site_is_not_its_own_parent",
        T_PAR,
    ),
    swap(
        "parent: a merged loser is no child",
        PARENT,
        "        or c.child in losers\n",
        "        or False\n",
        "test_a_site_a_merge_retires_is_neither_child_nor_parent",
        T_PAR,
    ),
    swap(
        "parent: a merged loser is no parent",
        PARENT,
        "        c.parent in losers\n",
        "        False\n",
        "test_a_site_a_merge_retires_is_neither_child_nor_parent",
        T_PAR,
    ),
    swap(
        "parent: a duplicate-of parent is no parent",
        PARENT,
        '        or str(parent["scope_reason"] or "").startswith(DUPLICATE_PREFIX)\n',
        "        or False\n",
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: the child names no parent yet",
        PARENT,
        '    if child["parent_site_id"] is not None:',
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: one country",
        PARENT,
        '    if child["country"] != parent["country"]:',
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: the pair has a distance",
        PARENT,
        "    if metres is None:",
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: at most 5 km (planner)",
        PARENT,
        "    if metres > PARENT_METRES:",
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: the parent is no component",
        PARENT,
        '    if parent["parent_site_id"] is not None:',
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: the child has no children",
        PARENT,
        '    if int(child["n_children"]) > 0:',
        "test_each_check_holds_a_child_back_on_its_own",
        T_PAR,
    ),
    at(
        "parent: the parent is no child of the wave",
        PARENT,
        "    if c.parent in wave_children:",
        "test_the_parent_of_a_child_in_the_wave_is_held_for_depth",
        T_PAR,
    ),
    at(
        "parent: the child is no parent of the wave",
        PARENT,
        "    if c.child in wave_parents:",
        "test_the_parent_of_a_child_in_the_wave_is_held_for_depth",
        T_PAR,
    ),
    at(
        "parent: a lane that wrote is never planned again",
        PARENT,
        "    if written:",
        "test_a_lane_that_has_written_is_not_planned_again",
        T_PAR,
    ),
    at(
        "parent: a plan has children",
        PARENT,
        "    if not changes:",
        "test_a_wave_with_nothing_left_is_refused_and_says_why",
        T_PAR,
    ),
    at(
        "parent: the held children are written",
        PARENT,
        "    if held:",
        "test_the_held_children_are_written_and_listed_in_the_plan",
        T_PAR,
    ),
    at(
        "parent: no merge decisions yet",
        PARENT,
        "    if not path.exists():",
        "test_the_merged_losers_are_read_from_the_duplicate_decisions",
        T_PAR,
        nth=1,
    ),
    at(
        "parent: a decided child exists",
        PARENT,
        "            if not decided:",
        "test_the_waves_command_refuses_without_a_decided_child",
        T_PAR,
    ),
    at(
        "parent: a dry plan reads nothing",
        PARENT,
        "        if not args.write:",
        "test_the_waves_command_and_the_dry_plan_command",
        T_PAR,
    ),
    # ----------------------------------------------------------------------------- rounds.py
    at(
        "rounds: no rounds file is no round",
        ROUNDS,
        "    if not path.exists():",
        "test_an_unknown_round_is_named",
        T_RW,
        nth=0,
    ),
    at(
        "rounds: a round is found by its name",
        ROUNDS,
        "        if r.name == name:",
        "test_an_export_writes_the_prompts_the_manifest_and_the_round",
        T_RW,
    ),
    at(
        "rounds: a re-ask needs a round",
        ROUNDS,
        "    if not rounds:",
        "test_a_reask_needs_a_round_to_re_ask",
        T_RW,
    ),
    at(
        "rounds: a re-ask needs the round imported",
        ROUNDS,
        "    if not imported(run, stage, rounds[-1].name):",
        "test_the_first_round_asks_everything_and_a_reask_the_held",
        T_RW,
    ),
    at(
        "rounds: a batch holds a question",
        ROUNDS,
        "    if per_batch < 1:",
        "test_the_batches_hold_five_questions_in_label_order",
        T_RW,
    ),
    at(
        "rounds: a round asks a question",
        ROUNDS,
        "    if not labels:",
        "test_no_question_and_a_label_asked_twice_are_refused",
        T_RW,
    ),
    at(
        "rounds: a label is asked once",
        ROUNDS,
        "    if len(set(labels)) != len(labels):",
        "test_no_question_and_a_label_asked_twice_are_refused",
        T_RW,
    ),
    at(
        "rounds: a handoff directory is new",
        ROUNDS,
        "    if handoff.exists() and any(handoff.iterdir()):",
        "test_a_handoff_directory_with_files_is_refused",
        T_DJ,
    ),
    at(
        "rounds: at most three rounds",
        ROUNDS,
        "    if len(load_rounds(run, stage)) >= MAX_ROUNDS:",
        "test_at_most_three_rounds",
        T_DJ,
    ),
    at(
        "rounds: a MiniMax answer is never ground truth",
        ROUNDS,
        "    if answer.model == OH.MINIMAX_MODEL:",
        "test_each_case",
        T_RW,
    ),
    at(
        "rounds: an answer names its role",
        ROUNDS,
        "    if named is None:",
        "test_each_case",
        T_RW,
    ),
    at(
        "rounds: the role is the stage's",
        ROUNDS,
        "    if named not in allowed:",
        "test_each_case",
        T_RW,
    ),
    at(
        "rounds: the round validates",
        ROUNDS,
        "    if not check.ok:",
        "test_unanswered_questions_stop_the_read",
        T_RW,
    ),
    at(
        "rounds: only the newest round is imported",
        ROUNDS,
        "    if record.name != newest:",
        "test_only_the_newest_round_is_importable",
        T_RW,
    ),
    at(
        "rounds: quotes are a list",
        ROUNDS,
        "    if not isinstance(data, list):",
        "test_the_quote_helpers_are_the_shape_rules_of_every_stage",
        T_RW,
    ),
    at(
        "rounds: a quote is a source and a text",
        ROUNDS,
        '        if not isinstance(q, dict) or set(q) != {"source", "quote"}:',
        "test_the_quote_helpers_are_the_shape_rules_of_every_stage",
        T_RW,
    ),
    at(
        "rounds: a quote has both",
        ROUNDS,
        '        if not all(isinstance(q[k], str) and q[k].strip() for k in ("source", "quote")):',
        "test_the_quote_helpers_are_the_shape_rules_of_every_stage",
        T_RW,
    ),
    at(
        "rounds: a quote cites a URL",
        ROUNDS,
        '        if not Q.is_url(q["source"]):',
        "test_the_quote_helpers_are_the_shape_rules_of_every_stage",
        T_RW,
    ),
    at(
        "rounds: a quote's page is fetchable",
        ROUNDS,
        "        if refused:",
        "test_the_quote_helpers_are_the_shape_rules_of_every_stage",
        T_RW,
    ),
    at(
        "rounds: the first round asks everything",
        ROUNDS,
        "    if not load_rounds(stage_run, stage):",
        "test_the_first_round_asks_everything_and_a_reask_the_held",
        T_RW,
    ),
    swap(
        "rounds: a later round asks what no round decided yet",
        ROUNDS,
        "    unasked = [label for label in first if label not in decisions]",
        "    unasked: list[str] = []",
        "test_a_label_decided_in_a_later_verdict_round_joins_the_next_recheck",
        T_RW,
    ),
    at(
        "rounds: a calibration flag is ROLE=ID",
        ROUNDS,
        "        if not separator or not role or not calibration_id:",
        "test_the_flag_is_role_equals_id",
        T_RW,
    ),
    at(
        "rounds: a role is calibrated once",
        ROUNDS,
        "        if role in out:",
        "test_the_flag_is_role_equals_id",
        T_RW,
    ),
    at(
        "rounds: an answering role names its calibration",
        ROUNDS,
        "        if calibration_id is None:",
        "test_a_role_without_a_named_calibration_does_not",
        T_RW,
    ),
    at(
        "rounds: a calibration has a verdict",
        ROUNDS,
        "        if not path.exists():",
        "test_a_calibration_without_a_verdict_does_not",
        T_RW,
        nth=0,
    ),
    at(
        "rounds: a calibration is the role's",
        ROUNDS,
        '        if verdict["role"] != role:',
        "test_another_role_s_calibration_does_not",
        T_RW,
    ),
    at(
        "rounds: a calibration passed",
        ROUNDS,
        '        if verdict["passed"] is not True:',
        "test_a_failed_verdict_does_not",
        T_RW,
    ),
    swap(
        "rounds: a calibration is sealed and its role unchanged",
        ROUNDS,
        "            CC._need_unchanged_role(CC._sealed(base, calibration_id))",
        "            pass",
        "test_a_role_whose_registry_entry_changed_after_the_seal_does_not",
        T_RW,
    ),
    swap(
        "rounds: the import checks the calibrations",
        ROUNDS,
        "    check_calibrated(\n"
        "        {RO.role_of(a.answered_by) for a in answers.values()}, calibrations, calibration_root\n"
        "    )\n",
        "",
        "test_an_answer_of_a_role_without_a_passed_calibration_counts_for_nothing",
        T_DJ,
    ),
    at(
        "rounds: a quote must be found",
        ROUNDS,
        "    if check.counted:",
        "test_a_merge_whose_quotes_are_found_and_which_is_near_is_decided",
        T_DJ,
    ),
    at(
        "rounds: no quotes no outcome",
        ROUNDS,
        "    if not quotes:",
        "test_the_quote_helpers_are_the_shape_rules_of_every_stage",
        T_RW,
    ),
    at(
        "rounds: a cached page is not fetched",
        ROUNDS,
        "        if cached is None:",
        "test_an_uncached_url_is_fetched_once_and_a_cached_one_not_again",
        T_RW,
    ),
    at(
        "rounds: a cached page is kept once",
        ROUNDS,
        '        if not (pages / f"{Q.url_key(url)}.json").exists():',
        "test_the_cache_is_stored_as_the_text_the_agent_read",
        T_RW,
    ),
    at(
        "rounds: an answer not the role's stops the import",
        ROUNDS,
        "        if problem is not None:",
        "test_an_answer_that_is_not_the_role_s_stops_the_import",
        T_DJ,
    ),
    # ------------------------------------------------------------------------------- wiki.py
    at(
        "wiki: a cited article is a Wikipedia URL",
        WIKI,
        "    if match is None:",
        "test_the_url_of_an_article_round_trips",
        T_RW,
    ),
    at(
        "wiki: the cache must exist",
        WIKI,
        "    if not (cache / INDEX_FILE).exists():",
        "test_the_context_needs_the_wikipedia_cache",
        T_PJ,
    ),
    at(
        "wiki: the index names pages the cache holds",
        WIKI,
        "            if not path.exists():",
        "test_an_index_naming_a_file_the_cache_lacks_is_an_error",
        T_RW,
    ),
    at(
        "wiki: a page is found by its resolved title too",
        WIKI,
        "            if page.resolved_title:",
        "test_a_cited_article_is_found_by_its_url_or_its_resolved_title",
        T_RW,
    ),
    # ---------------------------------------------------------------------------- dup_judge.py
    at(
        "dup_judge: a cluster record is an object of two keys",
        DUP_JUDGE,
        '    if not isinstance(data, dict) or set(data) != {"cluster_id", "members"}:',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: the answer is this question's",
        DUP_JUDGE,
        '    if data["cluster_id"] != cluster_id:',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: members are a list",
        DUP_JUDGE,
        '    if not isinstance(data["members"], list):',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a member has exactly its keys",
        DUP_JUDGE,
        "        if not isinstance(row, dict) or set(row) != MEMBER_KEYS:",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a member is a record of the cluster",
        DUP_JUDGE,
        "        if site not in ids:",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a member is answered once",
        DUP_JUDGE,
        "        if site in members:",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a verdict is one of four",
        DUP_JUDGE,
        "        if verdict not in VERDICTS:",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a survivor goes with MERGE",
        DUP_JUDGE,
        '        if (survivor is None) == (verdict == "MERGE"):',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a parent goes with PART_OF",
        DUP_JUDGE,
        '        if (parent is None) == (verdict == "PART_OF"):',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a record is not its own target",
        DUP_JUDGE,
        "        if site in (survivor, parent):",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a verdict says why",
        DUP_JUDGE,
        '        if not isinstance(row["why"], str) or not row["why"].strip():',
        "test_each_shape_error_is_named",
        T_DJ,
        nth=0,
    ),
    at(
        "dup_judge: MERGE PART_OF WRONG_ID carry a quote",
        DUP_JUDGE,
        '        if verdict != "DISTINCT" and not quotes:',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: every member is answered",
        DUP_JUDGE,
        "    if set(members) != set(ids):",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: no chain",
        DUP_JUDGE,
        '        if target is not None and members[target].verdict != "DISTINCT":',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a relation has exactly its keys",
        DUP_JUDGE,
        "        if not isinstance(row, dict) or set(row) != RECHECK_KEYS:",
        "test_each_shape_error_is_named",
        T_DJ,
        nth=0,
    ),
    at(
        "dup_judge: a relation is one the recheck asks",
        DUP_JUDGE,
        "        if site not in asked:",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a decision is one of three",
        DUP_JUDGE,
        "        if decision not in RECHECK_DECISIONS:",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a target goes with CONFIRM and RETARGET",
        DUP_JUDGE,
        '        if (target is None) == (decision != "REJECT"):',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: CONFIRM names the first target",
        DUP_JUDGE,
        '        if decision == "CONFIRM" and target != first_target:',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: RETARGET names another record",
        DUP_JUDGE,
        '        if decision == "RETARGET" and target in (first_target, site):',
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a decision carries a quote",
        DUP_JUDGE,
        "        if not quotes:",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: every relation is answered",
        DUP_JUDGE,
        "    if set(relations) != set(asked):",
        "test_each_shape_error_is_named",
        T_DJ,
    ),
    at(
        "dup_judge: a MERGE beyond two kilometres asks the override",
        DUP_JUDGE,
        "            if metres > DEFAULT_METRES:",
        "test_a_merge_beyond_two_kilometres_is_held_without_an_override",
        T_DJ,
    ),
    at(
        "dup_judge: a MERGE beyond two kilometres is held",
        DUP_JUDGE,
        "                if granted is None:",
        "test_a_merge_beyond_two_kilometres_is_held_without_an_override",
        T_DJ,
    ),
    swap(
        "dup_judge: the decision carries the override's limit and evidence",
        DUP_JUDGE,
        "                    metres_limit, limit_evidence = granted",
        "                    metres_limit = granted[0]",
        "test_an_override_with_a_found_quote_and_a_big_enough_limit_decides_it",
        T_DJ,
    ),
    swap(
        "dup_judge: the evidence of the limit reaches the merge",
        DUP_JUDGE,
        '                    item["limit_evidence"] = m["limit_evidence"]',
        '                    item["limit_evidence"] = []',
        "test_the_decision_carries_the_override_s_limit_and_evidence_to_the_merge",
        T_DJ,
    ),
    at(
        "dup_judge: an override needs a limit and a quote",
        DUP_JUDGE,
        "    if limit < math.ceil(metres) or not quotes:",
        "test_an_override_too_small_without_evidence_or_with_a_false_quote_decides_nothing",
        T_DJ,
    ),
    at(
        "dup_judge: no override no limit",
        DUP_JUDGE,
        "    if override is None:",
        "test_a_merge_beyond_two_kilometres_is_held_without_an_override",
        T_DJ,
    ),
    at(
        "dup_judge: a cluster without a verdict is unanswered",
        DUP_JUDGE,
        "        if verdict is None:",
        "test_a_cluster_without_a_verdict_is_unanswered",
        T_DJ,
    ),
    at(
        "dup_judge: a held member is listed",
        DUP_JUDGE,
        '            if m["status"] == HELD:',
        "test_a_held_member_holds_the_cluster_and_names_why",
        T_DJ,
    ),
    at(
        "dup_judge: a relation waits for its recheck",
        DUP_JUDGE,
        "                if second is None or recheck is None:",
        "test_a_merge_waits_for_its_recheck",
        T_DJ,
    ),
    at(
        "dup_judge: only a CONFIRM decides a relation",
        DUP_JUDGE,
        '                if second["status"] == HELD or second["decision"] != "CONFIRM":',
        "test_a_reject_or_a_retarget_holds_the_merge",
        T_DJ,
    ),
    at(
        "dup_judge: an override widens the lane's limit",
        DUP_JUDGE,
        '                if m["verdict"] == "MERGE":',
        "test_the_decision_carries_the_override_s_limit_and_evidence_to_the_merge",
        T_DJ,
    ),
    at(
        "dup_judge: a shape-held cluster is held",
        DUP_JUDGE,
        '        if not verdict["members"]:',
        "test_a_shape_held_cluster_is_held_with_its_reason",
        T_DJ,
    ),
    at(
        "dup_judge: a recheck needs a decided relation",
        DUP_JUDGE,
        "    if not first and not rounds.load_rounds(dup_run(run), STAGE_RECHECK):",
        "test_no_recheck_without_a_decided_relation",
        T_DJ,
    ),
    at(
        "dup_judge: a brief names a batch of the round",
        DUP_JUDGE,
        "    if batch_id not in record.batches:",
        "test_an_unknown_batch_is_refused",
        T_DJ,
    ),
    at(
        "dup_judge: a check names a question of the round",
        DUP_JUDGE,
        "    if label not in record.labels:",
        "test_the_shape_check_answers_with_the_problem_or_none",
        T_DJ,
    ),
    at(
        "dup_judge: a brief names a role of the stage",
        DUP_JUDGE,
        "    if role not in allowed:",
        "test_a_brief_names_a_role_of_its_stage",
        T_DJ,
    ),
    swap(
        "dup_judge: a calibration brief drops the shape check",
        DUP_JUDGE,
        "    return text if check else _without_check(text)",
        "    return text",
        "test_a_calibration_brief_has_no_shape_check",
        T_DJ,
    ),
    # -------------------------------------------------------------------------- parent_judge.py
    at(
        "parent_judge: a site a merge retires is asked about neither way",
        PARENT_JUDGE,
        '        if parent["id"] in losers or parent["id"] not in shown:',
        "test_a_site_a_merge_retires_is_asked_about_neither_way",
        T_PJ,
    ),
    swap(
        "parent_judge: a parent with no child asks nothing",
        PARENT_JUDGE,
        "        if kids:",
        "        if True:",
        "test_a_site_a_merge_retires_is_asked_about_neither_way",
        T_PJ,
    ),
    at(
        "parent_judge: a part-of child of a retired parent is left out",
        PARENT_JUDGE,
        "        if child in losers or parent in losers or child not in shown or parent not in shown:",
        "test_a_part_of_verdict_names_a_site_a_merge_retires_or_one_not_shown",
        T_PJ,
    ),
    at(
        "parent_judge: a child with a parent is not asked",
        PARENT_JUDGE,
        '        if shown[child]["parent_site_id"] is not None:',
        "test_a_part_of_child_that_names_a_parent_already_is_not_asked",
        T_PJ,
    ),
    at(
        "parent_judge: the parents come after the duplicates",
        PARENT_JUDGE,
        "    if not decisions_path.exists():",
        "test_the_parents_come_after_the_duplicates",
        T_PJ,
    ),
    at(
        "parent_judge: an answer is an object of two keys",
        PARENT_JUDGE,
        '    if not isinstance(data, dict) or set(data) != {"parent_id", "children"}:',
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: the answer is this question's",
        PARENT_JUDGE,
        '    if data["parent_id"] != parent_id:',
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: children are a list",
        PARENT_JUDGE,
        '    if not isinstance(data["children"], list):',
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a child has exactly its keys",
        PARENT_JUDGE,
        "        if not isinstance(row, dict) or set(row) != CHILD_KEYS:",
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a child is a candidate",
        PARENT_JUDGE,
        "        if site not in ids:",
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a child is answered once",
        PARENT_JUDGE,
        "        if site in children:",
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a verdict is one of three",
        PARENT_JUDGE,
        '        if row["verdict"] not in VERDICTS:',
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a verdict says why",
        PARENT_JUDGE,
        '        if not isinstance(row["why"], str) or not row["why"].strip():',
        "test_each_shape_error_is_named",
        T_PJ,
        nth=0,
    ),
    at(
        "parent_judge: PART and DUPLICATE carry a quote",
        PARENT_JUDGE,
        '        if row["verdict"] != "NOT_PART" and not quotes:',
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: every child is answered",
        PARENT_JUDGE,
        "    if set(children) != set(ids):",
        "test_each_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a relation has exactly its keys",
        PARENT_JUDGE,
        "        if not isinstance(row, dict) or set(row) != RECHECK_KEYS:",
        "test_each_recheck_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a relation is one the recheck asks",
        PARENT_JUDGE,
        "        if site not in asked:",
        "test_each_recheck_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a relation is answered once",
        PARENT_JUDGE,
        "        if site in relations:",
        "test_a_relation_answered_twice_is_refused",
        T_PJ,
    ),
    at(
        "parent_judge: a decision is CONFIRM or REJECT",
        PARENT_JUDGE,
        '        if row["decision"] not in RECHECK_DECISIONS:',
        "test_each_recheck_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: a decision carries a quote",
        PARENT_JUDGE,
        "        if not quotes:",
        "test_each_recheck_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: every relation is answered",
        PARENT_JUDGE,
        "    if set(relations) != set(asked):",
        "test_each_recheck_shape_error_is_named",
        T_PJ,
    ),
    at(
        "parent_judge: no store no P361",
        PARENT_JUDGE,
        "    if ctx.store is None:",
        "test_a_missing_item_is_no_proof",
        T_PJ,
    ),
    at(
        "parent_judge: P361 names the parent's item",
        PARENT_JUDGE,
        "        if entity is not None and parents & set(H.item_ids(entity, P_PART_OF)):",
        "test_the_wikidata_part_of_statement_is_evidence_on_top_of_the_quote",
        T_PJ,
    ),
    at(
        "parent_judge: a held verdict holds the part",
        PARENT_JUDGE,
        '            if m["status"] == HELD:',
        "test_a_held_verdict_holds_the_part",
        T_PJ,
    ),
    at(
        "parent_judge: a part waits for its recheck",
        PARENT_JUDGE,
        "            elif second is None:",
        "test_a_part_waits_for_its_recheck",
        T_PJ,
    ),
    at(
        "parent_judge: a held recheck holds the part",
        PARENT_JUDGE,
        '            elif second["status"] == HELD:',
        "test_a_reject_or_a_held_recheck_holds_it",
        T_PJ,
    ),
    at(
        "parent_judge: a reject holds the part",
        PARENT_JUDGE,
        '            elif second["decision"] != "CONFIRM":',
        "test_a_reject_or_a_held_recheck_holds_it",
        T_PJ,
    ),
    at(
        "parent_judge: a child of two parents is a conflict",
        PARENT_JUDGE,
        "        if len(decided) > 1:",
        "test_a_child_that_two_parents_confirm_is_a_conflict",
        T_PJ,
    ),
    at(
        "parent_judge: a recheck needs a decided part",
        PARENT_JUDGE,
        "    if not first and not rounds.load_rounds(parent_run(run), STAGE_RECHECK):",
        "test_no_recheck_without_a_decided_part",
        T_PJ,
    ),
    at(
        "parent_judge: a brief names a batch of the round",
        PARENT_JUDGE,
        "    if batch_id not in record.batches:",
        "test_the_brief_and_the_shape_check",
        T_PJ,
    ),
    at(
        "parent_judge: a brief names a role of the stage",
        PARENT_JUDGE,
        "    if role not in allowed:",
        "test_a_brief_names_a_role_of_its_stage",
        T_PJ,
    ),
    at(
        "parent_judge: a check names a question of the round",
        PARENT_JUDGE,
        "    if label not in record.labels:",
        "test_the_brief_and_the_shape_check",
        T_PJ,
    ),
    # --------------------------------------------------------------------------- calibration.py
    at(
        "calibration: a pair is a negative once",
        CALIBRATION,
        "            if key in seen:",
        "test_a_named_negative_is_not_chosen_a_second_time",
        T_CAL,
    ),
    at(
        "calibration: enough negatives",
        CALIBRATION,
        "    if len(negatives) < n_negatives:",
        "test_too_few_negatives_are_an_error",
        T_CAL,
    ),
    at(
        "calibration: a name is one site",
        CALIBRATION,
        "        if len(ids) != 1:",
        "test_a_named_pair_resolves_to_exactly_two_sites",
        T_CAL,
    ),
    at(
        "calibration: the export is still rewritable",
        CALIBRATION,
        "        if sql.count(old) != 1:",
        "test_an_export_that_no_longer_filters_on_shown_stops_the_rewrite",
        T_CAL,
    ),
    at(
        "calibration: the sites are all there",
        CALIBRATION,
        "    if missing:",
        "test_the_tagged_read_becomes_facts_and_a_missing_site_is_named",
        T_CAL,
    ),
    at(
        "calibration: only the pilot judge labels the gold",
        CALIBRATION,
        "        if problem is not None:",
        "test_only_the_pilot_judge_labels_the_gold",
        T_CAL,
        nth=0,
    ),
    at(
        "calibration: a positive the gold does not merge",
        CALIBRATION,
        "            if not merged:",
        "test_a_positive_the_gold_does_not_merge_is_listed",
        T_CAL,
    ),
    at(
        "calibration: a swapped survivor",
        CALIBRATION,
        '            elif relations.get(case.expected["loser"]) != f"MERGE:{case.expected[\'survivor\']}":',
        "test_a_swapped_survivor_is_listed_apart",
        T_CAL,
    ),
    at(
        "calibration: a negative the gold merges",
        CALIBRATION,
        "        elif merged:",
        "test_a_negative_the_gold_merges_is_a_finding_about_the_case",
        T_CAL,
    ),
    at(
        "calibration: nested names only",
        CALIBRATION,
        "            if not left or not right or not (left < right or right < left):",
        "test_names_that_are_not_nested_make_no_case",
        T_CAL,
    ),
    at(
        "calibration: shown sites only",
        CALIBRATION,
        '            if pair["a"] not in shown or pair["b"] not in shown:',
        "test_a_pair_with_a_retired_member_is_left_out",
        T_CAL,
        nth=0,
    ),
    at(
        "calibration: enough parent pairs",
        CALIBRATION,
        "        if taken < wanted:",
        "test_names_that_are_not_nested_make_no_case",
        T_CAL,
    ),
    at(
        "calibration: a positive parent the gold does not call a part",
        CALIBRATION,
        '        if case.kind == "positive" and verdict != "PART":',
        "test_the_gold_is_checked_against_the_heuristic_classes",
        T_CAL,
    ),
    at(
        "calibration: a negative parent the gold calls a part",
        CALIBRATION,
        '        elif case.kind == "negative" and verdict == "PART":',
        "test_the_gold_is_checked_against_the_heuristic_classes",
        T_CAL,
    ),
    # ------------------------------------------------------------------------- mcode_driver.py
    at(
        "mcode: an identity answer is read as units",
        MCODE,
        "    if identity is not None:",
        "test_a_verdict_answer_is_a_unit_per_site_with_the_survivor_in_it",
        T_CAL,
    ),
    at(
        "mcode: an identity list is the members or the children",
        MCODE,
        "    if key is None:",
        "test_what_is_no_identity_answer_is_not_read_as_one",
        T_CAL,
    ),
    swap(
        "mcode: the target is part of the unit",
        MCODE,
        '        units.append((str(row["site_id"]), f"{verdict}:{target}" if target else str(verdict)))',
        '        units.append((str(row["site_id"]), str(verdict)))',
        "test_a_verdict_answer_is_a_unit_per_site_with_the_survivor_in_it",
        T_CAL,
    ),
    swap(
        "mcode: a quote's source is a cited URL",
        MCODE,
        '                url = (quote.get("url") or quote.get("source")) if isinstance(quote, dict) else None',
        '                url = quote.get("url") if isinstance(quote, dict) else None',
        "test_the_urls_of_the_quotes_are_listed_whatever_they_call_the_key",
        T_CAL,
    ),
]


if __name__ == "__main__":
    # `mutation_sweep_merge.py [label substring ...]` runs the cases whose label holds any of them.
    wanted = [c for c in CASES if not sys.argv[1:] or any(a in c.label for a in sys.argv[1:])]
    if not wanted:
        sys.exit(f"no case label contains any of {sys.argv[1:]}")
    sys.exit(main(wanted))
