"""Mutation sweep for the identity package's questions, plans and lanes (D13, D20, D23).

Every guard of `scripts/remediation/identity/` that refuses an answer, a plan or a command - and of
`mechanical/identity_lanes.py` - is falsified once (`if <condition>:` becomes `if False:`) and the
named test has to go red. The machinery is `mechanical/mutation_sweep.py`'s: a case counts as FIRED
only when its needle occurs exactly once, the mutant compiles, the named test passed on the
unmutated file and is reported FAILED against the mutant - anything else fails the sweep.

The cases were found, not guessed: each guard was falsified in turn and the first test of the
module's test files to fail was named (`test_identity_b_*.py`). A guard no test noticed got its test
first.

Run it from a parent process on a clean committed tree, never from inside a subagent lane (a lane
killed between applying a mutation and restoring it leaves the mutant behind):

    ./.venv/Scripts/python.exe scripts/remediation/identity/mutation_sweep_b.py            # all
    ./.venv/Scripts/python.exe scripts/remediation/identity/mutation_sweep_b.py rounds     # by label

`git status` must be clean afterwards: the sweep restores every file and checks its sha256.
"""

from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve()
for _root in (str(_HERE.parents[3]), str(_HERE.parents[1])):
    if _root not in sys.path:
        sys.path.insert(0, _root)

from mechanical.mutation_sweep import REPO, Case, main  # noqa: E402

IDENTITY = REPO / "scripts/remediation/identity"
ROUNDS = IDENTITY / "rounds.py"
ANSWERS = IDENTITY / "answers.py"
RETARGET = IDENTITY / "retarget.py"
RETARGET_PLAN = IDENTITY / "retarget_plan.py"
NAME_WRITE = IDENTITY / "name_write.py"
WAVES = IDENTITY / "waves.py"
SCOPE_JUDGE = IDENTITY / "scope_judge.py"
NAMES_JUDGE = IDENTITY / "names_judge.py"
PLAN_FILES = IDENTITY / "plan_files.py"
VERIFY = IDENTITY / "verify.py"
CALIBRATION = IDENTITY / "calibration.py"
RUN = IDENTITY / "run.py"
PROMPTS = IDENTITY / "prompts.py"
LANES = REPO / "scripts/remediation/mechanical/identity_lanes.py"

T = "tests/remediation/"
T_ROUNDS = T + "test_identity_b_rounds.py"
T_RUN = T + "test_identity_b_run.py"
T_RETARGET = T + "test_identity_b_retarget.py"
T_SCOPE = T + "test_identity_b_scope.py"
T_NAMES = T + "test_identity_b_names.py"
T_PLAN = T + "test_identity_b_plan.py"
T_FILES = T + "test_identity_b_files.py"
T_LANES = T + "test_identity_b_lanes.py"
T_CALIBRATION = T + "test_identity_b_calibration.py"
T_ANSWERS = T + "test_identity_b_answers.py"

CASES: list[Case] = [
    Case(
        'names_judge: data["site_id"] != ctx["site_id"]',
        NAMES_JUDGE,
        '    data = A.load_object(text, CLEAN_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, CLEAN_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_the_rules_a_rename_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        'names_judge: data["site_id"] != ctx["site_id"] #2',
        NAMES_JUDGE,
        '    data = A.load_object(text, RECHECK_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, RECHECK_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_a_name_re_check_answer_names_this_question_s_site",
        T_NAMES,
    ),
    Case(
        'names_judge: data["site_id"] != ctx["site_id"] #3',
        NAMES_JUDGE,
        '    data = A.load_object(text, SPOKEN_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, SPOKEN_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "retarget_plan: now is None",
        RETARGET_PLAN,
        '        if now is None:\n            skip(sid, "gone", "the site is no longer in unified_sites")',
        '        if False:\n            skip(sid, "gone", "the site is no longer in unified_sites")',
        "test_a_site_whose_state_moved_is_skipped_with_its_reason",
        T_PLAN,
    ),
    Case(
        "retarget_plan: now is None #2",
        RETARGET_PLAN,
        "        if now is None:\n            plan.skipped.append(",
        "        if False:\n            plan.skipped.append(",
        "test_a_site_gone_is_skipped",
        T_PLAN,
    ),
    Case(
        "retarget_plan: now is None #3",
        RETARGET_PLAN,
        '        if now is None:\n            out.append({"site_id": sid, "state": "gone", "deviations": ["the row is gone"]})',
        '        if False:\n            out.append({"site_id": sid, "state": "gone", "deviations": ["the row is gone"]})',
        "test_a_row_that_is_gone_is_a_deviation",
        T_PLAN,
    ),
    Case(
        'scope_judge: data["site_id"] != ctx["site_id"]',
        SCOPE_JUDGE,
        '    data = A.load_object(text, ANSWER_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, ANSWER_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        'scope_judge: data["site_id"] != ctx["site_id"] #2',
        SCOPE_JUDGE,
        '    data = A.load_object(text, RECHECK_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, RECHECK_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_a_re_check_answer_names_this_question_s_site",
        T_SCOPE,
    ),
    Case(
        'identity_lanes: SCOPE_WINDOW_LANE.match(f"scope-window-{wave}") is None',
        LANES,
        '    if SCOPE_WINDOW_LANE.match(f"scope-window-{wave}") is None:\n        raise ValueError(f"{wave!r} is not a wave label like 2026-10-12 or 2026-10-12b")',
        '    if False:\n        raise ValueError(f"{wave!r} is not a wave label like 2026-10-12 or 2026-10-12b")',
        "test_a_bad_wave_label_is_refused_by_every_factory",
        T_LANES,
    ),
    Case(
        'identity_lanes: pattern.match(f"{kind}-{wave}") is None',
        LANES,
        '    if pattern.match(f"{kind}-{wave}") is None:\n        raise ValueError(f"{wave!r} is not a wave label like 2026-10-12 or 2026-10-12b")',
        '    if False:\n        raise ValueError(f"{wave!r} is not a wave label like 2026-10-12 or 2026-10-12b")',
        "test_a_bad_wave_label_is_refused_by_every_factory",
        T_LANES,
    ),
    Case(
        'identity_lanes: SPOKEN_LANE.match(f"spoken-{wave}") is None',
        LANES,
        '    if SPOKEN_LANE.match(f"spoken-{wave}") is None:\n        raise ValueError(f"{wave!r} is not a wave label like 2026-10-12 or 2026-10-12b")',
        '    if False:\n        raise ValueError(f"{wave!r} is not a wave label like 2026-10-12 or 2026-10-12b")',
        "test_a_bad_wave_label_is_refused_by_every_factory",
        T_LANES,
    ),
    Case(
        "answers: not isinstance(value, str) or not value.strip() or value != value.strip()",
        ANSWERS,
        '    if not isinstance(value, str) or not value.strip() or value != value.strip():\n        raise AnswerError(f"{what} is not a trimmed, non-empty string")',
        '    if False:\n        raise AnswerError(f"{what} is not a trimmed, non-empty string")',
        "test_the_envelope_rules",
        T_RETARGET,
    ),
    Case(
        "answers: any(c in CONTROL for c in value)",
        ANSWERS,
        '    if any(c in CONTROL for c in value):\n        raise AnswerError(f"{what} carries a control character")',
        '    if False:\n        raise AnswerError(f"{what} carries a control character")',
        "test_a_text_is_trimmed_non_empty_clean_and_bounded",
        T_ANSWERS,
    ),
    Case(
        "answers: max_chars is not None and len(value) > max_chars",
        ANSWERS,
        '    if max_chars is not None and len(value) > max_chars:\n        raise AnswerError(f"{what} is longer than {max_chars} characters")',
        '    if False:\n        raise AnswerError(f"{what} is longer than {max_chars} characters")',
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        "answers: not isinstance(value, list)",
        ANSWERS,
        '    if not isinstance(value, list):\n        raise AnswerError(f"{what}: quotes is not a list")',
        '    if False:\n        raise AnswerError(f"{what}: quotes is not a list")',
        "test_every_way_a_quote_can_be_malformed",
        T_ANSWERS,
    ),
    Case(
        'answers: not isinstance(q, dict) or set(q) != {"url", "quote"}',
        ANSWERS,
        '        if not isinstance(q, dict) or set(q) != {"url", "quote"}:\n            raise AnswerError(f"{what}: a quote is not {{url, quote}}: {q!r}")',
        '        if False:\n            raise AnswerError(f"{what}: a quote is not {{url, quote}}: {q!r}")',
        "test_every_way_a_quote_can_be_malformed",
        T_ANSWERS,
    ),
    Case(
        'answers: not all(isinstance(q[k], str) and q[k].strip() for k in ("url", "quote"))',
        ANSWERS,
        '        if not all(isinstance(q[k], str) and q[k].strip() for k in ("url", "quote")):\n            raise AnswerError(f"{what}: a quote needs a url and a text")',
        '        if False:\n            raise AnswerError(f"{what}: a quote needs a url and a text")',
        "test_every_way_a_quote_can_be_malformed",
        T_ANSWERS,
    ),
    Case(
        'answers: not Q.is_url(q["url"])',
        ANSWERS,
        '        if not Q.is_url(q["url"]):\n            raise AnswerError(f"{what}: a quote\'s url must be the URL of the page: {q[\'url\']!r}")',
        "        if False:\n            raise AnswerError(f\"{what}: a quote's url must be the URL of the page: {q['url']!r}\")",
        "test_every_way_a_quote_can_be_malformed",
        T_ANSWERS,
    ),
    Case(
        "answers: refused",
        ANSWERS,
        "        if refused:\n            raise AnswerError(f\"{what}: {q['url']} is never fetched here ({refused})\")",
        "        if False:\n            raise AnswerError(f\"{what}: {q['url']} is never fetched here ({refused})\")",
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        "answers: len(out) < minimum",
        ANSWERS,
        '    if len(out) < minimum:\n        raise AnswerError(f"{what}: needs at least {minimum} quote(s), has {len(out)}")',
        '    if False:\n        raise AnswerError(f"{what}: needs at least {minimum} quote(s), has {len(out)}")',
        "test_the_envelope_rules",
        T_RETARGET,
    ),
    Case(
        "calibration: not cases",
        CALIBRATION,
        '    if not cases:\n        raise PoolError("the pool selected no case")',
        '    if False:\n        raise PoolError("the pool selected no case")',
        "test_an_empty_pool_is_refused",
        T_CALIBRATION,
    ),
    Case(
        "calibration: not path.exists()",
        CALIBRATION,
        '    if not path.exists():\n        raise PoolError(f"{path} does not exist: export the pool first")',
        '    if False:\n        raise PoolError(f"{path} does not exist: export the pool first")',
        "test_the_pool_is_the_lane_s_own_questions_and_a_manifest_of_hints",
        T_CALIBRATION,
    ),
    Case(
        "name_write: re.fullmatch(WAVE, wave) is None",
        NAME_WRITE,
        '    if re.fullmatch(WAVE, wave) is None:\n        raise ValueError(f"{wave!r} is not a wave label like 2026-10-12 or 2026-10-12b")',
        '    if False:\n        raise ValueError(f"{wave!r} is not a wave label like 2026-10-12 or 2026-10-12b")',
        "test_a_bad_wave_label_is_refused",
        T_PLAN,
    ),
    Case(
        'name_write: new_name == live["name"]',
        NAME_WRITE,
        '    if new_name == live["name"]:\n        skip("name-unchanged", "the stored name is already the planned name")',
        '    if False:\n        skip("name-unchanged", "the stored name is already the planned name")',
        "test_a_name_that_is_already_the_name_is_not_written",
        T_PLAN,
    ),
    Case(
        'name_write: old_row is None and new_key != live["name_normalized"]',
        NAME_WRITE,
        '    if old_row is None and new_key != live["name_normalized"]:\n        skip(',
        "    if False:\n        skip(",
        "test_a_site_with_no_row_for_its_old_name_is_listed_not_guessed",
        T_PLAN,
    ),
    Case(
        "name_write: len(plan.sites) > SITES_PER_WAVE",
        NAME_WRITE,
        '    if len(plan.sites) > SITES_PER_WAVE:\n        raise MP.PlanError(f"{len(plan.sites)} renames exceed one wave of {SITES_PER_WAVE} sites")',
        '    if False:\n        raise MP.PlanError(f"{len(plan.sites)} renames exceed one wave of {SITES_PER_WAVE} sites")',
        "test_no_alias_no_chunk_and_a_wave_is_at_most_a_hundred_sites",
        T_PLAN,
    ),
    Case(
        'names_judge: data["site_id"] != ctx["site_id"] #4',
        NAMES_JUDGE,
        '    data = A.load_object(text, CLEAN_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, CLEAN_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_the_rules_a_rename_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "names_judge: verdict not in (KEEP, RENAME)",
        NAMES_JUDGE,
        '    if verdict not in (KEEP, RENAME):\n        raise AnswerError(f"verdict {verdict!r} is not KEEP or RENAME")',
        '    if False:\n        raise AnswerError(f"verdict {verdict!r} is not KEEP or RENAME")',
        "test_the_rules_a_rename_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "names_judge: new is not None or attested is not None",
        NAMES_JUDGE,
        '        if new is not None or attested is not None:\n            raise AnswerError("new_name and attested_as are null for KEEP")',
        '        if False:\n            raise AnswerError("new_name and attested_as are null for KEEP")',
        "test_a_keep_carries_no_name",
        T_NAMES,
    ),
    Case(
        'names_judge: new == ctx["name"]',
        NAMES_JUDGE,
        '    if new == ctx["name"]:\n        raise AnswerError("new_name is the stored name - that is KEEP")',
        '    if False:\n        raise AnswerError("new_name is the stored name - that is KEEP")',
        "test_the_rules_a_rename_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "names_judge: attested not in ATTESTED_AS",
        NAMES_JUDGE,
        "    if attested not in ATTESTED_AS:\n        raise AnswerError(f\"attested_as {attested!r} is not one of {', '.join(ATTESTED_AS)}\")",
        "    if False:\n        raise AnswerError(f\"attested_as {attested!r} is not one of {', '.join(ATTESTED_AS)}\")",
        "test_the_rules_a_rename_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        'names_judge: not any(_normal(new) in _normal(q["quote"]) for q in quotes)',
        NAMES_JUDGE,
        '    if not any(_normal(new) in _normal(q["quote"]) for q in quotes):\n        raise AnswerError("a RENAME quotes a page with the new name in the quote")',
        '    if False:\n        raise AnswerError("a RENAME quotes a page with the new name in the quote")',
        "test_the_rules_a_rename_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "names_judge: not counted",
        NAMES_JUDGE,
        '    data["quotes"] = noted\n    if not counted:\n        return Outcome(HELD, f"quotes: a quote does not count ({reason})", data)',
        '    data["quotes"] = noted\n    if False:\n        return Outcome(HELD, f"quotes: a quote does not count ({reason})", data)',
        "test_a_quote_the_page_does_not_hold_holds_the_site",
        T_NAMES,
    ),
    Case(
        "names_judge: problems",
        NAMES_JUDGE,
        "    if problems:\n        return Outcome(HELD, problems[0], data)",
        "    if False:\n        return Outcome(HELD, problems[0], data)",
        "test_an_entity_page_that_is_a_redirect_holds_the_site",
        T_NAMES,
    ),
    Case(
        'names_judge: data["verdict"] not in (CONFIRM, REJECT)',
        NAMES_JUDGE,
        '    if data["verdict"] not in (CONFIRM, REJECT):\n        raise AnswerError(f"verdict {data[\'verdict\']!r} is not CONFIRM or REJECT")',
        "    if False:\n        raise AnswerError(f\"verdict {data['verdict']!r} is not CONFIRM or REJECT\")",
        "test_a_confirmation_quotes_a_page_that_holds_the_new_name",
        T_NAMES,
    ),
    Case(
        "names_judge: not counted #2",
        NAMES_JUDGE,
        '    }\n    if not counted:\n        return Outcome(HELD, f"quotes: a quote does not count ({reason})", data)',
        '    }\n    if False:\n        return Outcome(HELD, f"quotes: a quote does not count ({reason})", data)',
        "test_a_confirmation_quotes_a_page_that_holds_the_new_name",
        T_NAMES,
    ),
    Case(
        'names_judge: decision["status"] != DECIDED',
        NAMES_JUDGE,
        '            if decision["status"] != DECIDED:\n                out.append({"site_id": sid, "source": MODEL, "state": "held"})',
        '            if False:\n                out.append({"site_id": sid, "source": MODEL, "state": "held"})',
        "test_the_final_state_of_a_model_made_and_a_rule_made_rename",
        T_NAMES,
    ),
    Case(
        'names_judge: decision["data"]["verdict"] == KEEP',
        NAMES_JUDGE,
        '            if decision["data"]["verdict"] == KEEP:\n                out.append({"site_id": sid, "source": MODEL, "state": "keep"})',
        '            if False:\n                out.append({"site_id": sid, "source": MODEL, "state": "keep"})',
        "test_the_final_state_of_a_model_made_and_a_rule_made_rename",
        T_NAMES,
    ),
    Case(
        "names_judge: now is None",
        NAMES_JUDGE,
        '        def skip(reason: str, note: str, _sid: str = sid, _name: str = ctx["name"]) -> None:\n            plan.skipped.append({"site_id": _sid, "name": _name, "reason": reason, "note": note})\n\n        if now is None:\n            skip("gone", "the site is no longer in unified_sites")',
        '        def skip(reason: str, note: str, _sid: str = sid, _name: str = ctx["name"]) -> None:\n            plan.skipped.append({"site_id": _sid, "name": _name, "reason": reason, "note": note})\n\n        if False:\n            skip("gone", "the site is no longer in unified_sites")',
        "test_a_site_gone_or_a_name_already_borne_is_skipped",
        T_NAMES,
    ),
    Case(
        'names_judge: now["source_id"] != "ancient_nerds" or now["scope_status"] == "retired"',
        NAMES_JUDGE,
        '        if now["source_id"] != "ancient_nerds" or now["scope_status"] == "retired":\n            skip("not-live", f"{now[\'source_id\']} row, scope {now[\'scope_status\']!r}")',
        "        if False:\n            skip(\"not-live\", f\"{now['source_id']} row, scope {now['scope_status']!r}\")",
        "test_a_site_that_moved_is_skipped",
        T_NAMES,
    ),
    Case(
        "names_judge: moved",
        NAMES_JUDGE,
        '        if moved:\n            skip("changed-since-the-question", "; ".join(moved))',
        '        if False:\n            skip("changed-since-the-question", "; ".join(moved))',
        "test_a_site_that_moved_is_skipped",
        T_NAMES,
    ),
    Case(
        'names_judge: unicodedata.category(ch) == "Lm"',
        NAMES_JUDGE,
        '            if unicodedata.category(ch) == "Lm":\n                problems.append(f"modifier letter {ch!r} ({unicodedata.name(ch, \'?\')})")',
        "            if False:\n                problems.append(f\"modifier letter {ch!r} ({unicodedata.name(ch, '?')})\")",
        "test_a_spoken_name_a_voice_cannot_read_is_refused",
        T_NAMES,
    ),
    Case(
        "names_judge: not names_triage.is_latin(ch)",
        NAMES_JUDGE,
        '            elif not names_triage.is_latin(ch):\n                problems.append(f"letter {ch!r} of another script")',
        '            elif False:\n                problems.append(f"letter {ch!r} of another script")',
        "test_a_spoken_name_a_voice_cannot_read_is_refused",
        T_NAMES,
    ),
    Case(
        "names_judge: ch.isdigit()",
        NAMES_JUDGE,
        '        elif ch.isdigit():\n            problems.append("a digit")',
        '        elif False:\n            problems.append("a digit")',
        "test_a_spoken_name_a_voice_cannot_read_is_refused",
        T_NAMES,
    ),
    Case(
        "names_judge: ch not in SPOKEN_PUNCTUATION",
        NAMES_JUDGE,
        '        elif ch not in SPOKEN_PUNCTUATION:\n            problems.append(f"character {ch!r}")',
        '        elif False:\n            problems.append(f"character {ch!r}")',
        "test_a_spoken_name_a_voice_cannot_read_is_refused",
        T_NAMES,
    ),
    Case(
        'names_judge: data["site_id"] != ctx["site_id"] #5',
        NAMES_JUDGE,
        '    data = A.load_object(text, SPOKEN_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, SPOKEN_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "names_judge: verdict not in (SPEAK, NONE)",
        NAMES_JUDGE,
        '    if verdict not in (SPEAK, NONE):\n        raise AnswerError(f"verdict {verdict!r} is not SPEAK or NONE")',
        '    if False:\n        raise AnswerError(f"verdict {verdict!r} is not SPEAK or NONE")',
        "test_every_rule_an_answer_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        'names_judge: data["spoken"] is not None or data["from_form"] is not None',
        NAMES_JUDGE,
        '        if data["spoken"] is not None or data["from_form"] is not None:\n            raise AnswerError("spoken and from_form are null for NONE")',
        '        if False:\n            raise AnswerError("spoken and from_form are null for NONE")',
        "test_none_carries_no_name",
        T_NAMES,
    ),
    Case(
        'names_judge: form not in ctx["attested"]',
        NAMES_JUDGE,
        '    if form not in ctx["attested"]:\n        raise AnswerError(f"from_form {form!r} is none of the attested forms {ctx[\'attested\']}")',
        "    if False:\n        raise AnswerError(f\"from_form {form!r} is none of the attested forms {ctx['attested']}\")",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "names_judge: _fold(spoken) != _fold(form) and not _leaves_out_only_kinds(form, spoken)",
        NAMES_JUDGE,
        "    if _fold(spoken) != _fold(form) and not _leaves_out_only_kinds(form, spoken):\n        raise AnswerError(",
        "    if False:\n        raise AnswerError(",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "names_judge: problems #2",
        NAMES_JUDGE,
        "    if problems:\n        raise AnswerError(f\"spoken {spoken!r} is not TTS-safe: {'; '.join(problems)}\")",
        "    if False:\n        raise AnswerError(f\"spoken {spoken!r} is not TTS-safe: {'; '.join(problems)}\")",
        "test_the_machine_refuses_a_respelling_a_voice_cannot_read",
        T_NAMES,
    ),
    Case(
        'names_judge: spoken == ctx["name"]',
        NAMES_JUDGE,
        '    if spoken == ctx["name"]:\n        raise AnswerError("spoken is the stored name - that is NONE")',
        '    if False:\n        raise AnswerError("spoken is the stored name - that is NONE")',
        "test_every_rule_an_answer_can_break_on_its_own",
        T_NAMES,
    ),
    Case(
        "names_judge: now is None #2",
        NAMES_JUDGE,
        '        def skip(reason: str, note: str, _sid: str = sid, _name: str = row["name"]) -> None:\n            plan.skipped.append({"site_id": _sid, "name": _name, "reason": reason, "note": note})\n\n        if now is None:\n            skip("gone", "the site is no longer in unified_sites")',
        '        def skip(reason: str, note: str, _sid: str = sid, _name: str = row["name"]) -> None:\n            plan.skipped.append({"site_id": _sid, "name": _name, "reason": reason, "note": note})\n\n        if False:\n            skip("gone", "the site is no longer in unified_sites")',
        "test_a_site_that_moved_or_is_set_is_skipped",
        T_NAMES,
    ),
    Case(
        'names_judge: now["source_id"] != "ancient_nerds" or now["scope_status"] == "retired" #2',
        NAMES_JUDGE,
        '        elif now["source_id"] != "ancient_nerds" or now["scope_status"] == "retired":\n            skip("not-live", f"{now[\'source_id\']} row, scope {now[\'scope_status\']!r}")',
        "        elif False:\n            skip(\"not-live\", f\"{now['source_id']} row, scope {now['scope_status']!r}\")",
        "test_a_site_that_moved_or_is_set_is_skipped",
        T_NAMES,
    ),
    Case(
        'names_judge: now["name"] != row["name"]',
        NAMES_JUDGE,
        '        elif now["name"] != row["name"]:\n            skip(',
        "        elif False:\n            skip(",
        "test_a_site_that_moved_or_is_set_is_skipped",
        T_NAMES,
    ),
    Case(
        'names_judge: now["spoken_name"] is not None',
        NAMES_JUDGE,
        '        elif now["spoken_name"] is not None:\n            skip("already-set", f"spoken_name is {now[\'spoken_name\']!r}")',
        '        elif False:\n            skip("already-set", f"spoken_name is {now[\'spoken_name\']!r}")',
        "test_a_site_that_moved_or_is_set_is_skipped",
        T_NAMES,
    ),
    Case(
        'names_judge: row["spoken"] == now["name"]',
        NAMES_JUDGE,
        '        elif row["spoken"] == now["name"]:\n            skip("same-as-name", "the spoken name is the stored name")',
        '        elif False:\n            skip("same-as-name", "the spoken name is the stored name")',
        "test_a_spoken_name_equal_to_the_name_is_not_written",
        T_NAMES,
    ),
    Case(
        "names_judge: len(plan.sites) > SITES_PER_WAVE",
        NAMES_JUDGE,
        '    if len(plan.sites) > SITES_PER_WAVE:\n        raise MP.PlanError(f"{len(plan.sites)} sites exceed one wave of {SITES_PER_WAVE}")',
        '    if False:\n        raise MP.PlanError(f"{len(plan.sites)} sites exceed one wave of {SITES_PER_WAVE}")',
        "test_the_plan_is_a_cell_lane_plan_of_at_most_a_hundred_sites",
        T_NAMES,
    ),
    Case(
        'plan_files: (out / "APPLY.sql").exists()',
        PLAN_FILES,
        '    if (out / "APPLY.sql").exists():\n        raise MP.PlanError(',
        "    if False:\n        raise MP.PlanError(",
        "test_a_plan_whose_statement_was_emitted_is_never_planned_again",
        T_FILES,
    ),
    Case(
        "prompts: not index.exists()",
        PROMPTS,
        "    if not index.exists():\n        raise common.IdentityError(",
        "    if False:\n        raise common.IdentityError(",
        "test_the_cache_index_gives_absolute_paths_per_site",
        T_RETARGET,
    ),
    Case(
        "retarget: unknown",
        RETARGET,
        '    if unknown:\n        raise common.IdentityError(f"{len(unknown)} site(s) are not in the funnel: {unknown[:3]}")',
        '    if False:\n        raise common.IdentityError(f"{len(unknown)} site(s) are not in the funnel: {unknown[:3]}")',
        "test_the_questions_are_the_funnel_records_and_an_unknown_site_is_refused",
        T_RETARGET,
    ),
    Case(
        "retarget: count < 1 or count > len(questions)",
        RETARGET,
        '    if count < 1 or count > len(questions):\n        raise common.IdentityError(f"a pilot of {count} sites from {len(questions)} questions")',
        '    if False:\n        raise common.IdentityError(f"a pilot of {count} sites from {len(questions)} questions")',
        "test_the_pilot_is_spread_over_the_funnel_order",
        T_RETARGET,
    ),
    Case(
        "retarget: isinstance(value, bool) or not isinstance(value, int | float) or not low <= valu",
        RETARGET,
        '    if isinstance(value, bool) or not isinstance(value, int | float) or not low <= value <= high:\n        raise AnswerError(f"{what} is not a number in [{low}, {high}]")',
        '    if False:\n        raise AnswerError(f"{what} is not a number in [{low}, {high}]")',
        "test_the_coordinates_are_numbers_with_a_quote",
        T_RETARGET,
    ),
    Case(
        "retarget: not QID_RE.fullmatch(qid.value)",
        RETARGET,
        '    if not QID_RE.fullmatch(qid.value):\n        raise AnswerError(f"target.qid: {qid.value!r} is not an item id")',
        '    if False:\n        raise AnswerError(f"target.qid: {qid.value!r} is not an item id")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        'retarget: qid.value in ctx["qids"]',
        RETARGET,
        '    if qid.value in ctx["qids"]:\n        raise AnswerError(f"target.qid: {qid.value} is the record\'s own item - that is KEEP")',
        '    if False:\n        raise AnswerError(f"target.qid: {qid.value} is the record\'s own item - that is KEEP")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        "retarget: not A.cites(qid.quotes, ENTITY_DATA.format(qid.value))",
        RETARGET,
        '    if not A.cites(qid.quotes, ENTITY_DATA.format(qid.value)):\n        raise AnswerError(f"target.qid: a quote cites {ENTITY_DATA.format(qid.value)}")',
        '    if False:\n        raise AnswerError(f"target.qid: a quote cites {ENTITY_DATA.format(qid.value)}")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        'retarget: CONTROL_RE.search(title.value) or "#" in title.value or "|" in title.value',
        RETARGET,
        '    if CONTROL_RE.search(title.value) or "#" in title.value or "|" in title.value:\n        raise AnswerError(f"target.enwiki_title: {title.value!r} is not an article title")',
        '    if False:\n        raise AnswerError(f"target.enwiki_title: {title.value!r} is not an article title")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        'retarget: title.value in ctx["enwiki"]',
        RETARGET,
        '    if title.value in ctx["enwiki"]:\n        raise AnswerError(f"target.enwiki_title: {title.value!r} is the record\'s own article")',
        '    if False:\n        raise AnswerError(f"target.enwiki_title: {title.value!r} is the record\'s own article")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        'retarget: not any(enwiki_title_from_url(q["url"]) == title.value for q in title.quotes)',
        RETARGET,
        '    if not any(enwiki_title_from_url(q["url"]) == title.value for q in title.quotes):\n        raise AnswerError(f"target.enwiki_title: a quote cites {article_url(title.value)}")',
        '    if False:\n        raise AnswerError(f"target.enwiki_title: a quote cites {article_url(title.value)}")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        "retarget: len(name.value) > NAME_CHARS",
        RETARGET,
        '    if len(name.value) > NAME_CHARS:\n        raise AnswerError(f"target.name: longer than {NAME_CHARS} characters")',
        '    if False:\n        raise AnswerError(f"target.name: longer than {NAME_CHARS} characters")',
        "test_a_name_longer_than_a_name_column_is_refused",
        T_RETARGET,
    ),
    Case(
        'retarget: not any(_normal(name.value) in _normal(q["quote"]) for q in name.quotes)',
        RETARGET,
        '    if not any(_normal(name.value) in _normal(q["quote"]) for q in name.quotes):\n        raise AnswerError("target.name: a quote holds the name word for word")',
        '    if False:\n        raise AnswerError("target.name: a quote holds the name word for word")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        'retarget: url.value == ctx["source_url"]',
        RETARGET,
        '    if url.value == ctx["source_url"]:\n        raise AnswerError("target.source_url: it is the record\'s current source_url")',
        '    if False:\n        raise AnswerError("target.source_url: it is the record\'s current source_url")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        "retarget: not A.cites(url.quotes, url.value)",
        RETARGET,
        '    if not A.cites(url.quotes, url.value):\n        raise AnswerError("target.source_url: a quote cites the page given")',
        '    if False:\n        raise AnswerError("target.source_url: a quote cites the page given")',
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        "retarget: url.value.startswith(ENWIKI) and enwiki_title_from_url(url.value) != title.value",
        RETARGET,
        "    if url.value.startswith(ENWIKI) and enwiki_title_from_url(url.value) != title.value:\n        raise AnswerError(",
        "    if False:\n        raise AnswerError(",
        "test_every_cell_rule_an_answer_can_break_on_its_own",
        T_RETARGET,
    ),
    Case(
        'retarget: data["site_id"] != ctx["site_id"]',
        RETARGET,
        '    data = A.load_object(text, ANSWER_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, ANSWER_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_the_envelope_rules",
        T_RETARGET,
    ),
    Case(
        "retarget: verdict not in VERDICTS",
        RETARGET,
        "    if verdict not in VERDICTS:\n        raise AnswerError(f\"verdict {verdict!r} is not one of {', '.join(VERDICTS)}\")",
        "    if False:\n        raise AnswerError(f\"verdict {verdict!r} is not one of {', '.join(VERDICTS)}\")",
        "test_the_envelope_rules",
        T_RETARGET,
    ),
    Case(
        'retarget: data["merge_with"] is not None',
        RETARGET,
        '        if data["merge_with"] is not None:\n            raise AnswerError("merge_with is null unless the verdict is MERGE")',
        '        if False:\n            raise AnswerError("merge_with is null unless the verdict is MERGE")',
        "test_the_envelope_rules",
        T_RETARGET,
    ),
    Case(
        'retarget: data["target"] is not None',
        RETARGET,
        '        if data["target"] is not None:\n            raise AnswerError("target is null unless the verdict is RETARGET")',
        '        if False:\n            raise AnswerError("target is null unless the verdict is RETARGET")',
        "test_only_a_retarget_carries_a_target",
        T_RETARGET,
    ),
    Case(
        "retarget: merge not in allowed",
        RETARGET,
        '            if merge not in allowed:\n                raise AnswerError(f"merge_with {merge!r} is none of the candidates {allowed}")',
        '            if False:\n                raise AnswerError(f"merge_with {merge!r} is none of the candidates {allowed}")',
        "test_a_merge_names_one_of_the_candidates",
        T_RETARGET,
    ),
    Case(
        'retarget: data["merge_with"] is not None #2',
        RETARGET,
        '        elif data["merge_with"] is not None:\n            raise AnswerError("merge_with is null unless the verdict is MERGE")',
        '        elif False:\n            raise AnswerError("merge_with is null unless the verdict is MERGE")',
        "test_only_a_merge_names_a_record_to_merge_with",
        T_RETARGET,
    ),
    Case(
        "retarget: not counted",
        RETARGET,
        '    if not counted:\n        raise Hold(f"{key}: a quote does not count ({reason})")',
        '    if False:\n        raise Hold(f"{key}: a quote does not count ({reason})")',
        "test_a_quote_the_page_does_not_hold_holds_the_site",
        T_RETARGET,
    ),
    Case(
        "retarget: moved > MAX_MOVE_M",
        RETARGET,
        "    if moved > MAX_MOVE_M:\n        raise Hold(",
        "    if False:\n        raise Hold(",
        "test_a_target_far_from_the_stored_point_is_a_coordinate_question",
        T_RETARGET,
    ),
    Case(
        'retarget: data["site_id"] != ctx["site_id"] #2',
        RETARGET,
        '    data = A.load_object(text, RECHECK_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, RECHECK_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_the_answer_confirms_with_a_quote_or_rejects_with_a_reason",
        T_RETARGET,
    ),
    Case(
        'retarget: data["verdict"] not in RECHECK_VERDICTS',
        RETARGET,
        '    if data["verdict"] not in RECHECK_VERDICTS:\n        raise AnswerError(f"verdict {data[\'verdict\']!r} is not CONFIRM or REJECT")',
        "    if False:\n        raise AnswerError(f\"verdict {data['verdict']!r} is not CONFIRM or REJECT\")",
        "test_the_answer_confirms_with_a_quote_or_rejects_with_a_reason",
        T_RETARGET,
    ),
    Case(
        "retarget_plan: not 1 <= number <= 999",
        RETARGET_PLAN,
        '        if not 1 <= number <= 999:\n            raise MP.PlanError(f"step {number} is not a step number")',
        '        if False:\n            raise MP.PlanError(f"step {number} is not a step number")',
        "test_a_step_number_is_one_to_nine_ninety_nine",
        T_PLAN,
    ),
    Case(
        'retarget_plan: decision["status"] != DECIDED',
        RETARGET_PLAN,
        '        if decision["status"] != DECIDED:\n            raise MP.PlanError(f"{sid} is not decided - DECISIONS.jsonl is stale")',
        '        if False:\n            raise MP.PlanError(f"{sid} is not decided - DECISIONS.jsonl is stale")',
        "test_an_undecided_site_stops_the_plan",
        T_PLAN,
    ),
    Case(
        "retarget_plan: now is None #4",
        RETARGET_PLAN,
        '        if now is None:\n            skip(sid, "gone", "the site is no longer in unified_sites")',
        '        if False:\n            skip(sid, "gone", "the site is no longer in unified_sites")',
        "test_a_site_whose_state_moved_is_skipped_with_its_reason",
        T_PLAN,
    ),
    Case(
        'retarget_plan: now["source_id"] != "ancient_nerds"',
        RETARGET_PLAN,
        '        if now["source_id"] != "ancient_nerds":\n            skip(sid, "not-curated", f"a {now[\'source_id\']} row")',
        '        if False:\n            skip(sid, "not-curated", f"a {now[\'source_id\']} row")',
        "test_a_site_whose_state_moved_is_skipped_with_its_reason",
        T_PLAN,
    ),
    Case(
        'retarget_plan: now["scope_status"] == "retired"',
        RETARGET_PLAN,
        '        if now["scope_status"] == "retired":\n            skip(sid, "retired", "hidden everywhere: nothing of it is written")',
        '        if False:\n            skip(sid, "retired", "hidden everywhere: nothing of it is written")',
        "test_a_site_whose_state_moved_is_skipped_with_its_reason",
        T_PLAN,
    ),
    Case(
        "retarget_plan: moved",
        RETARGET_PLAN,
        '        if moved:\n            skip(sid, "changed-since-the-question", "; ".join(moved))',
        '        if False:\n            skip(sid, "changed-since-the-question", "; ".join(moved))',
        "test_a_site_whose_state_moved_is_skipped_with_its_reason",
        T_PLAN,
    ),
    Case(
        "retarget_plan: any(len(v) > 1 for v in links.values())",
        RETARGET_PLAN,
        '        if any(len(v) > 1 for v in links.values()):\n            skip(sid, "links-not-one-each", f"stored links {links}: one row of a kind at most")',
        '        if False:\n            skip(sid, "links-not-one-each", f"stored links {links}: one row of a kind at most")',
        "test_a_site_with_two_items_is_not_a_link_the_step_can_express",
        T_PLAN,
    ),
    Case(
        "retarget_plan: twins",
        RETARGET_PLAN,
        "        if twins:\n            skip(",
        "        if False:\n            skip(",
        "test_two_sites_of_a_wave_are_not_given_one_item",
        T_PLAN,
    ),
    Case(
        "retarget_plan: now is None #5",
        RETARGET_PLAN,
        "        if now is None:\n            plan.skipped.append(",
        "        if False:\n            plan.skipped.append(",
        "test_a_site_gone_is_skipped",
        T_PLAN,
    ),
    Case(
        "retarget_plan: not landed",
        RETARGET_PLAN,
        "        if not landed:\n            plan.skipped.append(",
        "        if False:\n            plan.skipped.append(",
        "test_a_site_whose_links_have_not_landed_waits_for_its_link_step",
        T_PLAN,
    ),
    Case(
        "retarget_plan: sid in skipped",
        RETARGET_PLAN,
        '        if sid in skipped:\n            out.append({"site_id": sid, "state": "skipped", "why": skipped[sid], "deviations": []})',
        '        if False:\n            out.append({"site_id": sid, "state": "skipped", "why": skipped[sid], "deviations": []})',
        "test_a_site_a_plan_skipped_is_reported_as_skipped_not_as_a_deviation",
        T_PLAN,
    ),
    Case(
        "retarget_plan: stage not in CHAIN",
        RETARGET_PLAN,
        '    earlier stages are not all done: one site finishes the chain in order."""\n    if stage not in CHAIN:\n        raise ChainError(f"{stage!r} is not a stage of the chain {CHAIN}")',
        '    earlier stages are not all done: one site finishes the chain in order."""\n    if False:\n        raise ChainError(f"{stage!r} is not a stage of the chain {CHAIN}")',
        "test_a_stage_cannot_be_recorded_out_of_order_twice_or_for_a_stranger",
        T_PLAN,
    ),
    Case(
        "retarget_plan: not stamp.strip()",
        RETARGET_PLAN,
        '    if not stamp.strip():\n        raise ChainError("a stage is recorded with the run stamp that wrote it")',
        '    if False:\n        raise ChainError("a stage is recorded with the run stamp that wrote it")',
        "test_a_stage_cannot_be_recorded_out_of_order_twice_or_for_a_stranger",
        T_PLAN,
    ),
    Case(
        "retarget_plan: stranger",
        RETARGET_PLAN,
        '    if stranger:\n        raise ChainError(f"{stranger[:3]} are not sites of wave {wave}")',
        '    if False:\n        raise ChainError(f"{stranger[:3]} are not sites of wave {wave}")',
        "test_a_stage_cannot_be_recorded_out_of_order_twice_or_for_a_stranger",
        T_PLAN,
    ),
    Case(
        "retarget_plan: stage in done",
        RETARGET_PLAN,
        "        if stage in done:\n            raise ChainError(f\"{sid}: {stage} is recorded already ({done[stage]['stamp']})\")",
        "        if False:\n            raise ChainError(f\"{sid}: {stage} is recorded already ({done[stage]['stamp']})\")",
        "test_a_stage_cannot_be_recorded_out_of_order_twice_or_for_a_stranger",
        T_PLAN,
    ),
    Case(
        "retarget_plan: missing",
        RETARGET_PLAN,
        "        if missing:\n            raise ChainError(f\"{sid}: {stage} waits for {', '.join(missing)}\")",
        "        if False:\n            raise ChainError(f\"{sid}: {stage} waits for {', '.join(missing)}\")",
        "test_a_stage_cannot_be_recorded_out_of_order_twice_or_for_a_stranger",
        T_PLAN,
    ),
    Case(
        "retarget_plan: stage not in CHAIN #2",
        RETARGET_PLAN,
        '    """The sites `stage` may start on: every earlier stage done, `stage` not."""\n    if stage not in CHAIN:\n        raise ChainError(f"{stage!r} is not a stage of the chain {CHAIN}")',
        '    """The sites `stage` may start on: every earlier stage done, `stage` not."""\n    if False:\n        raise ChainError(f"{stage!r} is not a stage of the chain {CHAIN}")',
        "test_a_stage_cannot_be_recorded_out_of_order_twice_or_for_a_stranger",
        T_PLAN,
    ),
    Case(
        "rounds: path.exists()",
        ROUNDS,
        '    if path.exists():\n        raise RoundError(f"{path} exists: a round file is written once")',
        '    if False:\n        raise RoundError(f"{path} exists: a round file is written once")',
        "test_a_round_file_is_written_once",
        T_ROUNDS,
    ),
    Case(
        "rounds: not imported(out, rounds[-1].name)",
        ROUNDS,
        "    if not imported(out, rounds[-1].name):\n        raise RoundError(",
        "    if False:\n        raise RoundError(",
        "test_only_the_newest_round_is_imported_and_a_re_ask_waits_for_the_import",
        T_ROUNDS,
    ),
    Case(
        "rounds: not rounds",
        ROUNDS,
        '    if not rounds:\n        raise RoundError(f"no round is exported yet - {doing} reads the imported answers")',
        '    if False:\n        raise RoundError(f"no round is exported yet - {doing} reads the imported answers")',
        "test_a_re_ask_before_any_round_is_refused",
        T_ROUNDS,
    ),
    Case(
        "rounds: len(rounds) >= MAX_ROUNDS",
        ROUNDS,
        "    if len(rounds) >= MAX_ROUNDS:\n        raise RoundError(",
        "    if False:\n        raise RoundError(",
        "test_only_the_newest_round_is_imported_and_a_re_ask_waits_for_the_import",
        T_ROUNDS,
    ),
    Case(
        "rounds: per_batch < 1",
        ROUNDS,
        '    if per_batch < 1:\n        raise RoundError("a batch holds at least one question")',
        '    if False:\n        raise RoundError("a batch holds at least one question")',
        "test_batches_are_in_site_order_and_bounded",
        T_ROUNDS,
    ),
    Case(
        "rounds: not path.exists()",
        ROUNDS,
        '    if not path.exists():\n        raise RoundError(f"{path} does not exist - the round\'s contexts were never stored")',
        '    if False:\n        raise RoundError(f"{path} does not exist - the round\'s contexts were never stored")',
        "test_a_round_whose_stored_contexts_are_gone_cannot_be_checked",
        T_ROUNDS,
    ),
    Case(
        "rounds: not questions",
        ROUNDS,
        '    if not questions:\n        raise RoundError("no question to ask - nothing to export")',
        '    if False:\n        raise RoundError("no question to ask - nothing to export")',
        "test_a_used_directory_and_a_site_asked_twice_are_refused",
        T_ROUNDS,
    ),
    Case(
        "rounds: len(set(ids)) != len(ids)",
        ROUNDS,
        '    if len(set(ids)) != len(ids):\n        raise RoundError("a site is asked twice in one round")',
        '    if False:\n        raise RoundError("a site is asked twice in one round")',
        "test_a_used_directory_and_a_site_asked_twice_are_refused",
        T_ROUNDS,
    ),
    Case(
        "rounds: handoff.exists() and any(handoff.iterdir())",
        ROUNDS,
        '    if handoff.exists() and any(handoff.iterdir()):\n        raise RoundError(f"{handoff} is not empty: a round is exported into a new directory")',
        '    if False:\n        raise RoundError(f"{handoff} is not empty: a round is exported into a new directory")',
        "test_a_used_directory_and_a_site_asked_twice_are_refused",
        T_ROUNDS,
    ),
    Case(
        "rounds: number == 1 and earlier",
        ROUNDS,
        '    if number == 1 and earlier:\n        raise RoundError("round 1 re-asks nothing")',
        '    if False:\n        raise RoundError("round 1 re-asks nothing")',
        "test_a_re_ask_asks_exactly_the_held_sites",
        T_ROUNDS,
    ),
    Case(
        "rounds: set(earlier) != set(ids) or not set(ids) <= set(held_sites(out))",
        ROUNDS,
        '        if set(earlier) != set(ids) or not set(ids) <= set(held_sites(out)):\n            raise RoundError("a re-ask round asks exactly the held sites, each with its reason")',
        '        if False:\n            raise RoundError("a re-ask round asks exactly the held sites, each with its reason")',
        "test_a_re_ask_asks_exactly_the_held_sites",
        T_ROUNDS,
    ),
    Case(
        "rounds: number > MAX_ROUNDS",
        ROUNDS,
        '        if number > MAX_ROUNDS:\n            raise RoundError(f"{len(known)} rounds are out: at most {MAX_ROUNDS}")',
        '        if False:\n            raise RoundError(f"{len(known)} rounds are out: at most {MAX_ROUNDS}")',
        "test_a_fourth_round_is_never_exported",
        T_ROUNDS,
    ),
    Case(
        "rounds: batch_id not in record.batches",
        ROUNDS,
        '    if batch_id not in record.batches:\n        raise RoundError(f"{batch_id} is no batch of round {round_name}")',
        '    if False:\n        raise RoundError(f"{batch_id} is no batch of round {round_name}")',
        "test_the_brief_names_the_role_its_model_and_the_exact_commands",
        T_ROUNDS,
    ),
    Case(
        "rounds: label not in record.batches.get(batch_id, [])",
        ROUNDS,
        '    if label not in record.batches.get(batch_id, []):\n        raise RoundError(f"{batch_id}/{label} is no question of round {round_name}")',
        '    if False:\n        raise RoundError(f"{batch_id}/{label} is no question of round {round_name}")',
        "test_check_answer_returns_the_shape_problem_or_none",
        T_ROUNDS,
    ),
    Case(
        "rounds: not verdict_path.exists()",
        ROUNDS,
        "    if not verdict_path.exists():\n        raise RoundError(",
        "    if False:\n        raise RoundError(",
        "test_no_verdict_a_failed_verdict_and_another_role_close_it",
        T_ROUNDS,
    ),
    Case(
        'rounds: not verdict["passed"]',
        ROUNDS,
        '    if not verdict["passed"]:\n        raise RoundError(f"calibration {calibration_id} did not pass: {verdict.get(\'tier_move\')}")',
        "    if False:\n        raise RoundError(f\"calibration {calibration_id} did not pass: {verdict.get('tier_move')}\")",
        "test_no_verdict_a_failed_verdict_and_another_role_close_it",
        T_ROUNDS,
    ),
    Case(
        'rounds: verdict["role"] != role',
        ROUNDS,
        '    if verdict["role"] != role:\n        raise RoundError(',
        "    if False:\n        raise RoundError(",
        "test_no_verdict_a_failed_verdict_and_another_role_close_it",
        T_ROUNDS,
    ),
    Case(
        'rounds: verdict["model"] != registered.model',
        ROUNDS,
        '    if verdict["model"] != registered.model:\n        raise RoundError(',
        "    if False:\n        raise RoundError(",
        "test_a_verdict_of_another_model_or_under_another_registry_entry_is_stale",
        T_ROUNDS,
    ),
    Case(
        'rounds: seal is None or seal["role_sha256"] != RO.role_sha256(role)',
        ROUNDS,
        '    if seal is None or seal["role_sha256"] != RO.role_sha256(role):\n        raise RoundError(',
        "    if False:\n        raise RoundError(",
        "test_a_verdict_of_another_model_or_under_another_registry_entry_is_stale",
        T_ROUNDS,
    ),
    Case(
        "rounds: named != spec.role",
        ROUNDS,
        "        if named != spec.role:\n            problems.append(",
        "        if False:\n            problems.append(",
        "test_an_answer_under_no_role_is_refused",
        T_ROUNDS,
    ),
    Case(
        "rounds: why is not None",
        ROUNDS,
        '        if why is not None:\n            problems.append(f"{sid}: {why}")',
        '        if False:\n            problems.append(f"{sid}: {why}")',
        "test_an_answer_stamped_by_another_model_than_the_role_s_is_refused",
        T_ROUNDS,
    ),
    Case(
        "rounds: record.name != newest",
        ROUNDS,
        "    if record.name != newest:\n        raise RoundError(",
        "    if False:\n        raise RoundError(",
        "test_only_the_newest_round_is_imported_and_a_re_ask_waits_for_the_import",
        T_ROUNDS,
    ),
    Case(
        "rounds: imported(out, round_name)",
        ROUNDS,
        '    if imported(out, round_name):\n        raise RoundError(f"round {round_name} is imported already")',
        '    if False:\n        raise RoundError(f"round {round_name} is imported already")',
        "test_decided_and_held_answers_are_merged_by_site",
        T_ROUNDS,
    ),
    Case(
        "rounds: not check.ok",
        ROUNDS,
        "    if not check.ok:\n        raise RoundError(",
        "    if False:\n        raise RoundError(",
        "test_an_unanswered_round_does_not_validate",
        T_ROUNDS,
    ),
    Case(
        "rounds: problems",
        ROUNDS,
        "    if problems:\n        raise RoundError(",
        "    if False:\n        raise RoundError(",
        "test_an_answer_under_no_role_is_refused",
        T_ROUNDS,
    ),
    Case(
        "rounds: missing",
        ROUNDS,
        '    if missing:\n        raise RoundError(f"{len(missing)} title(s) came back unresolved: {missing[:3]}")',
        '    if False:\n        raise RoundError(f"{len(missing)} title(s) came back unresolved: {missing[:3]}")',
        "test_a_title_the_resolver_does_not_answer_stops_the_import",
        T_ROUNDS,
    ),
    Case(
        "run: not path.exists()",
        RUN,
        '    if not path.exists():\n        raise UsageError(f"{path} does not exist: run `--lane retarget result` first")',
        '    if False:\n        raise UsageError(f"{path} does not exist: run `--lane retarget result` first")',
        "test_the_clean_name_export_can_leave_out_the_records_d13_has_not_left_alone",
        T_RUN,
    ),
    Case(
        "run: unknown",
        RUN,
        "        if unknown:\n            raise UsageError(",
        "        if False:\n            raise UsageError(",
        "test_a_sites_file_and_a_pilot_choose_the_questions",
        T_RUN,
    ),
    Case(
        "run: R.load_rounds(out)",
        RUN,
        '        if R.load_rounds(out):\n            raise UsageError("round 1 is exported already - re-ask with export-reask")',
        '        if False:\n            raise UsageError("round 1 is exported already - re-ask with export-reask")',
        "test_a_question_stage_a_calibration_gate_a_wave_a_plan_and_a_read_back",
        T_RUN,
    ),
    Case(
        "run: not ready",
        RUN,
        '        if not ready:\n            raise UsageError("no site of this wave has finished links, name and alias yet")',
        '        if False:\n            raise UsageError("no site of this wave has finished links, name and alias yet")',
        "test_the_whole_chain_from_the_question_to_the_hand_off_lists",
        T_RUN,
    ),
    Case(
        "run: re.fullmatch(WAVE, text) is None",
        RUN,
        "    if re.fullmatch(WAVE, text) is None:\n        raise argparse.ArgumentTypeError(",
        "    if False:\n        raise argparse.ArgumentTypeError(",
        "test_a_wave_label_is_a_date_and_an_optional_letter",
        T_RUN,
    ),
    Case(
        "run: not args.kind",
        RUN,
        '        if not args.kind:\n            raise UsageError("lane names needs --kind clean or --kind spoken")',
        '        if False:\n            raise UsageError("lane names needs --kind clean or --kind spoken")',
        "test_a_names_command_needs_its_kind",
        T_RUN,
    ),
    Case(
        "scope_judge: region is None",
        SCOPE_JUDGE,
        "    if region is None:\n        raise common.IdentityError(f\"{record['id']} has no longitude: the window cannot be told\")",
        "    if False:\n        raise common.IdentityError(f\"{record['id']} has no longitude: the window cannot be told\")",
        "test_a_record_without_a_longitude_has_no_window",
        T_SCOPE,
    ),
    Case(
        "scope_judge: isinstance(value, bool) or not isinstance(value, int) or not YEAR_LOW <= valu",
        SCOPE_JUDGE,
        '    if isinstance(value, bool) or not isinstance(value, int) or not YEAR_LOW <= value <= YEAR_HIGH:\n        raise AnswerError(f"{what} is not a year (an integer from {YEAR_LOW} to {YEAR_HIGH})")',
        '    if False:\n        raise AnswerError(f"{what} is not a year (an integer from {YEAR_LOW} to {YEAR_HIGH})")',
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        'scope_judge: data["site_id"] != ctx["site_id"] #3',
        SCOPE_JUDGE,
        '    data = A.load_object(text, ANSWER_KEYS)\n    if data["site_id"] != ctx["site_id"]:\n        raise AnswerError(f"site_id {data[\'site_id\']!r} is not this question\'s {ctx[\'site_id\']}")',
        "    data = A.load_object(text, ANSWER_KEYS)\n    if False:\n        raise AnswerError(f\"site_id {data['site_id']!r} is not this question's {ctx['site_id']}\")",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        "scope_judge: verdict not in VERDICTS",
        SCOPE_JUDGE,
        "    if verdict not in VERDICTS:\n        raise AnswerError(f\"verdict {verdict!r} is not one of {', '.join(VERDICTS)}\")",
        "    if False:\n        raise AnswerError(f\"verdict {verdict!r} is not one of {', '.join(VERDICTS)}\")",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        "scope_judge: (value is not None) != (name == expected)",
        SCOPE_JUDGE,
        "        if (value is not None) != (name == expected):\n            raise AnswerError(",
        "        if False:\n            raise AnswerError(",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        'scope_judge: year > ctx["cutoff"]',
        SCOPE_JUDGE,
        '        if year > ctx["cutoff"]:\n            raise AnswerError(',
        "        if False:\n            raise AnswerError(",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        'scope_judge: year <= ctx["cutoff"]',
        SCOPE_JUDGE,
        '        if year <= ctx["cutoff"]:\n            raise AnswerError(',
        "        if False:\n            raise AnswerError(",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        'scope_judge: not ctx["museum_question"]',
        SCOPE_JUDGE,
        '        if not ctx["museum_question"]:\n            raise AnswerError("MUSEUM_KEEP is for an entry of type Museum")',
        '        if False:\n            raise AnswerError("MUSEUM_KEEP is for an entry of type Museum")',
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        "scope_judge: kind not in KINDS",
        SCOPE_JUDGE,
        '        if kind not in KINDS:\n            raise AnswerError(f"kind {kind!r} is not one of {list(KINDS)}")',
        '        if False:\n            raise AnswerError(f"kind {kind!r} is not one of {list(KINDS)}")',
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        'scope_judge: len({website(q["url"]) for q in quotes}) < MIN_SITES',
        SCOPE_JUDGE,
        '        if len({website(q["url"]) for q in quotes}) < MIN_SITES:\n            raise AnswerError(',
        "        if False:\n            raise AnswerError(",
        "test_every_rule_an_answer_can_break_on_its_own",
        T_SCOPE,
    ),
    Case(
        "scope_judge: not counted",
        SCOPE_JUDGE,
        '    data["quotes"] = noted\n    if not counted:\n        return Outcome(HELD, f"quotes: a quote does not count ({reason})", data)',
        '    data["quotes"] = noted\n    if False:\n        return Outcome(HELD, f"quotes: a quote does not count ({reason})", data)',
        "test_a_quote_the_page_does_not_hold_holds_the_site",
        T_SCOPE,
    ),
    Case(
        'scope_judge: data["verdict"] not in (CONFIRM, REJECT)',
        SCOPE_JUDGE,
        '    if data["verdict"] not in (CONFIRM, REJECT):\n        raise AnswerError(f"verdict {data[\'verdict\']!r} is not CONFIRM or REJECT")',
        "    if False:\n        raise AnswerError(f\"verdict {data['verdict']!r} is not CONFIRM or REJECT\")",
        "test_a_confirmation_needs_a_found_quote_a_rejection_needs_a_reason",
        T_SCOPE,
    ),
    Case(
        "scope_judge: not counted #2",
        SCOPE_JUDGE,
        '    }\n    if not counted:\n        return Outcome(HELD, f"quotes: a quote does not count ({reason})", data)',
        '    }\n    if False:\n        return Outcome(HELD, f"quotes: a quote does not count ({reason})", data)',
        "test_a_confirmation_needs_a_found_quote_a_rejection_needs_a_reason",
        T_SCOPE,
    ),
    Case(
        "scope_judge: now is None",
        SCOPE_JUDGE,
        '        if now is None:\n            skip(sid, "gone", "the site is no longer in unified_sites")',
        '        if False:\n            skip(sid, "gone", "the site is no longer in unified_sites")',
        "test_an_entry_that_moved_since_the_question_is_skipped_and_asked_again",
        T_SCOPE,
    ),
    Case(
        'scope_judge: now["source_id"] != "ancient_nerds"',
        SCOPE_JUDGE,
        '        if now["source_id"] != "ancient_nerds":\n            skip(sid, "not-curated", f"a {now[\'source_id\']} row")',
        '        if False:\n            skip(sid, "not-curated", f"a {now[\'source_id\']} row")',
        "test_an_entry_that_moved_since_the_question_is_skipped_and_asked_again",
        T_SCOPE,
    ),
    Case(
        "scope_judge: moved",
        SCOPE_JUDGE,
        "        if moved:\n            skip(",
        "        if False:\n            skip(",
        "test_an_entry_that_moved_since_the_question_is_skipped_and_asked_again",
        T_SCOPE,
    ),
    Case(
        'scope_judge: now["scope_status"] == RETIRED',
        SCOPE_JUDGE,
        '        if now["scope_status"] == RETIRED:\n            skip(sid, "already-retired", "retired since the question was asked")',
        '        if False:\n            skip(sid, "already-retired", "retired since the question was asked")',
        "test_a_retired_site_is_left_alone",
        T_SCOPE,
    ),
    Case(
        'scope_judge: now["scope_status"] == status',
        SCOPE_JUDGE,
        '        if now["scope_status"] == status:\n            skip(sid, "already-decided", f"scope_status is already {status!r}")',
        '        if False:\n            skip(sid, "already-decided", f"scope_status is already {status!r}")',
        "test_an_in_scope_museum_can_be_retired_and_a_kept_one_is_not_written_twice",
        T_SCOPE,
    ),
    Case(
        'scope_judge: second is None or second["data"]["verdict"] != CONFIRM',
        SCOPE_JUDGE,
        '            if second is None or second["data"]["verdict"] != CONFIRM:\n                raise MP.PlanError(f"{sid}: a retirement is written only after a CONFIRM")',
        '            if False:\n                raise MP.PlanError(f"{sid}: a retirement is written only after a CONFIRM")',
        "test_a_retirement_without_a_confirmation_is_refused",
        T_SCOPE,
    ),
    Case(
        "scope_judge: len(sites) > waves.SITES_PER_WAVE",
        SCOPE_JUDGE,
        '    if len(sites) > waves.SITES_PER_WAVE:\n        raise MP.PlanError(f"{len(sites)} sites exceed one wave of {waves.SITES_PER_WAVE}")',
        '    if False:\n        raise MP.PlanError(f"{len(sites)} sites exceed one wave of {waves.SITES_PER_WAVE}")',
        "test_a_wave_is_at_most_a_hundred_sites",
        T_SCOPE,
    ),
    Case(
        'verify: not column.replace("_", "").isalnum()',
        VERIFY,
        '        if not column.replace("_", "").isalnum():\n            raise common.IdentityError(f"{column!r} is not a column name")',
        '        if False:\n            raise common.IdentityError(f"{column!r} is not a column name")',
        "test_the_read_asks_only_the_planned_columns_of_the_planned_sites",
        T_FILES,
    ),
    Case(
        "waves: not 1 <= limit <= SITES_PER_WAVE",
        WAVES,
        '    if not 1 <= limit <= SITES_PER_WAVE:\n        raise WaveError(f"a wave holds 1..{SITES_PER_WAVE} sites, not {limit}")',
        '    if False:\n        raise WaveError(f"a wave holds 1..{SITES_PER_WAVE} sites, not {limit}")',
        "test_a_wave_holds_one_to_a_hundred_sites",
        T_FILES,
    ),
    Case(
        "waves: path.exists()",
        WAVES,
        '    if path.exists():\n        raise WaveError(f"{path} exists: a wave is selected once")',
        '    if False:\n        raise WaveError(f"{path} exists: a wave is selected once")',
        "test_a_wave_is_selected_once_and_a_site_is_in_one_wave_only",
        T_FILES,
    ),
    Case(
        "waves: not open_sites",
        WAVES,
        '    if not open_sites:\n        raise WaveError("no site is left for a new wave")',
        '    if False:\n        raise WaveError("no site is left for a new wave")',
        "test_a_wave_is_selected_once_and_a_site_is_in_one_wave_only",
        T_FILES,
    ),
    Case(
        "waves: not path.exists()",
        WAVES,
        '    if not path.exists():\n        raise WaveError(f"{path} does not exist: select the wave first")',
        '    if False:\n        raise WaveError(f"{path} does not exist: select the wave first")',
        "test_a_wave_that_was_never_selected_is_refused",
        T_FILES,
    ),
]


if __name__ == "__main__":
    wanted = [c for c in CASES if not sys.argv[1:] or any(a in c.label for a in sys.argv[1:])]
    if not wanted:
        sys.exit(f"no case label contains any of {sys.argv[1:]}")
    sys.exit(main(wanted))
