-- plan sha256 7557dad81aae4d326b3b2240b1f0ae9fbce543298ed10f2cdbcbfe160e19eed6
-- Generated by scripts/remediation/mechanical/apply.py - do not edit by hand.
-- 3 row(s) over 3 site(s); scope source_id = 'ancient_nerds';
-- run stamp '2026-09-22_mechanical-site-type-shape'; journal test id 'P6/site-type-shape'.
-- Every UPDATE is conditioned on the old value the plan names; every change is journalled
-- in the same transaction, so the audit trail cannot disagree with the data.
\set ON_ERROR_STOP on
BEGIN;

-- The server bounds this transaction itself: a lock wait or a runaway statement raises
-- here, psql stops the script (exit 3) and nothing is kept. A client that gives up does
-- not stop the server - psql has the whole script on its stdin.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _site_type_plan (
    site_id     UUID PRIMARY KEY,
    old_value   TEXT NOT NULL,
    new_value   TEXT NOT NULL,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    evidence    JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _site_type_plan (site_id, old_value, new_value, change_key, reason, evidence) VALUES
    ('99a98235-4cba-484b-b179-c3e34ed89908'::uuid, 'Grave (burial site) — not representable', 'Necropolis/tombs complex', 'site-type-shape:99a98235-4cba-484b-b179-c3e34ed89908', 'site-type-shape (restore-model-refusal): ''Grave (burial site) — not representable'' (model-refusal, phase 3 phase3:batch-0168:chunk-0001) -> ''Necropolis/tombs complex'', the value it replaced', '[{"source": "remediation_change_log:28606", "url": "remediation_change_log", "quote": "phase3:batch-0168:chunk-0001 (P3/site_type): ''Necropolis/tombs complex'' -> ''Grave (burial site) — not representable''"}, {"source": "output/remediation/snapshot/unified_sites.jsonl.gz (2026-09-20)", "url": "output/remediation/snapshot/unified_sites.jsonl.gz", "quote": "site_type = ''Necropolis/tombs complex'' before the remediation"}, {"source": "pipeline/normalizers/site_type.py:CANONICAL_TYPES", "url": "pipeline/normalizers/site_type.py", "quote": "''Necropolis/tombs complex'' is canonical and normalize_site_type(''Necropolis/tombs complex'') = ''Necropolis/tombs complex''; ''Grave (burial site) — not representable'' is not canonical (model-refusal)"}]'::jsonb),
    ('bad314d6-47c3-457f-ab77-9600fe9b04d2'::uuid, 'suspect_modern', 'Monument', 'site-type-shape:bad314d6-47c3-457f-ab77-9600fe9b04d2', 'site-type-shape (restore-marker-token): ''suspect_modern'' (marker-token, phase 3 phase3:batch-0285:chunk-0001) -> ''Monument'', the value it replaced', '[{"source": "remediation_change_log:29416", "url": "remediation_change_log", "quote": "phase3:batch-0285:chunk-0001 (P3/site_type): ''Monument'' -> ''suspect_modern''"}, {"source": "output/remediation/snapshot/unified_sites.jsonl.gz (2026-09-20)", "url": "output/remediation/snapshot/unified_sites.jsonl.gz", "quote": "site_type = ''Monument'' before the remediation"}, {"source": "pipeline/normalizers/site_type.py:CANONICAL_TYPES", "url": "pipeline/normalizers/site_type.py", "quote": "''Monument'' is canonical and normalize_site_type(''Monument'') = ''Monument''; ''suspect_modern'' is not canonical (marker-token)"}]'::jsonb),
    ('c5c5f2da-a5ea-41c6-807d-4c8ad7af03ba'::uuid, 'suspect_modern', 'City/town/settlement', 'site-type-shape:c5c5f2da-a5ea-41c6-807d-4c8ad7af03ba', 'site-type-shape (restore-marker-token): ''suspect_modern'' (marker-token, phase 3 phase3:batch-0209:chunk-0001) -> ''City/town/settlement'', the value it replaced', '[{"source": "remediation_change_log:28880", "url": "remediation_change_log", "quote": "phase3:batch-0209:chunk-0001 (P3/site_type): ''City/town/settlement'' -> ''suspect_modern''"}, {"source": "output/remediation/snapshot/unified_sites.jsonl.gz (2026-09-20)", "url": "output/remediation/snapshot/unified_sites.jsonl.gz", "quote": "site_type = ''City/town/settlement'' before the remediation"}, {"source": "pipeline/normalizers/site_type.py:CANONICAL_TYPES", "url": "pipeline/normalizers/site_type.py", "quote": "''City/town/settlement'' is canonical and normalize_site_type(''City/town/settlement'') = ''City/town/settlement''; ''suspect_modern'' is not canonical (marker-token)"}]'::jsonb);

DO $$
DECLARE
    bad      INTEGER;
    moved    INTEGER := 0;
    expected INTEGER := 3;
    r        RECORD;
BEGIN
    -- expected is the plan's own row count, rendered here, and not a second count of the
    -- temp table the loop below iterates: counting the same table twice would make the
    -- comparison after the loop a tautology. The instance that makes a short loop
    -- unreachable is apply_remediation_change, which raises unless exactly one row
    -- matched; this guard is what reports a loop that changed fewer rows than the plan.

    -- scope guard 1: every planned row is a curated site that still exists
    SELECT count(*) INTO bad
      FROM _site_type_plan p LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        -- the source name is a RAISE argument, never part of the quoted message: a name
        -- spliced into the message text only parses while the name happens to contain no
        -- quote, which is a property of today's value and not of this code. G0's guard is
        -- the shape this one copies.
        RAISE EXCEPTION 'site_type shape repair: % planned row(s) are not % sites', bad, 'ancient_nerds';
    END IF;

    -- scope guard 2: the plan is a set of real changes, each one writable in the column
    SELECT count(*) INTO bad FROM _site_type_plan p
     WHERE p.old_value IS NULL OR p.new_value = '' OR p.new_value = p.old_value
        OR length(p.new_value) > 100;
    IF bad > 0 THEN
        RAISE EXCEPTION 'site_type shape repair: % planned row(s) are not writable changes', bad;
    END IF;

    -- scope guard 3: every planned row still holds the old value the plan names
    SELECT count(*) INTO bad
      FROM _site_type_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE u.site_type IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'site_type shape repair: % planned row(s) no longer hold the planned old value', bad;
    END IF;

    -- scope guard 4: every planned row writes a value this lane owns (new value)
    SELECT count(*) INTO bad FROM _site_type_plan p
     WHERE p.new_value NOT IN ('City', 'Town', 'Village', 'Settlement', 'Urban', 'Villa', 'City/town/settlement', 'Residence/villa/farmhouse', 'City/town/settlement, Pyramid complex', 'Castle', 'Citadel', 'Fort', 'Fortress', 'Military', 'Wall', 'Gate', 'Fortress/citadel', 'Castle/palace', 'Gate/archway/bridge', 'Fortification', 'Church', 'Mosque', 'Temple', 'Monastery', 'Sacred site', 'Sanctuary', 'Religious', 'Temple complex', 'Church/cathedral', 'Minaret/tower', 'Stone cross', 'Cemetery', 'Necropolis', 'Tomb', 'Burial', 'Funerary', 'Necropolis/tombs complex', 'Barrow', 'Mound/tumulus', 'Cairn', 'Elongated skulls', 'Megalithic', 'Megalithic stones', 'Megalithic structures', 'Megalithic statues', 'Megalithic walls', 'Stone circle', 'Dolmen', 'Standing stone', 'Henge', 'Timber circle', 'Polygonal masonry', 'Cave', 'Cave Structures', 'Rock relief/carving', 'Rock art', 'Petroglyphs', 'Sculptured stone', 'Cave Structures, Rock art', 'Geoglyphs', 'Road', 'Bridge', 'Mine', 'Quarry', 'Infrastructure', 'Road/avenue/trackway', 'Reservoir/aqueduct/canal', 'Mine/quarry', 'Earthwork', 'Well', 'Aqueduct', 'Bath', 'Harbor', 'Port', 'Underwater structures', 'Shipwreck', 'Monument', 'Memorial', 'Stadium', 'Theater', 'Theatre', 'Forum', 'Palace', 'Pyramid complex', 'Museum', 'Amphitheatre', 'Scheduled monument', 'Heritage site', 'Archaeological site', 'Site', 'Ruin', 'Inscription', 'Natural feature', 'Impact crater', 'Geological interest', 'Magnetic anomaly', 'Unknown');
    IF bad > 0 THEN
        RAISE EXCEPTION 'site_type shape repair: % planned row(s) write a value this lane does not own', bad;
    END IF;

    -- the only writer: the conditional UPDATE and its journal row commit together, and
    -- the function raises unless exactly one row matched
    FOR r IN SELECT * FROM _site_type_plan ORDER BY site_id LOOP
        moved := moved + apply_remediation_change(
            'unified_sites', 'site_type', 'id', r.site_id::text,
            r.old_value, r.new_value,
            'P6/site-type-shape', '2026-09-22_mechanical-site-type-shape', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;

    IF moved <> expected THEN
        RAISE EXCEPTION 'site_type shape repair: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds the new value
    SELECT count(*) INTO bad
      FROM _site_type_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE u.site_type IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'site_type shape repair: % planned row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: the journal and the data agree, row for row, in both directions
    SELECT count(*) INTO bad
      FROM _site_type_plan p LEFT JOIN remediation_change_log l
        ON l.row_pk = p.site_id::text AND l.table_name = 'unified_sites'
       AND l.column_name = 'site_type'
       AND l.run_stamp = '2026-09-22_mechanical-site-type-shape'
     WHERE l.id IS NULL
        OR l.new_value IS DISTINCT FROM p.new_value
        OR l.old_value IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'site_type shape repair: % planned row(s) have no matching journal row', bad;
    END IF;

    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = '2026-09-22_mechanical-site-type-shape'
       AND (l.table_name <> 'unified_sites' OR l.column_name <> 'site_type');
    IF bad > 0 THEN
        RAISE EXCEPTION 'site_type shape repair: this run stamp journalled % row(s) outside unified_sites.site_type', bad;
    END IF;

    RAISE NOTICE 'site_type shape repair: % row(s) changed and journalled over % curated site(s)',
        moved, expected;
END $$;

COMMIT;

-- Post-commit read: the numbers the report quotes, from the database, not from the plan.
SELECT 'journal rows for this run stamp' AS metric, count(*)::text AS value
  FROM remediation_change_log WHERE run_stamp = '2026-09-22_mechanical-site-type-shape'
UNION ALL
SELECT 'journal rows for this test id', count(*)::text
  FROM remediation_change_log WHERE test_id = 'P6/site-type-shape'
UNION ALL
SELECT 'planned rows now holding the new value', count(*)::text
  FROM remediation_change_log l
 WHERE l.run_stamp = '2026-09-22_mechanical-site-type-shape' AND l.table_name = 'unified_sites'
   AND l.column_name = 'site_type'
   AND EXISTS (SELECT 1 FROM unified_sites u
                WHERE u.id::text = l.row_pk AND u.site_type = l.new_value)
UNION ALL
SELECT 'curated rows whose site_type is a marker token or a model refusal', count(*)::text
  FROM unified_sites
 WHERE source_id = 'ancient_nerds' AND (site_type ~ '^[a-z0-9]+(_[a-z0-9]+)+$' OR site_type ILIKE '%not representable%')
UNION ALL
SELECT 'curated sites', count(*)::text
  FROM unified_sites WHERE source_id = 'ancient_nerds';
