-- Generated by scripts/remediation/gallery_audit/chunk_writer.py - do not edit by hand.
-- plan sha256 39beb0c8a043cde42f1ea1f37365c3d89e328e64c60eb987c020e0e7cbb7c83f
-- The write of lane 'name-key-lyra', chunk 001: 11 row(s) over 6 site(s);
-- scope source_id = 'lyra'; run stamp 'name-key-lyra-2026-09-26-001'; journal test id 'P6/name-key-lyra'.
-- Every row goes through apply_remediation_change() (migrations 0017/0018/0022): the conditional
-- UPDATE and its journal row are one statement. This file holds no DELETE and no UPDATE.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _img_plan (
    seq         INTEGER PRIMARY KEY,
    table_name  TEXT NOT NULL,
    column_name TEXT NOT NULL,
    row_key     TEXT NOT NULL,
    site_id     UUID NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    evidence    JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _img_plan (seq, table_name, column_name, row_key, site_id, old_value, new_value, change_key, reason, evidence) VALUES
    (1, 'unified_site_names', 'name_normalized', '3617031', '624a1828-419b-46e4-93d0-ef7b4981aa29'::uuid, 'ヤッフ島', 'ヤップ島', 'name-key-lyra:unified_site_names.name_normalized:3617031', 'K1: the stored key ''ヤッフ島'' is not the match key of the name ''ヤップ島''; Postgres derives ''ヤップ島'' (K1)', '[{"quote": "wikidata_alias row name ''ヤップ島''; stored key ''ヤッフ島''; left(lower(unaccent(name)), 500) = ''ヤップ島''", "source": "unified_site_names:3617031"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (2, 'unified_site_names', 'name_normalized', '3617034', '624a1828-419b-46e4-93d0-ef7b4981aa29'::uuid, '야프 제도', '야프 제도', 'name-key-lyra:unified_site_names.name_normalized:3617034', 'K1: the stored key ''야프 제도'' is not the match key of the name ''야프 제도''; Postgres derives ''야프 제도'' (K1)', '[{"quote": "wikidata_alias row name ''야프 제도''; stored key ''야프 제도''; left(lower(unaccent(name)), 500) = ''야프 제도''", "source": "unified_site_names:3617034"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (3, 'unified_site_names', 'name_normalized', '3617035', '624a1828-419b-46e4-93d0-ef7b4981aa29'::uuid, '야프섬', '야프섬', 'name-key-lyra:unified_site_names.name_normalized:3617035', 'K1: the stored key ''야프섬'' is not the match key of the name ''야프섬''; Postgres derives ''야프섬'' (K1)', '[{"quote": "wikidata_alias row name ''야프섬''; stored key ''야프섬''; left(lower(unaccent(name)), 500) = ''야프섬''", "source": "unified_site_names:3617035"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (4, 'unified_site_names', 'name_normalized', '3617036', '624a1828-419b-46e4-93d0-ef7b4981aa29'::uuid, '야프제도', '야프제도', 'name-key-lyra:unified_site_names.name_normalized:3617036', 'K1: the stored key ''야프제도'' is not the match key of the name ''야프제도''; Postgres derives ''야프제도'' (K1)', '[{"quote": "wikidata_alias row name ''야프제도''; stored key ''야프제도''; left(lower(unaccent(name)), 500) = ''야프제도''", "source": "unified_site_names:3617036"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (5, 'unified_site_names', 'name_normalized', '3616936', '6eb8b50f-b9dc-4069-8135-efeb491b9e1b'::uuid, 'トッカーラント', 'ドッガーランド', 'name-key-lyra:unified_site_names.name_normalized:3616936', 'K1: the stored key ''トッカーラント'' is not the match key of the name ''ドッガーランド''; Postgres derives ''ドッガーランド'' (K1)', '[{"quote": "wikidata_alias row name ''ドッガーランド''; stored key ''トッカーラント''; left(lower(unaccent(name)), 500) = ''ドッガーランド''", "source": "unified_site_names:3616936"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (6, 'unified_site_names', 'name_normalized', '3616938', '6eb8b50f-b9dc-4069-8135-efeb491b9e1b'::uuid, '도거랜드', '도거랜드', 'name-key-lyra:unified_site_names.name_normalized:3616938', 'K1: the stored key ''도거랜드'' is not the match key of the name ''도거랜드''; Postgres derives ''도거랜드'' (K1)', '[{"quote": "wikidata_alias row name ''도거랜드''; stored key ''도거랜드''; left(lower(unaccent(name)), 500) = ''도거랜드''", "source": "unified_site_names:3616938"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (7, 'unified_site_names', 'name_normalized', '3616643', '848cbe6d-136e-4c15-819c-b017b290a909'::uuid, '북센티널섬', '북센티널섬', 'name-key-lyra:unified_site_names.name_normalized:3616643', 'K1: the stored key ''북센티널섬'' is not the match key of the name ''북센티널섬''; Postgres derives ''북센티널섬'' (K1)', '[{"quote": "wikidata_alias row name ''북센티널섬''; stored key ''북센티널섬''; left(lower(unaccent(name)), 500) = ''북센티널섬''", "source": "unified_site_names:3616643"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (8, 'unified_site_names', 'name_normalized', '3617346', '85dbd052-9423-4404-a059-3f69cb7bb82d'::uuid, 'ルーフクント湖', 'ループクンド湖', 'name-key-lyra:unified_site_names.name_normalized:3617346', 'K1: the stored key ''ルーフクント湖'' is not the match key of the name ''ループクンド湖''; Postgres derives ''ループクンド湖'' (K1)', '[{"quote": "wikidata_alias row name ''ループクンド湖''; stored key ''ルーフクント湖''; left(lower(unaccent(name)), 500) = ''ループクンド湖''", "source": "unified_site_names:3617346"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (9, 'unified_site_names', 'name_normalized', '3617283', 'ccccdfe7-8288-4451-a222-07facc1bfe50'::uuid, 'cerutti mastodon  site', 'cerutti mastodon (cm) site', 'name-key-lyra:unified_site_names.name_normalized:3617283', 'K1: the stored key ''cerutti mastodon  site'' is not the match key of the name ''Cerutti Mastodon (CM) site''; Postgres derives ''cerutti mastodon (cm) site'' (K1)', '[{"quote": "wikidata_alias row name ''Cerutti Mastodon (CM) site''; stored key ''cerutti mastodon  site''; left(lower(unaccent(name)), 500) = ''cerutti mastodon (cm) site''", "source": "unified_site_names:3617283"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (10, 'unified_site_names', 'name_normalized', '3617349', 'dab28cc0-615f-4779-9fef-882586a6ab6f'::uuid, 'チャーンウットの森', 'チャーンウッドの森', 'name-key-lyra:unified_site_names.name_normalized:3617349', 'K1: the stored key ''チャーンウットの森'' is not the match key of the name ''チャーンウッドの森''; Postgres derives ''チャーンウッドの森'' (K1)', '[{"quote": "wikidata_alias row name ''チャーンウッドの森''; stored key ''チャーンウットの森''; left(lower(unaccent(name)), 500) = ''チャーンウッドの森''", "source": "unified_site_names:3617349"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb),
    (11, 'unified_site_names', 'name_normalized', '3617350', 'dab28cc0-615f-4779-9fef-882586a6ab6f'::uuid, 'チャーンウットフォレスト', 'チャーンウッドフォレスト', 'name-key-lyra:unified_site_names.name_normalized:3617350', 'K1: the stored key ''チャーンウットフォレスト'' is not the match key of the name ''チャーンウッドフォレスト''; Postgres derives ''チャーンウッドフォレスト'' (K1)', '[{"quote": "wikidata_alias row name ''チャーンウッドフォレスト''; stored key ''チャーンウットフォレスト''; left(lower(unaccent(name)), 500) = ''チャーンウッドフォレスト''", "source": "unified_site_names:3617350"}, {"quote": "KEY_SQL_TEMPLATE = ''left(lower(unaccent({expr})), 500)''", "source": "pipeline/lyra/site_key.py"}]'::jsonb);

CREATE TEMP TABLE _img_may_empty (site_id UUID PRIMARY KEY) ON COMMIT DROP;
-- no site of this chunk may lose its last live image

CREATE TEMP TABLE _img_live_before ON COMMIT DROP AS
  SELECT DISTINCT w.site_id FROM wiki_images w
   WHERE w.site_id IN (SELECT site_id FROM _img_plan) AND w.is_excluded IS NOT TRUE;

DO $$
DECLARE
    bad      integer;
    moved    integer := 0;
    expected integer := 11;
    r        RECORD;
BEGIN
    -- guard 1: every planned site is a lyra site (the source is a RAISE argument, never
    -- part of the quoted message)
    SELECT count(*) INTO bad FROM (SELECT DISTINCT site_id FROM _img_plan) p
      LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'lyra';
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % planned site(s) are not % sites', bad, 'lyra';
    END IF;

    -- guard 2: every planned image row exists and lives on the site the plan names
    SELECT count(*) INTO bad FROM _img_plan p
      LEFT JOIN wiki_images w ON w.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND (w.id IS NULL OR w.site_id IS DISTINCT FROM p.site_id);
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % planned image row(s) do not live on the site the plan names', bad;
    END IF;

    -- guard 2b: every planned name row exists and belongs to the site the plan names
    SELECT count(*) INTO bad FROM _img_plan p
      LEFT JOIN unified_site_names n ON n.id = CASE WHEN p.table_name = 'unified_site_names' THEN p.row_key::integer END
     WHERE p.table_name = 'unified_site_names' AND (n.id IS NULL OR n.site_id IS DISTINCT FROM p.site_id);
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % planned name row(s) do not belong to the site the plan names', bad;
    END IF;

    -- guard 2c: every planned unified_site_names key is the key Postgres derives from the row's name now
    SELECT count(*) INTO bad FROM _img_plan p JOIN unified_site_names n ON n.id = CASE WHEN p.table_name = 'unified_site_names' THEN p.row_key::integer END
     WHERE p.table_name = 'unified_site_names' AND p.column_name = 'name_normalized'
       AND p.new_value IS DISTINCT FROM left(lower(unaccent(n.name)), 500);
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % planned key(s) are not the key Postgres derives from the name', bad;
    END IF;

    -- guard 3: every planned row still holds the planned old value (NULL-safe)

    SELECT count(*) INTO bad FROM _img_plan p JOIN unified_site_names t ON t.id = CASE WHEN p.table_name = 'unified_site_names' THEN p.row_key::integer END
     WHERE p.table_name = 'unified_site_names' AND p.column_name = 'name_normalized'
       AND t.name_normalized::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % planned name_normalized row(s) no longer hold the planned old value', bad;
    END IF;

    -- the only writer
    FOR r IN SELECT * FROM _img_plan ORDER BY seq LOOP
        moved := moved + apply_remediation_change(
            r.table_name, r.column_name, 'id', r.row_key, r.old_value, r.new_value,
            'P6/name-key-lyra', 'name-key-lyra-2026-09-26-001', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;
    IF moved <> expected THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds its new value

    SELECT count(*) INTO bad FROM _img_plan p JOIN unified_site_names t ON t.id = CASE WHEN p.table_name = 'unified_site_names' THEN p.row_key::integer END
     WHERE p.table_name = 'unified_site_names' AND p.column_name = 'name_normalized'
       AND t.name_normalized::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % planned name_normalized row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: plan -> journal, row for row, with the planned values and keys
    SELECT count(*) INTO bad FROM _img_plan p
      LEFT JOIN remediation_change_log l
        ON l.run_stamp = 'name-key-lyra-2026-09-26-001' AND l.table_name = p.table_name
       AND l.column_name = p.column_name AND l.row_pk = p.row_key
     WHERE l.id IS NULL OR l.old_value IS DISTINCT FROM p.old_value
        OR l.new_value IS DISTINCT FROM p.new_value OR l.change_key IS DISTINCT FROM p.change_key;
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % planned row(s) disagree with the journal', bad;
    END IF;

    -- invariant 3: journal -> plan: this run stamp journalled the planned rows and nothing else
    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = 'name-key-lyra-2026-09-26-001'
       AND NOT EXISTS (SELECT 1 FROM _img_plan p
                        WHERE p.table_name = l.table_name AND p.column_name = l.column_name
                          AND p.row_key = l.row_pk);
    IF bad > 0 OR (SELECT count(*) FROM remediation_change_log WHERE run_stamp = 'name-key-lyra-2026-09-26-001') <> expected THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: the journal of this run stamp is not the plan (% unplanned row(s))', bad;
    END IF;

    -- invariant 4: at most one hero per touched site
    -- the invariant the repair must leave behind: at most one hero per touched site
    -- (DISTINCT: _img_plan holds several rows per site, and a plain join would count each
    --  hero row twice - the check would then fail on a correct repair)
    SELECT count(*) INTO bad FROM (
        SELECT s.site_id FROM (SELECT DISTINCT site_id FROM _img_plan) s
          JOIN wiki_images w ON w.site_id = s.site_id
         GROUP BY s.site_id HAVING count(*) FILTER (WHERE w.is_hero) > 1) x;
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % touched site(s) end with more than one hero', bad;
    END IF;

    -- invariant 5: no hero on an excluded row of a touched site
    SELECT count(*) INTO bad FROM wiki_images w
     WHERE w.site_id IN (SELECT site_id FROM _img_plan) AND w.is_hero AND w.is_excluded IS TRUE;
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % hero row(s) are excluded', bad;
    END IF;

    -- invariant 6: a touched site that had a live image still has one, unless the chunk names it
    SELECT count(*) INTO bad FROM _img_live_before b
     WHERE NOT EXISTS (SELECT 1 FROM wiki_images w
                        WHERE w.site_id = b.site_id AND w.is_excluded IS NOT TRUE)
       AND b.site_id NOT IN (SELECT site_id FROM _img_may_empty);
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % site(s) lost their last live image', bad;
    END IF;

    -- invariant 7: every image kind of a touched row is in migration 0019's vocabulary
    SELECT count(*) INTO bad FROM wiki_images w
     WHERE w.site_id IN (SELECT site_id FROM _img_plan)
       AND w.image_kind IS NOT NULL AND w.image_kind NOT IN ('artifact', 'map_or_document', 'other', 'painting_or_artwork', 'people', 'site_photo', 'unknown');
    IF bad > 0 THEN
        RAISE EXCEPTION 'lyra alias key recompute chunk 001: % image kind(s) outside the vocabulary', bad;
    END IF;
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'name-key-lyra-2026-09-26-001';
SELECT 'planned rows', count(*)::text FROM _img_plan;
COMMIT;
