-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: cc0ffc22fe0ca15bf75d1eb023d8ebcd1424d6534cd1fd7048dc158440ebd70b
-- The reversal of lane 'ih6': the rows this wave created go back out, the flag returns to
-- the row that held it, and the thumbnail returns to the value the read found.
-- The row is named by the triple this lane wrote - (site_id, original_url, file_size_bytes) - so
-- the statement cannot delete a row somebody else created.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_uninsert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    original_url      TEXT NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT,
    change_key        TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_uninsert VALUES
    (1, '4b8583a1-da7c-4bf9-a702-05298be4227c'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Ankara_Roma_Tiyatrosu_-_Restorasyon_s%C3%BCreci_%2820.08.2023%29_02.jpg', 199152, NULL, NULL, '/data/images/wiki/4b8583a1/Ankara Roma Tiyatrosu - Restorasyon süreci (20.08.2023) 02.webp', 'import-hero/insert:4b8583a1-da7c-4bf9-a702-05298be4227c'),
    (2, '4ccebe8e-9f02-4188-b9f1-431108bbcd58'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/7/74/Chile-03199_-_Special_Rock_%2849072671368%29.jpg', 862712, NULL, NULL, '/data/images/wiki/4ccebe8e/Chile-03199 - Special Rock (49072671368).webp', 'import-hero/insert:4ccebe8e-9f02-4188-b9f1-431108bbcd58'),
    (3, '4df06c48-82c5-46d6-b82f-6b5023b1220e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Argolic_Gulf_from_the_archaeological_site_of_Mycenae_on_October_27%2C_2019.jpg', 284980, NULL, NULL, '/data/images/wiki/4df06c48/The Argolic Gulf from the archaeological site of Mycenae on October 27, 2019.webp', 'import-hero/insert:4df06c48-82c5-46d6-b82f-6b5023b1220e'),
    (4, '53fd5500-0ce2-4bd0-a3d3-8ec069605e3e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/62/Burdur_Museum_Athena_from_Cremna_2nd-3rd_Century_AD_3102.jpg', 178922, NULL, NULL, '/data/images/wiki/53fd5500/Burdur Museum Athena from Cremna 2nd-3rd Century AD 3102.webp', 'import-hero/insert:53fd5500-0ce2-4bd0-a3d3-8ec069605e3e'),
    (5, '540f24d5-bf3d-40b8-81f7-349d5107fd24'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/5/52/Stina_sign.jpg', 129574, NULL, NULL, '/data/images/wiki/540f24d5/Stina sign.webp', 'import-hero/insert:540f24d5-bf3d-40b8-81f7-349d5107fd24'),
    (6, '543c85d7-47af-4b78-a412-e55f6836d6ea'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/17/%D0%91%D0%BE%D1%80%D0%B0%D0%BB%D0%B4%D0%B0%D0%B9%D1%81%D0%BA%D0%B8%D0%B5_%D0%BF%D0%B5%D1%82%D1%80%D0%BE%D0%B3%D0%BB%D0%B8%D1%84%D1%8B.jpg', 1830332, NULL, NULL, '/data/images/wiki/543c85d7/Боралдайские петроглифы.webp', 'import-hero/insert:543c85d7-47af-4b78-a412-e55f6836d6ea'),
    (7, '54afc94b-b7e1-469c-9e54-9d838d101acf'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Mada%27in_Saleh_2017.jpg', 366706, NULL, NULL, '/data/images/wiki/54afc94b/Mada''in Saleh 2017.webp', 'import-hero/insert:54afc94b-b7e1-469c-9e54-9d838d101acf'),
    (8, '54dc63d1-d88f-4d40-976b-460b203a07ef'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/d7/House_of_Orpheus%2C_Archaelogical_Park%2C_Paphos_02.jpg', 282588, NULL, NULL, '/data/images/wiki/54dc63d1/House of Orpheus, Archaelogical Park, Paphos 02.webp', 'import-hero/insert:54dc63d1-d88f-4d40-976b-460b203a07ef'),
    (9, '58486903-37c4-4aa4-866f-f7f8d66205ac'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/93/Palacio_Pumamarka%2C_San_Sebasti%C3%A1n_%282021%29_04.jpg', 325680, NULL, NULL, '/data/images/wiki/58486903/Palacio Pumamarka, San Sebastián (2021) 04.webp', 'import-hero/insert:58486903-37c4-4aa4-866f-f7f8d66205ac'),
    (10, '59a722b9-4281-4426-8144-284e509f2061'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Edirne_Roman_Walls_and_Macedonian_Tower_0210.jpg', 505268, NULL, NULL, '/data/images/wiki/59a722b9/Edirne Roman Walls and Macedonian Tower 0210.webp', 'import-hero/insert:59a722b9-4281-4426-8144-284e509f2061'),
    (11, '5c6a72eb-0584-45d0-9fe7-fdfad15b632f'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/84/Hatay_Alt%C4%B1n%C3%B6z%C3%BC_Yunushan%C4%B1_Gelinler_Da%C4%9F%C4%B1_Nekropol%C3%BC.jpg', 758168, NULL, NULL, '/data/images/wiki/5c6a72eb/Hatay Altınözü Yunushanı Gelinler Dağı Nekropolü.webp', 'import-hero/insert:5c6a72eb-0584-45d0-9fe7-fdfad15b632f'),
    (12, '5d8a7c0e-3d54-497b-a9dc-5c9cbee82670'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/5/56/Marku%C5%A1ica%2C_Crkva_silaska_duha_svetoga_na_apostole%2C_kod_Z-1155%2C_DSC_0014.jpg', 250812, NULL, NULL, '/data/images/wiki/5d8a7c0e/Markušica, Crkva silaska duha svetoga na apostole, kod Z-1155, DSC 0014.webp', 'import-hero/insert:5d8a7c0e-3d54-497b-a9dc-5c9cbee82670'),
    (13, '5e53212a-df01-4e4e-b9d0-fde511c2ec55'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Gilwern_Hill_-_geograph.org.uk_-_4142783.jpg', 440420, NULL, NULL, '/data/images/wiki/5e53212a/Gilwern Hill - geograph.org.uk - 4142783.webp', 'import-hero/insert:5e53212a-df01-4e4e-b9d0-fde511c2ec55'),
    (14, '5ed144bd-59e1-4611-a462-a3098bea5231'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/09/Maria_Reiche_Nazca.jpg', 429120, NULL, NULL, '/data/images/wiki/5ed144bd/Maria Reiche Nazca.webp', 'import-hero/insert:5ed144bd-59e1-4611-a462-a3098bea5231'),
    (15, '5f745388-3793-459b-b55f-90dbb5bfed78'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Iznik_Lefke_Gate_97_017.jpg', 392112, NULL, NULL, '/data/images/wiki/5f745388/Iznik Lefke Gate 97 017.webp', 'import-hero/insert:5f745388-3793-459b-b55f-90dbb5bfed78'),
    (16, '61092d36-78c1-4aa9-b830-7bcef7673225'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/83/Adada_Antik_Kenti.jpg', 1592556, NULL, NULL, '/data/images/wiki/61092d36/Adada Antik Kenti.webp', 'import-hero/insert:61092d36-78c1-4aa9-b830-7bcef7673225'),
    (17, '62131a06-8c8c-4c55-bf8a-c19abbca2048'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Tepoztlan_mountains2019.jpg', 452082, NULL, NULL, '/data/images/wiki/62131a06/Tepoztlan mountains2019.webp', 'import-hero/insert:62131a06-8c8c-4c55-bf8a-c19abbca2048'),
    (18, '631de534-1de5-4dbc-ac03-ac5ee63eb84f'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/0/04/Stobno_Szczeci%C5%84skie_%28stacja_kolejowa%29.jpg', 369944, NULL, NULL, '/data/images/wiki/631de534/Stobno Szczecińskie (stacja kolejowa).webp', 'import-hero/insert:631de534-1de5-4dbc-ac03-ac5ee63eb84f'),
    (19, '639cad5c-6019-4516-92d2-deeb2227db41'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Laodikeia%2C_Stadion.jpg', 590462, NULL, NULL, '/data/images/wiki/639cad5c/Laodikeia, Stadion.webp', 'import-hero/insert:639cad5c-6019-4516-92d2-deeb2227db41'),
    (20, '67215100-355e-4586-ae41-00838c8e1566'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Tempel_van_Diana-Cefalu.jpg', 430728, NULL, NULL, '/data/images/wiki/67215100/Tempel van Diana-Cefalu.webp', 'import-hero/insert:67215100-355e-4586-ae41-00838c8e1566'),
    (21, '673332a5-3a27-4045-a929-ddbf7ff7e824'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/38/Thasos_medieval_fortress_SW_gate.jpg', 512588, NULL, NULL, '/data/images/wiki/673332a5/Thasos medieval fortress SW gate.webp', 'import-hero/insert:673332a5-3a27-4045-a929-ddbf7ff7e824'),
    (22, '679e85b1-245b-40bc-b815-8cd1ae71ee12'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/8d/2023-11-05_A_view_from_Kalek%C3%B6y_to_Kekova_Island.jpg', 360678, NULL, NULL, '/data/images/wiki/679e85b1/2023-11-05 A view from Kaleköy to Kekova Island.webp', 'import-hero/insert:679e85b1-245b-40bc-b815-8cd1ae71ee12'),
    (23, '6880170a-df11-4dbf-8c6c-02aa4e39ec7b'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Teatre_of_Clunia_and_sorrounding_views.jpg', 361114, NULL, NULL, '/data/images/wiki/6880170a/Teatre of Clunia and sorrounding views.webp', 'import-hero/insert:6880170a-df11-4dbf-8c6c-02aa4e39ec7b'),
    (24, '6933ea78-a024-455d-981e-fe4c09dfad75'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Fasillar.jpg', 554172, NULL, NULL, '/data/images/wiki/6933ea78/Fasillar.webp', 'import-hero/insert:6933ea78-a024-455d-981e-fe4c09dfad75'),
    (25, '6aa4c8de-3794-42fe-b68e-6b6ab77bd8ed'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/33/Miletus_Delphinion_in_2015_3355.jpg', 452414, NULL, NULL, '/data/images/wiki/6aa4c8de/Miletus Delphinion in 2015 3355.webp', 'import-hero/insert:6aa4c8de-3794-42fe-b68e-6b6ab77bd8ed'),
    (26, '6ee96ec3-9a2f-41be-ad77-f8187a54e493'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/46/Cylindrical_funerary_altar_%28Rhodes%29_01.jpg', 732220, NULL, NULL, '/data/images/wiki/6ee96ec3/Cylindrical funerary altar (Rhodes) 01.webp', 'import-hero/insert:6ee96ec3-9a2f-41be-ad77-f8187a54e493'),
    (27, '71f6f6f1-0cc8-4e43-9f9f-89ae7a635ffa'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/91/Head_of_a_warrior_wearing_boar_tusk_helmet_carved_of_hippopotamus_ivory_from_Phylaki%2C_1375-1300_BCE%2C_Archaeological_Museum_of_Chania_%28Crete%29.jpg', 867944, NULL, NULL, '/data/images/wiki/71f6f6f1/Head of a warrior wearing boar tusk helmet carved of hippopotamus ivory from Phylaki, 1375-1300 BCE, Archaeological Museum of Chania (Crete).webp', 'import-hero/insert:71f6f6f1-0cc8-4e43-9f9f-89ae7a635ffa'),
    (28, '74af1ed2-4221-4e13-8a96-e63631d01cc7'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/90/Be%C3%A7in_B%C3%BCy%C3%BCk_Hamam_5340.jpg', 574882, NULL, NULL, '/data/images/wiki/74af1ed2/Beçin Büyük Hamam 5340.webp', 'import-hero/insert:74af1ed2-4221-4e13-8a96-e63631d01cc7'),
    (29, '77b9b433-376a-468e-8af3-13197a31ed28'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Remains_of_a_Small_Enclosure%2C_Foel_Dduarth_-_geograph.org.uk_-_5724862.jpg', 391078, NULL, NULL, '/data/images/wiki/77b9b433/Remains of a Small Enclosure, Foel Dduarth - geograph.org.uk - 5724862.webp', 'import-hero/insert:77b9b433-376a-468e-8af3-13197a31ed28'),
    (30, '79f94fa1-4d25-4181-a0da-3fa7d794bdbc'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Korykos_land_castle_Main_castle_3235.jpg', 590860, NULL, NULL, '/data/images/wiki/79f94fa1/Korykos land castle Main castle 3235.webp', 'import-hero/insert:79f94fa1-4d25-4181-a0da-3fa7d794bdbc'),
    (31, '7af83a27-7b99-4486-a607-85020bc7819e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/61/Sillyon_Mescit_in_2015_5416.jpg', 652730, NULL, NULL, '/data/images/wiki/7af83a27/Sillyon Mescit in 2015 5416.webp', 'import-hero/insert:7af83a27-7b99-4486-a607-85020bc7819e'),
    (32, '7ee94c43-3a26-44db-8dee-bd7829b5a171'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/37/Castelo_Velho_de_Freixo_de_Num%C3%A3o_-_Portugal_%2850801841192%29.jpg', 435134, NULL, NULL, '/data/images/wiki/7ee94c43/Castelo Velho de Freixo de Numão - Portugal (50801841192).webp', 'import-hero/insert:7ee94c43-3a26-44db-8dee-bd7829b5a171'),
    (33, '810d09d7-37a5-443b-84de-e1101e44e855'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/39/Choquequirao_Usnu.jpg', 800276, NULL, NULL, '/data/images/wiki/810d09d7/Choquequirao Usnu.webp', 'import-hero/insert:810d09d7-37a5-443b-84de-e1101e44e855'),
    (34, '8442fc68-e408-4b2f-9aad-a5f42139685e'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/d/de/Harappan_elephant_figurine_-_Dabarkot_-_BM.jpg', 265686, NULL, NULL, '/data/images/wiki/8442fc68/Harappan elephant figurine - Dabarkot - BM.webp', 'import-hero/insert:8442fc68-e408-4b2f-9aad-a5f42139685e'),
    (35, '879a16b1-ba54-49c0-8b61-6a9265f23758'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/95/Gate_of_Hercules%2C_Colonia_Pietas_Iulia_Pola_Pollentia_Herculanea%2C_Histria_%2810419211935%29.jpg', 360328, NULL, NULL, '/data/images/wiki/879a16b1/Gate of Hercules, Colonia Pietas Iulia Pola Pollentia Herculanea, Histria (10419211935).webp', 'import-hero/insert:879a16b1-ba54-49c0-8b61-6a9265f23758'),
    (36, '8a87a57e-4e29-42e7-9dca-08f3c6c16539'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Terracettes_on_Dungeon_Hill_-_geograph.org.uk_-_7184095.jpg', 682390, NULL, NULL, '/data/images/wiki/8a87a57e/Terracettes on Dungeon Hill - geograph.org.uk - 7184095.webp', 'import-hero/insert:8a87a57e-4e29-42e7-9dca-08f3c6c16539'),
    (37, '8aa48093-66ab-456b-bbd6-b2ba884d47ed'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Cap%2C_Cival%2C_museu_Nacional_d%27Arqueologia_i_Etnologia_de_Guatemala.jpg', 71918, NULL, NULL, '/data/images/wiki/8aa48093/Cap, Cival, museu Nacional d''Arqueologia i Etnologia de Guatemala.webp', 'import-hero/insert:8aa48093-66ab-456b-bbd6-b2ba884d47ed'),
    (38, '8b32820a-13d2-41c9-b96a-173a567582e8'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/4/41/Ancient_Glory_of_Cyrene-libya.jpg', 281382, NULL, NULL, '/data/images/wiki/8b32820a/Ancient Glory of Cyrene-libya.webp', 'import-hero/insert:8b32820a-13d2-41c9-b96a-173a567582e8'),
    (39, '8bcea3e7-dfdc-4af5-8b75-70fb9e34d7ee'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/6/62/Pottery_from_Cult_place_at_the_Berbati_tholos%2C_AM_of_Nafplio%2C_202294.jpg', 634228, NULL, NULL, '/data/images/wiki/8bcea3e7/Pottery from Cult place at the Berbati tholos, AM of Nafplio, 202294.webp', 'import-hero/insert:8bcea3e7-dfdc-4af5-8b75-70fb9e34d7ee'),
    (40, '8c54ae5f-16b5-4ac1-9ae7-0d6e0a3eb0a6'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/5/51/Perge_Helenistik_Kap%C4%B1_Ve_Ana_Cadde.jpg', 363986, NULL, NULL, '/data/images/wiki/8c54ae5f/Perge Helenistik Kapı Ve Ana Cadde.webp', 'import-hero/insert:8c54ae5f-16b5-4ac1-9ae7-0d6e0a3eb0a6'),
    (41, '8df1e714-b5bb-4d4b-846b-71cdf7cb3d21'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/38/Tsitsamuri_Monument_11.jpg', 316142, NULL, NULL, '/data/images/wiki/8df1e714/Tsitsamuri Monument 11.webp', 'import-hero/insert:8df1e714-b5bb-4d4b-846b-71cdf7cb3d21');

DO $$
DECLARE
    bad integer;
BEGIN
    -- every named row is still the one this wave created
    SELECT count(*) INTO bad FROM _ih_uninsert r
      LEFT JOIN wiki_images w
        ON w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes
     WHERE w.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'rollback %: % row(s) this wave created are not there to undo',
            'insert-2026-10-07-005-001', bad;
    END IF;

    DELETE FROM wiki_images w USING _ih_uninsert r
     WHERE w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes;

    UPDATE wiki_images w SET is_hero = true
      FROM _ih_uninsert r
     WHERE r.demoted_id IS NOT NULL AND w.id = r.demoted_id AND w.is_hero IS NOT TRUE;

    UPDATE unified_sites u SET thumbnail_url = r.old_thumbnail
      FROM _ih_uninsert r
     WHERE u.id = r.site_id AND r.new_thumbnail IS DISTINCT FROM r.old_thumbnail
       AND u.thumbnail_url IS DISTINCT FROM r.old_thumbnail;

    -- the journal goes with the write it describes
    DELETE FROM remediation_change_log l USING _ih_uninsert r
     WHERE l.run_stamp = 'insert-2026-10-07-005-001' AND l.change_key LIKE r.change_key || '%';
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-005-001';
SELECT 'rows this chunk created',
       count(*)::text
  FROM wiki_images w
  JOIN _ih_uninsert r ON w.site_id = r.site_id AND w.original_url = r.original_url
                    AND w.file_size_bytes = r.file_size_bytes;
COMMIT;
