-- plan sha256 90d9f7c184ced2b103104c0a53febd477c59f483ffc6c016f5ee4943764072aa
-- Generated by scripts/remediation/mechanical/apply.py - do not edit by hand.
-- 2 row(s) over 1 site(s); scope source_id = 'ancient_nerds';
-- run stamp '2026-09-29_mechanical-chiapa-name-rollback'; journal test id 'Nr7/rename'.
-- Every UPDATE is conditioned on the old value the plan names; every change is journalled
-- in the same transaction, so the audit trail cannot disagree with the data.
\set ON_ERROR_STOP on
BEGIN;

-- The server bounds this transaction itself: a lock wait or a runaway statement raises
-- here, psql stops the script (exit 3) and nothing is kept. A client that gives up does
-- not stop the server - psql has the whole script on its stdin.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _chiapa_name_plan (
    site_id     UUID NOT NULL,
    column_name TEXT NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    premise     TEXT NOT NULL,
    evidence    JSONB NOT NULL,
    PRIMARY KEY (site_id, column_name)
) ON COMMIT DROP;

INSERT INTO _chiapa_name_plan (site_id, column_name, old_value, new_value, change_key, reason, premise, evidence) VALUES
    ('ed186ea9-9ed1-415d-828b-97d9f21401d2'::uuid, 'name', 'Chiapa de Corzo', 'Zoque Culture Archaeological Zone', 'chiapa-name-rollback:ed186ea9-9ed1-415d-828b-97d9f21401d2:name', 'rollback of chiapa-name: name ''Zoque Culture Archaeological Zone'' restored on Zoque Culture Archaeological Zone', 'duplicates retired onto it: 1, highest id 24aa135d-4714-47f5-96c0-d58f0bc04b6f', '[{"source": "output/remediation/HUMAN_ONLY_DECISIONS_2026-09-26.md", "url": null, "quote": "Nr. 7: eine Stätte, Richtung wie empfohlen - Chiapa de Corzo ausblenden (duplicate_of:ed186ea9...) und die Zoque-Zeile in ''Chiapa de Corzo'' umbenennen"}, {"source": "wikidata:Q4384315 en label", "url": "https://www.wikidata.org/wiki/Q4384315", "quote": "en label = ''Chiapa de Corzo'' (bcases/names.jsonl, read 2026-09-23)"}, {"source": "production:unified_sites", "url": null, "quote": "''Chiapa de Corzo'' (24aa135d-4714-47f5-96c0-d58f0bc04b6f): 0 content link(s), 0 image(s), external ids none; ''Zoque Culture Archaeological Zone'' (ed186ea9-9ed1-415d-828b-97d9f21401d2): 3 content link(s), 20 image(s), external ids enwiki_title=Chiapa de Corzo (Mesoamerican site), wikidata_qid=Q4384315; 7.4 m apart (read 2026-09-29 15:49:43.193037+00)"}]'::jsonb),
    ('ed186ea9-9ed1-415d-828b-97d9f21401d2'::uuid, 'name_normalized', 'chiapa de corzo', 'zoque culture archaeological zone', 'chiapa-name-rollback:ed186ea9-9ed1-415d-828b-97d9f21401d2:name_normalized', 'rollback of chiapa-name: name_normalized ''zoque culture archaeological zone'' restored on Zoque Culture Archaeological Zone', 'duplicates retired onto it: 1, highest id 24aa135d-4714-47f5-96c0-d58f0bc04b6f', '[{"source": "output/remediation/HUMAN_ONLY_DECISIONS_2026-09-26.md", "url": null, "quote": "Nr. 7: eine Stätte, Richtung wie empfohlen - Chiapa de Corzo ausblenden (duplicate_of:ed186ea9...) und die Zoque-Zeile in ''Chiapa de Corzo'' umbenennen"}, {"source": "wikidata:Q4384315 en label", "url": "https://www.wikidata.org/wiki/Q4384315", "quote": "en label = ''Chiapa de Corzo'' (bcases/names.jsonl, read 2026-09-23)"}, {"source": "production:unified_sites", "url": null, "quote": "''Chiapa de Corzo'' (24aa135d-4714-47f5-96c0-d58f0bc04b6f): 0 content link(s), 0 image(s), external ids none; ''Zoque Culture Archaeological Zone'' (ed186ea9-9ed1-415d-828b-97d9f21401d2): 3 content link(s), 20 image(s), external ids enwiki_title=Chiapa de Corzo (Mesoamerican site), wikidata_qid=Q4384315; 7.4 m apart (read 2026-09-29 15:49:43.193037+00)"}]'::jsonb);

DO $$
DECLARE
    bad      INTEGER;
    moved    INTEGER := 0;
    expected INTEGER := 2;
    r        RECORD;
BEGIN
    -- expected is the plan's own row count, rendered here, and not a second count of the
    -- temp table the loop below iterates: counting the same table twice would make the
    -- comparison after the loop a tautology. The instance that makes a short loop
    -- unreachable is apply_remediation_change, which raises unless exactly one row
    -- matched; this guard is what reports a loop that changed fewer rows than the plan.

    -- scope guard 1: every planned row is a curated site that still exists
    SELECT count(*) INTO bad
      FROM _chiapa_name_plan p LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        -- the source name is a RAISE argument, never part of the quoted message: a name
        -- spliced into the message text only parses while the name happens to contain no
        -- quote, which is a property of today's value and not of this code. G0's guard is
        -- the shape this one copies.
        RAISE EXCEPTION 'Nr 7 rename: % planned row(s) are not % sites', bad, 'ancient_nerds';
    END IF;

    -- scope guard 2: the plan is a set of real changes, each one writable in its column
    -- (compared in the column's own type; CASE, because only CASE fixes the order in
    -- which the casts are evaluated)
    SELECT count(*) INTO bad FROM _chiapa_name_plan p
     WHERE p.new_value = '' OR CASE p.column_name
                WHEN 'name' THEN p.new_value::character varying IS NOT DISTINCT FROM p.old_value::character varying OR p.old_value IS NULL OR p.new_value IS NULL OR length(p.new_value) > 500
                WHEN 'name_normalized' THEN p.new_value::character varying IS NOT DISTINCT FROM p.old_value::character varying OR p.old_value IS NULL OR p.new_value IS NULL OR length(p.new_value) > 500
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 rename: % planned row(s) are not writable changes', bad;
    END IF;

    -- scope guard 3: every planned row still holds the old value the plan names
    SELECT count(*) INTO bad
      FROM _chiapa_name_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE CASE p.column_name
                WHEN 'name' THEN u.name IS DISTINCT FROM p.old_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS DISTINCT FROM p.old_value::character varying
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 rename: % planned row(s) no longer hold the planned old value', bad;
    END IF;

    -- scope guard 5: every planned row still holds the input its value was derived from
    SELECT count(*) INTO bad
      FROM (SELECT DISTINCT site_id, premise FROM _chiapa_name_plan) p JOIN unified_sites u ON u.id = p.site_id
     WHERE ('duplicates retired onto it: ' || CAST((SELECT count(*) FROM unified_sites d WHERE d.source_id = 'ancient_nerds' AND d.scope_status = 'retired' AND d.scope_reason = 'duplicate_of:' || CAST(u.id AS text)) AS text) || ', highest id ' || coalesce((SELECT max(CAST(d.id AS text)) FROM unified_sites d WHERE d.source_id = 'ancient_nerds' AND d.scope_status = 'retired' AND d.scope_reason = 'duplicate_of:' || CAST(u.id AS text)), 'none')) IS DISTINCT FROM p.premise;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 rename: % planned row(s) no longer hold the premise the plan derived its value from', bad;
    END IF;

    -- the only writer: the conditional UPDATE and its journal row commit together, and
    -- the function raises unless exactly one row matched
    FOR r IN SELECT * FROM _chiapa_name_plan ORDER BY site_id, column_name LOOP
        moved := moved + apply_remediation_change(
            'unified_sites', r.column_name, 'id', r.site_id::text,
            r.old_value, r.new_value,
            'Nr7/rename', '2026-09-29_mechanical-chiapa-name-rollback', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;

    IF moved <> expected THEN
        RAISE EXCEPTION 'Nr 7 rename: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds the new value
    SELECT count(*) INTO bad
      FROM _chiapa_name_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE CASE p.column_name
                WHEN 'name' THEN u.name IS DISTINCT FROM p.new_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS DISTINCT FROM p.new_value::character varying
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 rename: % planned row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: the journal and the data agree, row for row, in both directions
    SELECT count(*) INTO bad
      FROM _chiapa_name_plan p LEFT JOIN remediation_change_log l
        ON l.row_pk = p.site_id::text AND l.table_name = 'unified_sites'
       AND l.column_name = p.column_name
       AND l.run_stamp = '2026-09-29_mechanical-chiapa-name-rollback'
     WHERE l.id IS NULL
        OR l.new_value IS DISTINCT FROM p.new_value
        OR l.old_value IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 rename: % planned row(s) have no matching journal row', bad;
    END IF;

    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = '2026-09-29_mechanical-chiapa-name-rollback'
       AND (l.table_name <> 'unified_sites' OR l.column_name NOT IN ('name', 'name_normalized'));
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 rename: this run stamp journalled % row(s) outside unified_sites.(name, name_normalized)', bad;
    END IF;

    -- invariant 3, the lane's own: no planned site is one of the
    -- curated rows whose name_normalized is not the key of their name
    SELECT count(*) INTO bad FROM unified_sites
     WHERE id IN (SELECT site_id FROM _chiapa_name_plan)
       AND (name_normalized IS DISTINCT FROM left(lower(unaccent(name)), 500));
    IF bad > 0 THEN
        RAISE EXCEPTION 'Nr 7 rename: % planned site(s) break the lane invariant after the write', bad;
    END IF;

    RAISE NOTICE 'Nr 7 rename: % of % planned cell(s) changed and journalled over 1 curated site(s)',
        moved, expected;
END $$;

COMMIT;

-- Post-commit read: the numbers the report quotes, from the database, not from the plan.
SELECT 'journal rows for this run stamp' AS metric, count(*)::text AS value
  FROM remediation_change_log WHERE run_stamp = '2026-09-29_mechanical-chiapa-name-rollback'
UNION ALL
SELECT 'journal rows for this test id', count(*)::text
  FROM remediation_change_log WHERE test_id = 'Nr7/rename'
UNION ALL
SELECT 'planned rows now holding the new value', count(*)::text
  FROM remediation_change_log l
 WHERE l.run_stamp = '2026-09-29_mechanical-chiapa-name-rollback' AND l.table_name = 'unified_sites'
   AND l.column_name IN ('name', 'name_normalized')
   AND EXISTS (SELECT 1 FROM unified_sites u
                WHERE u.id::text = l.row_pk AND CASE l.column_name
                WHEN 'name' THEN u.name IS NOT DISTINCT FROM l.new_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS NOT DISTINCT FROM l.new_value::character varying
                ELSE false END)
UNION ALL
SELECT 'curated rows whose name_normalized is not the key of their name', count(*)::text
  FROM unified_sites
 WHERE source_id = 'ancient_nerds' AND name_normalized IS DISTINCT FROM left(lower(unaccent(name)), 500)
UNION ALL
SELECT 'curated sites', count(*)::text
  FROM unified_sites WHERE source_id = 'ancient_nerds';
