-- Generated by scripts/remediation/gallery_audit/chunk_writer.py - do not edit by hand.
-- plan sha256 f663ec0002aa261698dd575dabcfa4028d98297fb2d0535e88bb856fb2ad17f6
-- The write of lane 'import-hero', chunk 001: 3 row(s) over 3 site(s);
-- scope source_id = 'ancient_nerds'; run stamp 'import-hero-2026-10-06-008-001'; journal test id 'import-hero/owner-2026-10-05'.
-- Every row goes through apply_remediation_change() (migrations 0017/0018/0022): the conditional
-- UPDATE and its journal row are one statement. This file holds no DELETE and no UPDATE.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _img_plan (
    seq         INTEGER PRIMARY KEY,
    table_name  TEXT NOT NULL,
    column_name TEXT NOT NULL,
    row_key     TEXT NOT NULL,
    site_id     UUID NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    evidence    JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _img_plan (seq, table_name, column_name, row_key, site_id, old_value, new_value, change_key, reason, evidence) VALUES
    (1, 'unified_sites', 'thumbnail_url', '33d2d754-e50a-4305-beff-87d2ad2c0227', '33d2d754-e50a-4305-beff-87d2ad2c0227'::uuid, '/data/images/wiki/33d2d754/Geschichtetes, zyklopenhaftes Mauerwerk über Parmenon-Turm, aus Süd C.webp', '/data/images/wiki/33d2d754/Geschichtetes_Mauerwerk_über_Parmenon-Turm,_aus_Süd_C.webp', 'import-hero:unified_sites.thumbnail_url:33d2d754-e50a-4305-beff-87d2ad2c0227', 'ih4: the globe popup serves the thumbnail, which must name the file the page now serves (the hero repair''s T1 target)', '[{"quote": "the 2025 import links ''https://upload.wikimedia.org/wikipedia/commons/e/e1/Geschichtetes%2C_zyklopenhaftes_Mauerwerk_%C3%BCber_Parmenon-Turm%2C_aus_S%C3%BCd_C.jpg'' for ''Archaeological Site of Ancient Thasos''", "source": "ancient_nerds_original.geojson:Images", "url": "data/raw/ancient_nerds/ancient_nerds_original.geojson"}, {"quote": "id=67724 site_id=33d2d754-e50a-4305-beff-87d2ad2c0227 filename=''Geschichtetes_Mauerwerk_über_Parmenon-Turm,_aus_Süd_C.webp'' is_hero=True is_excluded=False", "source": "snapshot:wiki_images", "url": "wiki_images.id=67724"}, {"quote": "2026-10-05: everything the 2025 import links wins as hero; the 427 whose local file is under 1600x900 are fetched at 1600 px first", "source": "owner decision", "url": "output/remediation/GOAL_IMAGES.md"}]'::jsonb),
    (2, 'unified_sites', 'thumbnail_url', '417445b4-e0db-49ac-99db-fe236794e9ff', '417445b4-e0db-49ac-99db-fe236794e9ff'::uuid, '/data/images/wiki/417445b4/The East Facade pf the Parthenon on March 22, 2021.webp', '/data/images/wiki/417445b4/The_East_Facade_of_the_Parthenon_on_March_22,_2021.webp', 'import-hero:unified_sites.thumbnail_url:417445b4-e0db-49ac-99db-fe236794e9ff', 'ih4: the globe popup serves the thumbnail, which must name the file the page now serves (the hero repair''s T1 target)', '[{"quote": "the 2025 import links ''https://upload.wikimedia.org/wikipedia/commons/0/03/The_East_Facade_pf_the_Parthenon_on_March_22%2C_2021.jpg'' for ''Parthenon''", "source": "ancient_nerds_original.geojson:Images", "url": "data/raw/ancient_nerds/ancient_nerds_original.geojson"}, {"quote": "id=70613 site_id=417445b4-e0db-49ac-99db-fe236794e9ff filename=''The_East_Facade_of_the_Parthenon_on_March_22,_2021.webp'' is_hero=True is_excluded=False", "source": "snapshot:wiki_images", "url": "wiki_images.id=70613"}, {"quote": "2026-10-05: everything the 2025 import links wins as hero; the 427 whose local file is under 1600x900 are fetched at 1600 px first", "source": "owner decision", "url": "output/remediation/GOAL_IMAGES.md"}]'::jsonb),
    (3, 'unified_sites', 'thumbnail_url', '55d6f958-6ee7-4a0a-9e3c-23bbdb63d571', '55d6f958-6ee7-4a0a-9e3c-23bbdb63d571'::uuid, '/data/images/wiki/55d6f958/East Terrace (4961323529).webp', '/data/images/wiki/55d6f958/Mount_Nemrut_-_East_Terrace_(4961323529).webp', 'import-hero:unified_sites.thumbnail_url:55d6f958-6ee7-4a0a-9e3c-23bbdb63d571', 'ih4: the globe popup serves the thumbnail, which must name the file the page now serves (the hero repair''s T1 target)', '[{"quote": "the 2025 import links ''https://upload.wikimedia.org/wikipedia/commons/a/a1/East_Terrace_%284961323529%29.jpg'' for ''Mount Nemrut''", "source": "ancient_nerds_original.geojson:Images", "url": "data/raw/ancient_nerds/ancient_nerds_original.geojson"}, {"quote": "id=74223 site_id=55d6f958-6ee7-4a0a-9e3c-23bbdb63d571 filename=''Mount_Nemrut_-_East_Terrace_(4961323529).webp'' is_hero=True is_excluded=False", "source": "snapshot:wiki_images", "url": "wiki_images.id=74223"}, {"quote": "2026-10-05: everything the 2025 import links wins as hero; the 427 whose local file is under 1600x900 are fetched at 1600 px first", "source": "owner decision", "url": "output/remediation/GOAL_IMAGES.md"}]'::jsonb);

CREATE TEMP TABLE _img_may_empty (site_id UUID PRIMARY KEY) ON COMMIT DROP;
-- no site of this chunk may lose its last live image

CREATE TEMP TABLE _img_live_before ON COMMIT DROP AS
  SELECT DISTINCT w.site_id FROM wiki_images w
   WHERE w.site_id IN (SELECT site_id FROM _img_plan) AND w.is_excluded IS NOT TRUE;

DO $$
DECLARE
    bad      integer;
    moved    integer := 0;
    expected integer := 3;
    r        RECORD;
BEGIN
    -- guard 1: every planned site is a curated site (the source is a RAISE argument, never
    -- part of the quoted message)
    SELECT count(*) INTO bad FROM (SELECT DISTINCT site_id FROM _img_plan) p
      LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % planned site(s) are not % sites', bad, 'ancient_nerds';
    END IF;

    -- guard 2: every planned image row exists and lives on the site the plan names
    SELECT count(*) INTO bad FROM _img_plan p
      LEFT JOIN wiki_images w ON w.id = CASE WHEN p.table_name = 'wiki_images' THEN p.row_key::integer END
     WHERE p.table_name = 'wiki_images' AND (w.id IS NULL OR w.site_id IS DISTINCT FROM p.site_id);
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % planned image row(s) do not live on the site the plan names', bad;
    END IF;

    -- guard 3: every planned row still holds the planned old value (NULL-safe)

    SELECT count(*) INTO bad FROM _img_plan p JOIN unified_sites t ON t.id = CASE WHEN p.table_name = 'unified_sites' THEN p.row_key::uuid END
     WHERE p.table_name = 'unified_sites' AND p.column_name = 'thumbnail_url'
       AND t.thumbnail_url::text IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % planned thumbnail_url row(s) no longer hold the planned old value', bad;
    END IF;

    -- the only writer
    FOR r IN SELECT * FROM _img_plan ORDER BY seq LOOP
        moved := moved + apply_remediation_change(
            r.table_name, r.column_name, 'id', r.row_key, r.old_value, r.new_value,
            'import-hero/owner-2026-10-05', 'import-hero-2026-10-06-008-001', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;
    IF moved <> expected THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds its new value

    SELECT count(*) INTO bad FROM _img_plan p JOIN unified_sites t ON t.id = CASE WHEN p.table_name = 'unified_sites' THEN p.row_key::uuid END
     WHERE p.table_name = 'unified_sites' AND p.column_name = 'thumbnail_url'
       AND t.thumbnail_url::text IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % planned thumbnail_url row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: plan -> journal, row for row, with the planned values and keys
    SELECT count(*) INTO bad FROM _img_plan p
      LEFT JOIN remediation_change_log l
        ON l.run_stamp = 'import-hero-2026-10-06-008-001' AND l.table_name = p.table_name
       AND l.column_name = p.column_name AND l.row_pk = p.row_key
     WHERE l.id IS NULL OR l.old_value IS DISTINCT FROM p.old_value
        OR l.new_value IS DISTINCT FROM p.new_value OR l.change_key IS DISTINCT FROM p.change_key;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % planned row(s) disagree with the journal', bad;
    END IF;

    -- invariant 3: journal -> plan: this run stamp journalled the planned rows and nothing else
    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = 'import-hero-2026-10-06-008-001'
       AND NOT EXISTS (SELECT 1 FROM _img_plan p
                        WHERE p.table_name = l.table_name AND p.column_name = l.column_name
                          AND p.row_key = l.row_pk);
    IF bad > 0 OR (SELECT count(*) FROM remediation_change_log WHERE run_stamp = 'import-hero-2026-10-06-008-001') <> expected THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: the journal of this run stamp is not the plan (% unplanned row(s))', bad;
    END IF;

    -- invariant 4: at most one hero per touched site
    -- the invariant the repair must leave behind: at most one hero per touched site
    -- (DISTINCT: _img_plan holds several rows per site, and a plain join would count each
    --  hero row twice - the check would then fail on a correct repair)
    SELECT count(*) INTO bad FROM (
        SELECT s.site_id FROM (SELECT DISTINCT site_id FROM _img_plan) s
          JOIN wiki_images w ON w.site_id = s.site_id
         GROUP BY s.site_id HAVING count(*) FILTER (WHERE w.is_hero) > 1) x;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % touched site(s) end with more than one hero', bad;
    END IF;

    -- invariant 5: no hero on an excluded row of a touched site
    SELECT count(*) INTO bad FROM wiki_images w
     WHERE w.site_id IN (SELECT site_id FROM _img_plan) AND w.is_hero AND w.is_excluded IS TRUE;
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % hero row(s) are excluded', bad;
    END IF;

    -- invariant 6: a touched site that had a live image still has one, unless the chunk names it
    SELECT count(*) INTO bad FROM _img_live_before b
     WHERE NOT EXISTS (SELECT 1 FROM wiki_images w
                        WHERE w.site_id = b.site_id AND w.is_excluded IS NOT TRUE)
       AND b.site_id NOT IN (SELECT site_id FROM _img_may_empty);
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % site(s) lost their last live image', bad;
    END IF;

    -- invariant 7: every image kind of a touched row is in migration 0019's vocabulary
    SELECT count(*) INTO bad FROM wiki_images w
     WHERE w.site_id IN (SELECT site_id FROM _img_plan)
       AND w.image_kind IS NOT NULL AND w.image_kind NOT IN ('artifact', 'map_or_document', 'other', 'painting_or_artwork', 'people', 'site_photo', 'unknown');
    IF bad > 0 THEN
        RAISE EXCEPTION 'import-hero import-hero-2026-10-06-008 - the import image takes the hero flag chunk 001: % image kind(s) outside the vocabulary', bad;
    END IF;
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'import-hero-2026-10-06-008-001';
SELECT 'planned rows', count(*)::text FROM _img_plan;
COMMIT;
