-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: 1e3d36a4fbf200634adf76ceca530d42797dc4af84d9104b9f4e1d79303aba7e
-- lane 'ih6' (import-hero/insert), 7 row(s) to create; run stamp 'insert-2026-10-07-011-001'.
-- Every row is created together with its journal rows, inside this transaction: a journal that
-- disagrees with the data cannot be committed, and a rolled-back statement leaves nothing behind.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_insert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    filename          TEXT NOT NULL,
    original_url      TEXT NOT NULL,
    commons_page_url  TEXT NOT NULL,
    title             TEXT NOT NULL,
    author            TEXT NOT NULL,
    author_url        TEXT NOT NULL,
    license           TEXT NOT NULL,
    license_url       TEXT NOT NULL,
    width             INTEGER NOT NULL,
    height            INTEGER NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT NOT NULL,
    change_key        TEXT NOT NULL,
    reason            TEXT NOT NULL,
    evidence          JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_insert (seq, site_id, filename, original_url, commons_page_url, title, author, author_url, license, license_url, width, height, file_size_bytes, demoted_id, old_thumbnail, new_thumbnail, change_key, reason, evidence) VALUES
    (1, '58a5a5b2-735a-4fda-bf2d-52e723fd86bc'::uuid, 'Volubilis mosaic Bacchus and Ariadne.webp', 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Volubilis_mosaic_Bacchus_and_Ariadne.jpg', 'https://commons.wikimedia.org/wiki/File%3AVolubilis%20mosaic%20Bacchus%20and%20Ariadne.jpg', 'Volubilis mosaic Bacchus and Ariadne', 'Prioryman', 'https://commons.wikimedia.org/wiki/User:Prioryman', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', 1500, 1477, 784912, NULL, NULL, '/data/images/wiki/58a5a5b2/Volubilis mosaic Bacchus and Ariadne.webp', 'import-hero/insert:58a5a5b2-735a-4fda-bf2d-52e723fd86bc', 'the 2025 import''s own link for this site, recorded as ''https://upload.wikimedia.org/wikipedia/commons/b/b2/Volubilis_mosaic_Bacchus_and_Ariadne.jpg'' in import-hero-2026-10-06-009/IMPORT_CLAIMS.json; the site showed nothing at all - no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Volubilis_mosaic_Bacchus_and_Ariadne.jpg", "source": "the import run import-hero-2026-10-06-009, which refused this site as ''no_target_row'' because its rows hold no file of the import", "url": "https://commons.wikimedia.org/wiki/File%3AVolubilis%20mosaic%20Bacchus%20and%20Ariadne.jpg"}, {"quote": "20 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/b/b2/Volubilis_mosaic_Bacchus_and_Ariadne.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 58a5a5b2-735a-4fda-bf2d-52e723fd86bc"}]'::jsonb),
    (2, '6c09f12a-a657-4395-8bc6-d3903f4eaa27'::uuid, 'Clachtoll Broch 20090612 02.webp', 'https://upload.wikimedia.org/wikipedia/commons/8/81/Clachtoll_Broch_20090612_02.jpg', 'https://commons.wikimedia.org/wiki/File%3AClachtoll%20Broch%2020090612%2002.jpg', 'Clachtoll Broch 20090612 02', 'Otter', 'https://commons.wikimedia.org/wiki/User:Otter', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0', 800, 534, 64664, NULL, NULL, '/data/images/wiki/6c09f12a/Clachtoll Broch 20090612 02.webp', 'import-hero/insert:6c09f12a-a657-4395-8bc6-d3903f4eaa27', 'the 2025 import''s own link for this site, recorded as ''https://upload.wikimedia.org/wikipedia/commons/8/81/Clachtoll_Broch_20090612_02.jpg'' in import-hero-2026-10-06-009/IMPORT_CLAIMS.json; the site showed nothing at all - no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/8/81/Clachtoll_Broch_20090612_02.jpg", "source": "the import run import-hero-2026-10-06-009, which refused this site as ''no_target_row'' because its rows hold no file of the import", "url": "https://commons.wikimedia.org/wiki/File%3AClachtoll%20Broch%2020090612%2002.jpg"}, {"quote": "20 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/8/81/Clachtoll_Broch_20090612_02.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 6c09f12a-a657-4395-8bc6-d3903f4eaa27"}]'::jsonb),
    (3, '82c9fb95-c776-4450-bb5c-93a70fdcb056'::uuid, 'Grand Cenote 20101006.webp', 'https://upload.wikimedia.org/wikipedia/commons/2/23/Grand_Cenote_20101006.jpg', 'https://commons.wikimedia.org/wiki/File%3AGrand%20Cenote%2020101006.jpg', 'Grand Cenote 20101006', 'anjči from London, UK', 'https://www.flickr.com/photos/9899582@N05', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', 1286, 854, 297024, NULL, NULL, '/data/images/wiki/82c9fb95/Grand Cenote 20101006.webp', 'import-hero/insert:82c9fb95-c776-4450-bb5c-93a70fdcb056', 'the 2025 import''s own link for this site, recorded as ''https://upload.wikimedia.org/wikipedia/commons/2/23/Grand_Cenote_20101006.jpg'' in import-hero-2026-10-06-009/IMPORT_CLAIMS.json; the site showed nothing at all - no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/2/23/Grand_Cenote_20101006.jpg", "source": "the import run import-hero-2026-10-06-009, which refused this site as ''no_target_row'' because its rows hold no file of the import", "url": "https://commons.wikimedia.org/wiki/File%3AGrand%20Cenote%2020101006.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/2/23/Grand_Cenote_20101006.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 82c9fb95-c776-4450-bb5c-93a70fdcb056"}]'::jsonb),
    (4, '83893760-fcb6-4824-8ee9-7e1c6fc74852'::uuid, 'Dead Womans Ditch (geograph 2880447).webp', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Dead_Womans_Ditch_%28geograph_2880447%29.jpg', 'https://commons.wikimedia.org/wiki/File%3ADead%20Womans%20Ditch%20%28geograph%202880447%29.jpg', 'Dead Womans Ditch (geograph 2880447)', 'Stephen McKay', 'https://www.geograph.org.uk/profile/1621', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0', 1280, 856, 269498, NULL, NULL, '/data/images/wiki/83893760/Dead Womans Ditch (geograph 2880447).webp', 'import-hero/insert:83893760-fcb6-4824-8ee9-7e1c6fc74852', 'the 2025 import''s own link for this site, recorded as ''https://upload.wikimedia.org/wikipedia/commons/9/92/Dead_Womans_Ditch_%28geograph_2880447%29.jpg'' in import-hero-2026-10-06-009/IMPORT_CLAIMS.json; the site showed nothing at all - no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/9/92/Dead_Womans_Ditch_%28geograph_2880447%29.jpg", "source": "the import run import-hero-2026-10-06-009, which refused this site as ''no_target_row'' because its rows hold no file of the import", "url": "https://commons.wikimedia.org/wiki/File%3ADead%20Womans%20Ditch%20%28geograph%202880447%29.jpg"}, {"quote": "1 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/9/92/Dead_Womans_Ditch_%28geograph_2880447%29.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 83893760-fcb6-4824-8ee9-7e1c6fc74852"}]'::jsonb),
    (5, '87d83a5b-d7a2-45dc-b8fd-1bed588bbeec'::uuid, 'Bhutalinga caves chaitya.webp', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg', 'https://commons.wikimedia.org/wiki/File%3ABhutalinga%20caves%20chaitya.jpg', 'Bhutalinga caves chaitya', 'Kevin Standage (kevinstandage1@googlemail.com) INDIAN TRAVEL PHOTOGRAPHY', 'https://kevinstandagephotography.wordpress.com/about/', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0', 1200, 1800, 341520, NULL, NULL, '/data/images/wiki/87d83a5b/Bhutalinga caves chaitya.webp', 'import-hero/insert:87d83a5b-d7a2-45dc-b8fd-1bed588bbeec', 'the 2025 import''s own link for this site, recorded as ''https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg'' in import-hero-2026-10-06-009/IMPORT_CLAIMS.json; the site showed nothing at all - no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg", "source": "the import run import-hero-2026-10-06-009, which refused this site as ''no_target_row'' because its rows hold no file of the import", "url": "https://commons.wikimedia.org/wiki/File%3ABhutalinga%20caves%20chaitya.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 87d83a5b-d7a2-45dc-b8fd-1bed588bbeec"}]'::jsonb),
    (6, '8ef3e56e-3dd8-4576-a5bf-eab965bcd0a7'::uuid, 'Bhutalinga caves chaitya.webp', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg', 'https://commons.wikimedia.org/wiki/File%3ABhutalinga%20caves%20chaitya.jpg', 'Bhutalinga caves chaitya', 'Kevin Standage (kevinstandage1@googlemail.com) INDIAN TRAVEL PHOTOGRAPHY', 'https://kevinstandagephotography.wordpress.com/about/', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0', 1200, 1800, 341520, NULL, NULL, '/data/images/wiki/8ef3e56e/Bhutalinga caves chaitya.webp', 'import-hero/insert:8ef3e56e-3dd8-4576-a5bf-eab965bcd0a7', 'the 2025 import''s own link for this site, recorded as ''https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg'' in import-hero-2026-10-06-009/IMPORT_CLAIMS.json; the site showed nothing at all - no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg", "source": "the import run import-hero-2026-10-06-009, which refused this site as ''no_target_row'' because its rows hold no file of the import", "url": "https://commons.wikimedia.org/wiki/File%3ABhutalinga%20caves%20chaitya.jpg"}, {"quote": "0 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = 8ef3e56e-3dd8-4576-a5bf-eab965bcd0a7"}]'::jsonb),
    (7, 'a2704598-c3b7-4cbb-9fdc-4055c445cec1'::uuid, 'ShafttombMNAH.webp', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/ShafttombMNAH.jpg', 'https://commons.wikimedia.org/wiki/File%3AShafttombMNAH.jpg', 'ShafttombMNAH', '·Maunus·ƛ·', 'https://en.wikipedia.org/wiki/User:Maunus', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', 1067, 709, 76464, NULL, NULL, '/data/images/wiki/a2704598/ShafttombMNAH.webp', 'import-hero/insert:a2704598-c3b7-4cbb-9fdc-4055c445cec1', 'the 2025 import''s own link for this site, recorded as ''https://upload.wikimedia.org/wikipedia/commons/f/f0/ShafttombMNAH.jpg'' in import-hero-2026-10-06-009/IMPORT_CLAIMS.json; the site showed nothing at all - no gallery row and no thumbnail_url (owner decision 2026-10-06)', '[{"quote": "https://upload.wikimedia.org/wikipedia/commons/f/f0/ShafttombMNAH.jpg", "source": "the import run import-hero-2026-10-06-009, which refused this site as ''no_target_row'' because its rows hold no file of the import", "url": "https://commons.wikimedia.org/wiki/File%3AShafttombMNAH.jpg"}, {"quote": "20 row(s) of this site, none holding https://upload.wikimedia.org/wikipedia/commons/f/f0/ShafttombMNAH.jpg", "source": "the plan''s read of production", "url": "wiki_images WHERE site_id = a2704598-c3b7-4cbb-9fdc-4055c445cec1"}]'::jsonb);

DO $$
DECLARE
    bad  integer;
    r    RECORD;
    new_id integer;
    cols TEXT;
BEGIN
    -- guard 1: every planned site is a curated site (the message names the source in words, so
    -- the log of a refused wave says what was expected)
    SELECT count(*) INTO bad FROM (SELECT DISTINCT site_id FROM _ih_insert) p
      LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % planned site(s) are not ancient_nerds sites',
            'insert-2026-10-07-011-001', bad;
    END IF;

    FOR r IN SELECT * FROM _ih_insert ORDER BY seq LOOP
        -- guard 2: no row of this site holds the file yet. The unique constraint on
        -- (site_id, original_url) is a second line of defence behind this one.
        IF EXISTS (SELECT 1 FROM wiki_images w
                    WHERE w.site_id = r.site_id AND w.original_url = r.original_url) THEN
            RAISE EXCEPTION '%: site % already holds this file', r.change_key, r.site_id;
        END IF;

        -- guard 3: the file reaches this run's floor
        IF r.width < 800 OR r.height < 300 THEN
            RAISE EXCEPTION '%: the file is %x%, under the %x% this run serves', r.change_key,
                r.width, r.height, 800, 300;
        END IF;

        -- guard 4: the row that holds the flag is still the one the plan demotes
        IF r.demoted_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM wiki_images w
             WHERE w.id = r.demoted_id AND w.site_id = r.site_id AND w.is_hero) THEN
            RAISE EXCEPTION '%: the row that held the flag for site % moved since the read',
                r.change_key, r.site_id;
        END IF;

        -- guard 5: the thumbnail still holds the value the read found
        IF (SELECT u.thumbnail_url FROM unified_sites u WHERE u.id = r.site_id)
           IS DISTINCT FROM r.old_thumbnail THEN
            RAISE EXCEPTION '%: the thumbnail of site % moved since the read', r.change_key, r.site_id;
        END IF;

        -- the row that gives up the flag, and the row that takes it
        IF r.demoted_id IS NOT NULL THEN
            UPDATE wiki_images SET is_hero = false
             WHERE id = r.demoted_id AND is_hero AND site_id = r.site_id;
        END IF;

        -- the three columns the file does not carry: the next free number of this site (derived,
        -- never invented), the owner's picture rather than a measured lead image of the article,
        -- and the source 49,683 of the 49,691 curated rows carry
        INSERT INTO wiki_images
            (site_id, filename, original_url, commons_page_url, title, author, author_url, license, license_url, width, height, file_size_bytes, is_lead, sort_order, source_type, is_hero, is_excluded)
        SELECT r.site_id, r.filename, r.original_url, r.commons_page_url, r.title, r.author, r.author_url, r.license, r.license_url, r.width, r.height, r.file_size_bytes, false,
               (SELECT COALESCE(MAX(w2.sort_order), -1) + 1 FROM wiki_images w2
                 WHERE w2.site_id = r.site_id),
               'wikimedia', true, false
        RETURNING id INTO new_id;

        IF r.new_thumbnail IS DISTINCT FROM r.old_thumbnail THEN
            UPDATE unified_sites SET thumbnail_url = r.new_thumbnail WHERE id = r.site_id;
        END IF;

        -- the journal, in this transaction: one row per column this statement wrote,
        -- read back from the row it created, so the journal records what the database holds
        INSERT INTO remediation_change_log
            (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value, change_key,
             confidence, evidence, site_id_ref)
        SELECT 'insert-2026-10-07-011-001', 'import-hero/insert/owner-2026-10-05', 'wiki_images', t.col, new_id::text, NULL, t.val,
               r.change_key || ':' || t.col, 'authoritative', r.evidence, r.site_id
          FROM wiki_images w
          CROSS JOIN LATERAL (VALUES
              ('filename', w.filename::text),
              ('original_url', w.original_url::text),
              ('commons_page_url', w.commons_page_url::text),
              ('title', w.title::text),
              ('author', w.author::text),
              ('author_url', w.author_url::text),
              ('license', w.license::text),
              ('license_url', w.license_url::text),
              ('width', w.width::text),
              ('height', w.height::text),
              ('file_size_bytes', w.file_size_bytes::text),
              ('is_lead', w.is_lead::text),
              ('sort_order', w.sort_order::text),
              ('source_type', w.source_type::text)
          ) AS t(col, val)
         WHERE w.id = new_id;

        IF r.demoted_id IS NOT NULL THEN
            INSERT INTO remediation_change_log
                (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value,
                 change_key, confidence, evidence, site_id_ref)
            VALUES ('insert-2026-10-07-011-001', 'import-hero/insert/owner-2026-10-05', 'wiki_images', 'is_hero',
                    r.demoted_id::text, 'true', 'false', r.change_key || ':demote',
                    'authoritative', r.evidence, r.site_id);
        END IF;

        IF r.new_thumbnail IS DISTINCT FROM r.old_thumbnail THEN
            INSERT INTO remediation_change_log
                (run_stamp, test_id, table_name, column_name, row_pk, old_value, new_value,
                 change_key, confidence, evidence, site_id_ref)
            VALUES ('insert-2026-10-07-011-001', 'import-hero/insert/owner-2026-10-05', 'unified_sites', 'thumbnail_url',
                    r.site_id::text, r.old_thumbnail, r.new_thumbnail,
                    r.change_key || ':thumbnail', 'authoritative', r.evidence, r.site_id);
        END IF;
    END LOOP;

    -- invariant 1: every planned row stands, with the planned values, the flag and the three
    -- columns the statement derived for it. The temp table is aliased `p`, never `r`: the loop
    -- variable of this block is `r`, and Postgres refuses a reference that could mean either
    -- (measured 2026-10-06, in the rehearsal of chunk-001).
    SELECT count(*) INTO bad FROM _ih_insert p
      LEFT JOIN wiki_images w ON w.site_id = p.site_id AND w.original_url = p.original_url
     WHERE w.id IS NULL OR w.is_hero IS NOT TRUE OR w.is_excluded IS NOT FALSE
        OR w.width IS DISTINCT FROM p.width OR w.height IS DISTINCT FROM p.height
        OR w.file_size_bytes IS DISTINCT FROM p.file_size_bytes
        OR w.filename IS DISTINCT FROM p.filename OR w.original_url IS DISTINCT FROM p.original_url
        OR w.is_lead IS NOT FALSE OR w.source_type IS DISTINCT FROM 'wikimedia'
        OR w.sort_order <> (SELECT COALESCE(MAX(w3.sort_order), 0) FROM wiki_images w3
                             WHERE w3.site_id = p.site_id);
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % inserted row(s) do not stand as planned', 'insert-2026-10-07-011-001', bad;
    END IF;

    -- invariant 2: at most one live hero per touched site (T09's invariant)
    SELECT count(*) INTO bad FROM (
        SELECT w.site_id FROM wiki_images w
          JOIN _ih_insert p ON p.site_id = w.site_id
         WHERE w.is_hero AND w.is_excluded IS NOT TRUE
         GROUP BY w.site_id HAVING count(*) > 1) d;
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % touched site(s) hold more than one live hero row',
            'insert-2026-10-07-011-001', bad;
    END IF;

    -- invariant 3: the journal carries every write, and nothing else
    SELECT count(*) INTO bad FROM _ih_insert p
      LEFT JOIN (SELECT site_id_ref, count(*) AS n FROM remediation_change_log
                  WHERE run_stamp = 'insert-2026-10-07-011-001' GROUP BY site_id_ref) l
        ON l.site_id_ref = p.site_id
     WHERE COALESCE(l.n, 0) <> 14
        + CASE WHEN p.demoted_id IS NOT NULL THEN 1 ELSE 0 END
        + CASE WHEN p.new_thumbnail IS DISTINCT FROM p.old_thumbnail THEN 1 ELSE 0 END;
    IF bad > 0 THEN
        RAISE EXCEPTION '%: % site(s) do not have exactly their planned journal rows',
            'insert-2026-10-07-011-001', bad;
    END IF;
END $$;

-- the same two read-back lines the shared writer ends with, so `--rehearse` recognises the run
SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-011-001';
SELECT 'planned rows', count(*)::text FROM _ih_insert;
COMMIT;
