-- Generated by scripts/remediation/import_hero/insert.py - do not edit by hand.
-- pin: 1e3d36a4fbf200634adf76ceca530d42797dc4af84d9104b9f4e1d79303aba7e
-- The reversal of lane 'ih6': the rows this wave created go back out, the flag returns to
-- the row that held it, and the thumbnail returns to the value the read found.
-- The row is named by the triple this lane wrote - (site_id, original_url, file_size_bytes) - so
-- the statement cannot delete a row somebody else created.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE _ih_uninsert (
    seq               INTEGER PRIMARY KEY,
    site_id           UUID NOT NULL,
    original_url      TEXT NOT NULL,
    file_size_bytes   INTEGER NOT NULL,
    demoted_id        INTEGER,
    old_thumbnail     TEXT,
    new_thumbnail     TEXT,
    change_key        TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _ih_uninsert VALUES
    (1, '58a5a5b2-735a-4fda-bf2d-52e723fd86bc'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Volubilis_mosaic_Bacchus_and_Ariadne.jpg', 784912, NULL, NULL, '/data/images/wiki/58a5a5b2/Volubilis mosaic Bacchus and Ariadne.webp', 'import-hero/insert:58a5a5b2-735a-4fda-bf2d-52e723fd86bc'),
    (2, '6c09f12a-a657-4395-8bc6-d3903f4eaa27'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/8/81/Clachtoll_Broch_20090612_02.jpg', 64664, NULL, NULL, '/data/images/wiki/6c09f12a/Clachtoll Broch 20090612 02.webp', 'import-hero/insert:6c09f12a-a657-4395-8bc6-d3903f4eaa27'),
    (3, '82c9fb95-c776-4450-bb5c-93a70fdcb056'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/2/23/Grand_Cenote_20101006.jpg', 297024, NULL, NULL, '/data/images/wiki/82c9fb95/Grand Cenote 20101006.webp', 'import-hero/insert:82c9fb95-c776-4450-bb5c-93a70fdcb056'),
    (4, '83893760-fcb6-4824-8ee9-7e1c6fc74852'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/9/92/Dead_Womans_Ditch_%28geograph_2880447%29.jpg', 269498, NULL, NULL, '/data/images/wiki/83893760/Dead Womans Ditch (geograph 2880447).webp', 'import-hero/insert:83893760-fcb6-4824-8ee9-7e1c6fc74852'),
    (5, '87d83a5b-d7a2-45dc-b8fd-1bed588bbeec'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg', 341520, NULL, NULL, '/data/images/wiki/87d83a5b/Bhutalinga caves chaitya.webp', 'import-hero/insert:87d83a5b-d7a2-45dc-b8fd-1bed588bbeec'),
    (6, '8ef3e56e-3dd8-4576-a5bf-eab965bcd0a7'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/3/39/Bhutalinga_caves_chaitya.jpg', 341520, NULL, NULL, '/data/images/wiki/8ef3e56e/Bhutalinga caves chaitya.webp', 'import-hero/insert:8ef3e56e-3dd8-4576-a5bf-eab965bcd0a7'),
    (7, 'a2704598-c3b7-4cbb-9fdc-4055c445cec1'::uuid, 'https://upload.wikimedia.org/wikipedia/commons/f/f0/ShafttombMNAH.jpg', 76464, NULL, NULL, '/data/images/wiki/a2704598/ShafttombMNAH.webp', 'import-hero/insert:a2704598-c3b7-4cbb-9fdc-4055c445cec1');

DO $$
DECLARE
    bad integer;
BEGIN
    -- every named row is still the one this wave created
    SELECT count(*) INTO bad FROM _ih_uninsert r
      LEFT JOIN wiki_images w
        ON w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes
     WHERE w.id IS NULL;
    IF bad > 0 THEN
        RAISE EXCEPTION 'rollback %: % row(s) this wave created are not there to undo',
            'insert-2026-10-07-011-001', bad;
    END IF;

    DELETE FROM wiki_images w USING _ih_uninsert r
     WHERE w.site_id = r.site_id AND w.original_url = r.original_url
       AND w.file_size_bytes = r.file_size_bytes;

    UPDATE wiki_images w SET is_hero = true
      FROM _ih_uninsert r
     WHERE r.demoted_id IS NOT NULL AND w.id = r.demoted_id AND w.is_hero IS NOT TRUE;

    UPDATE unified_sites u SET thumbnail_url = r.old_thumbnail
      FROM _ih_uninsert r
     WHERE u.id = r.site_id AND r.new_thumbnail IS DISTINCT FROM r.old_thumbnail
       AND u.thumbnail_url IS DISTINCT FROM r.old_thumbnail;

    -- the journal goes with the write it describes
    DELETE FROM remediation_change_log l USING _ih_uninsert r
     WHERE l.run_stamp = 'insert-2026-10-07-011-001' AND l.change_key LIKE r.change_key || '%';
END $$;

SELECT 'journal rows for this run', count(*)::text FROM remediation_change_log WHERE run_stamp = 'insert-2026-10-07-011-001';
SELECT 'rows this chunk created',
       count(*)::text
  FROM wiki_images w
  JOIN _ih_uninsert r ON w.site_id = r.site_id AND w.original_url = r.original_url
                    AND w.file_size_bytes = r.file_size_bytes;
COMMIT;
