-- plan sha256 befaacad99ecadf33ba414a8bf21f67e037cecad1c6e4b003cfba9a02f774726
-- Generated by scripts/remediation/mechanical/apply.py - do not edit by hand.
-- 2 row(s) over 2 site(s); scope source_id = 'ancient_nerds';
-- run stamp '2026-09-26_mechanical-country-b2-rollback'; journal test id 'B2/country'.
-- Every UPDATE is conditioned on the old value the plan names; every change is journalled
-- in the same transaction, so the audit trail cannot disagree with the data.
\set ON_ERROR_STOP on
BEGIN;

-- The server bounds this transaction itself: a lock wait or a runaway statement raises
-- here, psql stops the script (exit 3) and nothing is kept. A client that gives up does
-- not stop the server - psql has the whole script on its stdin.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _country_b2_plan (
    site_id     UUID PRIMARY KEY,
    old_value   TEXT NOT NULL,
    new_value   TEXT NOT NULL,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    premise     TEXT NOT NULL,
    evidence    JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _country_b2_plan (site_id, old_value, new_value, change_key, reason, premise, evidence) VALUES
    ('6aa4c8de-3794-42fe-b68e-6b6ab77bd8ed'::uuid, 'Türkiye', 'Greece', 'country-b2-rollback:6aa4c8de-3794-42fe-b68e-6b6ab77bd8ed', 'rollback of country-b2: ''Greece'' restored on Delphinion', '37.53012087208033,27.280715854142734', '[{"source": "output/remediation/HUMAN_ONLY_DECISIONS_2026-09-26.md", "url": null, "quote": "B2-L: Delphinion Greece -> Türkiye (O9, 2026-09-26)"}, {"source": "naturalearth:ne_10m_admin_0_countries (Turkey)", "url": "https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_0_countries.zip", "retrieved_at": "2026-09-20T18:41:24+00:00", "quote": "point (37.53012, 27.28072) inside the ''Türkiye'' polygon"}]'::jsonb),
    ('74145e9b-76a6-48de-a902-08ecb2f1f7bb'::uuid, 'Greece', 'Germany', 'country-b2-rollback:74145e9b-76a6-48de-a902-08ecb2f1f7bb', 'rollback of country-b2: ''Germany'' restored on Achladia', '35.16680700239597,26.050032182871053', '[{"source": "output/remediation/HUMAN_ONLY_DECISIONS_2026-09-26.md", "url": null, "quote": "B2-L: Achladia Germany -> Greece (O9, 2026-09-26)"}, {"source": "naturalearth:ne_10m_admin_0_countries (Greece)", "url": "https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_0_countries.zip", "retrieved_at": "2026-09-20T18:41:24+00:00", "quote": "point (35.16681, 26.05003) inside the ''Greece'' polygon"}, {"source": "wikidata:Q28791168:P17 -> Q41:P297", "url": "https://www.wikidata.org/entity/Q28791168", "retrieved_at": "2026-09-26T00:30:06+00:00", "quote": "Q28791168 P17 only: Q41 Greece (GR) -> ISO 3166-1 alpha-2 GR (''Greece''); anchor via site_external_ids:wikidata_qid"}, {"source": "wikidata:Q28791168:P625", "url": "https://www.wikidata.org/entity/Q28791168", "retrieved_at": "2026-09-26T00:30:06+00:00", "quote": "Q28791168 P625 (35.1692, 26.0719) lies in Greece, 2005 m from the stored point"}]'::jsonb);

DO $$
DECLARE
    bad      INTEGER;
    moved    INTEGER := 0;
    expected INTEGER := 2;
    r        RECORD;
BEGIN
    -- expected is the plan's own row count, rendered here, and not a second count of the
    -- temp table the loop below iterates: counting the same table twice would make the
    -- comparison after the loop a tautology. The instance that makes a short loop
    -- unreachable is apply_remediation_change, which raises unless exactly one row
    -- matched; this guard is what reports a loop that changed fewer rows than the plan.

    -- scope guard 1: every planned row is a curated site that still exists
    SELECT count(*) INTO bad
      FROM _country_b2_plan p LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        -- the source name is a RAISE argument, never part of the quoted message: a name
        -- spliced into the message text only parses while the name happens to contain no
        -- quote, which is a property of today's value and not of this code. G0's guard is
        -- the shape this one copies.
        RAISE EXCEPTION 'B2 country repair: % planned row(s) are not % sites', bad, 'ancient_nerds';
    END IF;

    -- scope guard 2: the plan is a set of real changes, each one writable in the column
    SELECT count(*) INTO bad FROM _country_b2_plan p
     WHERE p.old_value IS NULL OR p.new_value = '' OR p.new_value = p.old_value
        OR length(p.new_value) > 100;
    IF bad > 0 THEN
        RAISE EXCEPTION 'B2 country repair: % planned row(s) are not writable changes', bad;
    END IF;

    -- scope guard 3: every planned row still holds the old value the plan names
    SELECT count(*) INTO bad
      FROM _country_b2_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE u.country IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'B2 country repair: % planned row(s) no longer hold the planned old value', bad;
    END IF;

    -- scope guard 4: every planned row undos a value this lane owns (old value)
    SELECT count(*) INTO bad FROM _country_b2_plan p
     WHERE p.old_value NOT IN ('Greece', 'Türkiye');
    IF bad > 0 THEN
        RAISE EXCEPTION 'B2 country repair: % planned row(s) undo a value this lane does not own', bad;
    END IF;

    -- scope guard 5: every planned row still holds the input its value was derived from
    SELECT count(*) INTO bad
      FROM _country_b2_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE (u.lat::text || ',' || u.lon::text) IS DISTINCT FROM p.premise;
    IF bad > 0 THEN
        RAISE EXCEPTION 'B2 country repair: % planned row(s) no longer hold the premise the plan derived its value from', bad;
    END IF;

    -- the only writer: the conditional UPDATE and its journal row commit together, and
    -- the function raises unless exactly one row matched
    FOR r IN SELECT * FROM _country_b2_plan ORDER BY site_id LOOP
        moved := moved + apply_remediation_change(
            'unified_sites', 'country', 'id', r.site_id::text,
            r.old_value, r.new_value,
            'B2/country', '2026-09-26_mechanical-country-b2-rollback', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;

    IF moved <> expected THEN
        RAISE EXCEPTION 'B2 country repair: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds the new value
    SELECT count(*) INTO bad
      FROM _country_b2_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE u.country IS DISTINCT FROM p.new_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'B2 country repair: % planned row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: the journal and the data agree, row for row, in both directions
    SELECT count(*) INTO bad
      FROM _country_b2_plan p LEFT JOIN remediation_change_log l
        ON l.row_pk = p.site_id::text AND l.table_name = 'unified_sites'
       AND l.column_name = 'country'
       AND l.run_stamp = '2026-09-26_mechanical-country-b2-rollback'
     WHERE l.id IS NULL
        OR l.new_value IS DISTINCT FROM p.new_value
        OR l.old_value IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'B2 country repair: % planned row(s) have no matching journal row', bad;
    END IF;

    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = '2026-09-26_mechanical-country-b2-rollback'
       AND (l.table_name <> 'unified_sites' OR l.column_name <> 'country');
    IF bad > 0 THEN
        RAISE EXCEPTION 'B2 country repair: this run stamp journalled % row(s) outside unified_sites.country', bad;
    END IF;

    RAISE NOTICE 'B2 country repair: % row(s) changed and journalled over % curated site(s)',
        moved, expected;
END $$;

COMMIT;

-- Post-commit read: the numbers the report quotes, from the database, not from the plan.
SELECT 'journal rows for this run stamp' AS metric, count(*)::text AS value
  FROM remediation_change_log WHERE run_stamp = '2026-09-26_mechanical-country-b2-rollback'
UNION ALL
SELECT 'journal rows for this test id', count(*)::text
  FROM remediation_change_log WHERE test_id = 'B2/country'
UNION ALL
SELECT 'planned rows now holding the new value', count(*)::text
  FROM remediation_change_log l
 WHERE l.run_stamp = '2026-09-26_mechanical-country-b2-rollback' AND l.table_name = 'unified_sites'
   AND l.column_name = 'country'
   AND EXISTS (SELECT 1 FROM unified_sites u
                WHERE u.id::text = l.row_pk AND u.country = l.new_value)
UNION ALL
SELECT 'curated rows still holding a country the B2 decision replaces', count(*)::text
  FROM unified_sites
 WHERE source_id = 'ancient_nerds' AND ((id = '74145e9b-76a6-48de-a902-08ecb2f1f7bb'::uuid AND country = 'Germany') OR (id = '6aa4c8de-3794-42fe-b68e-6b6ab77bd8ed'::uuid AND country = 'Greece'))
UNION ALL
SELECT 'curated sites', count(*)::text
  FROM unified_sites WHERE source_id = 'ancient_nerds';
