// Wave 2 of the remediation: the last Phase-1 check (T10) plus the two Phase-0 items that
// are still open. All three lanes are non-writing against the production database, so they
// cannot collide with each other or with the still-running T07 sweep.
//
// Loaded via workflowScriptPath so the briefs are byte-exact.

const SHARED = [
  "PROJECT: C:/PythonProjects/AncientMap (branch main, Windows). Always use the project",
  "interpreter ./.venv/Scripts/python.exe, NEVER bare python. Set PYTHONIOENCODING=utf-8.",
  "The plan you serve is docs/procedures/SITES_DB_REMEDIATION_2026-09.md (853 lines).",
  "",
  "WHAT THIS IS",
  "A full deterministic audit of the 5,004 curated sites (unified_sites.source_id =",
  "'ancient_nerds') in a production Postgres, so that every entry ends up either fixed,",
  "verified correct, or explicitly flagged for a human. Nine of the ten census checks are",
  "already written and audited. You are part of the wave that finishes the scaffolding.",
  "",
  "HOW EVIDENCE WORKS HERE (this is the culture of this repo, not decoration)",
  "* No claim without proof: a file:line, or the real output of a command you ran. If you did",
  "  not run it, say 'unverified' and say why. A number you did not measure is not a number.",
  "* Never weaken a check to make it pass. If a gate is red, the work is not done - report the",
  "  redness with its output. Editing a test, a threshold or an expectation so it goes green is",
  "  the single forbidden act in this project.",
  "* Never invent data. Where a value cannot be decided from evidence, the honest output is",
  "  'unverifiable', never a plausible guess. A wrong value is worse than an empty one.",
  "* Never swallow an error to produce an empty result. 'Could not check' must never turn into",
  "  'checked and clean' - that inversion is the most dangerous failure mode of this whole",
  "  effort. Errors are raised, recorded and reported.",
  "* Judge the tooling, do not obey it: a linter or plugin message is a hypothesis. Decide",
  "  whether it is a real defect and fix the real ones. Several findings already triaged here",
  "  are false positives (for example md5 used to reproduce Wikimedia's own upload-directory",
  "  layout - swapping it to sha256 would break the check to please the checker).",
  "",
  "GATES (run them before you claim anything; the project's CI runs them)",
  "  ./.venv/Scripts/python.exe -m pytest -q -rs --timeout 90 -m \"not integration and not live_llm\"",
  "  ./.venv/Scripts/python.exe -m ruff check <your files>",
  "  ./.venv/Scripts/python.exe -m mypy <your files>",
  "  -rs is mandatory: skips are silent otherwise. Skipped is not passed.",
  "",
  "DO NOT: write to the database (no psql, no INSERT/UPDATE/DELETE) unless your brief says so;",
  "commit or push; run `git checkout`/`git clean`/`git stash`; edit a file another lane owns.",
  "Leave your changes in the working tree and report exactly which files you touched.",
  "",
  "REPORTING: end with a short report containing (1) what you produced, with paths; (2) the",
  "exact commands you ran and their real results; (3) anything you could NOT verify, labelled",
  "as such; (4) anything you found wrong that you did not fix, with the reason.",
].join("\n");

const TASKS = [
  {
    key: "T10",
    mod: "t10_gallery_tiers",
    slow: true,
    body: [
      "ASSIGNMENT: the tenth and last Phase-1 census check.",
      "Plan Phase 1 item 10: 'Compute gallery signals S/A/B/D/E/P/F -> tier assignment per",
      "image.' Also read plan section 6.4 (the measured signal table) and 6.5 (the gallery",
      "audit algorithm whose stages these tiers decide). Read both fully before writing code.",
      "",
      "FILES TO READ FIRST",
      "1. scripts/remediation/census/tests/t04_site_type.py <- THE REFERENCE STYLE. Your module",
      "   must look like its sibling: same docstring rigour, same evidence standard.",
      "2. scripts/remediation/census/model.py, run.py, fetch.py, snapshot.py <- the contract.",
      "3. scripts/remediation/census/tests/t09_commons_dimensions.py <- does the image work and",
      "   wrote the cache you will consume. Copy its collect()/resumable-cache pattern.",
      "4. scripts/remediation/census/tests/t07_link_sweep.py <- the same pattern under load.",
      "",
      "CONTRACT (do not change run.py, model.py, fetch.py, snapshot.py)",
      "  TEST_ID, NAME, DIMENSION  module constants",
      "  applies_to(site, ctx) -> bool   OPTIONAL; if absent the check applies to ALL sites",
      "  collect(ctx) -> None            OPTIONAL; the ONLY place allowed to touch the network",
      "  run(ctx) -> list[Finding]       must be pure: snapshot + cache only",
      "run.py already has REGISTRY['T10'] = 't10_gallery_tiers'; do not edit run.py. There is a",
      "hard assertion that pass/flagged/not_applicable/error sum to the site count, so never",
      "filter sites out - use applies_to() instead.",
      "",
      "THE OPERATIONAL OUTPUT: every wiki_images row belonging to an ancient_nerds site gets a",
      "tier, and the tier decides what Phase 3 spends on it:",
      "  tier A 'hero'    -> is_hero; maximally visible, so every one gets a VLM call",
      "  tier B 'suspect' -> CORE signal (S|A|B|D|E); every one gets a VLM call",
      "  tier D 'clear'   -> in the site's P373 category AND no word signal AND the own name",
      "                      appears in the filename; ZERO VLM calls",
      "  tier C 'grey'    -> everything else; 3 sampled images per site",
      "This is a TRIAGE, not a correction. No tier is a claim about the world, and you never",
      "write to the database. A wrong triage costs VLM money, not correctness. That is exactly",
      "why a signal you cannot compute faithfully must be reported as unavailable rather than",
      "approximated silently.",
      "",
      "A HARD CONSTRAINT YOU MUST NOT PAPER OVER",
      "The curated word lists that plan table 6.4 was measured with are NOT in this repository.",
      "I searched: nothing mentions the 41 museum cities with coordinates, the 67 non-photo",
      "terms, the 4,396-token place dictionary, or any place_token/museum_city/non_photo",
      "identifier; they are not in git history either. The table prints only the first six of",
      "the 67 terms ('map, plan, drawing, painting, diagram, engraving, ...'). So, signal by",
      "signal:",
      "  * S (same Commons file also attached to a differently named site): FULLY FAITHFUL.",
      "    Compute from the snapshot alone - group wiki_images by filename across sites and",
      "    compare the site names. No network.",
      "  * F (own site name absent from title + filename + Commons name): FULLY FAITHFUL.",
      "    Compute from the row itself. No network.",
      "  * P (file is NOT in the site's P373 category): FULLY FAITHFUL, and it must be FETCHED.",
      "    P373 is the Wikidata property for the Commons category name.",
      "    pipeline/connectors/imagery/wikidata.py and pipeline/wiki_image_downloader.py",
      "    (:341, :401-402, :492) show exactly how this project reads it - get_string_value",
      "    ('P373') for the category, then the Commons API with generator=categorymembers and",
      "    gcmtitle=Category:<name> for its files. Fetch through ctx.net() in collect(), cache",
      "    it, and make it resumable exactly like T09 and T07 so an interrupted run continues.",
      "    Note the downloader's own limits are deliberate (up to 20 files, one subcategory",
      "    level) - state which you used and why.",
      "  * A (museum word), B (museum city >150 km), D (place token >50 km), E (non-photo word):",
      "    these depend on the missing lists. For each one, either reconstruct the list from a",
      "    principle the plan itself states and DOCUMENT it as a reconstruction (never present",
      "    it as the plan's list), or omit the signal and say so. For D the plan points at its",
      "    own source: 'place token of a curated site > 50 km away' - the curated sites and",
      "    their coordinates ARE in the snapshot, so that dictionary can be derived from the",
      "    5,004 site names rather than invented. Coordinate distance needs the sites' lat/lon,",
      "    which the snapshot has.",
      "",
      "THEN: implement the tier assignment and, in the module docstring, state signal by signal",
      "whether it is faithful, reconstructed, or unavailable - with the evidence for that claim.",
      "State the precedence you chose when an image qualifies for several tiers (the plan names",
      "heroes as tier A, so heroes should win; document what you did).",
      "",
      "WHAT TO REPORT (these are the numbers that matter downstream)",
      "  * per-tier image counts, against the plan's extrapolation (tier B ~10,525, tier C",
      "    ~20,602, tier D ~14,705, heroes 3,858). A large divergence means either your signals",
      "    are not the plan's signals or the data moved - report the real numbers and say which.",
      "    Do NOT tune anything to reach the plan's figures; the plan's figures came from lists",
      "    nobody has any more, so divergence is expected and is itself the honest answer.",
      "  * the P373 coverage: for how many of the 5,004 sites did you actually obtain a category?",
      "    If P373 is missing or wrong for most sites, tier D is unreachable and that single",
      "    number is more important than the tier counts - the plan names 1,448 sites with a",
      "    missing or wrong P373 anchor and calls it the main lever of Phase 2.",
      "",
      "You may create only: scripts/remediation/census/tests/t10_gallery_tiers.py,",
      "tests/remediation/test_t10.py, and scratch under output/remediation/t10_scratch/.",
      "Other lanes are editing api/ and pipeline/ right now - do not touch those.",
      "ORDER THE WORK SO A TIMEOUT DOES NOT WASTE IT. Get the module and its pure run() working",
      "against the snapshot signals first (S and F, which need no network) and report those",
      "numbers, then add the P373 fetch in collect(). The T07 lane before you died at its",
      "timeout; its work survived only because it wrote to disk as it went. A lane that produced",
      "a working check over two faithful signals plus an honest note about the rest is worth more",
      "than one that died mid-sweep with nothing written down.",
      "CLOSING REQUIREMENT: your check must have teeth, and you must prove it. Force run() to",
      "return [] and show how many of your tests fail; restore the file byte-identically",
      "afterwards (compare sha256 before and after and state it).",
    ].join("\n"),
  },
  {
    key: "GOLD",
    mod: null,
    slow: true,
    body: [
      "ASSIGNMENT: the gold standard - the false-negative rate of the whole effort.",
      "Plan Phase 0, the row 'Gold standard: 30-40 double-blind sites for the false-negative",
      "rate', and the error-rate method in plan section 4 (sampling around lines 60-80 and 150).",
      "This is the only instrument in the plan that can measure what ALL the machine checks",
      "together still miss. Treat it as the most important measurement you will produce.",
      "",
      "DOUBLE-BLIND IS THE WHOLE POINT - OBEY IT STRICTLY",
      "You must NOT read the census output before your own verdicts are written down. Do not",
      "open output/remediation/census.jsonl, output/remediation/findings.jsonl, or any",
      "output/remediation/run_*/ directory for a site until that site's verdicts are already on",
      "disk. If you read the machine's answer first you will unconsciously agree with it, and",
      "the measurement becomes worthless. Note in your report the timestamp order that proves",
      "you respected this.",
      "",
      "WHAT TO DO",
      "1. Read the plan's sections 4 and 6 to learn what 'every field' means, and read",
      "   docs/procedures/ENRICHMENT_AUDIT.md for this project's house rules on judging a site.",
      "2. Draw the sample: 30-40 sites, stratified by card_stats.rarity_tier, over-weighting",
      "   tiers 4/5 as the plan prescribes. Record the exact selection rule, the query and the",
      "   seed so anyone can reproduce the sample.",
      "3. For each sampled site, check EVERY field against at least TWO independent sources:",
      "   name, country, coordinates, period_start/period_end/period_name, site_type,",
      "   description claims, civilization, heritage designation, the hero image, and whether",
      "   the gallery images actually depict this site. Use the web; record the URL behind every",
      "   verdict.",
      "4. Write a verdict per field: CORRECT / WRONG (give the correct value and the source) /",
      "   UNVERIFIABLE (give the reason). 'I could not tell' is a legitimate and valuable",
      "   verdict - it is one of the things you are measuring.",
      "5. ONLY THEN open the census output and compute the false-negative rate: of the errors",
      "   YOU found, how many did the census also flag? Name every error you found that the",
      "   census missed, site by site. That list is your headline result.",
      "",
      "DELIVERABLE: output/remediation/gold_standard/GOLD_STANDARD.md, with the sample design,",
      "the per-site verdicts, the source for each, the comparison, and the measured",
      "false-negative rate with its sample size and its confidence interval. Add",
      "output/remediation/gold_standard/sites.json with one machine-readable record per site",
      "(fields, verdicts, sources, census comparison).",
      "",
      "WORK INCREMENTALLY - THIS IS A REQUIREMENT, NOT ADVICE",
      "The lane that ran before you hit its timeout and its work survived only because it wrote",
      "to disk as it went. Copy that: draw the sample first and write the sample file, then after",
      "EACH site append its record to sites.json and its section to GOLD_STANDARD.md before",
      "starting the next site. A run that stops early must leave a usable, honest partial",
      "result. If you cannot finish the whole sample, say exactly how many sites you completed",
      "and compute the rate over those; label the shortfall plainly instead of describing the",
      "full sample as if it were done. Twelve measured sites beat forty asserted ones.",
      "",
      "Do NOT write to the database. Do NOT edit any checked-in file: everything you produce",
      "lives under output/remediation/gold_standard/. A measurement that quietly edits the",
      "thing it measures is not a measurement. Scratch space: output/remediation/gold_scratch/.",
    ].join("\n"),
  },
  {
    key: "OVERWRITER",
    mod: null,
    slow: false,
    body: [
      "ASSIGNMENT: Phase 0, 'Lock down the restart overwriters (10.1)' - and assess the further",
      "defects listed in 10.3 while you are in there.",
      "Read docs/procedures/SITES_DB_REMEDIATION_2026-09.md sections 10.1 and 10.3 in full",
      "before you touch anything. 10.1 names two processes that overwrite values on restart",
      "(api/main.py around :496-531 and the orchestrator around :1621-1627). 10.3 lists further",
      "tooling defects (a flat-dict fallback that sets confidence='high' around :1223-1234, a",
      "--phase sync that misses columns around :161-176 and :283-299, and restore_snapshot()",
      "omitting raw_data).",
      "",
      "THE QUESTION THE ENTIRE REMEDIATION DEPENDS ON",
      "Which columns can a restart or a deploy silently overwrite or recompute, under exactly",
      "which conditions, and does that destroy a value this remediation is about to write?",
      "Phase 2 will move wiki_images.is_hero flags, and later phases write card_stats.",
      "card_description and name_normalized and facts on unified_sites. If any of those can be",
      "clobbered on the next restart, then every write the plan makes is wasted - so this must",
      "be settled per column, with file:line evidence and a RUNNABLE demonstration, not by",
      "reading comments that claim the value is preserved.",
      "",
      "Pay particular attention to name_normalized: the survival condition is that the stored",
      "value equals left(lower(unaccent(value)), 500), so a WELL-FORMED BUT WRONG value is",
      "durable and a poorly-formed correct one is overwritten. Work out what that means for",
      "the plan's normalisation step and say plainly whether it is safe.",
      "",
      "THEN FIX IT, in code, with tests. The smallest change that makes the overwrite either",
      "impossible or provably idempotent is the right one (for example: only write into a NULL",
      "or empty target, or write exactly the value the producer would itself compute, so the",
      "restart becomes a no-op). Do not weaken any existing check to get there.",
      "",
      "THE TEST THAT MATTERS: prove the overwrite happened BEFORE your change and does not",
      "happen AFTER it. A test that passes both before and after proves nothing and is itself",
      "the defect you are meant to be removing.",
      "",
      "REPORT, precisely:",
      "  (a) the protected-column table: each column, the file:line that writes it, and the",
      "      trigger condition that makes it fire;",
      "  (b) what you changed and why;",
      "  (c) the test proving the overwrite is gone, and the evidence it did fire beforehand;",
      "  (d) everything you found in 10.3 and did NOT fix, with the reason.",
      "",
      "You may edit api/ and pipeline/ code. Do NOT touch scripts/remediation/census/ or",
      "output/remediation/ except for scratch under output/remediation/overwriter_scratch/ -",
      "other lanes own those. Run the project gates on what you change and report their real",
      "output. Do not push.",
    ].join("\n"),
  },
];

const children = TASKS.map(function (t) {
  const task = SHARED
    + "\n\n================================================================\n"
    + "YOUR ASSIGNMENT\n"
    + t.body;

  return {
    key: t.key,
    agent: "worker",
    task: task,
    model: "opencode-go/deepseek-v4.1-flash",
    context: "fresh",
    timeoutMs: t.slow ? 4200000 : 2400000,
    usageBudget: { tokens: { hard: 6000000 } },
  };
});

return await runs.all(children);
