// Wave 1 of the Phase-1 deterministic census: eight independent checks, one worker per
// file, all on opencode-go/deepseek-v4.1-flash. T10 is deliberately absent - it consumes
// T09's collected image dimensions and therefore runs as wave 2 once the cache exists.
//
// Loaded via workflowScriptPath so the briefs are byte-exact (an inline version of this
// file failed to parse in the tool argument, and a brief that silently loses a paragraph
// would produce a worker that silently checks the wrong thing).

const SHARED = [
  "PROJECT: C:/PythonProjects/AncientMap (branch main, Windows). Always use the project",
  "interpreter ./.venv/Scripts/python.exe, NEVER bare python. Set PYTHONIOENCODING=utf-8.",
  "",
  "WHAT THIS IS",
  "A full deterministic census of the 5,004 curated sites (unified_sites.source_id =",
  "'ancient_nerds') in a production Postgres. The plan is",
  "docs/procedures/SITES_DB_REMEDIATION_2026-09.md - read its Phase 1 list (around line 671).",
  "You are implementing ONE of the ten checks. Your check must run over the local snapshot,",
  "never the live database.",
  "",
  "FILES TO READ FIRST (in this order)",
  "1. scripts/remediation/census/tests/t04_site_type.py  <- THE REFERENCE. Copy its style,",
  "   its docstring rigour, its evidence standard. Your module must look like its sibling.",
  "2. scripts/remediation/census/model.py   <- Severity, Confidence, Proposal, Evidence, Finding",
  "3. scripts/remediation/census/run.py     <- the Context object and the module contract",
  "4. scripts/remediation/census/fetch.py    <- the polite cached HTTP client you MUST use",
  "5. scripts/remediation/census/snapshot.py <- Snapshot loader",
  "6. the Phase 1 section of the plan for YOUR numbered check",
  "",
  "CONTRACT (already fixed - do not change run.py, model.py, fetch.py, snapshot.py)",
  "  TEST_ID, NAME, DIMENSION  module constants",
  "  applies_to(site, ctx) -> bool    OPTIONAL. If absent the check applies to ALL sites.",
  "  collect(ctx) -> None             OPTIONAL. The ONLY place allowed to touch the network.",
  "  run(ctx) -> list[Finding]        the check. Must be pure: snapshot + cache only.",
  "Read run.py's docstring for how pass/flagged/not_applicable/error are counted. There is a",
  "hard assertion that the four statuses sum to the site count, so never filter sites in a",
  "way that drops them - use applies_to() instead.",
  "",
  "HARD RULES (violating these is a failed task)",
  "* NEVER invent data. If a value cannot be decided from evidence, emit",
  "  proposal=Proposal.REVIEW with confidence=Confidence.UNVERIFIABLE and proposed_value=None.",
  "  Proposal.REVIEW must NOT carry proposed_value (the model raises). Proposal.SET requires",
  "  proposed_value. A wrong value is worse than no value (project anti-pattern: an empty",
  "  field beats a wrong one).",
  "* Confidence semantics: AUTHORITATIVE = the canonical source itself says so (an official",
  "  API response, or a project module's own mapping). TWO_SOURCE = two independent hosts",
  "  agree. WEAK = one secondary source. Findings carry Evidence entries. Note that the",
  "  model's .applicable property requires proposal SET/CLEAR + confidence TWO_SOURCE or",
  "  AUTHORITATIVE + at least one evidence entry. Only findings genuinely safe to write",
  "  automatically should reach that bar - do not inflate confidence to make one apply.",
  "* NEVER swallow an error to produce an empty result. If the network fails, raise. Reporting",
  "  'no findings' because a request failed converts 'could not check' into 'checked and",
  "  clean', which is the single worst failure mode of this census. Use ctx.net() - it raises",
  "  with a clear message if no fetcher exists.",
  "* Never write to the database. No psql, no INSERT/UPDATE. Snapshot and cache only. Reading",
  "  a cache file another check writes is fine only if your task text says so.",
  "* Do not weaken anything to make it pass: no bare except, no fallback chain, no",
  "  try/except that quietly continues to the next candidate.",
  "",
  "SNAPSHOT SHAPES (verified 2026-09-20, already exported locally)",
  "  unified_sites (5004): id, source_id, source_record_id, name, name_normalized, lat, lon,",
  "    geom (JSON object, coordinates [lon, lat]), h3_index, site_type, period_start,",
  "    period_end, period_name, country, description, thumbnail_url, source_url, raw_data,",
  "    created_at, parent_site_id, edited_by, updated_at, last_audited",
  "  card_stats (5004, keyed by site_id): site_id, antiquity, fortification,",
  "    cultural_influence, mystery, legacy, total_power, rarity_score, rarity_tier,",
  "    category_group, civilization, empires (jsonb), empire_count, card_description,",
  "    last_enriched, confidence_score, source_language, best_wiki_url, wikidata_qid,",
  "    heritage_designation, inception_year, commons_image",
  "  wiki_images (49691): id, site_id, filename, original_url, commons_page_url, thumb_width,",
  "    author, author_url, license, license_url, title, is_hero, is_lead, sort_order,",
  "    source_type, file_size_bytes, width, height, created_at, is_excluded",
  "  site_content_links (16029): id, site_id, content_type, content_source, content_id,",
  "    title, thumbnail_url, content_url, relevance_score, link_metadata, created_at",
  "  site_external_ids (9237): site_id, kind, value, resolved_at ; kind in",
  "    {wikidata_qid, enwiki_title}",
  "  unified_site_names (5004): id, site_id, name, name_normalized, language_code, name_type",
  "",
  "Useful accessors: ctx.snap.rows('wiki_images'), ctx.snap.by('card_stats', 'site_id') ->",
  "dict keyed by site_id, and ctx.sites. Read snapshot.py for the exact API.",
  "",
  "REAL-WORLD FACTS YOU MUST RESPECT",
  "* 4,618 sites carry a wikidata_qid in site_external_ids; 4,619 carry enwiki_title. Use",
  "  those instead of reconciling again. There is NO wikidata_qid column on unified_sites -",
  "  note that card_stats DOES have one.",
  "* pipeline/lyra/orchestrator.py runs on every container restart and re-applies global",
  "  normalizations to site_type and name_normalized. Any value you propose for those fields",
  "  must be a fixed point of the project's own normalizer, or a reboot silently reverts it.",
  "  t04_site_type.py shows how to assert this.",
  "* The frontend reads the repo-root public/data/ only.",
  "",
  "HOW TO VERIFY - MANDATORY, DO NOT SKIP, DO NOT CLAIM WITHOUT RUNNING",
  "1. ./.venv/Scripts/python.exe -m mypy scripts/remediation/census/ --no-error-summary",
  "2. ./.venv/Scripts/python.exe -m ruff check scripts/remediation/census/",
  "3. Run your check for real:",
  "   PYTHONIOENCODING=utf-8 ./.venv/Scripts/python.exe scripts/remediation/census/run.py --tests YOURID --out output/remediation/run_yourid -v",
  "   If your module has collect(), the first run fills the cache - that is expected and can",
  "   take many minutes; use --collect-only once to fill the cache, then run for real.",
  "4. Read output/remediation/run_yourid/CENSUS.md and report its ACTUAL numbers.",
  "5. Prove your check has teeth: add tests/remediation/test_yourid.py with synthetic sites",
  "   carrying the defect your check exists to find, asserting that it fires. A check that",
  "   reports zero findings is indistinguishable from a broken check. See",
  "   tests/remediation/test_census_checks.py (class TestT04SiteType) for the pattern. Run",
  "   ./.venv/Scripts/python.exe -m pytest tests/remediation/test_yourid.py -q -rs",
  "",
  "REPORT BACK (this is the deliverable - be concise and factual)",
  "* the file path(s) you created",
  "* the exact command you ran and its REAL output (the CENSUS.md row for your test: sites,",
  "  applicable, flagged, not_applicable, errors, findings, applicable findings, seconds)",
  "* how many findings fall into each (severity, field, proposal) bucket - the actual numbers",
  "* the pytest result line and the mypy/ruff status",
  "* anything you could not decide, and every place you chose REVIEW over a guess - with why",
  "* anything broken OUTSIDE your task (do not fix it, just report it)",
  "Do not describe what the code should do. Report what it printed.",
].join("\n");

const TASKS = [
  {
    key: "T01",
    mod: "t01_wikidata_claims",
    slow: false,
    body: [
      "CHECK 1 - Wikidata claim comparison for name, country and coordinates.",
      "Plan Phase 1 item 1. Explicitly NOT periods: the plan's section 9.5 explains that",
      "Wikidata date precision makes period comparison unreliable, so do not compare",
      "period_start/period_end against P571/P580/P582. Check:",
      "  - coordinates: Wikidata P625 vs unified_sites.lat/lon",
      "  - country: Wikidata P17 -> country name vs unified_sites.country",
      "  - name: the Wikidata label (or the enwiki title) vs unified_sites.name, allowing",
      "    known alias forms",
      "Reuse the project's existing fetcher rather than writing a new one: read",
      "scripts/audit_wikidata_batch.py - fetch_wikidata_batch() and extract_claims() are",
      "importable and need no API key (50 QIDs per call, about 93 calls for 4,618 QIDs). Your",
      "collect() must use ctx.net() or that batch helper and write results into ctx.cache as",
      "resumable per-batch files; a second run must not refetch. run() is then PURE over the",
      "cache.",
      "Coordinate distance: use a haversine. A site whose stored coordinate is hundreds of",
      "metres from Wikidata's is worth flagging, but you must justify the threshold in the",
      "docstring rather than picking one silently. Decide the threshold, state it, say why.",
      "Remember: Wikidata is not automatically right - a disagreement is a REVIEW, not an",
      "instruction to overwrite our value.",
    ].join("\n"),
  },
  {
    key: "T02",
    mod: "t02_admin_country",
    slow: false,
    body: [
      "CHECK 2 - point-in-polygon: does lat/lon lie inside the claimed country?",
      "Plan Phase 1 item 2, which requires a Natural Earth 10m import.",
      "collect(): download the Natural Earth 10m admin-0 countries dataset once into ctx.cache",
      "and unzip it. Outbound network works (verified). Sources, in this order only: the",
      "naturalearthdata.com direct download, then the naciscdn mirror. Do NOT write a fallback",
      "loop over many mirrors - pick one URL, verify it works with a real request, and hard-code",
      "it with a dated comment saying you verified it. If it genuinely cannot be fetched, say",
      "so plainly.",
      "run(): for each site with a country and coordinates, test whether the point falls inside",
      "the polygon of the named country, using shapely/geopandas (both installed). This needs",
      "care:",
      "  - match the site's country string to the Natural Earth ADMIN/NAME field (normalise case",
      "    and punctuation; Natural Earth uses e.g. 'United States of America', 'Czechia').",
      "  - a site legitimately near a border, on a small island, or on a coastline may fall just",
      "    outside because of coastline generalisation. So flag only when the point is outside",
      "    by a meaningful margin, and grade severity by the distance to the polygon rather than",
      "    a binary in/out. Report the distance in the finding.",
      "  - handle antimeridian cases (Easter Island, Fiji) and multi-part countries explicitly.",
      "  - if the country string cannot be matched to any Natural Earth feature, that is itself a",
      "    finding (proposal REVIEW) - our country vocabulary and Natural Earth's differ.",
      "Explain your distance threshold in the docstring and justify it.",
    ].join("\n"),
  },
  {
    key: "T03",
    mod: "t03_years_in_text",
    slow: false,
    body: [
      "CHECK 3 - years mentioned in the description text vs period_start / period_name.",
      "Plan Phase 1 item 3. This catches contradictions Wikidata cannot see. Pure offline, no",
      "collect().",
      "Extract year-like tokens from unified_sites.description (and card_stats.card_description",
      "if useful - decide and justify). Handle: 'c. 3000 BC', '1500 BCE', '3rd millennium BC',",
      "'2500-2000 BC' ranges, 'AD 500' / '500 AD', bare '1998' (a modern excavation date, NOT",
      "the site's period - the main false-positive trap), '1.2 million years ago', and",
      "century/millennium phrases. Reuse the project's own date helpers where they fit:",
      "pipeline/normalizers/dates.py (parse_year, parse_iso_date, extract_year_from_wikidata_time)",
      "and pipeline/utils/text.py categorize_period/PERIOD_BUCKETS. Read them before writing your",
      "own.",
      "The judgement call: a description legitimately mentions excavation dates, publication",
      "years, and the dates of other nearby sites. So a year outside the site's period is NOT",
      "automatically an error. Distinguish by context - a year attached to words like",
      "'excavated', 'published', 'surveyed', 'restored', 'since' is a modern date. State your",
      "rule in the docstring and put genuinely ambiguous cases in REVIEW.",
      "Severity: a contradiction the card text repeats is worse than one in an unused field -",
      "the plan's section 15.4 explains that field visibility determines blast radius.",
    ].join("\n"),
  },
  {
    key: "T05",
    mod: "t05_country_values",
    slow: false,
    body: [
      "CHECK 5 - broken country values.",
      "Plan Phase 1 item 5 names concrete cases: 'Georgia (country)' 27 sites, 'Chile, Easter",
      "Island' 8 sites, 'Baltic Sea' 1 site. Pure offline, no collect().",
      "Start by enumerating the FULL distinct country vocabulary in the snapshot with counts -",
      "do not trust the plan's list to be complete, verify it, and report the real distribution.",
      "Then classify each distinct value:",
      "  - a disambiguated name that should be the plain name ('Georgia (country)' -> 'Georgia')",
      "  - a compound country/region ('Chile, Easter Island' -> country Chile)",
      "  - a sea or other non-country ('Baltic Sea') - a real data defect; the location is not a",
      "    country. Propose REVIEW or CLEAR with a justification, do not guess a country.",
      "  - anything else non-canonical you find (accents, case, historical names like 'USSR',",
      "    'Yugoslavia', 'Ottoman Empire', 'Persia', 'Burma')",
      "For each, decide and JUSTIFY whether the fix is SET (with the value), CLEAR, or REVIEW.",
      "Respect the project anti-pattern: an empty field beats a wrong one. Historical entities",
      "are NOT simply wrong - a site in the Ottoman Empire may legitimately carry that name - so",
      "default those to REVIEW with the reasoning, not to a modern replacement.",
      "Cross-check against the country vocabulary the frontend and API expect: search api/ and",
      "ancient-nerds-map/src/ for an existing country list (a dropdown or filter), and report any",
      "mismatch between it and our data.",
    ].join("\n"),
  },
  {
    key: "T06",
    mod: "t06_url_shape",
    slow: false,
    body: [
      "CHECK 6 - URL shapes.",
      "Plan Phase 1 item 6 gives measured counts: 7 non-http URLs, 9 fragment URLs, 42 missing",
      "URLs. Pure offline, no collect().",
      "Check the URL-bearing fields across the snapshot: unified_sites.thumbnail_url,",
      "unified_sites.source_url, card_stats.best_wiki_url, card_stats.commons_image,",
      "wiki_images.original_url, wiki_images.commons_page_url, wiki_images.author_url,",
      "wiki_images.license_url, site_content_links.content_url, site_content_links.thumbnail_url.",
      "Enumerate every URL-ish column yourself from the snapshot keys and report the full list -",
      "do not assume the ones above are all of them.",
      "Classifications to implement: missing/empty where it should be present; non-http(s)",
      "scheme; a fragment-only or javascript: value; whitespace or control characters; a value",
      "that is not a URL at all (a bare word, a filename); double slashes beyond the scheme;",
      "http where the site serves https; obvious truncation (ends mid-path, or an invalid",
      "percent-encoding); Wikimedia file URLs using the wrong shape.",
      "This is shape checking only - do NOT make network requests here (T07 does the",
      "reachability sweep); keep the two concerns separate.",
      "Report per-class counts and per-field counts.",
    ].join("\n"),
  },
  {
    key: "T07",
    mod: "t07_link_sweep",
    slow: true,
    body: [
      "CHECK 7 - HEAD sweep over the distinct reference-link URLs.",
      "Plan Phase 1 item 7: 15,230 distinct URLs, about 45 min at 24 parallel. This one NEEDS",
      "the network.",
      "collect(): gather every distinct URL from site_content_links.content_url, then issue a",
      "polite HEAD for each through ctx.net() (the client's head() already falls back to GET when",
      "a server refuses HEAD - read fetch.py). The client caches by URL, so the second run is",
      "offline and instant - make the collector resumable so it never refetches.",
      "Because this is many requests against third parties: keep the client's default",
      "politeness (it already paces, retries, and honours Retry-After), do not raise the worker",
      "count above the client default, and use ctx.fetch.map() so results are deterministic and",
      "ordered.",
      "run(): classify from the cache - 2xx reachable; 404 gone; 410 gone permanently;",
      "403/401/429 as 'refused, could not verify', which is NOT a dead link and must not be",
      "reported as one (this distinction is the point: a WAF returning 403 says nothing about",
      "the link); 5xx as 'server error, retry later'; timeouts/DNS failures as 'unreachable'.",
      "Group findings by site so the report says how many sites have at least one dead link and",
      "how severe that is. Record the final URL when the client exposes a redirect. Severity",
      "should reflect that a dead reference link matters more on a site whose card text cites it",
      "(check whether the link's id appears as a citation marker - T08 defines the marker",
      "format).",
    ].join("\n"),
  },
  {
    key: "T08",
    mod: "t08_citation_markers",
    slow: false,
    body: [
      "CHECK 8 - citation integrity: markers vs the evidence array.",
      "Plan Phase 1 item 8 calls this IMMEDIATELY ACTIONABLE and gives measured numbers: 76",
      "sites carry an evidence array with no [N] marker in the text at all, 11 have a marker",
      "with no matching entry, and 8 have an entry that is never cited. Pure offline, no",
      "collect().",
      "FIRST establish the facts, because getting this wrong makes the check meaningless: find",
      "which text field actually carries the markers and which table is the 'evidence array'.",
      "Read pipeline/lyra/theo_citations.py (1953 lines - it has strip_orphan_citation_markers,",
      "normalize_grouped_markers, _collect_non_numeric_markers, detect_placeholder_markers) and",
      "follow how its callers use it. The candidates are site_content_links rows as the array",
      "and card_stats.card_description as the text - but VERIFY this against the code and the",
      "real snapshot, and state in the docstring what you found and how you verified it.",
      "Then implement: parse the markers from the text (including grouped forms like [1,2] and",
      "ranges like [3-5]); compare the set of marker indices against the ordered evidence",
      "entries; classify the four failure modes (marker with no entry; entry never cited; array",
      "present but no markers at all; marker numbering that is not 1..N contiguous).",
      "Reuse the module's own parsers rather than writing new regexes where they exist - a",
      "second, subtly different parser is how this kind of check starts producing false findings.",
      "Report whether your numbers reproduce the plan's 76/11/8. If they do not match, that is a",
      "finding about the plan or about the data having changed - say so explicitly with your real",
      "numbers, and do not adjust anything to hit the plan's figures.",
    ].join("\n"),
  },
  {
    key: "T09",
    mod: "t09_commons_dimensions",
    slow: true,
    body: [
      "CHECK 9 - true Commons original dimensions per image.",
      "Plan Phase 1 item 9: 981 imageinfo batches. Also read plan sections 6.3 and 6.4: every",
      "hero image is broken, and 6.3 says the fix is to move the is_hero flag to an",
      "already-local 1600px image, so the true original size matters.",
      "collect(): for all 49,691 wiki_images rows, query the Commons API imageinfo with",
      "iiprop=size|url|extmetadata, batching titles 50 per request (about 981 calls), through",
      "ctx.net(), caching per batch so it is resumable. This must be robust: Commons will not",
      "always return every title you ask for (normalisation, redirects, missing files) - handle",
      "a partial response by recording which titles came back and which did not, rather than",
      "assuming alignment.",
      "run(): compare the stored width/height/file_size_bytes against the true original",
      "dimensions. Classify: stored size differs from truth; stored dimensions are the",
      "THUMBNAIL size rather than the original (the documented root cause - look at thumb_width",
      "and the plan's 6.2); the image is smaller than 1600px so it can never be a hero at the",
      "required width; the file is missing on Commons entirely. Then, for the hero repair,",
      "identify for each site the best available non-excluded image of at least 1600px, so",
      "Phase 2 can move the flag mechanically.",
      "Report: how many sites currently have a hero that is not the largest available image, and",
      "how many sites have NO image at all that qualifies as a hero - that second number is the",
      "one the plan needs to decide the remaining fetches.",
      "The plan's section 6.1 mentions 652 labelled images across 40 sites as the measurement",
      "basis. Look for that label set in the repo (output/audit_inventory/ or similar) and if",
      "you find it, use it to report precision/recall of your rule. If you cannot find it, say",
      "so rather than inventing a measurement.",
    ].join("\n"),
  },
];

const children = TASKS.map(function (t) {
  const task = SHARED
    + "\n\n================================================================\n"
    + "YOUR ASSIGNMENT\n"
    + "Create exactly ONE new check module:\n"
    + "  scripts/remediation/census/tests/" + t.mod + ".py\n"
    + "Do not modify run.py, model.py, fetch.py, snapshot.py, t04_site_type.py, or any other\n"
    + "check module. Other agents are writing those right now; touching them corrupts their\n"
    + "work. You may add only two further files: tests/remediation/test_" + t.key.toLowerCase()
    + ".py and, if you need scratch space, anything under output/remediation/.\n\n"
    + t.body;

  return {
    key: t.key,
    agent: "worker",
    task: task,
    model: "opencode-go/deepseek-v4.1-flash",
    context: "fresh",
    timeoutMs: t.slow ? 4200000 : 2400000,
    usageBudget: { tokens: { hard: 6000000 } },
  };
});

return await runs.all(children);
