-- plan sha256 e120d55a6d83389c4b489970affd568cb11569edeff800c2d19b4c57f73c8e58
-- Generated by scripts/remediation/mechanical/apply.py - do not edit by hand.
-- 4 row(s) over 2 site(s); scope source_id = 'ancient_nerds';
-- run stamp '2026-10-01_mechanical-name-fix-rollback'; journal test id 'B1/name-fix'.
-- Every UPDATE is conditioned on the old value the plan names; every change is journalled
-- in the same transaction, so the audit trail cannot disagree with the data.
\set ON_ERROR_STOP on
BEGIN;

-- The server bounds this transaction itself: a lock wait or a runaway statement raises
-- here, psql stops the script (exit 3) and nothing is kept. A client that gives up does
-- not stop the server - psql has the whole script on its stdin.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

CREATE TEMP TABLE _name_fix_plan (
    site_id     UUID NOT NULL,
    column_name TEXT NOT NULL,
    old_value   TEXT,
    new_value   TEXT,
    change_key  TEXT NOT NULL,
    reason      TEXT NOT NULL,
    premise     TEXT NOT NULL,
    evidence    JSONB NOT NULL,
    PRIMARY KEY (site_id, column_name)
) ON COMMIT DROP;

INSERT INTO _name_fix_plan (site_id, column_name, old_value, new_value, change_key, reason, premise, evidence) VALUES
    ('4a07cc38-1b55-4254-b0ad-fe875310caf7'::uuid, 'name', 'Temple of Augustus, Pula', 'Temple of Augustus, Split', 'name-fix-rollback:4a07cc38-1b55-4254-b0ad-fe875310caf7:name', 'rollback of name-fix: name ''Temple of Augustus, Split'' restored on Temple of Augustus, Split', 'enwiki_title=Temple of Augustus, Pula, wikidata_qid=Q770030', '[{"source": "en.wikipedia.org, article ''Temple of Augustus, Pula'' (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://en.wikipedia.org/wiki/Temple_of_Augustus,_Pula", "quote": "The Temple of Augustus (Croatian: Augustov hram; Italian: Tempio di Augusto) is a well-preserved Roman temple in the city of Pula, Croatia"}, {"source": "wikidata:Q770030 (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://www.wikidata.org/wiki/Q770030", "quote": "label ''Temple of Augustus'', description ''Roman temple in Pula, Croatia'', coordinate location 44.8702, 13.84185; the site''s stored point 44.87026, 13.84220 is 28 m from it"}, {"source": "wikidata search ''Temple of Augustus'' (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://www.wikidata.org/w/index.php?search=Temple+of+Augustus", "quote": "ten items named for a Temple of Augustus (Pula, Barcelona, Ankara, Vienne, Philae, Antioch in Pisidia, Cartagena, Rome, Nimes, Leptis Magna), none in Split"}, {"source": "production:unified_sites", "url": null, "quote": "name ''Temple of Augustus, Split'' (utf-8 hex 54656d706c65206f662041756775737475732c2053706c6974), key ''temple of augustus, split'', external ids enwiki_title=Temple of Augustus, Pula, wikidata_qid=Q770030 (read 2026-10-01 09:53:10.200573+00)"}]'::jsonb),
    ('4a07cc38-1b55-4254-b0ad-fe875310caf7'::uuid, 'name_normalized', 'temple of augustus, pula', 'temple of augustus, split', 'name-fix-rollback:4a07cc38-1b55-4254-b0ad-fe875310caf7:name_normalized', 'rollback of name-fix: name_normalized ''temple of augustus, split'' restored on Temple of Augustus, Split', 'enwiki_title=Temple of Augustus, Pula, wikidata_qid=Q770030', '[{"source": "en.wikipedia.org, article ''Temple of Augustus, Pula'' (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://en.wikipedia.org/wiki/Temple_of_Augustus,_Pula", "quote": "The Temple of Augustus (Croatian: Augustov hram; Italian: Tempio di Augusto) is a well-preserved Roman temple in the city of Pula, Croatia"}, {"source": "wikidata:Q770030 (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://www.wikidata.org/wiki/Q770030", "quote": "label ''Temple of Augustus'', description ''Roman temple in Pula, Croatia'', coordinate location 44.8702, 13.84185; the site''s stored point 44.87026, 13.84220 is 28 m from it"}, {"source": "wikidata search ''Temple of Augustus'' (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://www.wikidata.org/w/index.php?search=Temple+of+Augustus", "quote": "ten items named for a Temple of Augustus (Pula, Barcelona, Ankara, Vienne, Philae, Antioch in Pisidia, Cartagena, Rome, Nimes, Leptis Magna), none in Split"}, {"source": "production:unified_sites", "url": null, "quote": "name ''Temple of Augustus, Split'' (utf-8 hex 54656d706c65206f662041756775737475732c2053706c6974), key ''temple of augustus, split'', external ids enwiki_title=Temple of Augustus, Pula, wikidata_qid=Q770030 (read 2026-10-01 09:53:10.200573+00)"}]'::jsonb),
    ('f9cfc5f7-a6c8-4c6f-9d82-f30151a36d6c'::uuid, 'name', 'Gate of All Nations', 'Gate of All Nations‌ Persepolis', 'name-fix-rollback:f9cfc5f7-a6c8-4c6f-9d82-f30151a36d6c:name', 'rollback of name-fix: name ''Gate of All Nations\u200c Persepolis'' restored on Gate of All Nations‌ Persepolis', 'enwiki_title=Gate of All Nations, wikidata_qid=Q5527015', '[{"source": "en.wikipedia.org, article ''Gate of All Nations'' (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://en.wikipedia.org/wiki/Gate_of_All_Nations", "quote": "also known as the Gate of Xerxes, is located in the ruins of the ancient city of Persepolis, Iran."}, {"source": "wikidata:Q5527015 (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://www.wikidata.org/wiki/Q5527015", "quote": "English label ''Gate of All Nations''; enwiki sitelink ''Gate of All Nations''"}, {"source": "production:unified_sites", "url": null, "quote": "name ''Gate of All Nations\\u200c Persepolis'' (utf-8 hex 47617465206f6620416c6c204e6174696f6e73e2808c205065727365706f6c6973), key ''gate of all nations\\u200c persepolis'', external ids enwiki_title=Gate of All Nations, wikidata_qid=Q5527015 (read 2026-10-01 09:53:10.200573+00)"}]'::jsonb),
    ('f9cfc5f7-a6c8-4c6f-9d82-f30151a36d6c'::uuid, 'name_normalized', 'gate of all nations', 'gate of all nations‌ persepolis', 'name-fix-rollback:f9cfc5f7-a6c8-4c6f-9d82-f30151a36d6c:name_normalized', 'rollback of name-fix: name_normalized ''gate of all nations\u200c persepolis'' restored on Gate of All Nations‌ Persepolis', 'enwiki_title=Gate of All Nations, wikidata_qid=Q5527015', '[{"source": "en.wikipedia.org, article ''Gate of All Nations'' (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://en.wikipedia.org/wiki/Gate_of_All_Nations", "quote": "also known as the Gate of Xerxes, is located in the ruins of the ancient city of Persepolis, Iran."}, {"source": "wikidata:Q5527015 (read 2026-10-01 through the public MediaWiki and Wikidata APIs)", "url": "https://www.wikidata.org/wiki/Q5527015", "quote": "English label ''Gate of All Nations''; enwiki sitelink ''Gate of All Nations''"}, {"source": "production:unified_sites", "url": null, "quote": "name ''Gate of All Nations\\u200c Persepolis'' (utf-8 hex 47617465206f6620416c6c204e6174696f6e73e2808c205065727365706f6c6973), key ''gate of all nations\\u200c persepolis'', external ids enwiki_title=Gate of All Nations, wikidata_qid=Q5527015 (read 2026-10-01 09:53:10.200573+00)"}]'::jsonb);

DO $$
DECLARE
    bad      INTEGER;
    moved    INTEGER := 0;
    expected INTEGER := 4;
    r        RECORD;
BEGIN
    -- expected is the plan's own row count, rendered here, and not a second count of the
    -- temp table the loop below iterates: counting the same table twice would make the
    -- comparison after the loop a tautology. The instance that makes a short loop
    -- unreachable is apply_remediation_change, which raises unless exactly one row
    -- matched; this guard is what reports a loop that changed fewer rows than the plan.

    -- scope guard 1: every planned row is a curated site that still exists
    SELECT count(*) INTO bad
      FROM _name_fix_plan p LEFT JOIN unified_sites u ON u.id = p.site_id
     WHERE u.id IS NULL OR u.source_id <> 'ancient_nerds';
    IF bad > 0 THEN
        -- the source name is a RAISE argument, never part of the quoted message: a name
        -- spliced into the message text only parses while the name happens to contain no
        -- quote, which is a property of today's value and not of this code. G0's guard is
        -- the shape this one copies.
        RAISE EXCEPTION 'name fix: % planned row(s) are not % sites', bad, 'ancient_nerds';
    END IF;

    -- scope guard 2: the plan is a set of real changes, each one writable in its column
    -- (compared in the column's own type; CASE, because only CASE fixes the order in
    -- which the casts are evaluated)
    SELECT count(*) INTO bad FROM _name_fix_plan p
     WHERE p.new_value = '' OR CASE p.column_name
                WHEN 'name' THEN p.new_value::character varying IS NOT DISTINCT FROM p.old_value::character varying OR p.old_value IS NULL OR p.new_value IS NULL OR length(p.new_value) > 500
                WHEN 'name_normalized' THEN p.new_value::character varying IS NOT DISTINCT FROM p.old_value::character varying OR p.old_value IS NULL OR p.new_value IS NULL OR length(p.new_value) > 500
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'name fix: % planned row(s) are not writable changes', bad;
    END IF;

    -- scope guard 3: every planned row still holds the old value the plan names
    SELECT count(*) INTO bad
      FROM _name_fix_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE CASE p.column_name
                WHEN 'name' THEN u.name IS DISTINCT FROM p.old_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS DISTINCT FROM p.old_value::character varying
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'name fix: % planned row(s) no longer hold the planned old value', bad;
    END IF;

    -- scope guard 5: every planned row still holds the input its value was derived from
    SELECT count(*) INTO bad
      FROM (SELECT DISTINCT site_id, premise FROM _name_fix_plan) p JOIN unified_sites u ON u.id = p.site_id
     WHERE (coalesce((SELECT string_agg(e.kind || '=' || e.value, ', ' ORDER BY e.kind, e.value) FROM site_external_ids e WHERE e.site_id = u.id), '')) IS DISTINCT FROM p.premise;
    IF bad > 0 THEN
        RAISE EXCEPTION 'name fix: % planned row(s) no longer hold the premise the plan derived its value from', bad;
    END IF;

    -- the only writer: the conditional UPDATE and its journal row commit together, and
    -- the function raises unless exactly one row matched
    FOR r IN SELECT * FROM _name_fix_plan ORDER BY site_id, column_name LOOP
        moved := moved + apply_remediation_change(
            'unified_sites', r.column_name, 'id', r.site_id::text,
            r.old_value, r.new_value,
            'B1/name-fix', '2026-10-01_mechanical-name-fix-rollback', r.change_key, 'authoritative', r.evidence, r.site_id);
    END LOOP;

    IF moved <> expected THEN
        RAISE EXCEPTION 'name fix: % row(s) changed, % planned', moved, expected;
    END IF;

    -- invariant 1: every planned row now holds the new value
    SELECT count(*) INTO bad
      FROM _name_fix_plan p JOIN unified_sites u ON u.id = p.site_id
     WHERE CASE p.column_name
                WHEN 'name' THEN u.name IS DISTINCT FROM p.new_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS DISTINCT FROM p.new_value::character varying
                ELSE true END;
    IF bad > 0 THEN
        RAISE EXCEPTION 'name fix: % planned row(s) do not hold the new value', bad;
    END IF;

    -- invariant 2: the journal and the data agree, row for row, in both directions
    SELECT count(*) INTO bad
      FROM _name_fix_plan p LEFT JOIN remediation_change_log l
        ON l.row_pk = p.site_id::text AND l.table_name = 'unified_sites'
       AND l.column_name = p.column_name
       AND l.run_stamp = '2026-10-01_mechanical-name-fix-rollback'
     WHERE l.id IS NULL
        OR l.new_value IS DISTINCT FROM p.new_value
        OR l.old_value IS DISTINCT FROM p.old_value;
    IF bad > 0 THEN
        RAISE EXCEPTION 'name fix: % planned row(s) have no matching journal row', bad;
    END IF;

    SELECT count(*) INTO bad FROM remediation_change_log l
     WHERE l.run_stamp = '2026-10-01_mechanical-name-fix-rollback'
       AND (l.table_name <> 'unified_sites' OR l.column_name NOT IN ('name', 'name_normalized'));
    IF bad > 0 THEN
        RAISE EXCEPTION 'name fix: this run stamp journalled % row(s) outside unified_sites.(name, name_normalized)', bad;
    END IF;

    -- invariant 3, the lane's own: no planned site is one of the
    -- curated rows whose name_normalized is not the key of their name
    SELECT count(*) INTO bad FROM unified_sites
     WHERE id IN (SELECT site_id FROM _name_fix_plan)
       AND (name_normalized IS DISTINCT FROM left(lower(unaccent(name)), 500));
    IF bad > 0 THEN
        RAISE EXCEPTION 'name fix: % planned site(s) break the lane invariant after the write', bad;
    END IF;

    RAISE NOTICE 'name fix: % of % planned cell(s) changed and journalled over 2 curated site(s)',
        moved, expected;
END $$;

COMMIT;

-- Post-commit read: the numbers the report quotes, from the database, not from the plan.
SELECT 'journal rows for this run stamp' AS metric, count(*)::text AS value
  FROM remediation_change_log WHERE run_stamp = '2026-10-01_mechanical-name-fix-rollback'
UNION ALL
SELECT 'journal rows for this test id', count(*)::text
  FROM remediation_change_log WHERE test_id = 'B1/name-fix'
UNION ALL
SELECT 'planned rows now holding the new value', count(*)::text
  FROM remediation_change_log l
 WHERE l.run_stamp = '2026-10-01_mechanical-name-fix-rollback' AND l.table_name = 'unified_sites'
   AND l.column_name IN ('name', 'name_normalized')
   AND EXISTS (SELECT 1 FROM unified_sites u
                WHERE u.id::text = l.row_pk AND CASE l.column_name
                WHEN 'name' THEN u.name IS NOT DISTINCT FROM l.new_value::character varying
                WHEN 'name_normalized' THEN u.name_normalized IS NOT DISTINCT FROM l.new_value::character varying
                ELSE false END)
UNION ALL
SELECT 'curated rows whose name_normalized is not the key of their name', count(*)::text
  FROM unified_sites
 WHERE source_id = 'ancient_nerds' AND name_normalized IS DISTINCT FROM left(lower(unaccent(name)), 500)
UNION ALL
SELECT 'curated sites', count(*)::text
  FROM unified_sites WHERE source_id = 'ancient_nerds';
